#+title:Adult Rudin
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{mathrsfs}
#+latex_header: \usepackage{csquotes}
#+latex_header: \MakeOuterQuote{"}
#+latex_header: \setlength{\parskip}{1em}
#+options: tex:dvisvgm toc:2

* Chapter 01 Abstract Integration

** before main

Toward the end of the nineteenth century it became clear to many mathematicians that the Riemann integral (about which one learns in calculus courses) should be replaced by some other type of integral, more general and more flexible, better suited for dealing with limit processes. Among the attempts made in this direction, the most notable ones were due to Jordan, Borel, W. H. Young, and Lebesgue. It was Lebesgue's construction which turned out to be the most successful.

In brief outline, here is the main idea : The Riemann integral of a function \(f\) over an interval \([a,b]\) can be approximated by sums of the form

\[\sum _{i=1} ^{n} f(t_{i})m(E_{i})\]

where \(E_{1}, \dots , E_{n}\) are disjoint intervals whose union is [a,b], \(m (E_{i})\) denotes the length of \(E_{i}\) , and \(t_{i} \in E_{i}\) for \(i = 1, \dots, n\). Lebesgue discovered that a completely satisfactory theory of integration results if the sets \(E_{i}\) in the above sum are allowed to belong to a larger class of subsets of the line, the so-called "measurable sets", and if the class of functions under consideration is enlarged to what he called "measvrable functions". The crucial set-theoretic properties involved are the following : The union and the intersection of any countable family of measurable sets are measurable; so is the complement of every measur able set ; and, most important, the notion of "length" (now called "measure") can be extended to them in such a way that

\[m (E_{1} \cup E_{2} \cup E_{3} \cup \dots) = m(E_{1}) + m(E_{2}) + m(E_{3}) + \dots\]

# end of page 5

for every countable collection \(\left\{E_i\right\}\) of pairwise disjoint measurable sets. This property of \(m\) is called countable additivity.

The passage from Riemann's theory of integration to that of Lebesque is a process of completion (in a sense which will appear more precisely later). It is of the same fundamental importance in analysis as is the construction of the real number system from the rationals.

The above-mentioned measure \(m\) is of course intimately related to the geometry of the real line. In this chapter we shall present an abstract (axiomatic) version of the Lebesgue integral, relative to any countably additive measure on any set. (The precise definitions follow.) This abstract theory is not in any way more difficult than the special case of the real line; it shows that a large part of integration theory is independent of any geometry (or topology) of the underlying space; and, of course, it gives us a tool of much wider applicability. The existence of a large class of measures, among them that of Lebesgue, will be established in Chap. 2.

** Set theoretic notations and Terminology

**1.1** Some sets can be described by listing their members. Thus \(\left\{x_1, \ldots, x_n\right\}\) is the set whose members are \(x_1, \ldots, x_n\); and \(\{x\}\) is the set whose only member is \(x\). More often, sets are described by properties. We write
\[\{x: P\}\]
for the set of all elements \(x\) which have the property \(P\). The symbol \(\varnothing\) denotes the empty set. The words collection, family, and class will be used synonymously with /set/.

We write \(x \in A\) if \(x\) is a member of the set \(A\); otherwise \(x \notin A\). If \(B\) is a subset of \(A\), i.e., if \(x \in B\) implies \(x \in A\), we write \(B \subset A\). If \(B \subset A\) and \(A \subset B\), then \(A=B\). If \(B \subset A\) and \(A \neq B, B\) is a proper subset of \(A\). Note that \(\varnothing \subset A\) for every set \(A\).

\(A \cup B\) and \(A \cap B\) are the union and intersection of \(A\) and \(B\), respectively. If \(\left\{A_\alpha\right\}\) is a collection of sets, where \(\alpha\) runs through some index set \(I\), we write
\[\bigcup_{\alpha \in I} A_\alpha \text { and } \bigcap_{\alpha \in I} A_\alpha\]
for the union and intersection of \(\left\{A_\alpha\right\}\) :
\[\begin{aligned}
& \bigcup_{\alpha \in I} A_\alpha=\left\{x: x \in A_\alpha \text { for at least one } \alpha \in I\right\} \\
& \bigcap_{\alpha \in I} A_\alpha=\left\{x: x \in A_\alpha \text { for every } \alpha \in I\right\}
\end{aligned}\]

If \(I\) is the set of all positive integers, the customary notations are
\[
\bigcup_{n=1}^{\infty} A_n \text { and } \bigcap_{n=1}^{\infty} A_n .
\]
# end of page 6


If no two members of \(\left\{A_\alpha\right\}\) have an element in common, then \(\left\{A_\alpha\right\}\) is a /disjoint collection/ of sets.

We write \(A-B=\{x: x \in A, x \notin B\}\), and denote the complement of \(A\) by \(A^c\) whenever it is clear from the context with respect to which larger set the complement is taken.

The /cartesian product/ \(A_1 \times \cdots \times A_n\) of the sets \(A_1, \ldots, A_n\) is the set of all ordered \(n\)-tuples \(\left(a_1, \ldots, a_n\right)\) where \(a_i \in A_i\) for \(i=1, \ldots, n\).

The /real line/ (or real number system) is \(R^1\), and
\[
R^k=R^1 \times \cdots \times R^1 \quad(k \text { factors }).
\]

The /extended real number system/ is \(R^1\) with two symbols, \(\infty\) and \(-\infty\), adjoined, and with the obvious ordering. If \(-\infty \leq a \leq b \leq \infty\), the /interval/ \([a, b]\) and the /segment/ \((a, b)\) are defined to be
\[ [a, b]=\{x: a \leq x \leq b\}, \quad(a, b)=\{x: a<x<b\} \]

We also write
\[ [a, b)=\{x: a \leq x<b\}, \quad(a, b]=\{x: a<x \leq b\} .\]

If \(E \subset[-\infty, \infty]\) and \(E \neq \varnothing\), the least upper bound (supremum) and greatest lower bound (infimum) of \(E\) exist in \([-\infty, \infty]\) and are denoted by sup \(E\) and inf \(E\).

Sometimes (but only when \(\sup E \in E\) ) we write max \(E\) for \(\sup E\).
The symbol
\[
f: X \rightarrow Y
\]
means that \(f\) is a function (or mapping or transformation) of the set \(X\) into the set \(Y\); i.e., \(f\) assigns to each \(x \in X\) an element \(f(x) \in Y\). If \(A \subset X\) and \(B \subset Y\), the image of \(A\) and the inverse image (or pre-image) of \(B\) are
\[\begin{aligned}
f(A) & =\{y: y=f(x) \text { for some } x \in A\}, \\
f^{-1}(B) & =\{x: f(x) \in B\} .
\end{aligned}\]
Note that \(f^{-1}(B)\) may be empty even when \(B \neq \varnothing\).

The domain of \(f\) is \(X\). The range of \(f\) is \(f(X)\).

If \(f(X)=Y, f\) is said to map \(X\) onto \(Y\).

We write \(f^{-1}(y)\), instead of \(f^{-1}(\{y\})\), for every \(y \in Y\). If \(f^{-1}(y)\) consists of at most one point, for each \(y \in Y, f\) is said to be one-to-one. If \(f\) is one-to-one, then \(f^{-1}\) is a function with domain \(f(X)\) and range \(X\).

If \(f: X \rightarrow[-\infty, \infty]\) and \(E \subset X\), it is customary to write \(\sup _{x \in E} f(x)\) rather than sup \(f(E)\).

If \(f: X \rightarrow Y\) and \(g: Y \rightarrow Z\), the composite function \(g \circ f: X \rightarrow Z\) is defined by the formula
\[(g \circ f) (x) = g(f(x))\quad (x \in X).\]

# page 8

If the range of \(f\) lies in the real line (or in the complex plane), the \(f\) is said to be a /real function/ (or a /complex function/). For a complex function \(f\), the statement \(f \ge 0\), means that all values \(f(x)\) of \(f\) are nonnegative real numbers.

** The concept of measurability

The class of measurable functions plays a fundamental role in integration theory. It has some basic properties in common with another most important class of functions, namely, the continuous ones. It is helpful to keep these similarities in mind. Our presentation is therefore organized in such a way that the analogies between the concepts topological space, open set, and continuous function, on the one hand, and measurable space, measurable set, and measurable function, on the other, are strongly emphasized. It seems that the relations between these concepts emerge most clearly when the setting is quite abstract, and this (rather than a desire for mere generality) motivates our approach to the subject.

\medskip
<<Def 1.2>> *Def 1.2 topology*

(a) A collection \(\tau\) of subsets of a set \(X\) is said to be a /topology/ in \(X\) if \(\tau\) has the following three properties:

  1. \(\varnothing \in \tau\) and \(X \in \tau\).
  2. If \(V_i \in \tau\) for \(i = 1, \ldots, n\), then \(V_1 \cap V_2 \cap \cdots \cap V_n \in \tau\).
  3. If \(\{V_\alpha\}\) is an arbitrary collection of members of \(\tau\) (finite, countable, or uncountable), then \(\bigcup_\alpha V_\alpha \in \tau\).

(b) If \(\tau\) is a topology in \(X\), then \(X\) is called a topological space, and the members of \(\tau\) are called the open sets in \(X\).

(c) If \(X\) and \(Y\) are topological spaces and if \(f\) is a mapping of \(X\) into \(Y\), then \(f\) is said to be continuous provided that \(f^{-1}(V)\) is an open set in \(X\) for every open set \(V\) in \(Y\).

\medskip
<<Def 1.3>> *Def 1.3 sigma algebra*

(a) A collection \(\mathfrak{M}\) of subsets of a set \(X\) is said to be a \(\sigma\)-algebra in \(X\) if \(\mathfrak{M}\) has the following properties:

  1. \(X \in \mathfrak{M}\).
  2. If \(A \in \mathfrak{M}\), then \(A^c \in \mathfrak{M}\), where \(A^c\) is the complement of \(A\) relative to \(X\).
  3. If \(A=\bigcup_{n=1}^{\infty} A_n\) and if \(A_n \in \mathfrak{M}\) for \(n=1,2,3, \dots\), then \(A \in \mathfrak{M}\).

(b) If \(\mathfrak{M}\) is a \(\sigma\)-algebra in \(X\), then \(X\) is called a measurable space, and the members of \(\mathfrak{M}\) are called the measurable sets in \(X\).

(c) If \(X\) is a measurable space, \(Y\) is a topological space, and \(f\) is a mapping of \(X\) into \(Y\), then \(f\) is said to be measurable provided that \(f^{-1}(V)\) is a measurable set in \(X\) for every open set \(V\) in \(Y\).
# page 9

It would perhaps be more satisfactory to apply the term "measurable space" to the ordered pair \((X, \mathfrak{M})\), rather than to \(X\). After all, \(X\) is a set, and \(X\) has not been changed in any way by the fact that we now also have a \(\sigma\)-algebra of its subsets in mind. Similarly, a topological space is an ordered pair \((X, \tau)\). But if this sort of thing were systematically done in all mathematics, the terminology would become awfully cumbersome. We shall discuss this again at somewhat greater length in Sec. 1.21.

\medskip
*1.4 Comments* on Definition 1.2 The most familiar topological spaces are the metric spaces. We shall assume some familiarity with metric spaces but shall give the basic definitions, for the sake of completeness.

A metric space is a set \(X\) in which a distance function (or metric) \(\rho\) [fn:: we use \(d\) elsewhere] is defined, with the following properties:

- (a) \(0 \leq \rho(x, y)<\infty\) for all \(x\) and \(y \in X\).
- (b) \(\rho(x, y)=0\) if and only if \(x=y\).
- (c) \(\rho(x, y)=\rho(y, x)\) for all \(x\) and \(y \in X\).
- (d) \(\rho(x, y) \leq \rho(x, z)+\rho(z, y)\) for all \(x, y\), and \(z \in X\).

Here property \((d)\) is called the /triangle inequality/.

If \(x \in X\) and \(r \geq 0\), the open ball with center at \(x\) and radius \(r\) is the set \(\{y \in X: \rho(x, y)<r\}\).

If \(X\) is a metric space and if \(\tau\) is the collection of all sets \(E \subset X\) which are arbitrary unions of open balls, then \(\tau\) is a topology in \(X\). This is not hard to verify; the intersection property depends on the fact that if \(x \in B_1 \cap B_2\), where \(B_1\) and \(B_2\) are open balls, then \(x\) is the center of an open ball \(B \subset B_1 \cap B_2\). We leave this as an exercise.

For instance, in the real line \(R^1\) a set is open if and only if it is a union of open segments \((a, b)\). In the plane \(R^2\), the open sets are those which are unions of open circular discs.

Another topological space, which we shall encounter frequently, is the extended real line \([-\infty, \infty]\); its topology is defined by declaring the following sets to be open: \((a, b),[-\infty, a),(a, \infty]\), and any union of segments of this type.

The definition of continuity given in Sec. 1.2(c) is a global one. Frequently it is desirable to define continuity locally: A mapping \(f\) of \(X\) into \(Y\) is said to be continuous at the point \(x_0 \in X\) if to every neighborhood \(V\) of \(f\left(x_0\right)\) there corresponds a neighborhood \(W\) of \(x_0\) such that \(f(W) \subset V\).
(A neighborhood of a point \(x\) is, by definition, an open set which contains \(x\).)
When \(X\) and \(Y\) are metric spaces, this local definition is of course the same as the usual epsilon-delta definition, and is equivalent to the requirement that \(\lim f\left(x_n\right)=f\left(x_0\right)\) in \(Y\) whenever \(\lim x_n=x_0\) in \(X\).

The following easy proposition relates the local and global definitions of continuity in the expected manner:

\medskip
<<Prop 1.5>>
**1.5 Proposition** Let \(X\) and \(Y\) be topological spaces. A mapping \(f\) of \(X\) into \(Y\) is continuous if and only iff is continuous at every point of \(X\).
# page 10

*Proof* If \(f\) is continuous and \(x_0 \in X\), then \(f^{-1}(V)\) is a neighborhood of \(x_0\), for every neighborhood \(V\) of \(f\left(x_0\right)\). Since \(f\left(f^{-1}(V)\right) \subset V\), it follows that \(f\) is continuous at \(x_0\).

If \(f\) is continuous at every point of \(X\) and if \(V\) is open in \(Y\), every point \(x \in f^{-1}(V)\) has a neighborhood \(W_x\) such that \(f\left(W_x\right) \subset V\). Therefore \(W_x \subset\) \(f^{-1}(V)\). It follows that \(f^{-1}(V)\) is the union of the open sets \(W_x\), so \(f^{-1}(V)\) is itself open. Thus \(f\) is continuous. QED

\medskip
<<Com 1.6>>
1.6 Comments on Definition 1.3

Let \(\mathfrak{M}\) be a \(\sigma\)-algebra in a set \(X\). Referring to Properties (i) to (iii) of Definition 1.3(a) [[Def 1.3]], we immediately derive the following facts.

(a) Since \(\varnothing=X^c\), (i) and (ii) imply that \(\varnothing \in \mathfrak{M}\).
(b) Taking \(A_{n+1}=A_{n+2}=\cdots=\varnothing\) in (iii), we see that \(A_1 \cup A_2 \cup \cdots \cup A_n\) \(\in \mathfrak{M}\) if \(A_i \in \mathfrak{M}\) for \(i=1, \ldots, n\).
(c) Since
\[
\bigcap_{n=1}^{\infty} A_n=\left(\bigcup_{n=1}^{\infty} A_n^c\right)^c,
\]
\(\mathfrak{M}\) is closed under the formation of countable (and also finite) intersections.
(d) Since \(A-B=B^c \cap A\), we have \(A-B \in \mathfrak{M}\) if \(A \in \mathfrak{M}\) and \(B \in \mathfrak{M}\).

The prefix \(\sigma\) refers to the fact that (iii) is required to hold for all /countable/ unions of members of \(\mathfrak{M}\). If (iii) is required for finite unions only, then \(\mathfrak{M}\) is called an algebra of sets.

\medskip
<<Thm 1.7>>
1.7 Theorem Let \(Y\) and \(Z\) be topological spaces, and let \(g: Y \rightarrow Z\) be continuous.

- (a) If \(X\) is a topological space, if \(f: X \rightarrow Y\) is continuous, and if \(h=g \circ f\), then \(h: X \rightarrow Z\) is continuous.
- (b) If \(X\) is a measurable space, if \(f: X \rightarrow Y\) is measurable, and if \(h=g \circ f\), then \(h: X \to Z \) is measurable.

Stated informally, continuous functions of continuous functions are continuous; continuous functions of measurable functions are measurable.

Proof If \(V\) is open in \(Z\), then \(g^{-1}(V)\) is open in \(Y\), and
\[h^{-1}(V)=f^{-1}\left(g^{-1}(V)\right) .\]
If \(f\) is continuous, it follows that \(h^{-1}(V)\) is open, proving \((a)\).
If \(f\) is measurable, it follows that \(h^{-1}(V)\) is measurable, proving \((b)\). ////
# page 11

\medskip
<<Thm 1.8>>
**1.8 Theorem** Let \(u\) and \(v\) be real measurable functions on a measurable space \(X\), let \(\Phi\) be a continuous mapping of the plane (\(\mathbb R^{2}\)) into a topological space \(Y\), and define
\[
h(x)=\Phi(u(x), v(x))
\]
for \(x \in X\). Then \(h: X \rightarrow Y\) is measurable.

Proof. Put \(f(x)=(u(x), v(x))\). Then \(f\) maps \(X\) into the plane. Since \(h=\Phi \circ f\), Theorem 1.7 shows that it is enough to prove the measurability of \(f\).

If \(R\) is any open rectangle in the plane, with sides parallel to the axes, then \(R\) is the cartesian product of two segments \(I_1\) and \(I_2\), and
\[
f^{-1}(R)=u^{-1}\left(I_1\right) \cap v^{-1}\left(I_2\right),
\]
which is measurable, by our assumption on \(u\) and \(v\). Every open set \(V\) in the plane is a countable union of such rectangles \(R_i\), and since
\[
f^{-1}(V)=f^{-1}\left(\bigcup_{i=1}^{\infty} R_i\right)=\bigcup_{i=1}^{\infty} f^{-1}\left(R_i\right),
\]
\(f^{-1}(V)\) is measurable. QED

\medskip
<<Prop 1.9>>
1.9 Let \(X\) be a measurable space. The following propositions are corollaries of Theorems 1.7 and 1.8:

(a) If \(f=u+i v\), where \(u\) and \(v\) are real measurable functions on \(X\), then \(f\) is \(a\) complex measurable function on \(\boldsymbol{X}\).
This follows from Theorem 1.8 , with \(\Phi(z)=z\).

(b) If \(f=u+i v\) is a complex measurable function on \(X\), then \(u, v\), and \(|f|\) are real measurable functions on \(X\).

This follows from Theorem 1.7, with \(g(z)=\operatorname{Re}(z), \operatorname{Im}(z)\), and \(|z|\).
(c) Iff and \(g\) are complex measurable functions on \(X\), then so are \(f+g\) and \(f g\).

For real \(f\) and \(g\) this follqws from Theorem 1.8, with
\[
\Phi(s, t)=s+t
\]
and \(\Phi(s, t)=s t\). The complex case then follows from \((a)\) and \((b)\).

(d) If \(E\) is a measurable set in \(X\) and if
\[
\chi_E(x)= \begin{cases}1 & \text { if } x \in E \\ 0 & \text { if } x \notin E\end{cases}
\]
then \(\chi_E\) is a measurable function.

  This obvious. We call \(\chi _{E}\) the characteristic function of the set \(E\). The letter \(\chi\) will be reserved for characteristic functions throughout this book.

(e) If \(f\) is a complex measurable function on \(X\), there is a complex measurable function \(\alpha\) on \(X\) such that \(\vert \alpha \vert = 1\) and \(f = \alpha \vert f \vert\).

# page 12

\medskip
*Proof* Let \(E=\{x: f(x)=0\}\), let \(Y\) be the complex plane with the origin removed, define \(\varphi(z)=z /|z|\) for \(z \in Y\), and put
\[
\alpha(x)=\varphi\left(f(x)+\chi_E(x)\right) \quad(x \in X) .
\]

If \(x \in E, \alpha(x)=1\); if \(x \notin E, \alpha(x)=f(x) /|f(x)|\). Since \(\varphi\) is continuous on \(Y\) and since \(E\) is measurable (why?), the measurability of \(\alpha\) follows from (c), (d), and Theorem 1.7.

\bigskip
We now show that \(\sigma\)-algebras exist in great profusion.

\medskip
<<Thm 1.10>>
1.10 Theorem If \(\mathscr{F}\) is any collection of subsets of \(\boldsymbol{X}\), there exists a smallest \(\sigma\)-algebra \(\mathfrak{M}^*\) in \(\boldsymbol{X}\) such that \(\mathscr{F} \subset \mathfrak{M}^*\).

This \(\mathfrak{M}^*\) is sometimes called the \(\sigma\)-algebra generated by \(\mathscr{F}\).

\medskip
*Proof* Let \(\Omega\) be the family of all \(\sigma\)-algebras \(\mathfrak{M}\) in \(X\) which contain \(\mathscr{F}\). Since the collection of all subsets of \(X\) is such a \(\sigma\)-algebra, \(\Omega\) is not empty. Let \(\mathfrak{M}^*\) be the intersection of all \(\mathfrak{M} \in \Omega\). It is clear that \(\mathscr{F} \subset \mathfrak{M}^*\) and that \(\mathfrak{M}^*\) lies in every \(\sigma\)-algebra in \(X\) which contains \(\mathscr{F}\). To complete the proof, we have to show that \(\mathfrak{M}^*\) is itself a \(\sigma\)-algebra.
  If \(A_n \in \mathfrak{M}^*\) for \(n=1,2,3, \ldots\), and if \(\mathfrak{M} \in \Omega\), then \(A_n \in \mathfrak{M}\), so \(\bigcup A_n \in \mathfrak{M}\), since \(\mathfrak{M}\) is a \(\sigma\)-algebra. Since \(\bigcup A_n \in \mathfrak{M}\) for every \(\mathfrak{M} \in \Omega\), we conclude that \(\bigcup A_n \in \mathfrak{M}^*\). The other two defining properties of a \(\sigma\)-algebra are verified in the same manner.
QED

\medskip
<<Def 1.11>>
*1.11 Borel Sets* Let \(X\) be a topological space. By Theorem 1.10 [[Thm 1.10]], there exists a smallest \(\sigma\)-algebra \(\mathscr{B}\) in \(X\) such that every open set in \(X\) belongs to \(\mathscr{B}\). The members of \(\mathscr{B}\) are called the Borel sets of \(\boldsymbol{X}\).

  In particular, closed sets are Borel sets (being, by definition, the complements of open sets), and so are all countable unions of closed sets and all countable intersections of open sets. These last two are called \(F_\sigma\) 's and \(G_\delta\) 's, respectively, and play a considerable role. The notation is due to Hausdorff. The letters \(F\) and \(G\) were used for closed and open sets, respectively, and \(\sigma\) refers to union (Summe), \(\delta\) to intersection (Durchschnitt). For example, every half-open interval \([a, b)\) is a \(G_\delta\) and an \(F_\sigma\) in \(R^1\).

  Since \(\mathscr{B}\) is a \(\sigma\)-algebra, we may now regard \(X\) as a measurable space, with the Borel sets playing the role of the measurable sets; more concisely, we consider the measurable space \((X, \mathscr{B})\). If \(f: X \rightarrow Y\) is a continuous mapping of \(X\), where \(Y\) is any topological space, then it is evident from the definitions that \(f^{-1}(V) \in \mathscr{B}\) for every open set \(V\) in \(Y\). In other words, every continuous mapping of \(X\) is Borel measurable.

  Borel measurable mappings are often called borel mappigns or borel functions.

# page 13


\medskip
<<Thm 1.12>> *Theorem 1.12*

Suppose \( \mathfrak{M} \) is a σ-algebra in \( X \), and \( Y \) is a topological space. Let \( f \) map \( X \) into \( Y \).

(a) If \( \Omega \) is the collection of all sets \( E \subseteq Y \) such that \( f^{-1}(E) \in \mathfrak M\), then \( \Omega \) is a σ-algebra in \( Y \).
(b) If \( f \) is measurable and \( E \) is a Borel set in \( Y \), then \( f^{-1}(E) \in \mathfrak M\).
(c) If \( Y = [-\infty, \infty] \) and \( f^{-1}((\alpha, \infty]) \in \mathfrak M\) for every real \( \alpha \), then \( f \) is measurable.
(d) If \( f \) is measurable, if \( Z \) is a topological space, if \( g: Y \to Z \) is a Borel mapping, and if \( h = g \circ f \), then \( h: X \to Z \) is measurable.

**Proof**: (a) follows from the relations
\[ f^{-1}(Y) = X, \]
\[ f^{-1}(Y - A) = X - f^{-1}(A), \]
and
\[ f^{-1}(A_1 \cup A_2 \cup \cdots) = f^{-1}(A_1) \cup f^{-1}(A_2) \cup \cdots. \]
To prove (b), let \(\Omega\) be as in (a); the measurability of \(f\) implies that \(\Omega\) contains all open sets in \(Y\), and since \(\Omega\) is a σ-algebra, \(\Omega\) contains all Borel sets in \(Y\).

To prove (c), let \(\Omega\) be the collection of all \(E \subset [-\infty, \infty]\) such that \(f^{-1}(E) \in \mathfrak{M}\). Choose a real number \(\alpha\), and choose \(\alpha_n < \alpha\) so that \(\alpha_n \to \alpha\) as \(n \to \infty\). Since \((\alpha_n, \infty] \in \Omega\) for each \(n\), since
\[ [-\infty, \alpha) = \bigcup_{n=1}^{\infty} [-\infty, \alpha_n] = \bigcup_{n=1}^{\infty} (\alpha_n, \infty]^c. \]
and since \((a)\) shows that \(\Omega\) is a sigma algebra, we see that \([- \infty, \alpha) \in \Omega\). The same is then true of
\[(\alpha, \beta) = [- \infty, \beta) \cap (\alpha, \infty].\]
Since every open set in \([-\infty, \infty]\) is a countable union of segments of the above types, \(\Omega\) contains every open set. Thus \(f\) is measurable.

  To prove \((d)\), let \(V \subset Z\) be open. Then \(g ^{-1}(V)\) is a Borel set of \(Y\), and since
\[h^{-1}(V) = f^{-1}(g ^{-1} (V)),\]
\((b)\) shows that \(h^{-1}(V) \in \mathfrak M\).

\medskip
<<Def 1.13>> *1.13 Definition* Let \(\{\alpha_{n} \}\) be a sequence in \([-\infty, \infty]\), and put
\[b_{k} = \sup \{a_{k}, a_{k+1} , a _{k+1}, \dots \}\quad (k = 1,2,3,\dots)\]

# page 14

** simple functions

<<Def 1.16>>
Def 1.16 A complex function \(s\) on a measurable space \(X\) whose range consists of only finitely many points will be called a /simple function/.
Among these are the /nonnegative simple functions/, whose range is a finite subset of \([0, \infty)\). Note that we explicitly exclude \(\infty\) from the values of a simple function.

If \(\alpha_1, \ldots, \alpha_n\) are the distinct values of a simple function \(s\), and if we set \(A_i=\left\{x: s(x)=\alpha_i\right\}\), then clearly
\[
s=\sum_{i=1}^n \alpha_i \chi_{A_i}
\]
where \(\chi_{A_i}\) is the characteristic function of \(A_i\), as defined in Sec. 1.9(d).

It is also clear that \(s\) is measurable if and only if each of the sets \(A_i\) is measurable.

<<Thm 1.17>>
1.17 Theorem Let \(f: X \rightarrow[0, \infty]\) be measurable. There exist simple measurable functions \(s_n\) on \(X\) such that

- (a) \(0 \leq s_1 \leq s_2 \leq \cdots \leq f\).
- (b) \(s_n(x) \rightarrow f(x)\) as \(n \rightarrow \infty\), for every \(x \in X\).

Proof. Put \(\delta_n=2^{-n}\). To each positive integer \(n\) and each real number \(t\) corresponds a unique integer \(k=k_n(t)\) that satisfies \(k_{n}(t) \delta_n \leq t<(k_{n}(t)+1) \delta_n\). Define
\[\varphi_n(t)= \begin{cases}k_n(t) \delta_n & \text { if } 0 \leq t<n \\ n & \text { if } n \leq t \leq \infty .\end{cases}\]
# end of page 15
Each \(\varphi_n\) is then a Borel function on \([0, \infty]\),
\[
t-\delta_n<\varphi_n(t) \leq t \quad \text { if } 0 \leq t \leq n
\]
\(0 \leq \varphi_1 \leq \varphi_2 \leq \cdots \leq t\), and \(\varphi_n(t) \rightarrow t\) as \(n \rightarrow \infty\), for every \(t \in[0, \infty]\). It follows that the functions
\[s_n=\varphi_n \circ f\]
satisfy \((a)\) and \((b)\); they are measurable, by Theorem 1.12(d).

** Elementary Properties of Measures

<<Def 1.18>>

1.18 Definition

(a) A /positive measure/ is a function \(\mu\), defined on a \(\sigma\)-algebra \(\mathfrak{M}\), whose range is in \([0, \infty]\) and which is countably additive. This means that if \(\left\{A_i\right\}\) is a disjoint countable collection of members of \(\mathfrak{M}\), then
\[
\mu\left(\bigcup_{i=1}^{\infty} A_i\right)=\sum_{i=1}^{\infty} \mu\left(A_i\right) .
\]

To avoid trivialities, we shall also assume that \(\mu(A)<\infty\) for at least one \(A \in \mathfrak{M}\).
(b) A /measure space/ is a measurable space which has a positive measure defined on the \(\sigma\)-algebra of its measurable sets.
(c) A /complex measure/ is a complex-valued countably additive function defined on a \(\sigma\)-algebra.

/Note/: What we have called a /positive measure/ is frequently just called a /measure/; we add the word "positive" for emphasis. If \(\mu(E)=0\) for every \(E \in \mathfrak{M}\), then \(\mu\) is a positive measure, by our definition. The value \(\infty\) is admissible for a positive measure; but when we talk of a complex measure \(\mu\), it is understood that \(\mu(E)\) is a complex number, for every \(E \in \mathfrak{M}\). The real measures form a subclass of the complex ones, of course.

<<Thm 1.19>>
1.19 Theorem Let \(\mu\) be a positive measure on a \(\sigma\)-algebra \(\mathfrak{M}\). Then

- (a) \(\mu(\varnothing)=0\).
- (b) \(\mu\left(A_1 \cup \cdots \cup A_n\right)=\mu\left(A_1\right)+\cdots+\mu\left(A_n\right)\) if \(A_1, \ldots, A_n\) are pairwise disjoint members of \(\mathfrak{M}\).
- (c) \(A \subset B\) implies \(\mu(A) \leq \mu(B)\) if \(A \in \mathfrak{M}, B \in \mathfrak{M}\).
- (d) \(\mu\left(A_n\right) \rightarrow \mu(A)\) as \(n \rightarrow \infty\) if \(A=\bigcup_{n=1}^{\infty} A_n, A_n \in \mathfrak{M}\), and
- (e) \(\mu(A_{n}) \to \mu (A)\) as \(n \to \infty\) if \(A = \bigcap _{n=1}^{\infty} A_{n},\) \(A_{n}\in \mathfrak{M}\),
  \[A_1 \supset A_{2} \supset A_{3} \supset \dots,\]
  and \(\mu(A_1)\) is finite.
# end of page 16

** arithmetic in \([0, \infty]\)

<<1.22>>
*1.22* Throughout integration theory, one inevitably encounters \(\infty\). One reason is that one wants to be able to integrate over sets of infinite measure; after all, the real line has infinite length. Another reason is that even if one is primarily interested in real-valued functions, the lim sup of a sequence of positive real functions or the sum of a sequence of positive real functions may well be \(\infty\) at some points, and much of the elegance of theorems like 1.26 and 1.27 would be lost if one had to make some special provisions whenever this occurs.

Let us define \( a + \infty = \infty + a = \infty \) if \( 0 \leq a \leq \infty \), and
\[ a \cdot \infty = \infty \cdot a = \begin{cases}
\infty & \text{if } 0 < a \leq \infty \\
0 & \text{if } a = 0;
\end{cases} \]
Sums and products of real numbers are of course defined in the usual way.

  It may seem strange to define \( 0 \cdot \infty = 0 \). However, one verifies without difficulty that with this definition the commutative, associative, and distributive laws hold in \([0, \infty]\) without any restriction.

** Integration of Positive Functions

In this section, \( \mathfrak{M} \) will be a \( \sigma \)-algebra in a set \( X \) and \( \mu \) will be a positive measure on \( \mathfrak{M} \).

<<Def 1.23>>
**1.23 Definition** If \( s: X \rightarrow [0, \infty) \) is a measurable simple function, of the form

\[
s = \sum_{i=1}^{n} \alpha_{i} \chi_{A_{i}},
\]

where \( \alpha_{1}, \ldots, \alpha_{n} \) are the distinct values of \( s \) (compare Definition 1.16), and if \( E \in \mathfrak{M} \), we define

\[
\int_{E} s \, d\mu = \sum_{i=1}^{n} \alpha_{i} \mu(A_{i} \cap E).
\]

The convention \( 0 \cdot \infty = 0 \) is used here; it may happen that \( \alpha_{i} = 0 \) for some \( i \) and that \( \mu(A_{i} \cap E) = \infty \).

If \( f: X \rightarrow [0, \infty] \) is measurable, and \( E \in \mathfrak{M} \), we define

\[
\int_{E} f \, d\mu = \sup \int_{E} s \, d\mu,
\]

the supremum being taken over all simple measurable functions \( s \) such that \( 0 \leq s \leq f \).

The image contains additional mathematical content related to the Lebesgue integral and its properties. Here is the OCR-extracted text with the mathematical formulas:

The left member of (3) is called the **Lebesgue integral** of \( f \) over \( E \), with respect to the measure \( \mu \). It is a number in \([0, \infty]\).

Observe that we apparently have two definitions for \( \int_{E} f \, d\mu \) if \( f \) is simple, namely, (2) and (3). However, these assign the same value to the integral, since \( f \) is, in this case, the largest of the functions \( s \) which occur on the right.

<<Remark 1.24>>
**Remark 1.24** The following propositions are immediate consequences of the definitions. The functions and sets occurring in them are assumed to be measurable:

(a) If \( 0 \leq f \leq g \), then \( \int_{E} f \, d\mu \leq \int_{E} g \, d\mu \).
(b) If \( A \subseteq B \) and \( f \geq 0 \), then \( \int_{A} f \, d\mu \leq \int_{B} f \, d\mu \).
(c) If \( f \geq 0 \) and \( c \) is a constant, \( 0 \leq c < \infty \), then
\[
\int_{E} cf \, d\mu = c \int_{E} f \, d\mu.
\]
(d) If \( f(x) = 0 \) for all \( x \in E \), then \(\int_{E} f \, d\mu = 0\), even if \(\mu(E) = \infty\).
(e) If \(\mu(E) = 0\), then \(\int_{E} f \, d\mu = 0\), even if \( f(x) = \infty \) for every \( x \in E \).
(f) If \( f \geq 0 \), then \(\int_{E} f \, d\mu = \int_{X} \chi_{E} f \, d\mu\).

This last result shows that we could have restricted our definition of integration to integrals over all of \( X \), without losing any generality. If we wanted to integrate over subsets, we could then use (f) as the definition. It is purely a matter of taste which definition is preferred.

One may also remark here that every measurable subset \( E \) of a measure space \( X \) is again a measure space, in a perfectly natural way: The new measurable sets are simply those measurable subsets of \( X \) which lie in \( E \), and the measure is unchanged, except that its domain is restricted. This shows again that as soon as we have integration defined over every measure space, we automatically have it defined over every measurable subset of every measure space.

<<Prop 1.25>>
**1.25 Proposition**: Let \( s \) and \( t \) be nonnegative measurable simple functions on \( X \). For \( E \in \mathfrak{M} \), define

\[
\varphi(E) = \int_{E} s \, d\mu.\tag{1}
\]

Then \( \varphi \) is a measure on \( \mathfrak{M} \). Also

\[
\int_{X} (s + t) \, d\mu = \int_{X} s \, d\mu + \int_{X} t \, d\mu. \tag{2}
\]

(This proposition contains provisional forms of Theorems 1.27 and 1.29.)

**Proof** If \( s \) is as in Definition 1.23, and if \( E_{1}, E_{2}, \ldots \) are disjoint members of \( \mathfrak{M} \) whose union is \( E \), the countable additivity of \( \mu \) shows that

\[
\varphi(E) = \sum_{i=1}^{n} \alpha_{i} \, \mu(A_{i} \cap E) = \sum_{i=1}^{n} \alpha_{i} \sum_{r=1}^{\infty} \mu(A_{i} \cap E_{r})
\]
\[
= \sum_{r=1}^{\infty} \sum_{i=1}^{n} \alpha_{i} \, \mu(A_{i} \cap E_{r}) = \sum_{r=1}^{\infty} \varphi(E_{r}).
\]

Also, \( \varphi(\emptyset) = 0 \), so that \( \varphi \) is not identically \( \infty \).

Next, let \( s \) be as before, let \( \beta_{1}, \ldots, \beta_{m} \) be the distinct values of \( t \), and let \( B_{j} = \{x \colon t(x) = \beta_{j}\} \). If \( E_{ij} = A_{i} \cap B_{j} \), then

\[
\int_{E_{ij}} (s + t) \, d\mu = (\alpha_{i} + \beta_{j}) \mu(E_{ij})
\]
and
\[
\int_{E_{ij}} s \, d\mu + \int_{E_{ij}} t \, d\mu = \alpha_{i} \mu(E_{ij}) + \beta_{j} \mu(E_{ij}).
\]

Thus (2) holds with \( E_{ij} \) in place of \( X \). Since \( X \) is the disjoint union of the sets \( E_{ij} \) (\( 1 \leq i \leq n \), \( 1 \leq j \leq m \)), the first half of our proposition implies that (2) holds. QED

We now come to the interesting part of the theory. One of its most remark able features is the ease with which it handles limit operations.

<<Thm 1.26>>
**1.26 Lebesgue's Monotone Convergence Theorem** Let \(\{f_n\}\) be a sequence of measurable functions on \(X\), and suppose that

(a) \(0 \leq f_1(x) \leq f_2(x) \leq \cdots \leq \infty\) for every \(x \in X\), \\
(b) \(f_n(x) \to f(x)\) as \(n \to \infty\), for every \(x \in X\).

Then \(f\) is measurable, and

\[
\int_X f_n \, d\mu \to \int_X f \, d\mu \quad \text{as } n \to \infty.
\]

**Proof** Since \(\int f_n \leq \int f_{n+1}\), there exists an \(\alpha \in [0, \infty]\) such that

\[
\int_X f_n \, d\mu \to \alpha \quad \text{as } n \to \infty.\tag{1}
\]


By Theorem 1.14, \(f\) is measurable. Since \(f_n \leq f\), we have \(\int f_n \leq \int f\) for every \(n\), so (1) implies

\[
\alpha \leq \int_X f \, d\mu.\tag{2}
\]

Let \(s\) be any simple measurable function such that \(0 \leq s \leq f\), let \(c\) be a constant, \(0 < c < 1\), and define

\[
E_n = \{x: f_n(x) \geq cs(x)\} \quad (n = 1, 2, 3, \ldots).\tag{3}
\]

Each \(E_{n}\) is measurable, \(E_{1} \subset E_{2} \subset E_{3} \subset \cdots\), and \(X = \bigcup E_{n}\). To see this equality, consider some \(x \in X\). If \(f(x) = 0\), then \(x \in E_{1}\); if \(f(x) > 0\), then \(cs(x) < f(x)\), since \(c < 1\); hence \(x \in E_{n}\) for some \(n\). Also

\[
\int_{X} f_{n} \, d\mu \geq \int_{E_{n}} f_{n} \, d\mu \geq c \int_{E_{n}} s \, d\mu \qquad (n = 1, 2, 3, \ldots).\tag{4}
\]

Let \( n \rightarrow \infty \), applying Proposition 1.25 and Theorem 1.19\((d)\) to the last integral in (4). The result is

\[
\alpha \geq c \int_{X} s \, d\mu.
\](5)

Since (5) holds for every \( c < 1 \), we have

\[
\alpha \geq \int_{X} s \, d\mu
\](6)

for every simple measurable \( s \) satisfying \( 0 \leq s \leq f \), so that

\[
\alpha \geq \int_{X} f \, d\mu.
\](7)

The theorem follows from (1), (2), and (7).

<<Thm 1.27>>
**1.27 Theorem**: If \( f_{n} \colon X \to [0, \infty] \) is measurable, for \( n = 1, 2, 3, \ldots \), and

\[
f(x) = \sum\limits_{n=1}^{\infty} f_{n}(x) \qquad (x \in X),
\](1)

then

\[
\int_{X} f \, d\mu = \sum\limits_{n=1}^{\infty} \int_{X} f_{n} \, d\mu.
\](2)

**Proof** First, there are sequences \(\{s^{\prime}_{i}\}\), \(\{s^{\prime\prime}_{i}\}\) of simple measurable functions such that \( s^{\prime}_{i} \rightarrow f_{1} \) and \( s^{\prime\prime}_{i} \rightarrow f_{2} \), as in Theorem 1.17. If \( s_{i} = s^{\prime}_{i} + s^{\prime\prime}_{i} \), then \( s_{i} \rightarrow f_{1} + f_{2} \), and the monotone convergence theorem, combined with Proposition 1.25, shows that

\[
\int_{X} (f_{1} + f_{2}) \, d\mu = \int_{X} f_{1} \, d\mu + \int_{X} f_{2} \, d\mu.
\](3)

Next, put \( g_{N} = f_{1} + \cdots + f_{N} \). The sequence \(\{g_{N}\}\) converges monotonically to \( f \), and if we apply induction to (3) we see that

\[
\int_{X} g_{N} \, d\mu = \sum\limits_{n=1}^{N} \int_{X} f_{n} \, d\mu.
\](4)

Applying the monotone convergence theorem once more, we obtain (2), and the proof is complete. QED

If we let \( \mu \) be the counting measure on a countable set, Theorem 1.27 is a statement about double series of nonnegative real numbers (which can of course be proved by more elementary means):

# page 23

**Corollary**: If \( a_{ij} \geq 0 \) for \( i \) and \( j = 1, 2, 3, \ldots \), then

\[
\sum_{i=1}^{\infty} \sum_{j=1}^{\infty} a_{ij} = \sum_{j=1}^{\infty} \sum_{i=1}^{\infty} a_{ij}.
\]

<<Lemma 1.28>>
**1.28 Fatou's Lemma**: If \( f_{n} \colon X \to [0, \infty] \) is measurable, for each positive integer \( n \), then

\[
\int_{X} \left( \liminf_{n \to \infty} f_{n} \right) d\mu \leq \liminf_{n \to \infty} \int_{X} f_{n} d\mu.
\](1)

Strict inequality can occur in (1); see Exercise 8.

**Proof** Put

\[
g_{k}(x) = \inf_{i \geq k} f_{i}(x) \qquad (k = 1, 2, 3, \ldots; x \in X).
\](2)

Then \( g_{k} \leq f_{k} \), so that

\[
\int_{X} g_{k} d\mu \leq \int_{X} f_{k} d\mu \qquad (k = 1, 2, 3, \ldots).
\](3)

Also, \( 0 \leq g_{1} \leq g_{2} \leq \dots \), each \( g_{k} \) is measurable, by Theorem 1.14, and \( g_{k}(x) \to \liminf f_{n}(x) \) as \( k \to \infty \), by Definition 1.13. The monotone convergence theorem shows therefore that the left side of (3) tends to the left side of (1), as \( k \to \infty \). Hence (1) follows from (3). QED

<<Thm 1.29>>
**1.29 Theorem**: Suppose \( f \colon X \to [0, \infty] \) is measurable, and

\[
\varphi(E) = \int_{E} f \, d\mu \qquad (E \in \mathfrak{M}).\tag{1}
\]

Then \( \varphi \) is a measure on \( \mathfrak{M} \), and

\[
\int_{X} g \, d\varphi = \int_{X} g f \, d\mu\tag{2}
\]


for every measurable \( g \) on \( X \) with range in \([0, \infty]\).

**Proof** Let \( E_{1}, E_{2}, E_{3}, \ldots \) be disjoint members of \( \mathfrak{M} \) whose union is \( E \). Observe that

\[
\chi_{E} f = \sum_{j=1}^{\infty} \chi_{E_{j}} f\tag{3}
\]

and that

\[
\varphi(E) = \int_{X} \chi_{E} f \, d\mu, \qquad \varphi(E_{j}) = \int_{X} \chi_{E_{j}} f \, d\mu.\tag{4}
\]


# page 24

It now follows from Theorem 1.27 that

\[
\varphi(E) = \sum_{j=1}^{\infty} \varphi(E_{j}).\tag{5}
\]

Since \( \varphi(\emptyset) = 0 \), (5) proves that \( \varphi \) is a measure.

Next, (1) shows that (2) holds whenever \( g = \chi_{E} \) for some \( E \in \mathfrak{M} \). Hence (2) holds for every simple measurable function \( g \), and the general case follows from the monotone convergence theorem. QED

**Remark** The second assertion of Theorem 1.29 is sometimes written in the form

\[
d\varphi = f \, d\mu.\tag{6}
\]

We assign no independent meaning to the symbols \( d\varphi \) and \( d\mu \); (6) merely means that (2) holds for every measurable \( g \geq 0 \).

Theorem 1.29 has a very important converse, the Radon-Nikodym theorem, which will be proved in Chap. 6.

** Integration of Complex Functions

As before, \( \mu \) will in this section be a positive measure on an arbitrary measurable space \( X \).

<<Def 1.30>>
**1.30 Definition** We define \( L^{1}(\mu) \) to be the collection of all complex measurable functions \( f \) on \( X \) for which

\[
\int_{X} |f| \, d\mu < \infty.
\]

Note that the measurability of \( f \) implies that of \( |f| \), as we saw in Proposition 1.9(b); hence the above integral is defined.

The members of \( L^{1}(\mu) \) are called **Lebesgue integrable functions** (with respect to \( \mu \)) or **summable functions**. The significance of the exponent 1 will become clear in Chap. 3.

<<Def 1.31>>
**1.31 Definition** If \( f = u + iv \), where \( u \) and \( v \) are real measurable functions on \( X \), and if \( f \in L^{1}(\mu) \), we define

\[
\int_{E} f \, d\mu = \int_{E} u^{+} \, d\mu - \int_{E} u^{-} \, d\mu + i \int_{E} v^{+} \, d\mu - i \int_{E} v^{-} \, d\mu \tag{1}
\]

for every measurable set \( E \).

Here \( u^{ + } \) and \( u^{ - } \) are the positive and negative parts of \( u \), as defined in Sec. 1.15; \( v^{ + } \) and \( v^{ - } \) are similarly obtained from \( v \). These four functions are measurable, real, and nonnegative; hence the four integrals on the right of (1) exist, by Definition 1.23. Furthermore, we have \( u^{ + } \leq |u| < |f| \), etc., so that

# page 25

each of these four integrals is finite. Thus (1) defines the integral on the left as a complex number.

Occasionally it is desirable to define the integral of a measurable function \( f \) with range in \([-\infty, \infty]\) to be

\[
\int_{E} f \, d\mu = \int_{E} f^{+} \, d\mu - \int_{E} f^{-} \, d\mu,\tag{2}
\]


provided that at least one of the integrals on the right of (2) is finite. The left side of (2) is then a number in \([-\infty, \infty]\).

**1.32 Theorem**: Suppose \( f \) and \( g \in L^{1}(\mu) \) and \( \alpha \) and \( \beta \) are complex numbers. Then \( \alpha f + \beta g \in L^{1}(\mu) \), and

\[
\int_{X} (\alpha f + \beta g) \, d\mu = \alpha \int_{X} f \, d\mu + \beta \int_{X} g \, d\mu.\tag{1}
\]

**Proof**: The measurability of \( \alpha f + \beta g \) follows from Proposition 1.9(c). By Sec. 1.24 and Theorem 1.27,

\[
\int_{X} |\alpha f + \beta g| \, d\mu \leq \int_{X} \left( |\alpha| |f| + |\beta| |g| \right) \, d\mu
\]
\[
= |\alpha| \int_{X} |f| \, d\mu + |\beta| \int_{X} |g| \, d\mu < \infty.
\]

Thus \( \alpha f + \beta g \in L^{1}(\mu) \).

To prove (1), it is clearly sufficient to prove

\[
\int_{X} (f + g) \, d\mu = \int_{X} f \, d\mu + \int_{X} g \, d\mu\tag{2}
\]

and

\[
\int_{X} (\alpha f) \, d\mu = \alpha \int_{X} f \, d\mu.\tag{3}
\]

and the general case of (2) will follow if we prove (2) for real \( f \) and \( g \) in \( L^{1}(\mu) \).

Assuming this, and setting \( h = f + g \), we have

\[
h^{+} - h^{-} = f^{+} - f^{-} + g^{+} - g^{-}
\]

or

\[
h^{+} + f^{-} + g^{-} = f^{+} + g^{+} + h^{-}.\tag{4}
\]

By Theorem 1.27,

\[
\int h^{+} + \int f^{-} + \int g^{-} = \int f^{+} + \int g^{+} + \int h^{-},\tag{5}
\]

and since each of these integrals is finite, we may transpose and obtain (2).

# page 26

That (3) holds if \( \alpha \geq 0 \) follows from Proposition 1.24(c). It is easy to verify that (3) holds if \( \alpha = -1 \), using relations like \( (-u)^{+} = u^{-} \). The case \( \alpha = i \) is also easy: If \( f = u + iv \), then

\[
\int (i f) = \int (i u - v) = \int (-v) + i \int u = -\int v + i \int u = i \left( \int u + i \int v \right)
\]
\[
= i \int f.
\]

Combining these cases with (2), we obtain (3) for any complex \( \alpha \).

<<Thm 1.33>>
**1.33 Theorem**: If \( f \in L^{1}(\mu) \), then

\[
\left| \int_{X} f \, d\mu \right| \leq \int_{X} |f| \, d\mu.
\]
# page 27

**Proof** Put \( z = \int_{X} f \, d\mu \). Since \( z \) is a complex number, there is a complex number \( \alpha \), with \( |\alpha| = 1 \), such that \( \alpha z = |z| \). Let \( u \) be the real part of \( \alpha f \). Then \( u \leq |\alpha f| = |f| \). Hence

\[
\left| \int_{X} f \, d\mu \right| = \alpha \int_{X} f \, d\mu = \int_{X} \alpha f \, d\mu = \int_{X} u \, d\mu \leq \int_{X} |f| \, d\mu.
\]

The third of the above equalities holds since the preceding ones show that \( \int \alpha f \, d\mu \) is real. QED

We conclude this section with another important convergence theorem.

<<Thm 1.34>>
**1.34 Lebesgue's Dominated Convergence Theorem**: Suppose \(\{f_{n}\}\) is a sequence of complex measurable functions on \( X \) such that

\[
f(x) = \lim_{n \to \infty} f_{n}(x)\tag{1}
\]

exists for every \( x \in X \). If there is a function \( g \in L^{1}(\mu) \) such that

\[|f_{n}(x)| \leq g(x) \qquad (n = 1, 2, 3, \ldots; x \in X),\tag{2}\]

then \( f \in L^{1}(\mu) \),

\[
\lim_{n \to \infty} \int_{X} |f_{n} - f| \, d\mu = 0,\tag{3}
\]

and

\[
\lim_{n \to \infty} \int_{X} f_{n} \, d\mu = \int_{X} f \, d\mu.\tag{4}
\]

**Proof** Since \( |f| \leq g \) and \( f \) is measurable, \( f \in L^{1}(\mu) \). Since \( |f_{n} - f| \leq 2g \), Fatou's lemma applies to the functions \( 2g - |f_{n} - f| \) and yields

\[\begin{aligned}
  \int_{X} 2g \, d\mu & \leq \liminf_{n \to \infty} \int_{X} (2g - |f_{n} - f|) \, d\mu\\
& = \int_{X} 2g \, d\mu + \liminf_{n \to \infty} \left( -\int_{X} |f_{n} - f| \, d\mu \right)\\
& = \int_{X} 2g \, d\mu - \limsup_{n \to \infty} \int_{X} |f_{n} - f| \, d\mu.
\end{aligned}\]

Since \( \int 2g \, d\mu \) is finite, we may subtract it and obtain

\[
\limsup_{n \to \infty} \int_{X} |f_{n} - f| \, d\mu \leq 0.\tag{5}
\]

If a sequence of nonnegative real numbers fails to converge to 0, then its upper limit is positive. Thus (5) implies (3). By Theorem 1.33, applied to \( f_{n} - f \), (3) implies (4). QED

** The Role Played by Sets of Measure Zero

<<Def 1.35>>
**1.35 Definition** Let \(P\) be a property which a point \(x\) may or may not have. For instance, \(P\) might be the property "\(f(x) > 0\)" if \(f\) is a given function, or it might be "\(\{f_{n}(x)\}\) converges" if \(\{f_{n}\}\) is a given sequence of functions.

If \(\mu\) is a measure on a \(\sigma\)-algebra \(\mathfrak{M}\) and if \(E \in \mathfrak{M}\), the statement "\(P\) holds almost everywhere on \(E\)" (abbreviated to "\(P\) holds a.e. on \(E\)") means that there exists an \(N \in \mathfrak{M}\) such that \(\mu(N) = 0\), \(N \subset E\), and \(P\) holds at every point of \(E - N\). This concept of a.e. depends of course very strongly on the given measure, and we shall write "a.e. \([\mu]\)" whenever clarity requires that the measure be indicated.

For example, if \(f\) and \(g\) are measurable functions and if

\[
\mu(\{x : f(x) \neq g(x)\}) = 0,\tag{1}
\]

we say that \(f = g\) a.e. \([\mu]\) on \(X\), and we may write \(f \sim g\). This is easily seen to be an equivalence relation. The transitivity (\(f \sim g\) and \(g \sim h\) implies \(f \sim h\)) is a consequence of the fact that the union of two sets of measure 0 has measure 0.

Note that if \(f \sim g\), then, for every \(E \in \mathfrak{M}\),

\[
\int_{E} f \, d\mu = \int_{E} g \, d\mu. \tag{2}
\]

To see this, let \(N\) be the set which appears in (1); then \(E\) is the union of the disjoint sets \(E - N\) and \(E \cap N\); on \(E - N\), \(f = g\), and \(\mu(E \cap N) = 0\).

# page 28

Thus, generally speaking, sets of measure 0 are negligible in integration. It ought to be true that every subset of a negligible set is negligible. But it may happen that some set \( N \in \mathfrak{M} \) with \( \mu(N) = 0 \) has a subset \( E \) which is not a member of \( \mathfrak{M} \). Of course we can _define_ \( \mu(E) = 0 \) in this case. But will this extension of \( \mu \) still be a measure, i.e., will it still be defined on a \( \sigma \)-algebra? It is a pleasant fact that the answer is affirmative:

<<Thm 1.36>>
**1.36 Theorem**: Let \( (X, \mathfrak{M}, \mu) \) be a measure space, let \( \mathfrak{M}^{ * } \) be the collection of all \( E \subset X \) for which there exist sets \( A \) and \( B \in \mathfrak{M} \) such that \( A \subset E \subset B \) and \( \mu(B - A) = 0 \), and define \( \mu(E) = \mu(A) \) in this situation. Then \( \mathfrak{M}^{ * } \) is a \( \sigma \)-algebra, and \( \mu \) is a measure on \( \mathfrak{M}^{ * } \).

This extended measure \( \mu \) is called _complete_, since all subsets of sets of measure 0 are now measurable; the \( \sigma \)-algebra \( \mathfrak{M}^{*} \) is called the \( \mu \)-_completion_ of \( \mathfrak{M} \). The theorem says that every measure can be completed, so, whenever it is convenient, we may assume that any given measure is complete; this just gives us more measurable sets, hence more measurable functions. Most measures that one meets in the ordinary course of events are already complete, but there are exceptions; one of these will occur in the proof of Fubini's theorem in Chap. 8.

**Proof:** We begin by checking that \(\mu\) is well defined for every \(E\in\mathfrak{M}^{*}\). Suppose \(A\subset E\subset B,\ A_{1}\subset E\subset B_{1}\) and \(\mu(B-A)=\mu(B_{1}-A_{1})=0\). (The letters \(A\) and \(B\) will denote members of \(\mathfrak{M}\) throughout this proof.) Since

\[A-A_{1}\subset E-A_{1}\subset B_{1}-A_{1}\]

we have \(\mu(A-A_{1})=0\), hence \(\mu(A)=\mu(A\cap A_{1})\). For the same reason, \(\mu(A_{1})=\mu(A_{1}\ \cap\ A)\). We conclude that indeed \(\mu(A_{1})=\mu(A)\).

Next, let us verify that \(\mathfrak{M}^{*}\) has the three defining properties of a \(\sigma\)-algebra.

(i) \(X\in\mathfrak{M}^{ * }\), because \(X\in\mathfrak{M}\) and \(\mathfrak{M}\subset\mathfrak{M}^{ * }\).

(ii) If \(A\subset E\subset B\) then \(B^{c}\subset E^{c}\subset A^{c}\). Thus \(E\in\mathfrak{M}^{ * }\) implies \(E^{c}\in\mathfrak{M}^{*}\), because \(A^{c}-B^{c}=A^{c}\ \cap\ B=B-A\).

(iii) If \(A_{i}\subset E_{i}\subset B_{i}\), \(E=\bigcup\limits_{i}E_{i}\), \(A=\bigcup\limits_{i}A_{i}\), \(B=\bigcup\limits_{i}B_{i}\), then \(A\subset E\subset B\) and
\[B-A=\bigcup\limits_{1}^{\infty}(B_{i}-A)\subset\bigcup\limits_{1}^{\infty}(B_{i}-A_{i}).\]

Since countable unions of sets of measure zero have measure zero, it follows that \(E\in\mathfrak{M}^{* }\) if \(E_{i}\in\mathfrak{M}^{ *}\) for \(i=1,\,2,\,3,\,\ldots\).

Finally, if the sets \(E_{i}\) are disjoint in step (iii), the same is true of the sets \(A_{i}\), and we conclude that

\[\mu(E)=\mu(A)=\sum\limits_{1}^{\infty}\mu(A_{i})=\sum\limits_{1}^{\infty}\mu(E_{i}).\]

This proves that \(\mu\) is countably additive on \(\mathfrak{M}^{*}\).

# page 29

**1.37** The fact that functions which are equal a.e. are indistinguishable as far as integration is concerned suggests that our definition of measurable function might profitably be enlarged. Let us call a function \( f \) defined on a set \( E \in \mathfrak{M} \) _measurable on \( X \)_ if \( \mu(E^{c}) = 0 \) and if \( f^{-1}(V) \cap E \) is measurable for every open set \( V \). If we define \( f(x) = 0 \) for \( x \in E^{c} \), we obtain a measurable function on \( X \), in the old sense. If our measure happens to be complete, we can define \( f \) on \( E^{c} \) in a perfectly arbitrary manner, and we still get a measurable function. The integral of \( f \) over any set \( A \in \mathfrak{M} \) is independent of the definition of \( f \) on \( E^{c} \); therefore this definition need not even be specified at all.

There are many situations where this occurs naturally. For instance, a function \( f \) on the real line may be differentiable only almost everywhere (with respect to Lebesgue measure), but under certain conditions it is still true that \( f \) is the integral of its derivative; this will be discussed in Chap. 7. Or a sequence \( \{f_{n}\} \) of measurable functions on \( X \) may converge only almost everywhere; with our new definition of measurability, the limit is still a measurable function on \( X \), and we do not have to cut down to the set on which convergence actually occurs.

To illustrate, let us state a corollary of Lebesgue's dominated convergence theorem in a form in which exceptional sets of measure zero are admitted:

<<Thm 1.38>>
**1.38 Theorem** Suppose \(\{f_{n}\}\) is a sequence of complex measurable functions defined a.e. on \(X\) such that

\[
\sum\limits_{n=1}^{\infty}\int_{X}|\,f_{n}\,|\;d\mu<\infty.\tag{1}
\]

Then the series

\[
f(x)=\sum\limits_{n=1}^{\infty}f_{n}(x)\tag{2}
\]

converges for almost all \(x\), \(f\in L^{1}(\mu)\), and

\[
\int_{X}f\;d\mu=\sum\limits_{n=1}^{\infty}\int_{X}f_{n}\;d\mu.\tag{3}
\]

**Proof:** Let \(S_{n}\) be the set on which \(f_{n}\) is defined, so that \(\mu(S_{n}^{c})=0\). Put \(\varphi(x)=\sum|\,f_{n}(x)\,|\), for \(x\in S=\bigcap S_{n}\). Then \(\mu(S^{c})=0\). By (1) and Theorem 1.27,

\[
\int_{S}\varphi\;d\mu<\infty.\tag{4}
\]

If \(E=\{x\in S\colon\varphi(x)<\infty\}\), it follows from (4) that \(\mu(E^{c})=0\). The series (2) converges absolutely for every \(x\in E\), and if \(f(x)\) is defined by (2) for \(x\in E\), then \(|\,f(x)\,|\leq\varphi(x)\) on \(E\), so that \(f\in L^{1}(\mu)\) on \(E\), by (4). If \(g_{n}=f_{1}+\cdots+f_{n}\), then \(|\,g_{n}\,|\leq\varphi\), \(g_{n}(x)\to f(x)\) for all \(x\in E\), and Theorem 1.34 gives (3) with \(E\) in place of \(X\). This is equivalent to (3), since \(\mu(E^{c})=0\). QED

# page 30

Note that even if the \( f_{n} \) were defined at /every point/ of \( X \), (1) would only imply that (2) converges /almost everywhere/. Here are some other situations in which we can draw conclusions only almost everywhere:

<<Thm 1.39>>
**1.39 Theorem**

\((a)\) Suppose \( f \colon X \to [0, \infty] \) is measurable, \( E \in \mathfrak{M} \), and \( \int_{E} f \, d\mu = 0 \). Then \( f = 0 \) a.e. on \( E \).

\((b)\) Suppose \( f \in L^{1}(\mu) \) and \( \int_{E} f \, d\mu = 0 \) for every \( E \in \mathfrak{M} \). Then \( f = 0 \) a.e. on \( X \).

\((c)\) Suppose \( f \in L^{1}(\mu) \) and

\[
\left| \int_{X} f \, d\mu \right| = \int_{X} |f| \, d\mu.
\]

Then there is a constant \( \alpha \) such that \( \alpha f = |f| \) a.e. on \( X \).

Note that (c) describes the condition under which equality holds in Theorem 1.33.

**Proof**

\((a)\) If \(A_{n}=\{x\in E\colon f(x)>1/n\}\), \(n=1\), 2, 3, \(\ldots\), then
  \[
  \frac{1}{n}\,\mu(A_{n})\leq\int_{A_{n}}f\,d\mu\leq\int_{E}f\,d\mu=0,
  \]
  so that \(\mu(A_{n})=0\). Since \(\{x\in E\colon f(x)>0\}=\bigcup\,A_{n}\), \((a)\) follows.

\((b)\) Put \(f=u+iv\), let \(E=\{x\colon u(x)\geq 0\}\). The real part of \(\int_{E}f\,d\mu\) is then \(\int_{E}u^{ + }\ d\mu\). Hence \(\int_{E}u^{ + }\ d\mu=0\), and \((a)\) implies that \(u^{ + }=0\) a.e. We conclude similarly that

  \[
  u^{-}=v^{+}=v^{-}=0\qquad\text{a.e.}
  \]

\((c)\) Examine the proof of Theorem 1.33. Our present assumption implies that the last inequality in the proof of Theorem 1.33 must actually be an equality. Hence \(\int\left(|\,f\,|-u\right)\,d\mu=0\). Since \(|\,f\,|-u\geq 0\), \((a)\) shows that \(|\,f\,|=u\) a.e. This says that the real part of \(af\) is equal to \(|\,af\,|\) a.e., hence \(af=|\,af\,|=|\,f\,|\) a.e., which is the desired conclusion. QED

<<Thm 1.40>>
**1.40 Theorem**: Suppose \(\mu(X)<\infty\), \(f\in L^{1}(\mu)\), \(S\) is a closed set in the complex plane, and the averages

\[
A_{E}(f)=\frac{1}{\mu(E)}\int_{E}f\,d\mu
\]

lie in \(S\) for every \(E\in\mathfrak{M}\) with \(\mu(E)>0\). Then \(f(x)\in S\) for almost all \(x\in X\).

# page 31

**Proof** Let \( \Delta \) be a closed circular disc (with center at \( \alpha \) and radius \( r > 0 \), say) in the complement of \( S \). Since \( S^{c} \) is the union of countably many such discs, it is enough to prove that \( \mu(E) = 0 \), where \( E = f^{-1}(\Delta) \).

If we had \( \mu(E) > 0 \), then

\[|A_{E}(f) - \alpha| = \frac{1}{\mu(E)} \left| \int_{E} (f - \alpha) \, d\mu \right| \leq \frac{1}{\mu(E)} \int_{E} |f - \alpha| \, d\mu \leq r,\]

which is impossible, since \( A_{E}(f) \in S \). Hence \( \mu(E) = 0 \).

<<Thm 1.41>>
**1.41 Theorem**: Let \( \{E_{k}\} \) be a sequence of measurable sets in \( X \), such that

\[
\sum_{k=1}^{\infty} \mu(E_{k}) < \infty.\tag{1}
\]

Then almost all \( x \in X \) lie in at most finitely many of the sets \( E_{k} \).

**Proof** If \( A \) is the set of all \( x \) which lie in infinitely many \( E_{k} \), we have to prove that \( \mu(A) = 0 \). Put

\[
g(x) = \sum_{k=1}^{\infty} \chi_{E_{k}}(x) \qquad (x \in X).\tag{2}\]

For each \( x \), each term in this series is either 0 or 1. Hence \( x \in A \) if and only if \( g(x) = \infty \). By Theorem 1.27, the integral of \( g \) over \( X \) is equal to the sum in (1). Thus \( g \in L^{1}(\mu) \), and so \( g(x) < \infty \) a.e.

** Exercises

1 Does there exist an infinite sigma algebra has only countably many members?
   (Spoiler: no)

2 Prove an analogue of Theorem 1.8 ([[Thm 1.8]] \(h\circ(f_1 \times f_2)\) is measurable) for \(n\) functions.

3 Prove that if \(f\) is a real function on a measurable space \(X\) such that \(\{x \colon f(x)\ge r\}\) is measurable for every rational \(r\) then \(f\) is measurable.

4 Let \(\{a_{n}\}\) and \(\{b_{n}\}\) be sequences in \([-\infty, +\infty]\) and prove the following assertions

(a) \[\mathop{\lim\sup}_{n\to \infty}(-a_{n}) = -\mathop{\lim\inf}_{n \to \infty} a_{n}.\]

(b) \[\mathop{\lim\sup}_{n\to \infty} (a_{n} + b_{n}) \le \mathop{\lim\sup}_{n\to \infty} a _{n} + \mathop{\lim\sup}_{n \to\infty}b_{n}\]

provided none of the sums is of the form \( \infty - \infty \).

(c) If \( a_{n} \leq b_{n} \) for all \( n \), then

\[
\liminf_{n \to \infty} a_{n} \leq \liminf_{n \to \infty} b_{n}.
\]

Show by an example that strict inequality can hold in \((b)\).

5 (a) suppose \(f\colon X \to [- \infty, \infty]\) and \(g \colon X \to [- \infty, \infty]\) are measureable. Prove that the sets
\[\{x \colon f(x) < g(x)\}, \{x \colon f(x) = g(x)\}\]
are measurable.

(b) Prove that the set of points at which a sequence of measurable real-valued functions converges (to a finite limit) is measurable.

6 Let \( X \) be an uncountable set, let \( \mathfrak{M} \) be the collection of all sets \( E \subset X \) such that either \( E \) or \( E^c \) is at most countable, and define \( \mu(E) = 0 \) in the first case, \( \mu(E) = 1 \) in the second. Prove that \( \mathfrak{M} \) is a \( \sigma \)-algebra in \( X \) and that \( \mu \) is a measure on \( \mathfrak{M} \). Describe the corresponding measurable functions and their integrals.

7 Suppose \( f_n: X \rightarrow [0, \infty] \) is measurable for \( n = 1, 2, 3, \ldots, f_1 \geq f_2 \geq f_3 \geq \cdots \geq 0 \), \( f_n(x) \rightarrow f(x) \) as \( n \rightarrow \infty \), for every \( x \in X \), and \( f_1 \in L^1(\mu) \). Prove that then

\[
\lim_{n \rightarrow \infty} \int_X f_n \, d\mu = \int_X f \, d\mu
\]

and show that this conclusion does not follow if the condition "\( f_1 \in L^1(\mu) \)" is omitted.

8 Put \( f_n = \chi_E \) if \( n \) is odd, \( f_n = 1 - \chi_E \) if \( n \) is even. What is the relevance of this example to Fatou's lemma?

9 Suppose \( \mu \) is a positive measure on \( X \), \( f: X \rightarrow [0, \infty] \) is measurable, \( \int_X f \, d\mu = c \), where \( 0 < c < \infty \), and \( \alpha \) is a constant. Prove that

\[\lim_{n \rightarrow \infty} \int_X n \log \left[ 1 + (f/n)^\alpha \right] \, d\mu =
\begin{cases}
\infty & \text{if } 0 < \alpha < 1, \\
c & \text{if } \alpha = 1, \\
0 & \text{if } 1 < \alpha < \infty.
\end{cases}\]

Hint: If \( \alpha \geq 1 \), the integrands are dominated by \( \alpha f \). If \( \alpha < 1 \), Fatou's lemma can be applied.

10 Suppose \( \mu(X) < \infty \), \( \{f_n\} \) is a sequence of bounded complex measurable functions on \( X \), and \( f_n \rightarrow f \) uniformly on \( X \). Prove that
\[
\lim_{n \rightarrow \infty} \int_X f_n \, d\mu = \int_X f \, d\mu,
\]
and show that the hypothesis "\( \mu(X) < \infty \)" cannot be omitted.

11 Show that
\[
A = \bigcap_{n=1}^{\infty} \bigcup_{k=n}^{\infty} E_k
\]
in Theorem 1.41, and hence prove the theorem without any reference to integration.

12 Suppose \( f \in L^1(\mu) \). Prove that to each \( \epsilon > 0 \) there exists a \( \delta > 0 \) such that \( \int_E |f| \, d\mu < \epsilon \) whenever \( \mu(E) < \delta \).

13 Show that proposition 1.24(c) is also true when \(c = \infty\).

* COMMENT chapter 02 positive borel measures :noexport:

** vector spaces

*** page 33
