#+title:Archive
#+author:MAO
#+startup: overview noindent margin
#+options: toc:3

# #+html_head: <link rel="stylesheet" type="text/css" href="https://orgmode.org/worg/style/worg.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css"/>
#+infojs_opt: view:info toc:3
#+HTML_LINK_HOME: index.html

* 2024
** 2024-10 October
*** 2024-10-8 Tuesday
**** 对于人的态度的察觉

以前是在高中，在那里，其实每个人都是没有什么坏的倾向的。我是一个老师，那么我的职责就是教好你。我是你的同学，那我们就共同进步，或者至少不相互干扰。

一种勉强、一种敷衍、一种自己没有察觉的沉醉，都是极度让人敏感的……我们亲爱的学长，仿佛是自己也不怎么想干这种事情的样子……真是令人无语……尤其对于我来说。

也就是这种事情最能打击人的积极性……

*** 2024-10-13 Sunday

**** AvPD

Avoidant personality disorder。也就是回避型人格。可以想象到的是，回避型依恋人格是一种简体中文的特供版本。

即使如此，加上一个 Disorder 未免是有点没有良心了。

这是一种巧合还是说？但总之两种 Disorder，都是完美地对上了。在这里我说，她为什么要提这个事情？也许是找了借口，想指出我当前的这种状态。

**** 累

体测累人，也只有这种时候才会想着“Damn，我早该做点运动”。

但今天让人想起那一年之前的事情啊，也就是酗酒而后体测之事。

像是怀念又不像是怀念。为何人都是要变化的呢？难道时间带来的变化都是让人伤感的吗？

*** 2024-10-14 Monday

这里是测试

*** 2024-10-15 Tuesday

**** 耻辱！

在写所谓的开题报告

耻辱！

当然只是因为不想写所以才那么别扭的

但是耻辱！

对于人的依赖，竟然到了这种程度

说是“依赖型人格障碍”……以前竟然不知道这类事物

即使是障碍也过于耻辱了！

**** 现在的肩膀还是痛的

这是何等的强力！

（这仅仅是因为体测而已）

*** 2024-10-16 Wednesday

**** AvPD 以及雪国
:PROPERTIES:
:CUSTOM_ID: xueguo
:END:

在雪国里的那种描写

徒劳作为关键词反复出现。

一种矛盾的话语，一种重复的说辞。到底是哪边呢？到底是在乎还是不在乎？

我想问清楚。但有什么在阻碍着……到底是作为人的能力下降了

*** 2024-10-18 Friday

**** Nicorenka

尼古拉和尼古连卡。说到底人是难以意识到后者怎么就是爱称了。

但假设用另一种思路来看，也就是考虑重音。

前者的话，应该是 ~ˈnɪkɚlaɪ~ ，但是对于后者来说 ~ˈnɪkɚˈrenka~ 了。

其实是差别很大的，后者确实更像爱称。尤其你尝试用日本人的读法的话。

可是我说这话谁又懂呢？

*** 2024-10-19 Saturday

**** 星期六，啥也不想干

但是今天还是搞了一些 org 的玩意。

到底是无聊的。

说起来挺想打电话的。但是……

在犹豫什么呢？

**** meta

今天还看见有人说为何要搞什么 meta-programming。真是愚蠢。不搞 meta 一点哪里来的 pattern matching 呢？

**** dere 是买不来的！

这只是一句很无聊的台词。

为什么突然想到呢？

可能从来不是迟钝，而是更吃 dere 这一套。

稍微想一下，如果说的是 せんぱい，且不是英语的那种重音，效果又会如何呢？

难道说人的真情都是会在这种小事之中被忽视而消散吗？

*** 2024-10-20 Sunday

**** 味道

人身上的味道……

一股药味，这倒是正当的理由，人总不能不治病

但还是很影响人……

**** 周日的图书馆

周日人多了，难不成来这里消遣的？

何必来这里做消遣，

把我的位置都占了。

**** 焦躁

一种焦躁，仿佛是那种说法，在什么上空的幽灵。说到底是什么……

……

到底是……

*** 2024-10-21 Monday

**** 君可知有些人只看 lesbian porn
:PROPERTIES:
:CUSTOM_ID: lesbianporn
:END:

我称这种现象为“和现实的短路”，和现实的短路连接，经验的重叠。

当人说出“I am not an actor”的时候，似乎能够预见其为什么只会看 lesbian porn：porn 里面演员们的演技，短路到现实之中，而现实是“I am not an actor”，于是一种重叠的、矛盾的经验让人产生了厌恶。而为什么 lesbian porn 会被人中意？为的就是消解“矛盾的”这一特征：lesbian 在取悦女人这方面自然地超过几乎所有男性。

从另一个角度，可以消解掉“短路”这一现象：如果我消费的产品不会让人联想到现实即可。仅仅从这个角度来说，似乎是可以解释的了。

**** Textual Poacher

中文翻译出版的时候有对原作者的采访，采访之中有提及耽美……

等会儿，说到底这个词究竟是如何诞生的？00 年代的时候就有这个词吗……

你们这些人真实罪孽不浅啊……

既然有男性和男性在性交，为什么不直接叫 BL！

**** 折腾

搞了一下午的问题，解决起来确实如此的简单。

只要将 ~init-org~ 放在最后就行了。

真是胡闹……

但这也说明了作日志是很重要的，因为我想起来说，就是从用了新的 org 开始，emacs 变得贼卡。

见鬼了
*** 2024-10-22 Tuesday
**** debug for org

Today I figure out why the inline math formulae looked very small in the exported html.

This is because that the width of the svg is not right. And then the css resize the width. Thus the formulae looked very small.

The problem can be solved after specifying the ~:page-width~ in
~org-html-latex-image-options~.

**** today I make a post in ~mildlypenis~ subreddit

And then maybe the "mildlypenis" is not mildly at all. It is just penis symbol but with a LaTeX symbol package.

I deleted the post (after I saw a fucking downvote).

ps. reddit is so powerful because I can literally see the ratio. Damn.

**** 重复

[[*AvPD 以及雪国]]

一种常常说出口的话语就在这里。令人怀念的感觉……

就好像雪国里面那样，驹子的一本本厚厚的日记……

岛村看到了，“徒劳”二字浮现出来。倒不是日记真的徒劳，而是……

是不是偶尔会想到雪国是不是就是这个原因呢？

这种反复到底意味着什么？这虚幻的，倒不是那种让人心生怜爱的事物，反而是搅动了什么，让人感到了什么

一种 detachment，又或者说 bewilderedness？为什么说是“令人怀念”，就如同许久以前的那样。原来也有这一层的原因……

人到底还是太贪心了

[2024-10-22 Tue 20:18]

**** 累了不想搞

其实是很简单的事情，具体来说就是写 PPT 这种程度的事情。直接复制上去就可以了。但是……想到要将这种其实没什么价值的事物念出来……真是丢人！

[2024-10-22 Tue 20:22]

**** 腰部

一个人的手，应该放在哪里呢？

在腰部上的这个部分，也就是硬的和石头一样的这个部分，手放在这个地方上非常适合

非常适合……

*** 2024-10-23 Wednesday

**** 有关 R18 音声的思考

说到底就是两个字：官能。如果要用别的字眼的话，那就是感官。

对于音声来说，要达成的就是一种共感：如何要用听觉传达出别的感官上的刺激？

人都是精神的生物。要做到这点，只能说靠大脑欺骗自己。让精神接受那听觉的官能之中的暗示，作为其他官能的媒介。

人的感受力就是关于接受这种暗示的能力。

这样的话似乎能够解释这种现象：音声之中出现的体液的声音、“stimulator”的震动声，几乎是最让人 turn on 的声音。

这里说得太直接了，过于羞耻，于是言尽于此。

**** 咖啡吓人

有点 Panic Attack，现在感觉更像是咖啡导致的。

*** 2024-10-24 Thursday

**** 很严重的发现！

草婴的《安娜》的译本的前言，居然有借鉴的痕迹！

真是可耻啊。

**** 答辩了

作为第一个上去的，感觉担忧的事物其实在人眼中是那么无关紧要的事情。伤心

**** 又想看 Ulysses 了

但是我和 War and Peace 对比了一下，结果还是后者好看得多。

所以看个毛线的 Ulysses。

*** 2024-10-25 Friday

**** 又整了一些 Emacs

得不偿失！但事实果真如此？

究竟到底，只是消遣时间……

[2024-10-25 Fri 12:54]

**** today I learn how to modify the frame parameter

#+begin_src emacs-lisp
  (modify-all-frames-parameters
   '((right-divider-width . 20)
     (internal-border-width . 10)))
#+end_src

And also I install ~org-modern~, and other things. I have learn a lot. And also
I know that ~window-divider~ is the name of the face line/border between
windows. Customizing that face helps a lot.

#+begin_src emacs-lisp
  (dolist (face '(window-divider
                  window-divider-first-pixel
                  window-divider-last-pixel))
    (face-spec-reset-face face)
    (set-face-foreground face (face-attribute 'default :background)))
#+end_src

**** Alternative

看到了吉成钢的作画

COOL~~~~~~~~~~~~~~

着实好看

但感觉 Muv Luv 像是变成超级系机器人动画了，就像是 Gurren Lagann 里面的剧情一样了，“接下来是准备让谁牺牲呢？”，竟然能让人怀着这种心情……

感觉能把这种有点右翼的情结写得和机器人动画一样，有点别扭地好笑

欸！

[2024-10-25 Fri 19:52]

**** Bangledash

人也是被逼的，家庭产业吗？

可能是我见识少了还是如何，但确实少见

人都是有苦衷的啊

只不过我可没有闲工夫来帮你

[2024-10-25 Fri 22:29]

*** 2024-10-26 Saturday

**** 人还是得和人讲话

受不了……确实受不了

**** boki

王朔的《动物凶猛》，倒不是作品本身有什么可说的

而是一个对于勃起的描写

就是小伙伴们脱光了衣服去泳池玩，有男有女的，还不是精虫上脑的年龄，甚至恰恰相反

直言，“在那里，却看见了骇人的勃起”

主人公就怒斥这个勃起的家伙，叫他滚，然后他就滚了

骇人吗……确实骇人，丑陋！

PS. 找了一下原文

#+begin_quote
“直了直了！”大家忽然一起指了半大的孩子。

在倥偬悠高的手电光中，我看到一个骇人的勃起。

犹如肚子被撞了一肘，我感到一阵恶心。就像人脑袋上突然长出一枝梅花鹿的角杈令我无法忍受，简直是活见鬼！
#+end_quote

[2024-10-26 Sat]

*** 2024-10-27 Sunday

**** VILE PH

这个组织可以使用 vile 来形容！

简直是 society of control 之下的典范

在这里，用户没有被当作人来看待，而是数据，是 database 里的一条 entity

作为感性的 fetish 被 algorithms 揣测

**** 每个人的 Vices

每个人都有的 Vices

都是等待偿还的债

**** Denote 好像找到一点感觉了

#+begin_quote
"好像找到一点感觉了"
#+end_quote

怎么感觉有些色情

总之 denote 将 query 的职责完全推卸了，file tag 全部体现在文件名上面，于是 query 就交给用户了

有点卑鄙

**** 为了鸡汤掉书袋

其实连掉书袋都算不上，就如同国外就已经有的，拿着斯多葛主义的名声，写一些垃圾至极的鸡汤

在简中也渐渐流行了起来吗……

其实不如读一读圣经来的好，虽然所有人都瞧不起圣经，但谁又瞧得起你那些东西呢？

想起了谷崎润一郎的《少将滋干之母》，又想起了京阿尼火灾纪录片里的一位。
看到了自己女儿烧焦的死尸，受到了冲击，转向圣经以寻慰藉……

到底是人生的启示，还是面对灾难的应激反应？

那么对于今天这些人，到底是哪里来的蛊惑的力量，又满足了什么需求呢？

[2024-10-27 Sun 18:41]
* archive
:PROPERTIES:
:CUSTOM_ID: archive
:END:

** 针对「身患红斑狼疮晚期的上海女子沙白，赴瑞士自杀」掀起舆论热潮，你怎么想？
Homeros 等 23 人赞同了该回答

本老保觉得 “去瑞自裁女” 和 “在日饿殍女” 这俩人差不多，被我归于目田的后现代猪队友这一类，我对这种人没有同情心，就像我不同情饿殍女这种没有自理能力的人，就像我更不同情嫌下馆子贵，又不会做饭，天天抱怨环境的小留学生一样。

作为一个人，你应该先成为一个合格的动物（有求生欲，能维系肉体存在，能自己觅食，能满足好自己的肠胃），满足前现代性，再成为一个合格的人类（活得有尊严有健康有自由），满足现代性。最后再扯什么追求啊观点啊实现啊这些后现代的东西。而在日饿殍女直接无视了前两步，知道自己低血糖还要喝无糖可乐，我觉得也属于一种精神异化了。这个去瑞自裁女也差不多，有病不治，还扯什么自由啊、生活啊、尊严啊之类的形而上词汇，不为 “实在” 而活或死，却为了 “虚无的理念” 送死，我觉得无法理解。

[2024-10-28 Mon]

** 斯坦福监狱实验是否具有普适性？

赵泠
2023 年度新知答主 [fn:: inline footnote]

236 人赞同了该回答

否，斯坦福监狱实验的结论不会具有普适性，因为该结果来自学术造假。这是心理学界的巨大丑闻。

2018 年，Medium、Vox 等媒体刊登了揭露该学术造假的文章。2019 年，更彻底地揭穿该学术造假的文章发表在 American Psychologist[1]。

  - 2018 年的证据是当年负责斯坦福监狱实验的心理学家 Philip Zimbardo 的未发表录音和对参与者的采访，这些证据显示，扮演 “警卫” 的参与者被明确教导要残忍，实验中最令人难忘的时刻 —— 一名 “囚犯” 突然高叫 "I mean, Jesus Christ, I’m burning up inside!"—— 是即兴表演。
  - Zimbardo 在 1971 年明确声称实验中的 “警卫” 没有得到关于要做什么的具体指导或培训。
  - 2019 年，参考 1 列出了更多证据，显示扮演警卫的参与者知道实验者想要他们做什么、实验结果是预先设定的。

Simine Vazire 等心理学家公开表示，应当从教科书删除斯坦福监狱实验。

社会心理学家 Jay Van Bavel 称，底线是，从众不是自然的、不是盲目的、不是不可避免的。Zimbardo 在这方面误导了数百万人。

在 Vox 的相关文章里，作者 Brian Resnick 称，心理学中一些经典的、著名的、令人叹为观止的实验已被证明是错误的、欺诈的或过时的，教科书应当修改相关表述或移除它们。

  - 例如，罗夏墨迹测试不能像历史上某些研究声称的那样揭示某人的更多特征 [2]。
  - 例如，Muzafer Sherif 的罗伯山洞实验包含学术造假，作者做了失败的实验，丢弃了反驳其假设的数据。
  - 例如，Stanley Milgram 关于服从的实验包含学术造假 [3]。不过，类似的实验在适当条件下是可以复制的。

一些读者可能条件反射式地想起 “25 号宇宙”。

你怎么看待 “25 号宇宙” 这个实验？
2292 赞同・17 评论回答
参考

1 https://www.gwern.net/docs/psychology/2019-letexier.pdf\\
2 http://moemesto.ru/rorschach_club/file/895917/download/56-3-2000-5%252520Rorschahiana4.pdf\\
3 Perry, G., Brannigan, A., Wanner, R. A., & Stam, H. (2020). Credibility and Incredulity in Milgram’s Obedience Experiments: A Reanalysis of an Unpublished Test. Social Psychology Quarterly, 83(1), 88-106. https://doi.org/10.1177/0190272519861952\\
编辑于 2024-10-26 20:24

(ps. vox 的文章连接在这里 https://www.vox.com/2018/6/13/17449118/stanford-prison-experiment-fraud-psychology-replication)

[2024-10-27 Sun]

** 如果国家每个月给每个公民发 500 元人民币，一直持续下去，会逐渐的产生什么样的影响？
212 人赞同了该回答

贫穷是真限制了大家的想象力啊…… 发个 500 块钱还得加上 “极端理想情况” 的前提。

就算这笔钱不发给每个公民，也会首先发给银行、投资商来 “刺激经济”，说什么发给公民就会造成 “通货膨胀”，楼下那群人真是脑子被驴踢了。

在通货膨胀中，只有越靠后拿到这笔钱的人才越有可能受到通货膨胀的实际影响（因为 “坎蒂隆效应” 钱到他手上的时候已经不值钱了），如果这笔钱是首先发给银行、投资商，那么全盘接受通货膨胀影响的才无疑将是每一个公民。

这不是一个 “给与不给” 的问题，而是一个 “先给谁” 的问题。

正如哈耶克在《通往奴役之路》中所区分的属于每个人的 “有限度的保障” 与只属于一部分利益集团的 “绝对的保障”：

#+begin_quote
一种是有限度的保障，它是大家都能够获得的，因而，不是什么特权，而是人们可以期望的正当目标。一种是绝对的保障，在自由社会里，这种绝对的保障不可能让所有人都得到，也不应当把它当作特权给予任何人，除非在极少数的特殊情况下，例如法官，其完全的独立才是非常重要的。

这两种保障中的第一种是，防止严重的物质匮乏的保障，即确保每个人维持生计的某种最低需要；第二种是，某种生活水准的保障，或者说，一个人或集团与其他的人或集团相比较的相对地位的保障；或者，我们可以简单地说，可以区分为一个最低限度的收入的保障和一个人被认为应有的特定收入的保障。
#+end_quote

美国、英国、德国、法国、日本、韩国、新加坡以及中国香港与台湾地区都用他们的实际行动告诉人们：如果这笔钱一定要被利维坦花出去的话，先把钱给公民要远比把钱给银行更减少对经济的波动。

美国：3 月 19 日，美国政府宣布将实行 1.2 万亿美元的经济刺激计划，具体的实施方案是，把钱直接发给国民。发钱的标准为成人 1000 美元，儿童 500 美元。

加拿大：3 月 18 日，加拿大财政部长宣布，将实施 250 亿加币的经济援助计划，这笔钱将会直接打到个人账户，形式为牛奶金和就业保险金。这里说一下，加拿大是北美福利最完善的国家，生一个孩子每年能领到 6000 加币左右的牛奶金。

日本：为了减轻疫情对国民经济生活的影响，日本政府正在考虑向每位国民发放现金。在 2008 年经济危机的时候，日本政府就发过钱，那次向每位国民发放了 12000 日元，这次应该也不会少于这个数字。

中国澳门：疫情出现后，中国澳门特区政府将 2020 的 “现金分享计划” 提前，最早 4 月份就开始发钱。每个澳门居民能收到 10000 元的红包。除了提前发红包，澳门政府还给每位居民发放了价值 3000 元的购物券。

中国澳门和中国香港 “现金分享计划”，每到年底给居民发 “利是”。香港发一万港币左右，澳门发 9000 澳币左右。

在几年前疫情初期的时候，就有人讨论过发不发钱这个问题，当时网上一片骂声全部反对，甚至出现了 “发钱等于不发钱” 这种弱智谣言，而站在今天的历史坐标往回看，这个问题的热度再也赶不上当年 —— 因为疫情真的让那些疯狂叫嚣（以为自己一辈子都会在有钱人行列）的企业主们和自视甚高的企业精英高管们破产了。

[2024-10-27 Sun]

** 最顶尖的程序员是不是不屑写注释？
884 人赞同了该回答

团队里有个大佬，注释写得很详细。他写的注释一般会包括：

  - 选择当前的实现的原因是什么（当解决此问题有多种办法时，为什么其他方案不如当前实现）；
  - 参数的注意事项，各种参数的范围，以及少见的组合可能会出现的 tricky 的问题；
  - 一些技术标准或外部依赖的参考资料，比如用了 uri 相关的术语，就把 uri 术语 rfc 链接上；或者用了三方库，会把库官方说明的参考资料列上；
  - 整体架构和当前类，或当前函数的关系的阐述；
  - 等等。

一开始我也对他写注释这么详细不以为然，直到后面碰到问题时（比如用到这个接口关心一些相关技术细节，或者接口返回值不符合预期），总能在他的注释里面找到说明或指引，我才意识到这样做的重要性，也总会在心里默默感叹一句，大佬 nb。给我的感觉是，写代码在他那里就如阳明心学说的，是一种 “用敬” 的功夫，从写注释的认真程度里可见一斑。

又可能有人会说，这些最好放在设计文档里，而不是注释里。但是，实际项目中你就会发现，有时候是没有留时间给你一些小改动做设计文档的。而且写在注释里也有文档比不了的好处，比如方便看到。

总之，会写注释的人，写出来的注释是非常有价值的；不会写注释的人，写出不写都一样，甚至起反作用（注释实现不匹配以至于误导后来者）。

[2024-10-27 Sun]

** 应试教育到底危害谁了？

Henry博雅教育

217 人赞同了该回答

应试教育最大的危害是让费拉青年更加费拉不堪。

应试教育的整个过程中，没有任何团队协作，参与者只要一条板凳、一张书桌，书簿纸张文具若干，就可以开搞。这会让费拉青年产生一种幻想，那就是 “我一个人就行”。

所以我们看到，应试教育的佼佼者大多数是一些独来独往的白面书生，因为这样的人心里比较平静，能耐得住寂寞，可以全身心投入到刷题中来，也就是俗称性格比较孤僻、甚至有点社交障碍的人（无意冒犯，事实如此）。

长此以往，这些费拉青年会产生强烈的路径依赖，陷入只要 “考试成绩好就一切都好” 的幻觉。

但是最终他们会发现，应试教育并不能改变他们的阶级地位，却剥夺了他们本可以在青年时期甚至更早就可以发展出的与他人团结协作的能力，这个伤害将会影响终身。

还有一个问题，不是应试教育的问题，而是学校的问题，其实这些学校存在的目的就是为了割裂学生与乡土、社区的联系，同时也不允许学生在学校里联合成新的组织，如禁止拉帮结派、禁止聚众喧哗等学生守则，目的就在于此。

最终的结果是应试教育的佼佼者可能会因为优越的文凭获得一些吃食，但是阶级地位没有任何变化，依然是城市里的原子人。他们出身的原社区则为国家输走了相对聪明的子弟，青年智力被榨干，也将继续衰败下去，同样是受害者。

结论：应试教育是流沙社会的产物，并进一步让社会流沙化。同时，流沙社会的人也很难理解这一点。

[2024-10-27 Sun]

** 有哪些反直觉的历史事实？

七暮
在虚无的漩涡里越陷越深，懒得挣扎

6087 人赞同了该回答

1967 年上海有极左造反派提出了十条主张:

第一，干部的收入财产要公开公示，以此杜绝腐化堕落。

第二，要建立退休机制，任何人员都要有相关的退休制度，不得终身制。

第三，允许个体工商户，承认个体工商户是无产阶级，只要不牵扯雇佣关系，那么就不算剥削。

第四，反对包产到户和分田单干，支持人民公社，并且要求把公社演变成公司制度，农民由身份变为职业，实现农民职业化，改称为 “农业工人”，一律按工人编制对待，享受工人的福利待遇。

第五，在工厂里引入合适的奖金制度和物质刺激，但是要公平合理数额何时，不要引起巨大的贫富差异。

第六，真正落实民主集中制。

第七，要让法律成为无产阶级的法律，并且任何人不准逾越法律，普及法律知识，不要成为法盲，树立法律意识。

第八，坚持 “两参一改三结合” 的思路，继续保持工人阶级的领导地位。

第九，加强民生建设，建立广泛全面的福利保障制度，要破除 “不劳动者不得食” 的旧观念，切实的保障民生。

第十，限制干部权利，减少机构臃肿，加强对干部的思想和能力考察。

[2024-10-27 Sun]

** 国内 ACG 作品频繁遭举报的根本原因是什么？

泰格

5333 人赞同了该回答

作为曾经受理举报（主要是广电领域）的人，走出来以后，我的理解是：

“被举报” 其实还不是问题发展到当前程度的症结。更多时候，“被举报” 是一个面上的说法。真的来自普通群众的自发的举报，有，但要形成足以影响政策的气候，不容易。更多的情况是 “因缘际会”，执事者已有心意，扒拉扒拉群众来信，嗯，正好有相关的，这就对上了。

最根本的问题，我原来提过，还是对 ACG 等各种亚文化的根本性的政治不信任。从摇滚到说唱再到脱口秀，凡是跟思想挂点边的东西，都逃不过这一境地。

这种不信任是根植于意识形态取向的对立性上的。亚文化之所以叫 “亚”，就是因为它天然带有某些反主流的意识形态特质。主流意识形态越是强调集中统一，这种张力就不可避免地越大。这不是哪个人、哪部作品或者哪类亚文化招惹了谁的问题，是与生俱来的天然矛盾的问题。

我也不知道怎么解决这个信任问题。理论上是无解的。主流意识形态和亚文化之间的张力，是人类历史的客观存在，资本和商品化的介入往往还能一定程度的 “稀释” 这种张力（我之前写过回答解释资本在消解亚文化方面的原理），但我们这里不一样。

[[https://www.zhihu.com/question/427535896/answer/1545238749][如何看待 10.27 央视新闻公众号关于解释 “内卷” 的视频？]]

这也是为什么我始终从根本上不看好亚文化在中国的发展，尤其是产业化发展。

在中国搞亚文化，最多也只能在相对较小范围内的 “地下” 搞，不要盲目尝试进入大众视野，因为一旦 “出圈” 就极大概率（目前我还没见到例外，但先不把话说死）精神性死亡，说白了就是亚文化的形式性内容被 “俗化” 且精神性内容被实质上的 “扼杀”。

那些尝试搞亚文化和主流文化融合的，不管初心有多好，最好的结局也只能是被评价为不伦不类但无伤大雅，基本上普遍会被原来的亚文化社群评价为 “取悦”“献媚”，搞不好还会被主流文化评价为 “糖衣炮弹”“包藏祸心”。

— 完 —

[2024-10-25 Fri]

** 中国当代文坛能否出一位像卡夫卡一样的作家？

Zpuzzle

大学等 4 个话题下的优秀答主

1351 人赞同了该回答

这个问题算是我今年以来看过的最好笑的问题之一了。哪怕你拿海明威、福克纳、马尔克斯等人举例子，然后再得出个 “不可能” 的结论，无论这中间的论证过程多么荒唐，但总归可以证明 “我们为什么发掘不出海明威、马尔克斯”。而卡夫卡呢？

因为只要稍微了解一点卡夫卡的生平就知道，卡夫卡是一个死后才得到普遍认可的作家。卡夫卡生前也是发表过作品的，也得到过一定的好评，但是这与卡夫卡死后才获得名气根本不可同日而语。也就是说，卡夫卡是一个生前并未得到广泛认可的顶级作家，这与梵高在美术界的遭遇如出一辙。

然而，卡夫卡有这样的遭遇又太过正常，甚至可以说这才是卡夫卡最好的归宿。因为卡夫卡之所以是卡夫卡，就是因为他在那个特殊的时代里，有了超出了同时代人的写作，而这种写作在当时的时代并不被认可。

或者说，只要稍微具备那么一点点文学知识的人，应该都能知道卡夫卡《变形记》、《城堡》等一系列小说要表达的主题是什么。那么，请问卡夫卡为什么要 “变形”？

关于这个事情，其实我之前在其他的很多问题下都已经说过，就是人不要双标。什么意思呢？当一个人称赞 “X 国的电影真是敢拍，这种事情都能拍” 的时候，那等于默认了 X 国的现实就是这样的，否则也不存在 “敢拍” 的问题。可很多人双标的地方就在于，一方面看着各种反映 X 国现实的影视作品称赞其 “敢拍”，另一方面又会用其他证据证明 X 过政通人和、人人都生活幸福。

那么请问，那个电影拍的到底是啥？

回到卡夫卡的作品里来说，如果你认为《变形记》的好，是写出了 “小说以主人公变为甲虫这一荒诞故事反映了世人唯利是图、对金钱顶礼膜拜、对真情人性不屑一顾，最终被社会挤压变形的现实”，那么这个 “世人唯利是图、对金钱顶礼膜拜、对真情人性不屑一顾” 的社会，不正是卡夫卡自己所生活的环境么？

高林老师的话说的有点难听，不过也确实说到了点子上：

#+begin_quote
这个问题有意思的地方在于，一大群庸俗、市侩的人想方设法证明卡夫卡是文化、教养、财富的产物，卡夫卡出身犹太富商.. 以这些外在的、肤浅的理由来判断 “我们不会拥有一个卡夫卡”。而这种对文学的肤浅理解、对创作的可笑解释，倒是充满了促成卡夫卡的那个愚蠢、呆板、沉闷的布拉格市民社会的气息。这些人在线下要是一脚踹开自己儿子的门大喊 “你也不看看自己几斤几两还敢在纸上瞎划拉？” 也一点不奇怪。
#+end_quote

充分的物质保障、相对自由的环境、良好的教育背景…… 这些因素只是可以诞生优秀文化的土壤，或者说是诞生优秀文化、优秀作品的背景，但并不表示其必然就会诞生优秀的作品。对于文学、文化的庸俗理解，就是 “我给了你这么好的条件，你必须给我创造出好的作品”，然而，马克思早就指出了艺术发展与社会发展的不对称性，也就是说艺术的发展有其独立的脉络，并不是经济越发达、社会越自由，艺术就越好。即便不看马克思的理论解释，文学史、艺术史也都能清晰无误的反映这一点。

比如，如果非按照 “自由” 作为伟大文学创造的必要条件，那没有任何人可以想象中国文学史上最伟大的文学作品居然诞生于文字狱最盛的年代。与此同时，也没人想到，中国古代学术史的巅峰，居然也是出现在这个时代。

所以，文字狱是催生艺术、学术繁荣的必要条件？

而按照这种对文艺创作、学术研究的庸俗理解，我之前还开过玩笑，说如果按照诺贝尔科学奖代表了国际水平评价的最高标准来理解，那么中国获得诺贝尔奖的科学发现 —— 青蒿素，诞生于 1972 年。而另一项已经非常接近诺贝尔奖成果的人工合成牛胰岛素，诞生于 1965 年。这两项发明均诞生于文革前后。这说明了什么？说明中国科技距离世界顶尖水平只差一场无产阶级文化大革命。

这可笑么？但按照某些人的逻辑来讲，这就是成立的。

虽然几乎所有人都在课堂上学习过语文，但绝大多数人对文学都是极其陌生的 —— 甚至于大多数所谓的 “文学教授”，更熟悉的也只是 “文学理论”，而对 “文学” 可以说没多少了解。其实无论是文学、艺术还是科学发现，本身就具有极大的不可控性。普通的作家、工程师、科学家等等，是可以通过一定的有计划地培养，大规模生产的，但是天才级别的人物，是完全不受这个规律制约的。或者说，正是因为天才极低的出现概率，才决定了他的出现具有高度不可控、不可预测性。

并且，可能更让某些人觉得难以理解的地方在于，越是好的条件保障，对于文艺的创作来说可能越是有害的。举凡文学艺术史上，绝大多数伟大艺术家的一生都不是一帆风顺的，很多人甚至还会频频遭遇人生变故。他们虽然获得了当世和后世的一致认可，但他们的人生缺并不幸福。另一些人，靠着一些杰出的作品获得了官职、财富或者其他保障，但自此之后他们的创造力也大大衰减，几乎再难以创作出好的作品。

不说那些已经作古的人物，就说知乎读者更熟悉的刘慈欣，自从靠着《三体》出名、实现了财富自由之后，如今刘慈欣的生活状态也已经完全改变了。如果说当年的刘慈欣搞创作，是在国企工作之余的摸鱼，可以把全部的身心都投入到写作中，那么如今作为公众人物的刘慈欣，最主要的工作就是开会、演讲、应酬等等。刘慈欣的确比以前生活的更好了，但你看看他过去 10 年出版的作品，你认为他再创作出《三体》—— 甚至都不用说《三体》，能有《三体》一半水平就行 —— 的概率有多大？


而以卡夫卡的人生经历而言，就算真的出了 “卡夫卡一样的作家”，等待他的也只是默默无闻的人生，且卡夫卡本人的性格也不习惯于成名后的生活。可以这么说，如果卡夫卡真的成名了，过上了极为富足的生活，他所面临的就是个人创作力的全面崩塌。

至于如蛤蟆所说：


这你要有这种文学环境，那不是在发掘卡夫卡，而是在扼杀卡夫卡。

当然，如果是商业文学创作，良好的商业机制是不可或缺的。只不过，包括蛤蟆在内的几乎所有的网文作者，因为是从网文这个圈子里成长起来的，所以认为天底下所有的文学都是这样。

卡夫卡这样的作家与商家作家最大的区别是，商业作家以市场为最主要的考量标准，一个好的商业作家是对市场有好的感受力的作家，他创作的作品越符合大众的需求，其受欢迎程度就越高，这是一个相互促进的关系。但是，卡夫卡这样的作家，从他们获得大众认可的那一刻起，他们也就基本丧失了自己的文学生命。

作为作家的卡夫卡，其最大的特点就是 “反体系”。这也就意味着，无论你期待以任何体系化的方式培养卡夫卡，只要这个体系一旦出现，那么卡夫卡就一定会出现在体系之外。而且，因为出现在体系之外，卡夫卡想要获得这个体系的认可也自然是很难的。

但对于卡夫卡来说，这是无所谓的。

如果真的期待中国能出现一位卡夫卡式的作家，那么首先需要做的，就是先放弃对这样一位作家的期待，因为即便他出现了，你也发现不了。

在我看来，期待出现卡夫卡一样的作家，只需要做到以下十个字就够了：

当他不存在，让他随便写。

[2024-10-24 Thu]

** 读史书时有没有让你笑出声的段落？

大汉魏王曹孟德 等 2571 人赞同了该回答

1958 年，中国人民大学出版了一本书，《高等学校右派言论选编》。试举一例如下：

#+begin_quote
“在我們社会里有一个阶層，处处享受特权。建筑工人盖了那么多楼房，可是他們自己只能任茅屋，享受特权的都是些干部。高級知识分子吃得很好，与一般人民相差太远。現在没有人敢大胆地来写反映这些現象的詩，因此我产生感慨和怀疑。我也知道党照顧高級知識分子是为了長远利益，但在感情上却接受不了。……‘谈’的文章‘阶级社会里的等级制度’，我觉得很有道理，说出了我不敢说的话。当然我在本質上是和他不同的。”

（北京大学 左言东）
#+end_quote

#+begin_quote
“在育才小学学习的都是党员高级干部的子女，他们父亲是党员，母亲是党员，将来自己也必定是党员，这是草成一个新的贵族阶级。”

（中山大学 董每戡）
#+end_quote

PS: 评论依旧是系统关掉的。
[2024-10-23 Wed]

** iroha tenga

As you can see, ~iroha tenga~ is adultery goods for women, while ~tenga~ is famous for making adultery goods for men.

[2024-10-23 Wed]

** 为什么 JRPG 没有选择电影叙事（反戏剧），而是沦为了舞台剧演出风格，这是否是漫画造成的影响？

神必天坑 神必壬

40 人赞同了该回答

感觉还是有必要对于 @护士衫下 的回答做一些补充。

首先所谓的角色不是东浩纪发明的，也不是东浩纪提出数据库消费的 90 年代才有。手冢治虫其实在画漫画的时候就已经觉察到了角色是标签符号的组合了。

#+begin_quote
我画的画，（人物）惊讶时眼睛就会睁圆，发怒时就会像老头一样眼睛周围出现皱纹，（这样）面容就栩栩如生了。是的，其中存在着样式（pattern），也就是一种符号（記号）。接着，把一个样式与这个和那个样式组合，就成了一张有条理的类似画的东西。但这还不是真正的绘画，而是极为省略的符号。（中略）也就是说，对我来说漫画只不过是表现手段的 “行话”（符牒，意为同业者之间使用的暗语、“黑话”），实际上，我觉得我并不是在画画，而是以一种特殊的文字在书写话语。（手塚治虫采访「珈琲と紅茶で深夜まで」「ぱふ」七九年一〇月号）
#+end_quote

并且如果就单纯的把数据库把握成贴标签那么其实你就会发现数据库出现在从古至今的各种文艺中，而不是当代特征，这其实对东浩纪是误读。

#+begin_src emacs-lisp
但是如果只看东浩纪的《动物化的后现代》，认为当下宅文化的表现方式就是从数据库中抽取（sampling）“萌要素” 来加以组合并觉得这就是 “后现代性” 的话，放在今天来看，这种思考实在是过于单纯。中世的语部，以及本书未能说明的近世的歌舞伎，还有战后漫画，每个时代的物语表现形式其实都是从数据库中抽取要素，把事先存在的样式组合起来。

—— 大冢英志《角色小说的制作方法》
#+end_src

#+begin_quote
若以 “夸张化的性格” 与 “戏画式的人物” 这些模糊印象来使用 “角色” 这一词语，讨论立刻就会被导向错误的方向。例如说什么，登场人物的夸张化是自古以来就有的，所以角色小说是中世纪开始就存在的，纯文学实际上也就是角色小说，之类的（实际上的确也有这样的主张）。

—— 东浩纪《离 “世界” 更近》
#+end_quote

东浩纪想要论证的当代角色小说的特征是角色能够脱离原本的故事而自我存在，用他的说法就是 meta 性。福尔摩斯在柯南道尔笔下那就是福尔摩斯，但是如果能给他转生异世界、进入幻想乡、娘化，那才意味着这是角色。不过东浩纪理论在这里的讨论中是细枝末节。

然后其实说东浩纪考察的是动画和漫画，其实不如说他是从动画、漫画、轻小说、galgame 等等整合起来的日本内容产业，考察当代日本社会乃至全世界社会的样貌，以及文学的样貌。而且其实东浩纪反而不太懂动画和漫画，感觉上他跟多动画史漫画史都是从大冢英志这边云的，他比较懂的是 galgame。

#+begin_quote
现代作家难以描写社会，也难以描写人类。所以他们转而描写角色。而这依赖于与读者共有的角色数据库。…… 当然也有很多人反对这种流向，他们认为文学就应当坚持描写社会与人，去直面人类的他者，而非依赖于角色。这确实有道理，但问题在于不再存在像以前那样强烈的 “社会性现实”，无论怎样去描写，最后都会变成好像在哪见过的扁平人，好像在哪读过的故事，许多作家都面对着这个纠葛。…… 现代人已经从 “世界” 中脱离了。现代社会是如此复杂，我们早已无法从社会全体的角度来看待问题，也难以面对各种各样不同价值观的人。
#+end_quote

另一方面所谓的贴标签和故事是对立的吗？恰恰相反！

#+begin_quote
创作人物的关键在于主人公的外貌、设定上的个性是否与剧情的总基调有适当的联系。 可见 “异色瞳的幽灵猎手少年的战斗故事” 和 “一个因为异色瞳而不得不成为幽灵猎手的少年的故事” 的区别。重要的是，“拥有不同颜色的眼睛” 这一角色特征和 “猎杀幽灵” 这一剧情框架是自然衔接的。如果你好好对待这个程序，“故事” 就已经成立了一半。
#+end_quote

#+begin_quote
如果是这样的话，那么那些将异色瞳角色当作主人公的投稿者们也许并没有把主人公的 “外表” 和他们要写的 “故事” 很好地联系起来。我认为这才是应该反思的地方。
#+end_quote

#+begin_quote
故事和角色不吻合的原因，是因为故事首先不是从角色设定中逻辑地衍生出来的。角色在剧中的性格变化也是一个问题，如果角色的设定和角色的行动原则是相通的，就不会出现这样的问题。也就是说，在没有任何根据的情况下，将人物设定为 “冷酷无情”，性格就会变得不稳定。但如果这个角色的性格自然而然地来源于他的左右眼不同→他能看到别人看不到的东西→他不喜欢自己的力量→所以才会内向，讨厌别人，像这样来自然地导入人物性格，在角色描写的时候就不会产生混乱。
#+end_quote

还一方面是跑团确实是活生生的玩家，但是玩家在扮演自己车的卡也就是角色。如果用贴标签的框架来分析，跑团车卡不就是一个贴标签的过程么。比如说我以前和朋友跑团时车的卡：

#+begin_verse
———— 角色 ————
角色名：埃琳 Eryn
玩家：天坑
种族：月精灵
职业：法师 - 防护学派
性别：女
年龄：45
阵营：混乱善良
信仰：月亮女神塞伦涅
———— 角色细节 ————
身高：5’3”（162cm）
体重： 114 磅（51.7kg）
发色：银白色
自由散漫的月精灵少女，有些自傲喜欢夸耀自己的才能和知识。同时不怎么考虑自己的言辞因而经常冒犯他人，也因此和他人的关系都不是太好，但自己对此不怎么在意。他认为言辞的条条框框也是拘束。因为和大家关系不太好，时常泡在图书馆，对于图书馆中的知识很感兴趣。在阅览图书时，偶然打开了一本古老封印书，里面封印着一只古老的魔法生物。魔法生物并不在意她的有些冒犯的言辞，很快成为了好朋友。作为回报，魔法生物教了一些魔法的基础。看到了魔法的许多有趣的效果后，便对魔法产生了极大的兴趣，决定专门研习魔法领域。在图书馆中阅览了大量的书籍后，她感到需要外出旅行来进一步精进了。她喜欢悠哉游哉的冒险，不喜欢各类条条框框，所以也不怎会定居在一个地方很久。如今，埃琳作为精灵虽然距离成年还有相当一段时间，不过丰富的旅行见闻和战斗经历让她能够在冒险中独当一面。对她来说，追求的东西只有两个：知识和无拘无束。
#+end_verse

顺带一提在那次团里因为我的角色经常知识鉴定失败所以又被贴上了不学无术的设定（标签）

同样你去看 the gamers 里面对于跑团的演绎，他们就是很刻板贴标签。甚至可以说，跑团是 rpg 贴标签的一个代表。

所以这还是要导向先问是不是，在问为什么。

贴标签真的是所有 jrpg 的操作方法么？这个问题可以说不是，或者说是因为我们在当代，所以接受作品的方法是这样的、贴标签式的，所以万事万物都只能通过贴标签来认识。

真的只有 jrpg 有这个特征么？crpg、或者其他 rpg 真的没有么？因为我玩的少，我不敢评价。

其实 @护士衫下 的回答还有一些地方需要修正的，不过我没时间继续写了，先这样的。

[2024-10-22 Tue]

** 该怎么写一篇和 galgame 有关的论文？

神必天坑 神必壬

50 人赞同了该回答

提出这个问题我想关键问题可能不是 galgame 有关而是怎么写论文。第一步还是先写个开题报告吧。不是给别人看而是梳理自己的论文思路。

**** 研究背景

你为什么要研究 galgame，你要在什么领域研究？是文学 / 社会科学研究？还是营销、市场、广告学研究？还是艺术研究？还是技术研究？不同专业领域着重的问题侧重点是完全不一样的。当然正如游戏研究可能是跨学科的，但是这也意味着你要对多个学科的框架都有理解才能做。

研究 galgame 在这些领域里能够解决这些领域的什么问题？

比如说，如果你要研究我国青年文化，以 galgame 社群为例，你就要知道自己面对的时代背景，中国当代青年的社会生活的背景，galgame 如何跨越国界和还下进入中国的背景，互联网时代的背景，galgame 与游戏、galgame 与二次元的关系，中国和日本的社会区别和联系等等等等

**** 研究目的

你要具体的针对哪个问题来进行解决？这个问题详细内容是什么？怎么通过研究 galgame 来解决？

上述背景中，你要怎么发现青年文化的特征，当然也就是通过研究 galgame 玩家群体的特征啦。

**** 选题意义

解决这个问题有什么用？为什么这个问题是有必要解决的？

galgame 群体是不是具有代表性，能不能从特殊到一般？研究青年文化的现状能够让我们对于更广泛意义上的社会有更好的把握嘛？


**** 国内外研究现状

这一步要阅读大量的文献，领域相关的或者 galgame 相关的都要，从中发现你的问题别人给过什么样的答案，别人的答案有哪些地方是不足，或者哪些东西是别人没有研究过的。

在上述研究中，可能要涉及国外的文献，例如欧美人写的《交互式视觉小说的历史与魅力》，日本人写的《エロゲー文化研究概論》《美少女ゲーム 35 年史 1981-2016 エルフの栄光と没落》、《美少女游戏的临界点》（这本杂志比较难找）等等，国内的研究也可以在知网上搜索。

galgame 的还不够，还需要了解相关领域的研究，例如一些典中典的文化研究、媒介研究、粉丝研究的经典书目，像是什么《通过仪式抵抗》《文本盗猎者》，或者按照《文化理论与大众文化导论》按图索骥，还有中国的青年亚文化视角的其他人的研究。文献远远不止这些，要根据你的研究目标选择合适的文献阅读。

重要的是，不是看完就完了，而是要梳理文献之间的脉络，不同的理论观点之间的联系，以及他们是在什么背景下提出的。这些理论和观点与你的选题的关系，他们的可取之处在哪里，他们的局限性又在哪里。进一步你的研究可以放在你梳理出来的这个脉络的那个位置，从而解决先行研究的不足之处或者问题。

**** 研究方法

你要通过什么方法来研究？问卷调查？深度访谈？文本细读？个案研究？比较研究？定量分析还是定性分析？

能把上面开题报告的问题想清楚了，不是像我的毕业论文那样浑水摸鱼而是切切实实的问题，那自然就是一片有实际意义的论文了。

[2024-10-22 Tue]

** 日语和韩语里有哪些中国没有或不常见的汉字成语？

檀信介 一片鱼心空付水，不见江河溯舟回。

4267 人赞同了该回答

1、白河夜船（しらかわよふね）这个成语很适合某些知乎大 v。形容讽刺那些自己什么都没做过、没听过，却伪造经历，装成一副全知全懂、什么都做过的样子的人。也形容昏睡误事的人。

出典是日本的民间故事。白河是京都的一个地名，叫白河却没有河，是个陆地村落。有个江户人向人吹嘘自己上洛去过京都。有人质疑他「你去京都路上路过白河了么？那里是什么样子？」那个人「去了，去了，路过白河刚好是晚上，我在船上睡觉，所以也没看到是什么样子。」

2、一期一会（いちごいちえ）意为很多际遇与邂逅，一生可能只有一次。出典自《茶湯者覚悟十躰》中记载日本茶道的开山祖师利休对弟子们的身教「路地へ入るより出でずるまで、一期に一度の会のように、亭主を敬畏すべし。世間雑談、無用也。」

3、愛別離苦 (あいべつりく)，形容亲人、爱人等离别时的痛苦。出典《大般涅槃经》，是佛教的八苦之一。

4、悪木盗泉（あくぼくとうせん），用法类似于「瓜田李下」，也有「不食嗟来之食」的意思。出典是晋代陆机的《猛虎行》「渴不饮盗泉水，热不息恶木阴。」

5、月下氷人（げっか - ひょうじん）氷就是冰，这个词指缔结男女姻缘的人，类似咱们说的月老。出典是《晋书 索紞伝》。tvb 前几年还拍了一部讲做媒人的港剧叫《金牌冰人》，应该是相同的典故。

6、窮猿投林（きゅうえん - とうりん）形容走投无路被收留的人，就不能再挑肥拣瘦了，收留者给予什么安排会接受。出典《晋书 李充传》

7、馬牛襟裾（ばぎゅう - きんきょ）类似于咱们的沐猴而冠、衣冠禽兽，形容没有学问、不知礼仪的人，却穿的光鲜亮丽。出典是韩愈的诗《符读书城南》「人不通古今， 马牛而襟裾。」

8、食前方丈（しょくぜん - ほうじょう）跟庙里的方丈没关系，形容饮食十分豪华，吃饭的时候，面前一丈都摆满了好吃的。出典是《孟子 尽心下》「食前方丈，侍妾数百人，我得志，弗为也。」

9、食馬解囲 (しょくばかいい) 形容曾收人恩惠的人，在恩人陷入危难时出手相救。出典《吕氏春秋》。

10、蛇心仏口 (だしんぶつこう) 仏就是佛，蛇心佛口，类似于咱们的口蜜腹剑。出典是中国的佛教经典《五灯会元》。

可以说，日语中大多数拿的上台面的成语都是出自咱们中国的古代经典和中国翻译的佛教经典。其中的多半都是中国古代也用过的，只不过现在不常用了。下面再介绍几个日本原创的成语。

11、無我夢中 (むがむちゅう) 意为，忘我地沉迷于什么。日本原创成语，无出典。

12、他力本願（たりき - ほんがん）意为期望依靠别人的力量，而非通过自己的努力实现愿望。出典是日本佛教净土宗经典《教行信証》，原意为信徒只要安心念佛，不需要自己修行，就能通过阿弥陀佛的本愿往生极乐世界。

13、一生懸命（いっしょう‐けんめい）这个比较中二，意思是连生命都搭上，努力完成某事。日本原创成语，无出典。

14、八方美人（はっぽう‐びじん）意思是八面玲珑、谁都不得罪的人。日本原创成语，无出典。

15、三日坊主 (みっかぼうず) 坊主是和尚，只做了三天和尚就还俗。形容那些三分钟热度的人。日本原创。

16、自業自得 (じごうじとく) 从佛教中衍生出，自己造下的业，自己要吃那个恶果。意思类似于咱们的自作自受。日本原创。

17、有耶無耶（うやむや）意为含糊其辞，用些有的没的说辞糊弄。日本原创。

18、岡目八目（おかめはちもく）围棋中衍生出的成语，意为当局者迷、旁观者清。日语原创。



待补充。

想要了解更多关于日本的新鲜事和冷知识么？那就关注信介君吧，嘻嘻。


我的公众号 信说霓虹 id：xinshuonihong。

[2024-10-22 Tue]

** 怎样学习范畴逻辑？
无限大炮

穢 yoku 等 126 人赞同了该回答

个人认为目前有且只有一本书是必读的，Categorical Logic and Type Theory (Studies in Logic and the Foundations of Mathematics)，Jacobs。这本书使用了（Grothendieck）fibration 来建立简单类型、依赖类型、多态类型（Polymorphic type）和一阶逻辑、高阶逻辑、逻辑--类型论混合系统的范畴语义模型，方法更为现代并且内容非常全面（很多 80 年代的老书，比如 Lambek&Scott、Goldblatt，都没有讲依赖类型。当然这也可以理解，依赖类型论的范畴模型——locally Cartesian Closed Category 直到 1984 年才被发现，而语境替换的 coherence problem 直到 90 年代才解决）。第一章 fibred category theory 是一切的基础，把第一章搞懂之后就可以根据需要来读后面的章节，如果你对的 dependent type theory 的范畴语义感兴趣就可以直接去看 comprehension category，这是依赖类型论最一般化的模型，其他一些模型，比如 category with attributes 和 category with families 都是它的特例。
[2024-10-22 Tue]

** 如何看待年薪 7 万美元竟不够租房 美国名校 UCLA 教授「无家可归」震惊社会！？
Deep Van、硅谷 IT 胖子 等 361 人赞同了该回答
笑死，刷知乎居然还刷到了隔壁组的奇葩大哥，作为这位老哥故事的知情人还是来还原一个事件全貌吧

Daniel（也就是这位自称是 UCLA “教授” 的大哥）去年刚从 UC Irvine 的 James Bullock 组 PhD 毕业，找了一圈 postdoc 的工作但被全聚德，只能去 UCLA 这个专门给本科生教基础课的 Lecturer 的工作，跟所谓的 UCLA “教授” 也就是 Professor 是完完全全不同的两个 rank

美国天文系的学术体系一般是 PhD student-Postdoc-Assistant Professor-Associate Professor-Professor，其中 Assistant Professor 也就是 AP 一般就可以被称为 Professor 了，大部分 AP 一般会在走 tenure track。这些 Professor 在承担教学任务的同时更重要的是要从事科学研究、指导研究生、向 funding agency 申请科研经费等工作

而 Daniel 当的这个 Lecturer 是 UCLA 为了缓解 Professor 们的授课压力创造的专门给本科生讲课的位置，这个位置不需要承担科研工作也不需要指导研究生，因此招聘时的标准可以降的很低，只需要能够讲好大学物理、大学物理实验课或者四小力学即可。Lecturer 一般是合同制，并且没有 tenure track 可走，走了这条路基本已经告别了正式的 professor track

说回到 Daniel 其人，我因为与他们组同属一个大的 collaboration 所以与他有一些交集。他自几年前加入 UCI 的 Bullock 组就神神叨叨的，经常是大话说得多而活干得少，结果五年 PhD 读下来这位大哥总共就发了一篇 paper，说实话他能毕业已经很不可思议了，要知道现在国内大学的天文系绝大多数情况都不可能一篇 paper 毕业的。于是不出意外的这位老哥在 postdoc job market 上毫无竞争力，再加上经济不景气，以他的能力也很难在工业界找到工作，所以去 UCLA 这个 Lecturer 的位置对他来说已经算是很好的选择了

Daniel 自己在社交媒体上大言不惭地自称是 Professor 基本属于是诈骗行为，要知道现在不少 UCLA 本科生都能发一篇一作文章或是多篇合作文章，他这种连基本的科研训练都完成得一般的人是敢自称是 Professor 也是滑天下之大稽了。他自己去年和 UCLA 签的合同就是 70k 的 teaching lecturer，才过了一年就发动媒体对 UCLA 口诛笔伐，这个操作也真的是很令人无语了

本质上 Daniel 在天文学术界应届博士毕业生里属于是最差那档的能力，能拿到 70k 的年薪对他来说已经很不错了，要知道美国现在最好的应届天文 postdoc 年薪也就是 80k 左右。当然如果你喷整个 academia 都是 underpaid 的话那我们还是好朋友，虽然这个工资也主要是由市场决定的

一般美国天文界的 postdoc 工资就是 60k-80k 之间，AP 跟地区有关在 90k-150k 之间，tenure 之后顶到天也就是 200k 这个样子，除非还有其他的 title（譬如兼任 chair 或者 dean 之类的）。说实话这个工资水平在当今的通胀下已经有点不好看了，所以一些想留在学术界的年轻人会选择回国，毕竟能拿到北美 tenure track 的基本都能在国内拿到海优，那么回国之后的前几年拿 600k-800k 人民币的年薪不成问题，同时还能拉自己的团队拿资源，何乐而不为呢？要是我我也选择回国捞钱。不过国内毕业的土博如果没有帽子的话想拿这样的工资估计就很难了

所以现在问题应该从 “UCLA 教授是否 underpaid” 改为 “能力最差一档的博士毕业生是否 underpaid”。这其实也是一个很好的问题，不过我想这就不是这个事件的核心问题了

[2024-10-22 Tue]

** 为什么韩国的热辣舞团无法征服中国的男性市场？？
Deep Van 等 2103 人赞同了该回答

说下背景: 其实我是学过跳舞的，黑怕还有爵士都学过一点点，大概四五十节课这样子。那个时候为了扒舞其实关注过不少这些博主。

下面步入正题:

我发现韩国女团甚至包括国内的一些学舞教舞的博主，都有一个相似的特点，就是魅男且厌男。

实际上有一点东西有点反直觉，就是说韩国女团最核心的受众其实不是男性，而是女性。

她们在演出中塑造的形象大概是这样子的

“姐又酷又帅又美又性感，但姐对你（男人）不屑一顾，但是又因为姐又酷又帅又美又性感，所以你（男人）必须喜欢姐”

她们必须要在穿着打扮以及舞蹈动作上魅男，因为不这么做无法证明她们 “又酷又帅又美又性感”，但她们在一些细节上又得厌男，因为她们的衣食父母是集美们。

其实韩国女团整体上是集美们的意识投射，和集美们精神状态挺像的，需要用魅男来证明自己的魅力，又要表现出对男人不屑一顾（厌男）来确立自己的地位，虽然集美们管这个叫 “独立女性”，但实际上无论是厌男还是魅男，都还是在绕着男人打转。

与韩国女团相对的是日本女团，不管她们私下里咋样，但她们演出的时候是真宠宅宅们啊。

[2024-10-22 Tue]

** 为何世界上已经很久没有新的发达国家诞生了？
薛定谔的鲨

2 人赞同了该回答

高赞那个所谓华农化学（副）教授 @shui0908 的回答看着都没超出高中文科生的水平，果然让化学老师答国际政治经济的问题还是有点超纲了（笑

让我们看看这些段让人贻笑大方的文字吧：

#+begin_quote
一个国家想发展，就必须持续地进行投资。资本从哪里来？现在只能靠对内剥削民众。
#+end_quote

Emm…… 确实是对政治经济学一窍不通的人写出来的一坨答辩，这段非蠢即坏的 “呼吁剥削” 和迫不及待地 “为剥削正名” 的投名状，仿佛就像是当下的学阀和既得利益者们 “脱离群众” 最好的写照。

剥削民众就剥削民众呗，反正剥削不到你们国内高校教授的头上是吧？死道友不死贫道，善哉善哉。

如果一个国家不是将发展成果惠及到民众头上，而是整天想着怎么盘剥民众，那么这个国家发不发展对于群众来说又有何意义？

这位整天呆在象牙塔里的副教授，甚至都从未察觉到出生率下降、人口增长率下降、老龄化严重、自杀率上升、失业率上升、无偿加班常态化、贫富差距拉大、市场预期下降、经济萧条已经完全成为国家持续发展的巨大障碍，还搁那儿念叨着怎么剥削民众可以把经济继续往上提一提……

#+begin_quote
还没发达就想搞福利主义，这是没头脑。只有逐渐发展了，才有能力去搞福利。
#+end_quote

在这位 “专家” 眼里，高龄农民每个月 100 块钱的补贴，甚至都是高贵阶级的 “大发善心” （简直都快要被自己感动坏了），如果你说要归还老百姓所创造的劳动果实（他们居然称这种 “归还” 为 “发福利”），那么他就会指责你这是 “没头脑”。

像极了你的老板告诉你 “只要你现在努力 996，将来你也一定能够成为亿万富翁的”，而这位所谓的 “专家” 完全忽视了造成贫富差距的社会制度的因素。

今天社会越来越大的阶级撕裂和贫富差距，并不是因为 “国家没有达到发达国家的标准”，而是因为劳动果实被通过制度的方式不公平地分配给了本不该享有该权利的特权阶级们。

如果社会劳动成果是 10 张饼，上层阶级占 9 张，下层阶级占 1 张。这时上层阶级告诉你要 996，于是大家下个月生产了 20 张饼，然后上层阶级去拿走了 18 张饼，留下 2 张饼让其他的下层阶级去撕抢，对外宣称 “我们社会这个月生产了 20 张饼，社会生产力大幅提高”。

而实际上当你生产 30 张时，他们就会拿走 27 张；当你生产 40 张时，他们就会拿走 36 张，因为他们通过制度的规定将贫富差距合法化了。

然后这个时候我们的专家就跳出来了：社会还没有发展，你们这群低层人就想要福利？你们要学会接受剥削，这样我们的社会才会发展；等发展了，我们就会给你们发福利！什么时候 “发展” 才是个头？那不是你个底层该考虑的事！努力生产就完了！

而实际上，当他不想要给你发福利时，他永远都会有借口搪塞你 “发展还不到位”。

像极了以前某东大专家 “不能学习西方的民主制度，因为东大的教育水平还不够”，而实际上东大接受过高等教育的人口已经占到了 2.4 亿，远远超过了最早开放民主制度的所有国家的国民受教育水平。

但他依然会告诉你 “还不够”，唯一的原因就是他根本就不想实现，所以你在他那里得到的答案永远都是 “还不行”。

#+begin_quote
能否成功，取决于像高赞回答这样思路的人，会不会在国家成为真正的发达国家之前掌权。

如果没有，那这个国家发达有望。
#+end_quote

都已经是共和国了，有些人的脑子里还是这种 “人微言轻”“火车快不快，全靠车头带” 的封建君主思想和幼稚愚蠢的精英视角，国家的发达与不发达不取决于金字塔尖是谁，而是人民，只有人民群众才是历史的创造者。

再说一遍：是人民选择国家，而不是国家选择人民。

劝这位 “专家” 没事带着同学们做做实验，发发刊物，搞搞无聊、无意又无害的课题，差不多得了，搁键政圈来当跳梁小丑干啥？水平连李建秋都不如……

[2024-10-22 Tue]

** 同样是机床企业，为什么马扎克涨价仍供不应求，而沈阳机床亏损了几十个亿？
Deep Van、托卡马克之冠 等 5977 人赞同了该文章

刚毕业的时候去了沈阳机床。大约 2006~2007 年左右。很多经历：

机床普遍漏油漏液，车间常备锯末，用于 “抗洪抢险”。很多时候人都是用油浴桑拿，满身都是油。枪钻油、液压油洗眼都是正常现象。我就被液压油糊了眼睛，实践发现貌似没有刺激性。

车间主任派工人用硅酮胶（玻璃胶）堵漏，好几大管堆上去，根本不起作用，工人用手涂抹，下班一看手上的皮肤脱落，像是手套一样可以揭下来。

车间早上 6 点点名，晚上 10 点半下班，一周 7 天，全年无休。一次早上领导放风通知说赶快干完手上的活，第二天给休息；结果等到晚上手上的活干完，又通知紧急任务，第二天不休了。我有一次跟另一个同事通宵调整配磨垫，一直到早上点名，第二天继续干不休息。

车间食堂吃饭，食物普遍都是机油味，打饭的势利眼，看谁比较不好惹就先给谁打，当时我戴着眼镜就认为我好欺负，一直不理我。。边上有卖可乐的，当时叫 “非常可乐”，花 4 块钱买了一瓶，喝了一口，发现还是假的，根本不对味，喝不了，最后只好扔了。

规定车间园区行走转弯必须走直角，不允许抄近路，违者罚款。并排走路不准超过两人，违者罚款。规定白色工作服不准弄脏，弄脏罚款。路口有摄像的，上述各种问题被拍到继续罚款。

车间不允许坐着，也不允许做任何看起来像休息的姿势，如果实在没事，就必须用 “八分布（就是破服装切碎当抹布）” 不断的擦机床，防范上级领导突击检查。

车间规定门窗必须紧闭，上锁，只有在运输车进来的时候才开，后来得知是为了防范记者随便进入，出负面报道。

到了设计室画图，阳光毒辣，屏幕反光看不清，但是规定不准拉窗帘，怕影响美观，领导看了不爽。设计室前后不允许说话，理由是交头接耳工作不饱满。

电脑无法上网，USB 接口用胶带封住，理由是怕病毒。但实际上病毒一点都不少，堪称病毒库。

等级制度，除有关系外，专科生进厂一直在车间做工；本科生扔进车间 “实习” 个一年半载再说启用；研究生进车间就是参观，东摸摸西看看。在设计室，研究生的电脑可以上网的，工作量几乎没有，经常挂着电驴下载毛片，上网聊天。



当时是普车走量，赔本卖，上方的意思是压倒所有小厂，形成大厂垄断增效。



我在车间跟的是曲轴油孔加工专机，各种毛病不断，我来之前就开始装配，等我受不了这个环境，跑路了，这台床子还没完事。拆了装装了拆，没有一处完整的，到处是拆装过程中的伤疤。后来没办法，把半成品 + 一名钳工，打包给客户交货了。传说中的 “买机床，送钳工，买一赠一”，据老工人说是普遍现象。很多床子出问题，派人去做售后，而派出去的钳工一般都会被对方收编，因为经常坏，不如直接在那边工作算了。

还是那台油孔加工专机，德国留学生来实习参观，给人家演示，恰好还在拍 PR 宣传片，摄像机、围观群众一大堆，众目睽睽之下，曲轴咣当一下从卡具上掉下来了。冷却液（枪钻油）喷的到处都是。场面一度相当尴尬。后来我看见那些德国留学生坐在车间外边一脸沮丧，一副人生走错路的样子。

亲耳听见一个负责销售的，挺直腰板自豪的对客户介绍，大概意思是：就算我们用的所有组件都是用欧版（控制系统、液压系统、卡盘、主轴等）的，也比国外的机床有价格优势，因为床身铸件是自己做的，全世界就我们的铸件工人工资最低，成本优势无可比拟。

当时听老师傅说，还有个零工资制度：就是徒弟没有工资，机床组装由师傅承包，带着徒弟装配干活，干完一个不给钱，什么时候被售出，什么时候分钱，如果卖不出去，就继续等。这样做有一个目的就是留住人，因为人们总觉得没得到钱就走有点亏了，然而不断的有活过来，不断被拖欠，不断想回本，最后上瘾，跟赌博一样。老乡别走的戏码不仅在股市，其实早就有人玩的炉火纯青了有木有！

在老厂区（后来搬家到开发区），一个车间的同事，扶着床身（机床底座）穿出来的圆钢（作用类似扁担）抬头指挥天车（就是车间顶棚上的吊车，老式的天车人要爬上去开动），“落” 字一出口，中指就被切断了，原来是恰好下边有个木箱子，与圆钢一头形成剪切。一开始车间耍赖不算工伤，后来发现这同事的哥哥是人事部的，找上来了，车间主任这才没说啥。还派我去护理，当时好像叫手外科医院，然后看到医院里很多残肢断腿的，大开眼界。亲眼看见壮汉晕血昏倒、一个老太太整个手被脱粒机卷进去只剩下白骨、一个小男孩手指坏死变黑插还着钢钉、小女孩的一只手没皮了被缝进肚皮养伤、老汉失去双腿无法接受现实闹着要自杀.... 这是人间地狱么...

车间里有一对双胞胎女孩，长相一模一样，样子还不赖，还都是开天车的天车工，但是话一出口就是男声，还是很憨的那种。动作也不像女生，大大咧咧的，还各种爆粗口。可能是在工厂环境下熏陶出来的吧，真是无法接受这种反差。敬而远之。反而有些男工温文尔雅，多才多艺，比如可以露一手用改锥工具什么的表演花样转笔，有的还参加过当时的唱歌选秀比赛。

当时正好赶上厂子从市区搬家到开发区，从暗无天日的车间搬到了宽敞明亮的车间，感觉还不错，但是过程经历挺可惜的：旧车间下边有防空洞，考虑到这块地已经卖给了开发商盖房子，所以防空洞也要拆，但是里边储存了很多工具啊、零件啊什么的，车间就让我们给搬出来卖掉给各个小加工厂什么的拉走了；旧厂区各种被遗忘的角落里有很多陈年的图纸，都是各个年代的智慧结晶，来不及搬走，有的工程师舍不得拿走了一部分自己珍藏，但是多数估计都被卖了废纸；参与押车，到了新厂区，从车上搬下来各种东西放进一个临时的仓库里，很多文物重见天日，宝贝很多，比如一大柜子的从未拆封的正版 DOS 操作系统....

在新厂区，距离住处很远，需要坐班车，有一次下班大暴雨，班车司机因为堵车跟另一个司机打架，又堵车又赌气谁也不让谁，把一车人晾在大雨里，气温很低，冻得发抖。最后只好下了班车打出租车回家，结果出租车也是趁人之危强制拼车，各种等，各种冷，落汤鸡一样感觉满世界都是雨水看不清谁是谁，差点冻死，最后到家只剩一口气了。

另外，班车坐着坐着就冒黑油烟，不开窗就能呛死，据说是从别的厂子报废淘汰下来的，买来重新喷漆的。

因为搬迁，各厂合并，管理一下子就混乱了，所以当我受不了环境想离职的时候却找不到人事部门办离职证明，都不知道人事部去哪了！问谁都不知道，索性干脆在新的单位当黑户先干着……结果就是，我还白领了 2 个月的旧工资，虽然钱太 tmd 少了，但是一份工作双份工资想想就美滋滋。2 个月后才找到办离职的人员，后来去办手续，才知道一个钳工同事即将要跟着那台曲轴油孔机床打包在一起发给客户了……



说一下我跑路之后。打击还是挺大的，首先感觉自己在那个环境下，失声了，出来之后都不会说话了。去医院看说我有抑郁症。后来找工作感觉自己已经脱离了时代，像是从监狱里刚出来，什么都不懂。当我发现新的单位卫生间还提供擦手的白纸的时候，感动的都要哭了，更别提食堂饭菜还有食谱……

不断的怀疑问自己当初都做了些什么，为什么要在那种地方还呆了几个月之久……新工作还是不适应，干了一年后，又折腾了很长一阵。


最后到了互联网工作，当时有个插曲，就是当入职的时候，看到座位上放了一个皮包，我还在问这是谁的东西放这了。最后人家告诉我这是你的，是公司给发的笔记本电脑，哎呀我当时感觉是又被颠覆了，原来还可以这样！这些都是以前机床的时候从来没有过的尊重。



关注机械学霸小程序，

获取资源更直接！

免责声明：
本文系网络转载，版权归原作者所有。如涉及版权问题，请与机械学霸联系，我们将第一时间协商版权问题或删除内容。

[2024-10-21 Mon]

** 君可知有些人只看 lesbian porn

[[*2024-10-21 Monday][2024-10-21 Monday]]

** something for latex beamer to create a toc for every section and subsection

#+begin_src LaTeX
  \AtBeginSection[]{
    \begin{frame}
      <beamer>
      \frametitle{Topic}
      \tableofcontents[currentsection]
    \end{frame}}

  \AtBeginSubsection[]{
    \begin{frame}
      <beamer>
      \frametitle{Topic}
      \tableofcontents[currentsubsection]
    \end{frame}}
#+end_src

[2024-10-20 Sun]

** 如何看待我在长征路上开超市这一剧？合集
*** 如何看待我在长征路上开超市这一剧？

作者：cinder
链接：https://www.zhihu.com/question/743096417/answer/4425713608
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

祭祀具有一项古老的功能：安抚变成幽灵的祖先。用现在生产的商品去投喂死者，然后过去的冲突就都平息了，那些人作为幽灵就都安心了，我们的当下就可以不受打扰了。甚至可以让历史倒过来：他们当时奋斗的意义不是由自身在 “不知道最后坟墓上插鲜花还是牛粪” 的情况下做出的选择、实践确定的，而是由我们生产出很多商品后顺便给他们插上的鲜花决定的。各种纪念节日的功能也是这样。

#+begin_quote
为了结束革命，也为了消除威胁未来的不确定性，最紧迫的任务就是确定关于革命事件的叙事。如果有可能从有这个 “极其多变” 的民族抽取一个公认的历史解释，那就万事大吉了。删除胡作非为的日子，把革命投射成永恒的话语，这样既消解了人们对革命的质疑，也消解了人们对革命的坚持。此外，通过搬演那些 “美好的时代”，或许能够重新缔造失落的团结一致。无论如何，这是纪念性节日的组织者所追求的目标。他们并非不知道这里潜伏着危险：“革命的时代在本质上很难控制狂风暴雨，也很难创造晴朗的天气。”

确定这种叙事就需要做出选择：如何在革命的众多事件中做出选择？应该让编年史讲述所有的一切，因为这包含着一切能够激发人们好奇心的东西。但是节日仅仅是唯一一种感性的编年史，如果让这些节日讲述一切，会达不到目的；因为即使旧制度已经远远退隐，已不再让人想起 “其差异和杂乱”，那么革命的这段直接历史也正如米什莱在《十九世纪史》中清楚地显示的，乃是一个 “废墟的世界”。节日所寻找的只是那些能够通过让人感受到革命结束而加强民族和解的东西。革命节日向公众展现一系列彼此无关的画面，而不是提供一个连续的历史。那种让每个节日体现一种美德的做法也促成这种结果…… 通过权威命名，每一个历史节日都成为一个稳定价值的寄放处。
——《革命节日》
#+end_quote

比如人们提到十月革命的历史意义，会说这是建立世界上第一个社主义国家，教科书提醒我们这里有一个知识点，就是要和第一个社主义政权区分开来。要是习惯于这种 “建立了什么什么” 的历史意义的说辞，我们就会对猫在建国前那篇纪念文章的一开头就谈论国家、政党的消亡问题感到突兀。如果胜利完全实现，关于这种历史意义的说辞应该会变成 “在世界范围内消灭资本主义国家的开始”。

比如人的肉体被放入水晶之中，号称是要记住历史，实际是为了起到封印作用：因为事情他们已经做过了，所以我们需要做的就只是感恩地把自己交给他们的精神，然后只有在纪念活动中才配感觉自己和他们在一起。

比如提到历史上的筚路蓝缕，首先想到的是这种筚路蓝缕中体现的美德的榜样价值和引起的感恩反应，看到的是媒体给我们展示的一堆单纯的信念分野和善恶分类，而不是在历史形势中到底发生过什么样的复杂斗争。

[2024-10-12 Sat]

*** 如何看待我在长征路上开超市这一剧？

F-Hreinskilin

政治问题是一个美学问题，美学问题也是政治问题 —— 斯蒂格勒

271 人赞同了该回答

与内容令人忍俊不禁更相映成趣的是小说点赞数量一直水涨船高，而是评论区都一直叫好：虽然这种内容显然是一直在控评的，但是问题在于即便如此，认为这个作品是「佳作」的人也不在少数，属于是与原作共同构成了巨大的风景。

在这种问题下「后革命景观」已经说的够多了，所以我们不妨看看现代的 revolutionary history education 与后革命景观之间的关系。表面上来看，historical nihilism 要反对「娱乐化历史、解构崇高、消解神圣」，但是其赋予 revolutionary history 一种神圣性的同时也消解了其现实性。其本身就是一种「宜粗不宜细」的一种对于历史的再结构（当然，一切历史叙述都是被建构的）。后革命世代的历史叙述要面临的问题在于：现实建立在革命的基础之上，而另一方面革命又需要远离现实，也就是革命成为了一种幽灵般的存在，其在场恰恰在于它的不在场。从德里达的角度我们可以用这种幽灵重新激活一种非 - 存在论的革命活力，但是在后革命叙述中，这意味着革命的现实性被抽空了，只留下了遥远的、抽象的革命。而反 history nihilism 叙事所制造的，恰恰就在这样一个被 AIE 制造的作为 nation-state 合法性的革命，因此，革命被赋予了一种神力，一种非 - 现实性的神力。仿佛革命是如此从头到尾都是伟大光明正确，而在社会 - 象征秩序的缝合背后的对抗性现实：各种矛盾、斗争与分裂则被压抑、掩盖了。而《我在… 开超市》则是直接将革命是为了一种神力帮助下得以发展之物，这恰恰与 revolutionary historicism 所制造的革命神话有类似之处。对于现代人而言，革命成为了被放入博物馆中的奇异神秘之物，斗争、对抗的岁月成为了「遥远的历史」，而革命剩下旧只有一个神力与空洞的外壳。本来革命是历史的之线中的爆炸与断裂，而现在只剩下了革命制造的历史连续性。这也就是革命的「老英雄」在看到后革命的安定叫好的叙事所要传达的。

还是抖音评论幽默

现代基于革命而生，而革命又被现代所否定，这就是为什么后革命叙事的「革命之幽灵」何以存在：它需要革命的不在场的在场。需要哥们为当代的「安定」赋予历史的合法性。

[2024-10-20 Sun]

*** 如何看待我在长征路上开超市这一剧？

刘镇锐 等 417 人赞同了该回答

后革命百景，网文里没有一千也有八百的，男频有男频的玩法而女频的玩法罢了，此事平淡无奇。

你说女频的双穿援共文用消费主义的逻辑去重新理解革命很难绷，那难道男频的双穿援共文就不用帝国主义和殖民主义的逻辑重新理解革命吗？这里最大的区别可能只是在于双穿援共在女频因为审查相对不严所以写得比较多（别忘了 “小粉红” 这个词是晋江来的）而男频因为审核比较严所以只能缩在有毒之类的小站偷偷写，许多人都没看过。

说到底在于后革命时代里直接理解革命本身已经是尤为困难的，以至于只能通过雷普历史的方式来让历史重新变得可理解，而网文网剧也只不过是这一时代的产物，此事在不要被和谐辣评觉醒年代中亦有记载… 至于那个不可理解的革命本身？你说的对但是《措施》是布莱希特的一款…

---

《措施》（Die Maßnahme）是德国剧作家贝托尔特・布莱希特（Bertolt Brecht）创作的一部教育剧，也是他最具争议的作品之一。该剧通过一个审案戏的形式，讲述了四个宣传员受康米国际委托去契丹 SY 从事革命活动，其中一人因违反纪律而被其余四人处决的故事。这部剧作在目的与手段关系问题上提出了效果论的回答，即为了达到改变现实的目的，可以采取一切可以采取的手段，包括处决违反纪律的同志。

---


alalala
男频的双穿援共文真红的，别说发表在小网站了，连自娱自乐的发表在论坛都会被删帖，连几年前的帖子都会删的

雨宫优子
想你了时空门后 20 年


扣角歌 → 雨宫优子
你说的那些基本都被毙了，当年龙空遍地反贼[飙泪笑]，我现在就记着一个戈地图 1985，一个时空门后，那真的是明牌反贼，放现在作者都得进去[惊喜]

[2024-10-09 Wed]

** 从《冰菓》谈起：60 年代日本真实的高中生运动

北极星飞过什切青

これまで存在したあらゆる社会の歴史は、階級闘争の歴史である。

239 人赞同了该文章

#+begin_quote
一切都将不再主观，在悠长历史的远方化为古籍的一页。

而有朝一日，现在的我们也终将成为未来某人手中的古籍。
#+end_quote

估计有不少人对日本新左运的第一印象都是来自《冰菓》开头的关谷纯事件。在动画以及原作小说中讲述了这样一个故事：在 1967 年 6 月，神山高中的学生反对校方压缩学园祭时，学生方却因为担心惩罚，没有人愿意站出来领头。关谷纯被迫当上了名义上的领导者，为学生们所犯的所有错误背锅。最后在运动中，篝火点燃了学校的武道馆，导致关谷纯作为 “领导者” 被退学，却没有一个人站出来帮他说话。

关于《冰菓》的解读大都绕不开关谷纯事件。不过日本新左运本身知名度较低，关于其历史背景的解读大都不充分。比如有 B 站 up 主（[[https://www.bilibili.com/video/BV18b421n7pL/][link]]）将整个事件套到了东大斗争之上，认为 “神山高中狠抓教育” 对应 “大学生反抗校方管理”，“集体声明和罢课” 对应 “东大罢课”；而关谷纯的原型则是 “东大斗争中一名被错误处分的学生”，这一错误 “没有人去纠正” 对应了关谷纯被退学，等等。

而事实上，东大斗争中这名被错误处分的学生名叫粒良邦彦。这次处分在安田讲堂事件之前，起因是 1968 年 2 月 19 日东大医学部全学斗和医局长发生了肢体冲突。被处分的学生包括粒良，但是事后证明 2 月 19 日当天粒良本人根本不在现场，甚至不在东京，而是远在福冈的久留米医大参加联谊。东大学生为了还粒良清白，甚至直接占领了安田讲堂（这也是对安田讲堂的第一次占领，而知名度较高的则是同年 7 月开始的第二次占领），逼迫着校方无法举行毕业典礼。之后在 6 月 28 日大河内总长会见之后，校方也取消了对粒良的处分。因此，将其视为关谷纯的原型多少有些牵强。

至于其他的部分，根本不需要参照各个大学发生了什么 —— 这些情节本就是当时在日本无数高中真实发生过的事情。那些满腔热血的高中生（高校生）们，也是日本 68 年中被忽视的角色。我们的故事也从 60 年代说起。

*一、日本高中生运动的复兴*

60 年代初，在经历过安保斗争之后，高中生运动反而进入了低潮。反安保运动中的高校生组织中，日共 - 全自联系的 “保卫和平和民主主义高中生协议会”（平民高协）在日共有意的忽视下（宫本试图全力建设民青）而逐渐消亡；一次崩得和革共同系的 “阻止安保高中生会议” 则经历了分裂：革共同 - 马学同另组 “高中生马克思主义研究会”；崩得 - 社学同 - 社高同则自身难保，在社高同解散之后，整个组织也完全崩坏。到 1960 年后，高中生运动已经进入低潮。

高中生运动的复兴要等到 1964 年。这一年，社学同马战派创建了 “阻止日韩条约全国高中生会议”，机关报《战况》；同年， 革共同中核派重建了 “高中生马克思主义研究会”，机关报《灯塔》，由此成为了高中生运动复兴的两台引擎。

1965 年 7 月，中核派提议，解散 “高马研”，并以此为基础联合各派，创立 “反战高协”（反对战争和殖民主义、保卫生活和权利的高中生协议会）。结果，中核、革马、马战三派经过了激烈争论，最后只有中核派参与了反战高协的成立。中核派反战高协是这时最大的组织，可以独自动员 300 名高中生；而马战派能动员四五十人，革马派动员力更是只有个位数。

1966 年，崩得系内，马战派和统一委合并，在京都建立了 “社高同”（社义高中生同盟），在东京建立了 “全国高中生会议”；社青同解放派牵头，同革马系、ML 系、第四国际成员共同组建了 “高中生协议会”。1966 年反越战斗争中，反战高协动员了 250 人，高社研和崩得系高中生会议各自动员了 50 人。—— 虽然数字上不多，然而实际上到三派全学联结成准备大会的时候出场的也仅有 500 人。也就是说，高中生在其中发挥了相当的作用。

到此，高中生运动已不像 60 年安保斗争中以生徒会为核心了，而是已经变成了新左翼各党派旗下学生组织领导的运动。各派组织也经过各种统一、分裂、演化，左右翼各路高中生政治团体之间逐渐形成了如下格局（注：日共系高中生大都在民青体系内，不单独列出）：

...

此后几年，各派高中生纷纷参与街头斗争（除了革马派的人比较冷淡），包括 1968 年羽田斗争、阻止佐藤访美斗争、反对美军航母停靠佐世保斗争、三里塚斗争、阻止王子美军野战医院斗争、国际反战日斗争等等。这样的态势一直持续到 1969 年。

...

1968 年国际反战日，全日本 76 万人罢工、456 万人集会，席卷 46 个都道府县
东大斗争对于高中生运动是一个转折点。自安田讲堂决战、东大落城之后，高中生内的革命之火不仅没有被水炮熄灭，反而彻底烧穿了各新左政党间的界限，席卷了全日本各大高中。放眼望去，从北海道到九州岛，日本列岛上无数高中狼烟四起、火光冲天，如同千万座爆发的火山喷涌着无尽的愤怒。

1969 年热烈如火的高中纷争，到来了。

*二、激荡的六九年*

与大学全共斗相比，日本的高中生运动更有自己的特色。日本高中生提出的要求主要包括：

- 在校内举行集会和张贴揭示板、乃至进行政治性活动的权利；
- 反对高中制服、实现服装自由、反对校方对长发的限制；
- 要求学生参与校方处分的制定，乃至反对处分制度；
- 反对定期考试；
- 反对学分制、授课制；
- 反对教科书检定制度；
- 废除校规校纪，反对管理主义教育；
- 要求学校教师进行反思和自我批评。

在这场高中斗争中，各新左组织和 “全斗委” 之类的学生小组占据了主流，并通过这些口号引起了广泛的共情和认可。至于民青等既成左翼对全斗委继续保持敌对的态度。而生徒会组织大都对这场新左组织主导的运动保持冷淡、甚至派干事出面阻止 —— 根本上，双方有着截然不同的目标：新左组织希望把高中翼作为各自的群众组织来建设，而不希望出现安保斗争时期那种不分你我的 “大帐篷” 学生会联合。

而由于高中生将教师作为批评的对象，将其视为 “管理主义教育” 的一部分，各教师工会（教组）内不论左翼系还是保守系，都纷纷呼吁 “保持冷静”，乃至直接参与对其的打击。深层次上，教师中不论左右，基本都认为 “学生本就应该在教师的管理之下”。而跳出这种管理的企图，让教师本身开始质疑自己的职业意义。从这一点上来说，不论何种立场的教师基本都站在了体制和校方一侧，甚至有过直接冲突的案例。

而学校不仅动用各种处分活动，甚至多次采用导入机动队的方式解除封锁，将逮捕者关进少管所。高中斗争还直接惊动了日本文部省和教委，下达命令要求禁止高中生参与政性活动。这就是日本高校斗争的大观。

*毕业典礼斗争*

日本高中毕业典礼的 “答辞”，类似于我们所说的 “学生代表发言”。这是学生最常用的抗争方式。早在 1953 年，京都府立洛北高中的学生就在发言中高声呼吁反对核武器。1967 年，大阪府立泉大津高中的毕业生也在毕业典礼中呼吁反对越南战争。到 1968 年，这种抗争已经席卷全日本十余所高中。各校方对此进行了紧急应对，福岛县高在发现学生演讲内容与审查时不一样后，立刻以 “背信” 名义对学生进行了处分。

然而，学生的反应则是，已经先礼后兵仁至义尽，文的不行，就来武的。1969 年 3 月 19 日，东京都高中生召开了全都高中生毕业典礼斗争统一集会。随后 1969 年的毕业典礼上，全国有 88 所高中发生了这样混乱：在讲话或者唱校歌的时候合唱《国际歌》；典礼中拒绝起立或者集体背对讲台；“打入” 后台在典礼中途把舞台幕布给放了下来。更有学生戴着新左头盔、举着ゲバ棒就杀入了会场，还有人拿着蛋糕和臭鸡蛋往台上抡。

日本全国高中校长协会对此进行了紧急反应，要求各校简化毕业典礼，省掉最容易出乱子的知事致辞、校长致辞、来宾祝词等等。第二年 1970 年，都立日比谷高中破天荒地在全东京 6 个不同的地方同时举行 “分散毕业典礼” 以便管理，堪称教育史上的奇观。

*封锁学校、到街上去！*

到 1969 年夏末，局势变得更加紧张。为响应 1969 年 10 月 21 日 “国际反战日” 的号召，各高中纷纷启动了 “总决起”。火热的十月席卷了东京、乃至全日本：

- 7 月 7 日，大阪丰中高中占领了校长室；
- 7 月 19 日，各新左翼组织了反对文部省 “禁止参与政事” 的大行进；
- 8 月 23 日，爱知县社高同直接向交番送去了莫洛托夫牌鸡尾酒；静冈县挂川西高中举行了反处分斗争；
- 8 月 25 日，京都同志社商高封锁了职员室；
- 9 月 12 日，青山高中出现了街垒；
- 9 月 16 日，为反对校方中止文化祭，青山高中举行大规模反抗；
- 9 月 27 日，反战高协举行全关东高中生大行进；
- 10 月 4 日，都立赤城台高中举行全校大集会，航空工专全员罢课，葛西工科高中提出在屋顶天台举行反战大会；
- 10 月 6 日，九段高中封锁了教师办公室；日比谷高中开学典礼爆发混乱；
- 10 月 8 日，日比谷高中封锁了如兰会馆；
- 10 月 9 日，日比谷高中发生了拒绝进食的事件，持续到 12 日；
- 10 月 13 日，青山高中全校封锁；
- 10 月 14 日，忍冈高中全校大集会；
- 10 月 15 日，玉川高中全校封锁；
- 10 月 16 日，小石川高中学生停止进食；
- 10 月 17 日，航空工专全体学生罢课；
- 10 月 18 日，驹场高中封锁；忍冈高中封锁；航空工专和葛西工高学生停止进食；
- 10 月 20 日，樱町高中、南高、文京高中封锁；世田谷工高举行全校大会；
- 10 月 21 日，机动队强行攻入青山高中接触封锁；
- 10 月 22 日，深泽高中举行全校大会；竹早高中通过罢课决议；
- 10 月 23 日，志村高中封锁。
- 10 月 28 日，上野高中封锁，机动队攻入日比谷高中强行解除封锁；
- 10 月 30 日，青山高中进行了大量处分。

此时，高中生参与校外活动的规模也快速上升。1969 年 1 月，全高中校外活动的高中生还不到 500 人；到了 6 月上升到了 3000 多人；11 月阻止佐藤访美斗争的时候已经有多达 4500 人参加。处分和追责也随之而来。根据官方统计，1969 年全年，东京都竟检举了多达 387 名高中生；在其他各道府县，大阪检举了 62 人；北海道 30 人；京都 25 人；静冈 20 人；神奈川和兵库各 14 人；新潟 12 人；长崎 11 人；广岛 10 人，如此等等。


我们可以再从各个学校的角度看一些案例。

*三、各校的情况*

*福冈县立明善高中：“明善五原则”*

明善高中对于学生的行动反应迅速。1968 年，明善高中做出了让步，规定 “二人以上、存续超过五日” 的团体，将 “需要得到批准” 改为 “需要向生徒会报备”。由此之前的 11 个地下团体由此获得了公认，也获得了部费补贴和部室使用权。这一过程中，生徒会和校方进一步提出了 “明善五原则” 以对学生社团进行规范：

- 允许涉政的学习和研究活动；
- 不得进行涉政 “实践活动”；
- 若接受外部联络和指导，需取得许可；
- 学生团体必须接受教师的指导；
- 若有问题，需同指导教师取得联络。

五原则公布后，虽然学生一开始对其有不少反对意见，但是最终有效平息了明善高中的矛盾。1969 年斗争高潮时，甚至全九州有百余所高中派代表前往明善 “取经”。

*北海道小樽潮陵高中：火烧制帽事件*

1969 年，北海道小樽市的潮陵高中的学生掀起了争取服装自由化的斗争。6 月，生徒总会以绝对多数票通过了废止强制戴制帽的决议，但是校方拒绝认可这一决议。于是，1969 年 9 月 27 日，150 名学生聚集在教师办公室前的校庭内，点燃了 13 顶制帽。

在此事件之后，3 名高三学生被给予严重警告处分。但是学生仍然坚持抗争，最终潮陵高中于 1970 年代实现了制服自由化。

*大阪府立市冈高中：复杂的 “师生关系”*

大阪府立市冈高中本来就是左翼教师工会强大的学校。1961 年该校生徒会甚至派出了代表参加了社会党 - 日共举办的原子弹氢弹禁止世界大会，还是几名教师带着一起参加的。1967 年前后，教师工会 “高教组” 主要围绕两个问题进行反抗：一是反对教师强制调动；二是反对校务分掌（类似于教务处）的直接任命制度。教师们甚至成功发动了高中生们加入进来。1968 年，市冈高中的学生们组建了 “全大阪强制调动斗争委员会”（以崩得・社学同系为核心），支援教师们的反抗。早期市冈高中的斗争几乎就是在教师工会的指导下发展起来的。

但是，事情很快起了变化。社学同系学生先是于 1968 年 7 月破坏了第一学期结束仪式；之后又强行占领了校长室。当社学同 “府高联” 的红头盔和解放派 “反帝高评” 的蓝头盔一路杀入校长室之后，高教组立刻站到了对立面，将他们称为 “沱牌暴力分子”。双方的关系也就陷入敌对。

*东京都立青山高中的 “落城”*

高中斗争中的最大矛盾在青山高爆发。1969 年 1 月，中核派反战高协就在青山高中建立了 “青高反战会议”。青山高的学生格外活跃，甚至同年 9 月 2 日、静冈县立挂川西高占领了校长室时，还有 8 名高中生远赴静冈前去支援，甚至从三楼窗户外打出了反战高协的大旗。挂川西高逮捕了 11 人，其中还有一名青山高中的学生。

事件发生后，青山高中的教导主任立刻去静冈找人。青高反战会议则组建了全学斗争委员会（全斗委），阻止教导主任前往静冈。由于校长拒绝进行对话，青山高全斗委于 9 月 12 日占领了校长室。14 日，校长调来机动队强行解除封锁，并下达了终止文化祭的命令，招致全校更大的不满。9 月 29 日，高三教室被封锁，直到 10 月 21 日才导入机动队，解除封锁。双方发生了激烈对抗，几乎复刻了安田讲堂的那一幕：高中生从天台往下扔鸡尾酒和石头，下面则朝上喷水扔催泪弹。封锁解除后，十余名学生被退学等处分。

青山高 “落城” 举世震惊，日本民众第一次看到高中而不是大学发生这样的场景。日本当局也被迫转换思路，将高中纷争作为政治问题而不是教育问题来考虑。

*都立竹早高中、都立上野高中：自主学习的尝试*

1969 年 4 月，都立竹早高中被爆出了教师吃回扣的事件，强制补课等现象涉及了超 800 万日元。这一事件被列为刑事案件送检，都教育厅相关人员也被革职。而学生则发布了《学生权宣言》，宣布学校运营和维护事务当由学生来管理，但是这份宣言并没有得到校方认可。1969 年 11 月，都立竹早高中实行了以小组讨论和研究汇报为主要形式的 “实验教学”。但是这种实验很快被校方打断，不了了之。

另一边，在 1969 年 3 月都立上野高中的毕业典礼上，学生在致辞中强烈批判了 “考试型教育”；同日在校庭中学生们就举行了自主讨论会。在多次讨论会后，高中生们提出了反对考试制度、反对学分制度等等主张。10 月 28 日，上野高中的学生封锁了校舍。两天后，校方宣布接受学生部分要求，换来了封锁的自动解除。

此后，上野高中的学生们陆续推动了改革，把必修 102 学分减少到 85 学分；导入 “讲座式教学”；不论必修选修课程均可以由学生选择教师；废除定期考试，等等。上野高中还开创了各科 “自主研讨会” 共 379 种，供学生自由选择。当时的选题例如：

- 现代国语：丸山真男《日本的思想》研究、大江健三郎研究、萨特思想研究；
- 古文：《枕草子》研究、《论语》研究；
- 世界史：从魏玛共和国到德三；
- 数学：向量、行列式；
- 等等。

在当时，各大学都难以实现这种授课方式，但是上野高中把这种方式维护了很长时间。当时的上野高中校长森杉多曾经参加过诺门坎战役和冲绳战役，深感于战争的残酷，并成为了一名反战主义者，因此始终拒绝动用暴力。当时连文部省和教委都多次找上门，质问森校长 “为何让学生乱搞”；但是森本人仍然不为所动，坚持支持学生们的 “自主研讨会”。

*四、终焉*

1969 年轰轰烈烈的高中生运动最终在大规模的弹压下消退。从那之后，从日本各高中到文部省，到处都在努力地抹去这段记忆；但是这场运动的成果却以各种各样的方式顽强地留存了下来。包括上野高的 “自主讲座”；也包括各校规则的宽松化。比如：经过斗争的洗礼后，神奈川县立希望之丘高中废除了旧校规，取而代之的是一份仅有 12 条的 “开放式校规”；中央大学附属高中自 1971 年开始也废除了校规和制服要求；都立北园高中设立了专门的纠纷处理机构，倾听学生代表的呼声；等等。

像《冰菓》中那样的事件，当然可能会有一个或已不可考的原型；但是在真实的历史上，绝大多数的同学们不会像作品中那样，在同伴遭到退学处分时保持沉默 —— 我们看到更多的是对校方处分的激烈反抗、两肋插刀般的强力声援。

另外，在《冰菓》中设定的 1967 年，日本实际上并没有发生大规模的高中运动。这一时期的大学斗争也只是刚刚开始，同年刚刚发生了早大斗争和明大斗争，而日大全共斗结成和安田讲堂事件都要等到一年后；至于火苗烧到高中则是两年之后的事情。这或许包含了米沢的什么隐喻，不过笔者觉得更大可能是不严谨的疏忽吧。

本文很大程度参考了 高桥雄造 先生 所著『高校生運動の歴史 新制高校・生徒会連合・60 年安保・“高校紛争”・反管理主義』（明石書店 2020.10）。高桥先生 1961 年毕业于日比谷高校，是当时高中生参与安保斗争的亲历者。在书中，高桥先生写道：

将第五次高中生运动的事迹记录于此，愿传达与现在和将来的高中生们。
正如本文开头中的那句台词般，“后之视今，亦犹今之视昔”，我们生活的 “当下”，也终有一天会成为后人手中的 “古籍”。

不过，除了 “列叙时人，录其所述”，我们还能做什么呢？教育的问题最近数次成为某乎的热门，比如某高校 “强制收购学生电动车”，某高校 “占用志愿者时间为个别人庆生”，某高校 “被反映水电费过高之后立即解散所有宿舍群”，某部门某人 “禁止学生参加 cos”，如此等等。当面对这样那样的问题时，大家总是会问，我们是应该保持沉默吗？

请不要忘了关谷纯最后留下的话：

#+begin_quote
如果软弱的话，

有朝一日会变得连悲鸣都无法发出。
#+end_quote

[2024-10-20 Sun]

** 也说辛瓦尔之死与评论乱象

（注：辛瓦尔为哈马斯首领）

Deep Van 等 2259 人赞同了该文章

现在猪肉哈巴们开始疯狂造谣 “辛瓦尔是奋战在第一线阵亡的”。

事实是，辛瓦尔自开战第一天就躲进加沙平民没资格进的地道东躲西藏，靠逼迫诱导平民承受以军报复火力，抢劫联合国及各国提供给加沙平民的物资苟活一年多的。

辛瓦尔没有逃离加沙首先是因为它是头号死硬分子，它已经被哈马斯内部的死硬派抬到一个不能出逃的位置。其次它在前期没有预料到以色列的决心。要知道它是以色列以 1000 换 1 的恐怖分子之一，在以色列医院接受过肿瘤治疗，在它的认知里，以色列迫于国际舆论压力，不可能对哈马斯穷追猛打也做不到赶尽杀绝，以军很快就会如以前一样停火撤军草草收场不了了之。而它手上的人质与加沙肉盾们，以及不知从哪儿学的 “战无不胜 " 的老鼠洞 “神技” 也能让以军无功而返。

到中期想逃也已经不可能了，加沙被完全封锁，埃及更是加盖了四道隔离墙（加上原来的两道则是六道）。加上以军扛住压力进军拉法，摧毁了通向埃及的所有地道，截断了加沙同穆兄会的联络。

第三，或许这些天真的恐怖分子和千里之外愚昧的猪肉哈巴一样幻想着 “中东大团结”（从它们给 1007 大屠杀起了个 “阿克萨大洪水” 的中二名字就能推想一二），“九国联军” 蜂起围攻以色列，伊朗能迅速指挥真主党配合进攻，胡赛拖鞋能千里急行军 “神兵天降”，阿拉伯诸国会在神棍振臂一呼下群起响应，渗透欧美的移民则能掀起全球反犹浪潮，裹挟白左彻底孤立以色列……

然而这一切都没有发生。阿拉伯国家不动如山，除了放几句嘴炮批评以色列，连接受巴勒斯坦难民都严词拒绝；不仅真主党没有全面进攻以色列，只是不痛不痒用比平时多一两分力的火箭弹骚扰，还不如拖鞋军卖力，连老大伊朗也迅速做了切割，躲在后面反复升旗了事；幻想中团结的盟友一个也没出现，在欧美世界用愚蠢野蛮的方式兴风作浪的移民反而吓坏了岁月静好的欧美基本盘，催动欧美右翼抬头，引发全球对穆斯林势力的警惕，欧美圣母们开始难以左右局面，各国政府开始加大力度打击、整治、遣返移民并收紧政策；虽有聊聊几个自身一塌糊涂的小丑国家 —— 比如南非、哥伦比亚、尼加拉瓜 —— 和以色列较劲，但主要国家依旧支持以色列，尤其是美德两个大国，至于法国、意大利、加拿大、西班牙、比利时、爱尔兰之流，他们和以色列的军火交易本就微不足道，本国更因为穆斯林移民问题焦头烂额，西班牙内阁更是因为贪腐问题摇摇欲坠

它最后露面只不过是因为地道里物资不足，生活条件恶劣，地道不断被以军起获摧毁，它躲藏的空间不断被压缩。

它之所以没带人质是因为它此次出洞大概率是日常透风，或与下属碰面，或是搜刮物资补给，带着人质不便行动。当然更有可能是它们早已把人质杀害。

它没有一如往常带着防弹少年团，则是因为躲藏在地道一年多，物资紧张，须要不断转移逃窜的情况下根本不可能持续带着儿童，真带着的话俩月就能把少年团折腾死。

这货是地下越来越待不住才到地面上来的。它冒头的地方也不是现在以军重点清剿的加沙北部贾巴利亚而是已经没什么以军的南端城镇拉法。是以色列巡逻队在例行巡视时发现了它和随员，看到它们持枪判定它们为哈马斯后才发动了打击。最后消灭辛瓦尔的是一名才加入 IDF 几个月的新兵，可见这次行动绝非具有针对性与明确目标的特种行动。

辛瓦尔并非如猪肉哈巴吹嘘的那样死于战斗，而是在逃窜途中意外遭遇以军被正法。它最后朝无人机抛出木棍不过是穷途末路垂死时刻滑稽的挣扎而已。

无聊地造谣，无耻地对宗教极端恐怖分子的吹捧，还有荒唐地拿伊斯兰极端恐怖分子来类比抗日英雄的行为，可以休矣！

[2024-10-20 Sun]

** 性格很单纯怎么在社会上生存？

87 人赞同了该回答

我输出一个暴论：性格单纯但又头脑够用或是勤劳的人最适合美国，一定要去美国



不是说 “美国是个（全民）不讲究关系的国家” （第一代公知暴论），而是我认为 “美国是个即使性格很单纯，也不会有很大劣势的国家”（应该算另外一种升级改造过的暴论了）



性格单纯永远是吃亏的，孩子，相信叔叔我；美国也是人间，也无法逆转这种事实，在美国性格单纯也是非常吃亏的，失去了上升的空间和八面玲珑的优势



但是，在美国即使性格单纯，不影响赚 50 万、100 万美元年薪 —— 也许 300 万美元年薪的人偶尔也有幼稚单纯的，只是我没亲眼所见所以不敢乱说；—— 基本上就不影响买房子娶妻生子，过快活日子了



尤其是，美国是个特别原子化的社会、每个人关起门来过自己的日子，到日子出来匿名投票，基本上把单纯的损害降低到了可能的最低。如果再可以做到离人群远远的，自然就不需要担心为人的缺点



做一份技术工作（如写码），或是苦力工作（如开大车、修房子），没什么头脑情商，在大部分国家可能过得很一般，但在美国还是不错的



说起来，人间终究永远没有天国。性格单纯的人在美国更合适，无非是因为她是第一强国、又是移民大国包容，哪怕性格单纯受很大的强度削弱后，也能获得还算不错的生活罢了

[2024-10-20 Sun]

** 如果丁胖子讲师在美国获得绿卡并且在短视频领域赚到钱买房子，国内会不会很破防，会不会对价值观有所重树？

真知棒 等 238 人赞同了该回答

我之前说过，中国人从性格来讲，适合润美的其实并不多。但讲师绝对是个例外，他属于那种比较少见的能力不差，而在性格上和中国相比明显更适合美国社会的。

讲师这人学习和信息获取的能力极强，社交主动性极高，而最大的毛病是好逸恶劳。这点在中国是极大的劣势，基本是一票否决那种，但在美国并不是。

先说信息获取能力，一个在厂里打螺丝的人并不需要这个能力，但去异国他乡生活的移民非常需要。信息获取能力不强，就意味着你会不断的踩雷。你以为是运气不好，实际上是因为你规避风险的能力太差。

你不知道走线路上有被撅的风险，那你就真会被撅。你不知道急诊一次多少钱，那就真会被坑。

你不知道一 dozen 是 12 个，以为多给了你一个，这件事倒是无伤大雅，但也足以让你成为笑料。

讲师是真能弄清楚哪些地方不能去，哪些人不能接近，哪些事情不能做。而大部分润壬没这个能力。

再说社交主动性，美国社会极度重视社交，nerd 属于鄙视链的最底层，不如地痞流氓。而这种社交还不是日本那种会读空气就行了，而是你自己必须健谈，还得说人家爱听的。

国内大部分人社交主动性如何懂的都懂。不懂的可以去带带学生，组织一次课堂讨论，体验一下该讨论的时候全班鸦雀无声是什么感觉。你要是点名叫起来一个，又可以体验一把支支吾吾一句完整的话都讲不出来是什么感觉。

最搞笑的是同样一批人到了网上又开始狂喷应试教育不让他们说话，不给他们表达的权利。我只能说真到了人人都能放开表达的环境下你们只会死得更快。

而讲师是真的面对任何人都不怯场，而且会主动揣测人家喜欢听什么。见到黑哥是 bro，见到老墨是 amigo，见到白人是 god bless you，见到南亚脸是 buddha bless you，见到中年胖大妈是 you are gorgeous。

也正是优秀的信息获取能力以及社交主动性让他精准找到了自己在美国社会中的生态位 —— 做实体宠物。没错，做电子宠物是拿不到投喂的，但做实体宠物真可以。

人在衣食无忧以后就会开始寻求情绪价值，会需要一个施舍的对象来满足自己的 “爱心”。所以白左魔怔一样没有弱势群体也要制造弱势群体，还真不完全是为了钱。他们是真享受这种 “我做了好事”“我帮助了弱者” 的满足感，别管他们做的事情实际有多离谱，跟中国那些把陆龟扔到海里放生的善男信女属于一路人。

只不过国内整体来讲还没那么富裕，施舍对象还以猫狗为主，而美国中产以上的阶层会变着法的让人成为他们的施舍对象来满足他们的情绪需求，比如不是性少数的要强迫你变成性少数。像移民难民这种主动送上门来的施舍对象他们高兴还来不及呢。最近飓风之后有人指责民主党有钱给非法移民建公寓却没钱救灾，其实这和国内狗粉重视狗命超过人命是一模一样的道理，主打一个能满足我情绪价值的才是命，不能满足我情绪价值的是死是活跟我有什么关系。

做实体宠物，通过满足 “爱心人士” 的情绪价值换取投喂，这个生态位在国内可能也存在，但仅限于三陪之类的，你做流浪汉肯定是吃不到这碗饭的，习惯了国内思维方式，对美国社会不够了解的人也想不到这条路。能不卖钩子，做个流浪汉就把实体宠物的投喂赚了，这是讲师凭自己的本事和对美国社会的理解摸索出来的路，背后还是他优秀的信息获取和社交能力。

只不过从这个角度来讲讲师其实也不算什么无业游民，而是服务业从业者，还是服务质量很高的那种。毕竟你只要投喂点临期食品就能换来好心情以及积功德的满足感，不差钱的美国中产谁不喜欢？

并不是所有宠物都能拿到投喂的，你得先学会摇尾巴才可以。那些一见到人就躲得远远的，甚至一上来就对人呲牙狂吠的，饿死了也没人在乎。而摇尾巴本身属于技术活，你在选择做宠物之前最好先照照镜子，看看自己有没有这个潜力。

某群体总喜欢说什么 “爱具体的人，而不是抽象的人”。结果真润了以后只会狂舔他们心目中抽象的文明灯塔，而身边实实在在的美国人对他们来说只是 NPC。相比之下讲师是真的愿意对具体的美国人提供服务。

所以你问如果讲师拿了绿卡买了房，国内会不会破防，会不会重塑价值观？反正我不会。他这样的人在美国混得好符合我的认知。

但那些跟风润美的人最后多半会破防。

毕竟讲师是在付出情绪价值，而大部分润人只会无条件索取包括情绪价值在内的一切价值。

[2024-10-20 Sun]

** Buckling Spring 和 Alps 轴体

听人说这两个是最高级的。

果真如此？但是国内没有的卖啊。

[2024-10-19 Sat]

** 为什么每个公司都有摸鱼的员工，但是这类员工反而还混的不错？

OwlLite

2021 年度新知答主
59 人赞同了该回答

虽然基本上全世界都是 8 小时左右的工作制，但对于典型的脑力劳动型工作（这类工作占比越来越高）来说，一天的有效工作时长通常不到这个世间的一半。

从大量实验的结论来看，一个典型的脑力劳动者每天最长能有效工作的时长大约是 5 个小时，更多时长的产出减去公司付出的成本来说是负值 [1][2]:


8 小时的工作时长中，至少有 3 小时对公司来说是负面效益

也就是说，8 小时的工作时长中，至少有 3 小时对公司来说是负面效益。前置要求员工 8 小时专注工作，也不会改变这个结果。实际上，对于人脑这个生理系统来说，持续 2 个小时的精神集中基本上是绝大部分人的生理能力的上限，对于高强度的脑力活动来说，这个时间更短 [3]. 因此， 追求比每天 4 个小时左右的有效工作时长不仅没有实际意义，而且在理论上也不大可能做到。从生理学角度来讲，长期强制性的拉长注意力集中的时间，不仅不会锻炼注意力，还会产生对神经系统的生理性损伤，产生抑郁症、焦虑症等结果 [4].

因此，在 8 小时的工作时长中，合理摸鱼不仅是必然的，而且是一种必要的休息，对个人和公司来说是 “双赢” 的选择。

实际上，在中大型公司中，我们会发现一个典型的工作日内，会需要有相当的部分被用来处理琐事，比如不太相关的各种会议，必要的各种业务流程和审批，大量的讨论等等。这些都是公司制度的必然和必要的摩擦损耗。在互联网大公司中，典型有效工作时长通常仅仅在每天 2~3 小时 [5].

会摸鱼的员工，意味着会合理的利用每天剩下一半以上的时间 更合理的休息，更多的去跟其他同事和部门沟通，互通信息和利益，达成更多有效的合作从而产生更好的结果。这对公司来说会产生远超每天连续工作 8 小时所能产生的价值，对于自身来说也意味着更健康的身体和精神状态 [6][7]。

从个人角度来讲，“摸鱼” 不要有愧疚感，合理化摸鱼并优化摸鱼才是必要的。

[2024-10-19 Sat]

** 坐标湾区，留美还是回北京 / 上海呢？

威尼斯嘟嘟
2790 人赞同了该回答
我是美本美博，大叔年龄，私企搬砖，纽约养娃。作为过来人我说两句。手机码字。

根据你对自己财务状况的描述，我认为目前你们并不适合做不可逆的二选一决定。差钱的人才做取舍，有钱的都能要。以二百万美元为界，你们净资产积累的越多，就越会觉得中美两国的好处都能沾上。所以当务之急是在不放弃 “选项” 的情况下，“鼓足干劲，力争上游，多快好省” 的积累财富；对你们而言，现阶段哪边更容易就选哪个。以下我举几个栗子。

如果都留在美国，鉴于数据科学家的工资收入低于大厂程序员，我建议你们至少要有一人转码赶赴风口。人在湾区，不仅转码相对容易，工作轻松的一方可以搞点副业比如房产中介，亚麻卖货，职业培训，赚点外快。

如果回国，常见且稳妥的办法是一方回国创业拿股权，另一方在美国硅谷拿高薪等绿卡；中国上限高美国底线高的好处同时享受。等不确定性消失后再团聚。这样做的缺点是很异地辛苦，变数也存在。中国大城市白领女多男少，美国湾区男多女少；鸡贼的做法是太太回国，老公留守。

夫妻都想一起回国也可以，办好国家利益豁免 NIW 或者投资移民，这样可以在美国以外等排期。万一国内创业不顺也可以回美国躺平。按照现在的行情，对于程序员以外的职业，如果没有绿卡，海龟后再 “归海” 有一定难度。如果自己不想移民拿绿卡，至少可以把娃娃生在美国，给他们一个选项。万一他们长大后卷不过国内各种做题家，在美国长大后做个普通白领也算是条退路。

生活中 duck 不必破釜沉舟，万事留足回旋空间。
[2024-10-19 Sat]

** 2023 年日本经济为什么越来越好？

576 人赞同了该回答
对于日本失去的三十年，以往可以嗤之以鼻，如今最好逐帧分析。

失去的三十年的含金量极有可能会随着时间推移而逐渐增加，原因也很简单，倒不是日本有多出色，而是其他人衬托的好。

目前来看，在其他人都普遍缺乏衰退局解法的情况下，日本自己尝试着摸索出了一条路，在找不到第二个衰退已成定局的情况下做的更好的例子时，日本的情况就是衰退局的最优解。

车马炮全齐是一种玩法，进残局之后又是另一种玩法，目前来看，日本的残局玩的并不难看。

首先，日本在衰退过程中做的最正确的一件事就是认知没有受到污染，讨论没有受到禁锢，关于日本衰退和停滞的相关研究因此得以充分展开。

对日本衰退研究的最充分，批判的最彻底的恰恰是日本人自己，其他人差不多都是在拾日本人的牙惠。

我们如今讨论日本经济状况的所有素材，所有话题，所有术语，几乎都是日本人自己搞出来，比如 “失去的三十年” 这个说法是野口悠纪雄提出来的，“资产负债表衰退” 是辜朝明提出来的，“加拉帕戈斯化” 是野村综合研究所提出来的，“产业空洞化” 是产业空心化的最初来源，也是日本经济学界最早提出的，其他还有诸如 “日本病”“中产下流”“泡沫经济”“少子化”，这些措辞都是日本人自己搞出来的。

你能想象某些国家的经济学家要是如此批评本国的经济状况会被扣上什么帽子吗？

日本经济学界几十年来一直在致力于研究日本的经济衰退问题，野口旭，山田昌弘，中谷巳之助，榊原英资，黑田东彦，这些日本经济学家都对日本衰退的现状进行了研究并提出了自己的看法，给出了措施，一些人的观点还能被采纳并形成政策。

比如黑田东彦就当任过日本央行总裁，榊原英资当年更是成功把因为签署广场协议而大幅升值，对日本出口造成严重影响的日本汇率重新贬了回去，挽回了相当一部分泡沫破裂导致的损失。

日本产经省编写并公开发行的产业经济政策史非常详实，甚至把许多重大政策会议的发言内容都一一罗列出来，说是档案都不为过了，这至少说明他们不忌讳合订本。

这至少证明日本人没有试图掩盖问题的存在，更没有因为有人指出问题，抨击时局就去捂嘴消音，把当事人打为 “非国民” 或者收受了韩国人资助的境外势力，他们承认问题，并展开研究，充分讨论，试着解决，成效如何且不说，但起码进入了解决环节，你如果压根就不承认问题的存在，请问如何解决？

日本民众对日本经济环境的不满和抱怨得以充分释放，这极大的释放了社会压力，毕竟出了问题还不让人说，往往会比问题本身更令人不满。

先承认问题存在，然后问题才有解决的可能，如果讳疾忌医，文过饰非，涂脂抹粉，生了病不是想办法抗病吃药打针，而是先靠猛打兴奋剂，强行维持一个满面红光的假象，那是在透支生命和浪费时间。

这是其一。

其次是人口问题。

日本泡沫经济破裂于上世纪 80 年代末 90 年代初，从那时候起，日本进入失去的三十年，但是日本人口直到 2009 年才开始负增长，也就是说，日本在泡沫经济破裂后维持了 20 年的人口正增长，到了今天更是东亚三国中总和生育率最高的国家。

人口问题是一切问题的根本，日本是怎么做到这一点的，有必要深入研究。

再次是资本环境较为安全，进入衰退周期后，日本企业依然在海外投资经营，并把利润输送回国内，而不是树倒猢狲散，一看衰退降临就跳船逃生，争先恐后的携资外逃。

日本在进入衰退的三十年后，高净值人口移民数字非常小，每年只有 200 到 300 人左右的高净值人口移民出国，所谓高净值人口，指的是个人净资产不少于 100 万美元的人口。

作为对比，高净值人口移民数量排世界第二的国家是俄罗斯，每年有超过 13 万高净值人口移民出国。

营商环境良好，资本预期稳定（坏的预期也好过没有预期），安全感较强，政策稳定，只有这样才能把资本留在国内。

最后是家底，日本在泡沫经济破裂前，是世界上对中小企业最友好的国家，也是对垄断资本最排斥最警惕的国家，日本为了扶持中小企业推出了大量相关法规，建立了大量制度工具，并坚决依法执行。

诸如《排除经济力量过度集中法》《反垄断法》《中小企业合理化促进法》《中小企业基本法》《中小企业现代化促进法》《中小企业指导法》《中小企业现代化资金扶植法》《中小企业协同组合法》《中小企业安定法》《百货店法》《大型企业参与事业活动调整法》《中小企业参与事业活动安定法》《下请中小企业法》《中小规模企业共济法》《关于确保中小企业在公家需求上的订单的法律》等专注于服务中小企业的法案，还设立了国民金融公库和中小企业金融公库，建立了信贷保险制度，出台了《信用保障协会法》为还不起债的企业建立保障机制。

日本对垄断企业的打压和对中小企业的扶持力度是首屈一指的，他们甚至还专门设置了一个中小企业厅，在防卫厅升格为防卫省之前，双方是平级机构，中小企业被视为重要性不低于国防的关键问题。

日本甚至形成了一整套围绕培育和扶持中小企业，抵制大企业大资本搞垄断的经济学理论，出现了一大批专注于追踪研究中小企业的经济学家，例如有泽广巳提出的二重结构论和系列化理论，中村秀一郎提出的大规模时代终结论，长岛总一郎提出的产业缝隙论，迈克尔・波特的簇群竞争论等等。

此外日本还鼓励中小企业和普通劳动者建立基层自组织，壮大其力量，让他们抱起团来，从而有效应对大资本大企业的倾轧和竞争，举个例子，日本甚至有窨井盖制造企业组成的窨井盖协会。

日本的劳工运动十分发达，自日本的钢铁，机电企业劳工率先组织起工会进行劳工运动后，日本各行各业纷纷效仿，出现了按行业建工会的特点，甚至形成了 “春斗” 的习惯，每年春季工会定期组织劳工举行斗争，提升劳资博弈中劳方的话语权，改善劳工的收入待遇和工作环境，政府则将当年的谈判结果整理后向全社会公布，让其它那些没有参与劳工运动的企业参考谈判结果来提升本企业的工资待遇，这极大促进了日本劳工的收入增长，甚至还启发了台湾地区，让台湾地区效仿日本形成了 “秋斗” 的习惯。

日本的劳工运动后来甚至开始注意到正式员工和临时工，和劳务派遣人员之间的待遇差别，并意识到以往的劳工运动没有把这些人纳入其中是严重失误，他们开始有意识的把临时工，劳务派遣人员也纳入到运动进程中，开始争取 “薪酬一致化”，在劳工运动中对正式工和临时工尽力做到一视同仁，这是非常非常非常正面的经验。

中小企业的培育和保护，对劳工运动的怀柔和放任，让日本形成了规模庞大，业态多样，丰富绵密的中小企业产业集群，提振了居民的可支配收入，改善了就业，缩小了贫富差距，形成了 “一亿总中流” 的局面。

哪怕经历了多年衰退，日本依然是一个名副其实的高收入国家，在 90 年代初泡沫经济破裂时，日本大学毕业生的第一笔工资（也就是所谓 “初任工资”）平均为 199600 日元（男子为 201800 日元），高中毕业生平均为 157900 日元（男子为 160100 日元），在泡沫经济于 1990 年破裂后，日本国民可支配收入依然维持了继续增长，直到 1997 年增速才开始放缓，到了 2010 年才首次出现下降，此后又连续波动，没有出现断崖式的大幅下跌和严重的大规模失业现象。

在衰退开始后，依然在很长一段时间维持了国民收入的增长，避免了国民收入水平出现大幅下滑，还避免了大规模失业现象，这种经验同样值得仔细研究。

后之视今，亦犹今之视昔，后人哀之而不鉴之，亦使后人而复哀后人也。
[2024-10-17 Thu]

** DONE 书评 of east of eden
:PROPERTIES:
:ARCHIVE_TIME: 2024-10-09 Wed 14:40
:ARCHIVE_FILE: ~/org/note.org
:ARCHIVE_OLPATH: entries
:ARCHIVE_CATEGORY: note
:ARCHIVE_TODO: DONE
:END:
<2024-10-08 Tue>

John Steinbeck 的 east of eden。首先是让人惋惜，其次是让人骂出，“其实获普利策奖的作家也只不过是一个二流作家”。

一开始最引人瞩目的就是简洁轻快的语言。以及之中完全在把握之中的叙事。

但是这种把握却让人觉得二流。因为……

对于角色的描写，仿佛是为了剧情而服务的。在这里原本两者一体的，却变为两个分离的个体了。主人公母亲的性格仿佛就是用来打破的---她不被允许发表自己的意见---在某一章节的最后，仿佛是理所当然的，她破天荒说出了自己的心里话。仿佛她的存在就是为了这一刻，作为一个死板的家庭里面的、无法表示自己观点的母亲，以这个身份在章节的末尾营造一种戏剧性。

又一章的末尾，主人公和自己的哥讲点心里话。但这却让人疑惑，“他果真是如此讲话的吗？”。主人公难得有一段长一些的对话，但却感觉和他的性格对不上？但其实是“他的性格”本身居然没有定形下来。

小说里面最难写的就是对话。至此我已经放弃这本书了，因为对话让人发觉作者水平不咋的。不会写对话建议像百年孤独一样别写。

** 表格像素对齐

https://emacs-china.org/t/org-mode/13248/16
[2024-10-16 Wed]

** 如何看待赛雷话金模仿户晨风的风格，进行欧洲之行的购买力拍摄？

真知棒
闹麻了
硅谷 IT 胖子 等 533 人赞同了该回答
不由得感慨，我们那时候想了解国外，还能上脸书油管 MSN Space，上了大学想润，师兄师姐还在军训的时候就指给你前人走过的路把四年安排的明明白白

现在小孩想了解了解国外，除了教科书和课本，基本就只能看到这种玩意儿了

普通人啊，最后对命运影响最大的，还是出生在什么时代…
[2024-10-16 Wed]

** 小镇做题家的局限在哪里？

大剪子

当然容易被 “老农民成功学” 忽悠了

所谓老农民成功学：就是人情世故，人际关系，攀大哥，当小弟，耍小心思，玩小聪明等一系列土味浓厚的北方内陆特色成功学的统称。其特点主要是把一切赚钱 / 成事 / 发展归结为谁带着谁，谁有哪个决策者的背景，厚黑学，其思维底层逻辑跟老农民没有本质区别

确实在过去某一段时间，在政商经济系统对社会资源分配比较强大的情况下，老农民成功学能迷惑不少人。但由于政商经济系统的大水漫灌早已结束，成建制的产业化链条早已吞吃主流市场，现在的增量都是在专精特新赛道上跑

这就导致现在拼市场能力，拼资本和钱，远大于拼关系。同时关系与关系的博弈过度内卷导致贬值严重，除非爹妈身份显赫否则基本不要想关系的事

小镇做题家出了做题的坑，但一不小心可能就会掉入老农民成功学的坑。没亲自赚过钱，不了解现代社会，从小的生活经验 + 见识都只剩下那个落后版本的模式。于是看到 “人际关系学 “/“攀附大哥学”，很容易就被忽悠了，真的把这种东西当真了

琢磨老农民成功学的小镇做题家，我没见过一个混出头的。底层到中产最重要的就是能力，你连干活都干不好，没人跟你讲什么虚无缥缈的关系

要破局先从小事做起：不管你是干教培，还是做代写，不管你是去大厂实习，还是去校内创业平台上找个团队进去干活。凡是自己力所能及，又可以盈利的事，对于想接触社会的做题家来说都是有必要的。整个社会就是一个大型问题求解场，不要只做线性僵死的题，而是要做某一类细分领域的问题解决专家

之所以做题家在教培上的收入有优势，就是因为他们在这方面的专家程度高，当然这里不是说以后就得干教培，而是成为细分领域专家很重要

[2024-10-16 Wed]

** [2024-10-16 Wed] 中国 9 月货币供应量 M2 同比增长 6.8%，前值为 6.3%，该数据说明了什么？

Deep Van

cpi 还是半死不活对吧？m1 还是负增长对吧？

没有必要拉我来回答啦，几乎一模一样的回答我有好几个，只是大部分被阿瓦隆了。这个回答可能也是。

m1 是消费投资先行指标，如果还是起不来，那至少未来三个月社零不会有太大起色。依旧需要财政政策刺激来弥补需求的下滑。

总之，希望接下来的刺激给力吧，不然大家就一起过苦日子呗。我已经消费降级，以前单刷食冶，现在改大渔南里奥。

** 2024 年诺贝尔经济学奖授予制度对经济繁荣的影响研究，如何理解这项研究？
[2024-10-15 Tue]

134 人赞同了该回答

阿西莫格鲁和罗宾逊在《国家为什么会失败》中主要想说的就是，包容性经济和政治制度是经济持续繁荣的普遍原因。

他们采取的分类范畴是将政治经济制度分为 “容纳型” 体制和 “掠取型” 体制。

“容纳型”（inclusive）体制促使广泛的社会成员参与政治并分享经济财富，而 “掠取型”（extractive）体制导致统治精英同时垄断政治权力和经济资本（这是人为 “设计” 的产物，也不会发生自然转变）。

两种体制的差异会严重影响一个国家的兴衰，尤其是其长期发展的命运。

如果存在掠夺性经济制度（一般和掠夺性政治制度连为一体），企业家才能的整体收益会下降，如图所示：社会均衡点从 E1 移动到 E2，企业家数目大幅减少。


首先掠夺性的制度一般产权保护做的不足，这样企业家将不能获得他们创造的所有回报。

比如正常情况下企业家才能能获得 75000 美元的回报，但产权不完整时企业家需要贿赂政府官员（交保护费），比如 50000 美元，这时候企业家才能回报只有 25000 美元，低于机会成本，这部分企业家将不会选择成为企业家。

其次是法制不健全无法保证合约的有效执行，这会增加企业与供应商签订合约的成本，大量减少商业活动，从而减少企业家才能回报。

再次，掠夺性的制度还会增加机会成本。在正常情况下，只要企业家才能高于 50000 美元，人们就会选择成为企业家。但如果掠夺性的制度建立了进入壁垒，情况就不一样了。

比如每个企业家在创办企业时还必须交 25000 美元获得创业许可，那只有那些回报高于 75000 美元的潜在企业家才是有利可图的。


如果存在前面两种情况，那均衡点将继续左移到 E3，企业家数目进一步减少，创业、投资活动减弱，这会导致企业减少、GDP 降低、失业增加。

政府能做的自然是创造好的营商环境，根据上述模型，好的营商环境就是法治保障私人产权以及合约的执行，同时政府退出竞争性领域，让市场发挥基础性的资源配置作用，减少创业的机会成本。

即便除了今年诺奖得主，其他经济学家也都不对政府有形大手干预经济抱有乐观的期望。

新古典宏观经济学创始人卢卡斯在对萨缪尔森的货币经济的交叠世代模型研究后所发表《预期和货币中性》中强调，人依然是理性的且会对政府的各种经济干预政策提前作出预判从而使得经济干预政策失效。从这个意义上看，政府的货币政策是无效的。

卢卡斯在一系列文章里引入世代交叠模型与理性预期假设对经济周期作出全新的解释：在分析经济周期时，需要探讨外在冲击是暂时的还是永久的。

在资本不变的前提下如果是暂时冲击，个人会进行跨期选择替代；如果是永久性冲击，个人的决策保持不变。在资本可变情况下，决策相反。

同时，由于存在时滞个人选择会更复杂。如此一来，我们就能对经济周期进行准确的理论刻画。而由这套一般均衡的新古典经济学理论得出的政策建议就是放任自由，由个人的理性预期来应对外在的冲击。

而且，由于理性预期的存在，所有经济政策都会被预期到从而失去调控经济的作用。

同样也包括提出外生经济增长模型的索洛。在索洛模型中对经济总体的增长贡献被设定为由劳动、资本和技术进步三者组成，并且假设边际生产递减的一次齐次的总生产函数、满足特定数学条件、储蓄率不变。技术进步完全外生，不能由模型内部的参数决定。

在约束条件基础上索洛得出了促进经济增长的最优资源配置方案，同时也得出了政府政策对于经济增长的作用是无效的结论。

当然，奥地利学派的哈耶克和芝加哥学派的弗里德曼就更不用谈了（老熟人了），除了对政府干预经济不持乐观态度甚至反对之外，他们的另一个共同点就是都是诺贝尔奖得主（诺奖，只是参与讨论的门槛 doge

** 学级委员一条同学
[2024-10-13 Sun]

“那为何还在画漫画？” 答案很单纯，那就是因为你的笑靥。可是面对如此单纯的答案，押山清高却不得不进行一连的画面与音乐的铺陈。藤本树一格的内容不得不迫使押山使出浑身的解数，却只能眼睁睁地看着自己的动画在破坏那一极为单纯的瞬间。动画成了破坏转瞬之形象、把 < 瞬间 > 堕落成 < 持续 > 的劣化装置。《蓦然回首》的漫画有一个不得不令人不安的地方，那就是主人公们初次相遇时，与当时的气氛毫不协调，遽然出现在人物脚边的黑黢黢的洞坑。不知为何，藤本一定要画出人物的脚边，执意把这个洞坑安排在明暗的交界线上，让京本就站在洞坑与阴影的边缘。可是，为漫画填充种种丰富的风景的押山，就像用动画的 < 持续 > 淹没漫画的 < 瞬间 > 一般，很自然地用沟槽盖盖住了这个近在咫尺的危险。

** [2024-10-13 Sun] 如何看待杭州二胎妈妈夜班后只睡 2 个小时就起床给孩子做早饭？

真知棒 等 2693 人赞同了该回答
这种人

学生时代是用 10 种颜色的笔抄写勾股定理

工作时期调个 PPT 字体大小可以调一个礼拜

英语单词背个 abandon 背一年的那种

把自己感动的不得了，然后质问别人为什么看不见她的付出，稍微有点不顺心的地方就会歇斯底里发疯砸东西。

疑演丁真，鉴定为：经典力学的试验田，给两巴掌就老实了

** [2024-10-12 Sat] 如何评价曹丰泽突然转进视频赛道？

16 人赞同了该回答
我发现很多人都在刻舟求剑，根本意识不到一个问题：

世界发展太快，已经不一样了！拿旧时代（7-8 年前甚至更早）的刻板印象来套疫情后的时代，根本就是刻舟求剑。

很多回答拿曹博和曾博对比，其实他们虽然毕业只差几年，但是世界早就天翻地覆了。

曾博其实命很好，恰好又是在顶级 CS 豪门 UCB 读的博，虽然方向不是计算机但是转码机会很明显的，在泡沫最大最容易的年代、学校和硅谷转码，还赶上一次独角兽 IPO，本来就是时代红利吃的足足的。但是这条路，曹博真的没有，你们不会真以为差 5 年的这两个人机会真一样吧？

2020 或者 2021 年毕业的清华博士，你就算牛逼又怎么样？路真的很多吗？三清博士很了不起吗？记不记得就是那个时间段深圳中学招了多少清北毕业的当老师？现在呢？已经降薪了.....。他们才能比起曹博断档吗？

退一万步，就算曹博真的选择毕业转码，你不会觉得非科班的国内互联网码农在 2020 年以后就很好混吧？非科班博士 + 3 年工作经验，你觉得在今天的国内互联网大厂算什么？

他转码当然会有口饭吃，甚至可能第一份工作 offer 还不错，那到了 2024 年退潮，还会比现在强很多吗？别说三清的博士，就算是疫情里美国毕业的 CS 博士，2022 年以后还一堆被迫回亚洲工作的（只谈 offer，都没到抽签那一步）。

至于选调，这种事和三总五项一回事，早几年晚几年天地之差，计算机这个东西还确实有可能你少年成名牛逼到做出别人做不出的，打灰和公务员那就是一本以上其实人人平等就看上面机会愿意给谁了。坑就那么多，别人先占了，在公司里你还有 5-10% 的机会，但是体制内你 PK 掉他的机会是 0。今天选调真那么香这么牛逼的话，为什么深圳中学还招的到清北硕博当老师吗？

所以时代比学历重要 100 倍。生套前人的经验这是没见过市面的体现，20 年前我前老板博士毕业 + 5 年工作经验海归直接空降实职正厅（一把手，手下 1500 人 + 2 个院士）。往后推 10 年，当年我的同学里留国内搞学术的基本都是 30 岁前后就解决副教授，最快的一个是 28 岁正教授了，同样能力的同学出国后海归的反而 40 岁才搞定正教授。再往后推 10 年，今天你现在让美国 TOP 30 的教授海归看看能不能保证有杰青？

所以，曹博其实面对的机会并不是很多，这个不是他的问题，甚至不是土木的问题，是时代的问题。打灰只是把问题体现的更严重了，但是作为一个巨大的夕阳产业，还是有不少遗留红利可以抛洒出来。只是这些红利是有代价的，非洲就是代价。

现在全世界一个巨大的趋势就是，所有的职业红利都在快速消失，就像我面对很多咨询我的人，回答要比之前困难很多，因为不知道有什么真正的明路可以提供给人。嘲笑曹博这个行为本身属于不能认识这个时代洪流。

回到题目本身，曹博对于视频赛道的尝试对他自己在这个时代寻找方向是个正确的战略，能不能成功那是战术问题，但是去不去尝试是战略问题。

** [2024-10-12 Sat] 现代的 “资本家” 是如何定义？超市、小饭馆、小公司等的小老板算吗？

雨宫优子

3 人赞同了该回答

#+begin_quote
在《资本论》中，马克思主要是在结构意义上使用阶级概念的。因此，当他讨论一种特定的阶级关系时，是以资本关系为基础的：一方面是货币和生产资料的占有者，另一方面是在双重意义上 “自由的” 劳动者。那些既非资产阶级又非无产阶级的群体，主要是个体的手工业者、小商人、小农民，被马克思称为中间阶级或小资产阶级。

结构意义上的阶级无需通过其独特的历史印记来表现自己：资本家不一定要抽雪茄、配司机，无产阶级也不一定都是产业工人，居住在工人居住区。这种陈腐看法的消解也不意味着阶级的终结，而只是其历史形态的改变。

一个人在结构意义上属于哪一个阶级，也无法通过形式的特征来确定，比如看是否存在一种雇佣劳动关系，而是要看他在生产过程中的位置。更准确地说：只有在 “资本的总过程” 的层面，即马克思在第三卷中所达到的层面，以生产过程和流通过程的统一体为前提，才能确定阶级问题。在这一层面就会发现，无法只凭借是否占有生产资料来判定一个人的阶级。一个股份公司的董事长在形式上可能像是个雇佣劳动者，事实上他是 “职能资本家”，他支配着资本（即便不是他自己的财产），组织着剥削，而他的 “薪酬” 不来自他自己的劳动力，而是被生产出来的利润。与之相反，许多形式上自主的（可能甚至还占有一些小生产资料的）人始终还是无产阶级，他们事实上还是依靠出卖自己的劳动力生活，只是其生活条件可能比身处形式上的雇佣劳动关系之中更加糟糕。
#+end_quote

—— 米夏埃尔・海因里希《政治经济学批判》

** [2024-10-12 Sat] 互联网已经将绝大部分信息差抹除了，知识已经随处可以获得，为何大部分人依旧无法获得大幅突破？

作者：Zpuzzle

雨宫优子 等 447 人赞同了该回答
互联网只是将一些以前普通人需要花费更高成本获得的资源变得更为廉价，但整体上看，互联网非但没有做到抹平信息差，甚至还把信息差变得更大了。如同题目所问，“知识已经随处可以获得”，恰恰是问题的真正所在。

这里可以做这么一个设想，如果你是皇帝，手下有两个大臣分别向你汇报一件事，一个人说这件事情可以做，做了之后大大的利国利民，另一个说不能做，做了之后就是祸国殃民。那么，你该采纳哪位大臣的意见？

假如说采纳其中某位大臣的意见，就能实现预期的结果，其实并非是坏事，因为就算是必须要二选一，至少还有 50% 的概率成功。假如在这之外，再有其他的想法，结果可能就更糟。就如同是在三大战役中，国民党方面无论是坚决的打还是坚决地撤，结局都会比现在好很多。

而在有些时候，事情就是相反的，两个人看似说的都有道理，却可能都不对。比如有的人说要向南走，有的人要向北走，但实际上可能向东走才是对的。

如此，就可以看到，信息的增多对与普通人来说绝非是好事，因为信息的增多同时也意味着噪声的增多。而现实中，一个领导如果只有两个选择，那已经是万幸中的万幸，大多数时候，领导要面对的是十几种乃至于几十种选择，听到的也是几百种乃至成千上万种声音。

这个机制，也可以反过来被利用。欧美国家的议会会议中，假如有些提案无法通过，发起提案的一方还有个阴招 —— 制造噪声。例如，这个提案有 10 项内容，其中 8 项可以通过，2 项无法通过。那么，提案方就可以先把这 8 项内容做一个单独的提案通过，然后过段时间再提交一项有 2000 项内容的提案，将这没通过的两项放入其中。

他们赌的就是没有人会认真看这 2000 项内容。而现实中，这种策略屡屡都能奏效。

这些大都毕业于名校的精英们，在面对信息轰炸时尚且如此，更不用说普通人。一方面，人对于信息的处理能力是有上限的，信息的增多对很多人来说非但不是好事，反而意味着 “噪声” 的增多；另一方面，如果互联网上的 “信息” 真的只是信息倒还好，但现在互联网上的内容 —— 尤其是进入到了自媒体时代之后，由于人人都可以在网上传播信息，很多 “信息” 实际上只是 “观点”。

客观来说，在互联网时代以前，虽然人们获取信息的效率不高，但这并不意味着获取的信息质量低。这是因为在互联网时代以前，出版传媒行业还是相对精英化的，内容需要经过一系列的制作与审核才可以进入市场。这固然限制了大量普通人发声，却也意味着只有达到一定质量标准的内容才可以进入市场。

对于普通人来说，就算你无法判明信息，但只要认准媒介的品牌，大概率是不会踩雷的。比如，商务印书馆、中华书局、人民文学出版社等等业内知名的出版社，虽然也有烂书，但绝大多数的出版物质量都是比较高的。

哪怕是这些年一直被吐槽的《南方周末》等 “南方系” 的报纸，你可以基于自己的认知说其 “屁股歪” 等等，但不得不承认的是，这些报纸杂志的写作水平和编辑水平真的是非常高的。认不认同其观点是一回事，但信息的收集、写作是一门技术，这是可以有相对客观的评价标准的。

后来随着媒介的发展，出版物越来越多，对于普通人来说，获得高质量的信息就成为了一种麻烦。那该怎么办呢？于是，一个今天无数硕博都非常熟悉的东西就出现了 —— 文献索引，即 SCI、SSCI、CSSCI、AMI、CSCD 等等一系列的文献索引系统。

这种文献索引的核心目的，是按照相应的标准在所有的期刊中，挑选出一批质量相对较高的期刊，使科研人员能够节省精力来获得高质量的文献。当然，随后这就成为了一套评价标准，能否在这些期刊上发表文章，也成为了认定科研人员水平的一条线。

显然，至少在目前的互联网上并不存在这么一套系统。那么对于普通人来说，如果不事先具备一定的收集分析信息的能力，面对海量的信息轰炸，完全没有能力去区分出哪些是有用的信息。

假如只是信息量的增多，倒也还好，因为只要按照一定的标准去筛选，总能筛选出高质量的信息。但如前面所说，互联网上的很多信息，实际上是 “观点”，而这种观点又往往是跟情绪绑定在一起的，这就非常糟糕了。

举个例子，现在你去社交媒体搜随便一个普通二线省会城市的就业如何，都会看到大量类似 “XX 来了 XX 也得打 500 个销售电话” 之类的内容。对于 A 城市的描述，你换成 B 城市也完全不违和。你看多了这种信息，就会觉得哪怕是二线城市也是一片凋敝。

可如果你真的准备回到家乡的省会就业，应该怎么做呢？你可能需要收集城市经济的大体情况，自己对应的行业这几年的产业规划和现在企业的规模，然后可能还要研究一下这些企业这些年的发展情况，判断未来的成长空间。如有必要，甚至要去实地看一下，或者找一些相关的人员咨询。这是需要付出大量的时间和金钱成本的。

这样的信息有些在互联网上可以找到，有些找不到，但即便是能公开找到的信息，也需要你花大量的时间甄别，更不用说那些非公开的信息了。至于说如何收集信息、如何分析信息等等，这其实也算是一门学问。不同学科都有对于各自领域内信息进行收集、分析的方法，而这些一般都要经过系统的学习才可掌握。

这也就是我之前说的 “你一个中国人比美国人还了解美国？” 这种观点的错误之处。一个中国的经济学者，完全有可能比在美国生活的普通人更了解美国经济 —— 后者可能连美联储发布的数据都看不懂。同样，一个欧美的汉学家，无论是语言能力还是对中国文化的认识，也要远比大多数的中国人高得多的多。

但在互联网时代里，“专家” 的价值正逐渐消失。这一点，欧美的学者研究非常多。在前互联网时代，很多人对知识分子会有一种尊重和认可，因为普通人能接触的信息媒介有限，而这些知识分子不仅读书多，而且也占据了媒介传播的中心。我们小的时候，父母经常会用 “书上说了什么什么”、“电视上说了什么什么” 来说明某件事是重要、合理的，就是这种媒介传播特点的影响。但在互联网时代，由于每个人都可以接触大量的信息，“专家” 的优势也已经消失。再加上媒介对于 “专家” 信息的传播经常是断章取义、博取流量，这导致很多人对于 “专家” 已经完全失去了耐心。

如果说自己不认可 “专家” 的言论，但能自己搞出一套属于自己的认知，也不是什么问题。然而，这是不可能的。

之前网红猫一杯在巴黎捡作业的那个事件中，很多人在讨论这件事时，将关注点放在了事情的真假上。但我看到有一位博主的话说的很好，他说，就算这件事是真的，一个在国外捡到作业的事情，值得被炒的这么热吗？

这也就是如今的日常。很多人虽然再说互联网让信息的获取更方便，但真打开手机，他们更愿意看 “老公”、“老婆” 扭扭屁股，顺便给自己看得顺眼的主播打个赏。

你说看个哈佛大学的公开课，哪有听直播间的美女说一声 “谢谢榜一大哥” 来得爽是吧？

我在之前的回答里，多次引用过刘慈欣《诗云》里的一个情节。在那个小说里，刘慈欣设定了一个能写诗的工具，其能够通过文字的组合写出大量的诗，穷尽所有的可能，其中还有很多诗甚至比李白写的都要好很多。

然而，唯一的问题是，怎么把这些诗选出来。

如果你本身就读了很多诗且具备鉴赏能力，即便选不出超越李白的诗，但选几首不输于明清名家的作品总不是问题，但如果说一个人连《唐诗三百首》都没看完过，那他最终选出几首喊麦歌词，觉得这个超越了李白也很有可能。假如我们认为未来的 AI 真的有具备人一样的完全的智能能力的话，那么未来的 AI 与使用者一定是逐步趋同的。也就是说，你是什么样的人，就会把 AI 向什么方向调教，最终让 AI 与自己的水平相匹配。

手下有能臣，并不表示你不会是昏君。

** [2024-10-12 Sat] 如果当面叫一个现代英国人「盎格鲁撒克逊人」会怎么样？

康员外
无书不看，无话不谈
刘镇锐 等 108 人赞同了该回答
盎格鲁 - 萨克逊这个词现在的使用一般局限于历史和语言研究，在当下的日常中用它确实会有些让英美人摸不着头脑，但这并不代表盎格鲁萨克逊从来就是一个单纯的学术词汇。直到二十世纪，盎格鲁萨克逊都是一个英美主流族群自我标榜的民族主义和种族优越的词藻，它的退潮主要源于二战后整个西方对民族主义恶果的反省和摒弃，以及美国的族裔政治演变。

狭义的 “盎格鲁人” 和 “萨克逊人” 指的是历史上从日耳曼北部迁徙到英格兰的两大族群，他们在英格兰建立了影响至今的封建秩序，“盎格鲁” 变成了这个整个岛屿南方政治秩序的名称 “英格兰”，而 “萨克逊人的王国” 更是在英格兰的核心上留下了自己的烙印（萨塞克斯，威塞克斯，埃塞克斯，和米德塞克斯的 “赛克斯” 就是 “萨克逊”），更重要的是，盎格鲁 - 萨克逊人带来的日耳曼语言更是成了后世英语的主体，把 “盎格鲁 - 萨克逊” 和英格兰的语言深深地绑定在了一起。

但在之后的千百年变迁后，特别是在约翰王失地，百年战败以及国教会建立之后，“盎格鲁 - 萨克逊人” 逐渐成了一种 “操英语的英格兰非凯尔特人非天主教徒” 的统称，在中世纪封建秩序向现代民族主义的发展中成了 “英格兰的主体民族” 的代称。

特别讽刺的是，这种民族的构建是建立在一种对 “敌对种族” 的优越性上的。作为 “昂撒人” 的最重要特点是你不能是凯尔特人，不能和苏格兰爱尔兰威尔士的信天主教的蛮子叛徒们沆瀣一气。光荣的盎格鲁 - 萨克逊传统来自于日耳曼最高贵的部落，在英格兰的海岛上绽放了独立的荣耀之花，诞生了英勇的阿尔弗雷德和虔诚的爱德华，保持了英格兰独立于欧洲大陆的秩序与制度。哪怕诺曼征服之后，征服者依旧折服和同化于盎格鲁萨克逊独立于大陆的传统（其实是因为他们从大陆被赶跑了），采用优越的英格兰法律，采用撒克逊王名爱德华，更有甚者，认为维京人诺曼人和北日耳曼的盎格鲁 - 萨克逊人同宗同源，所以诺曼征服也算自己人，都属于一种 “条顿传统”。。。而亨利八世自立教会更是这一独立自主传统的光荣典范，凸显了盎格鲁 - 萨克逊人相对于岛上顽冥不化盲从罗马的凯尔特人，以及欧洲大陆上受困于陆权僵局的大陆人的优越性。

简而言之，在英格兰民族优越论的叙事中，“盎格鲁 - 萨克逊” 的内涵就是：

“我们比欧洲大陆那帮人不知道高到哪里去了”

“苏格兰人只配做狗，爱尔兰人狗都不如”

这一套说法在 18-19 世纪新兴的英格兰平民资产阶级中是很吃的开的，因为他们不像王室贵族有着能上溯到高贵的法兰克日耳曼先君的明确家系，他们唯一引以为荣的民族身份只能来源于他们脚下的土地 “盎格鲁之国” 和他们口中的 “盎格鲁语”。于是这种基于 “盎格鲁 - 萨克逊” 的优越感也被英国的平民殖民者带到了新大陆。

在新大陆，“盎格鲁 - 萨克逊” 的种族主义被催化出了新的巅峰：最初的北美东海岸并不是只有英格兰殖民地，还有瑞典，荷兰，法国，西班牙和爱尔兰天主教徒的殖民地。为了争夺殖民地利益，鼓吹英格兰殖民扩张的正当性，在殖民地的英国移民就很自然的转用了 “盎格鲁 - 撒克逊优越论”，于是就有了这段美国国父关于种族的典范论述：

#+begin_quote
the Number of purely white People in the World is proportionably very small. All Africa is black or tawny. Asia chiefly tawny. America (exclusive of the new Comers) wholly so. And in Europe, the Spaniards, Italians, French, Russians and Swedes, are generally of what we call a swarthy Complexion; as are the Germans also, the Saxons only excepted, who with the English, make the principal Body of White People on the Face of the Earth. I could wish their Numbers were increased. And while we are, as I may call it, Scouring our Planet, by clearing America of Woods, and so making this Side of our Globe reflect a brighter Light to the Eyes of Inhabitants in Mars or Venus, why should we in the Sight of Superior Beings, darken its People? why increase the Sons of Africa, by Planting them in America, where we have so fair an Opportunity, by excluding all Blacks and Tawneys, of increasing the lovely White and Red?
Benjamin Franklin； Observations Concerning the Increase of Mankind, Peopling of Countries, etc.
纯种白人在这世上所占比例是很低的。 非洲人肤色要么黑要么棕黄，亚洲人大多肤色棕黄，美洲土著亦然。就算在欧洲，西班牙人，意大利人，法国人，俄国人和瑞典人的肤都只堪称为暗沉。大多数日耳曼人也是如此，除了萨克逊人。萨克逊人和英格兰（盎格鲁）人是地球表面白种人的主体，而我希望这些白种人的数量能够增长众多。当我们开垦美洲森林来净化新世界，从而使我们这个半球连在火星和金星的居民眼中都能够反射着光彩的同时，我们为什么要黯淡了这片土地上的居民？如果我们有机会把所有黑黄皮肤的人都排除在外，让可爱的白种人增长众多，我们为什么还要把非洲人带来美洲？
—— 本杰明。富兰克林；关于诸国人口定居等事务的观察
#+end_quote

当然在富兰克林后面很直接的承认 “我的看法可能受到我国肤色的影响，但这种偏见举世皆然”。但这段话却非常好的概括了 “盎格鲁 - 萨克逊优越论” 对于殖民扩张和种族压迫的加持：即便后来美国不如富兰克林所愿没有保持北美种族纯净而是依然引进了大量黑奴和爱尔兰 / 日耳曼 / 意大利 / 天主教徒劳工，这套 “盎格鲁萨克逊优越论” 依然是确保英格兰裔移民奴役黑人和剥削其他白人族裔的理论基础。于是在美国诞生了一个有名的缩写来代表美国的 “主体民族 / 统治阶级”“WASP”——“白种（white）盎格鲁（anglo）撒克逊（saxon）新教徒（protestant）”。而在英国本土，“盎格鲁萨克逊优越论” 的顶峰是在帝国昌盛的维多利亚时期，特别是在全欧土豆歉收从而间接导致全欧洲大革命的 1840 中叶，英格兰人一面把粮食从爱尔兰人嘴里抢到英国，一面把大量 “不安定分子” 流放澳大利亚，于是他们就一面看着爱尔兰人饿死，一面看着欧洲革命遍地自家太平依旧，感叹 “盎格鲁萨克逊人就是比欧洲大陆的暴民和岛上的凯尔特蠢货要优越啊！”

当然，英国人搞得这一套本位种族优越论在欧洲也不是个例，当时法国人也在搞以法国为领导的 “泛拉丁主义”；意大利人也尝试从故纸堆里找出把南北半岛捆在一起的依据；俄罗斯人在搞 “信仰，民族，专制君主” 的神圣三位一体；匈牙利人在搞 “匈牙利人要说匈牙利语，斯洛文尼亚人更要说匈牙利语” 的民族革命；而日耳曼人。。。日耳曼的民族主义最后产生了什么，想必大家都知道了。

是的，作为全欧洲近代民族主义浪潮的一份子，英国的 “盎格鲁 - 萨克逊主义” 最后不可避免的被卷入了二十世纪初近五十年的 “欧洲民族主义大乱斗”，二战落幕，整个欧洲的民族主义运动陷入了空前的低潮，要么如东欧般噤若寒蝉，要么如西欧般心灰意冷，大多数英国人终于意识到了 “盎格鲁萨克逊天下第一” 的傲慢和狂妄是怎样把整个亚洲，非洲和（最重要的）欧洲都拖入地狱的。于是随着帝国的瓦解，英格兰人的民族主义变得隐晦衰落了很多，以至于 “盎格鲁 - 萨克逊” 也慢慢回归成了一种学术词汇。

至于美国，一战二战的空前动员以及战后对于经济增长填补空白市场的疯狂需求使得美国人不再只能依赖规模有限的 “盎格鲁 - 萨克逊” 族裔来支撑这个巨大无比的帝国了。在二十世纪早期，美国人就逐渐放宽了十九世纪极为普遍的对于中欧南欧和天主教移民的歧视和限制；二战时期，美国终于废除了对华人歧视性的排华法案；二十世纪中叶，轰轰烈烈的民权运动更是终于把黑人与白人之间的平等问题放上了台面。在这一系列不同族裔政治和经济权利的扩张后，“盎格鲁萨克逊” 美国人终于意识到自己不再在选票和财富上占有绝对优势了，天主教徒和黑人都当上总统了，于是新一代的 “WASP” 们团结一切可以团结的力量，用广义的肤色而不是狭义的族裔为基础，用广义的基督教而不是狭义的教派为纽带，塑造出了新一代以福音派白人基督徒为代表的美国保守派。不管你祖宗是德国人 / 意大利人 / 爱尔兰人 / 斯堪的纳维亚人，不管你属于圣公会 / 浸信会 / 卫理宗 / 天主教 /（哪怕是）摩门教，只要你皮肤白，只要你认为美国应该是个白人国家，只要你认为不信上帝的人都该下地狱，那么欢迎来到这个保守派的大家庭。而美国曾经风靡数代的 “盎格鲁 - 萨克逊优越主义”，也在这种新世代的 “保守主义大团结” 中就慢慢地被消解了，连三 K 党这种反犹反黑反天主教反爱尔兰人的极端白人至上组织都开始接纳天主教徒了。

二战后，当丘吉尔出版了 “泛盎格鲁” 的集大成之作 “英语民族史”，尝试构建一个团结英美澳加非的 “英语民族” 时，大西洋两岸的人们都冷淡地看着这个已经不属于这个时代的音符，美国乐此不疲地肢解着英帝国的脚步没有慢下一分。

所以，当下的英美人听到 “盎格鲁 - 萨克逊” 大多会有些陌生，仿佛你用一种极古老的古称，称德国人 “尼伯龙根子嗣 / 洛恩格林后裔”，称中国人为 “华夏 / 赤县神州之人” 一样 ，懂些历史的人可能在联想起盎格鲁萨克逊这个词背后的民族主义和殖民主义色彩后会微微一笑，然后要么开始大吹英格兰的光荣历史，要么开始和你讨论不同历史阶段帝国主义的不同形式。


或者（打个不太恰当的比方），随意称英美人为 “盎格鲁 - 萨克逊” 也有点像随意称呼中国人为 “皇汉”，都有一种不假选择地斥责 “你们这群种族优越分子” 的意味（英美人又不全是昂撒，中国也不是只有汉族，更何况又不是所有人都是种族主义者，你对着个爱尔兰裔骂他昂撒和对着个中国人骂他日本鬼子一样。。。）。当然，中国人既没有像英德一样吃过极端民族主义的苦头，也没有像美国人一样面临昂撒不再主流的处境，所以 “皇汉” 的涵义还没有像 “昂撒” 一样被消解罢了。

** [2024-10-10 Thu] 塔利班颁布新 “道德法” 彻底剥夺妇女基本权利，塔利班声称这是伊斯兰 “传统”。这种 “传统” 需要被尊重吗？

有人提到了这一点 @时令塘野老

就多介绍一点。

不可否认，塔利班今天对女性很多恶劣行为确实是基于伊斯兰教的糟粕或者伊斯兰教的画皮。

但这些不能全部归结为 “穆圣” 的古老智慧，而是来源于这块山区几千年的 “普什图智慧”—— 即普什图瓦里（ Pashtunwali）或者可以称之为普什图价值观，普什图传统习俗

（如果听说过 在红翼行动中，即使对抗塔利班也要庇护美军坠落飞行员的阿富汗部落的故事的话，这个阿富汗部落秉承的也是 “普什图瓦里” 中应该不惜一切代价庇护向你寻求援助的人这条规则。

这种骑士精神的准则和女性财产化的准则同时存在）

比如女性教育这一点，公开报道表示塔利班禁止一切女性上学。

但伊斯兰教并没有强调这一点，反而伊斯兰教从古到今都是允许妇女接受教育的 —— 当然是有隔离教育和教育内容上的差异，这一点是糟粕绝不否定。

比如古兰经里就有 “求知对所有男女穆斯林是主命（天命）”—— 这里男女都点了。

比如圣训里提到过 “辅士的妇女们是多么的光辉；羞耻并没有阻止他们在信仰上变得博学”（博学甚至是一个优点）

而看看实践，看古代，穆罕默德的妻子赫蒂彻和女儿法蒂玛都是接受教育的女性，而且黄金时代的伊斯兰女性教育是不缺乏的，甚至有上千名女性伊斯兰教学者，看今天，两个最清真国家，沙特和伊朗，这两个国家从建国开始就没有禁止过女性教育，伊朗甚至愿意给临时婚姻这种为公开卖淫这种教法上的老玩意开绿灯，也没有禁止过女性教育，沙特更是创下了所有大学毕业生中有 56% 是女性的案例。对这两个国家来说，禁止女性任何教育甚至不是一个值得讨论的话题，当然开展特殊只对女性的伊斯兰女性教育，经学教育，男女教学隔离等等等等是广泛存在的。

那塔利班这些玩意是怎么来的呢？相当部分是来自于我们上文提到的普什图瓦里。

普什图瓦里很重要的一条是妇女财产化，这一点比伊斯兰教对女性所有规范更可恶，因为伊斯兰教虽然在现代视角来看歧视和压迫女性，但伊斯兰教的希望是把女性变成清真的，符合教法规范的女性，只要在教法规范之下，符合古兰经和圣训的规定，那么女性可以成为学者、公共参与者和部分职业从事者。但普什图瓦里甚至部分否定了女性的基本资格，妇女不准受教育，不准参与公共事务，甚至妇女可供买卖 —— 这些都是普什图瓦里而非伊斯兰教法规定的，而前者的权重在塔利班那里不亚于甚至有时候大于伊斯兰教法。

甚至这么说 —— 如果真的只按伊斯兰教法，只按古兰经和圣训的字面意思去执行，那么塔利班治下女性地位可能还会有那么一些提高，至少阿訇们会让女性接受基本的伊斯兰通识教育和经学教育。

一篇西方论文报告巴基斯坦女性教育率低的时候（同样有很多的普什图人），做了一个调查，结果如下：


认为主要因素是贫穷、普什图瓦里、信仰、交通不便、物质资源匮乏、女性教师缺乏、课程内容不相关，以及腐败和缺乏意愿 —— 洋人就很明确两点，第一，普什图瓦里和信仰是两个玩意，得区分。第二，普什图瓦里比宗教更影响女性教育

我们引用同样报告里的采访：

“根据普什图瓦里（Pashtunwali），女性的生活以家庭为中心。她们有着预先定义的角色和责任：家务管理、食物准备和生育，这些都不支持她们接受教育。正如一位参与者（女性）所述，“普什图人的古老传统（普什图瓦里）迫使普什图人做这样的事情（限制她的学业）。他不让她外出。她被困在家里。这是普什图人根深蒂固的文化。” 如果男性被看到做女性的工作，他会受到家人和朋友的嘲笑。男性不应该在厨房工作、照顾孩子或在家做清洁工作。”
在山区，你知道，水必须从外面运来。取水是女性的工作。如果男性去做，他就会受到欺凌，并被冠以各种侮辱性的称呼。他们用一个特定的词来形容这样的男性：khazoonak（女性的傀儡）。所以人们会说‘哎呀，真是个 khazoonak’。所以女性负责取水、捡柴。女性收割庄稼。如果一个女孩去上学，然后回家做作业，那她就不能做这些事情了。
然而，人们一致认为，关于女孩教育的决策因地区而异，甚至因村庄而异。例如，普什图瓦里中限制女孩上学的规定在平原和定居地区并不像在山区和部落地区那样普遍。一些更严格的传统仅在毗邻阿富汗的偏远山区实行。
当然，下文也讨论了宗教的部分，讨论了宗教是如何影响女性受教育的

人们一致认为，宗教是塑造普什图人身份和社会结构的主要因素。一些参与者认为，特定的宗教解释通过戴面纱、严格遵守深闺制度、早婚以及女性在家中的明确核心责任等做法，间接地限制了女孩的教育。这一观点最有力的论据来自一位在迪尔、斯瓦特和莫曼德特区部落地区从事性别相关问题的非政府组织成员：“一些 [宗教领袖] 认为，如果你送女儿上学，你基本上就是在无视伊斯兰教的一个基本基础，那就是深闺制度。现在，这种极端的深闺制度限制给女孩的教育造成了障碍。”
深闺制度是什么，当我搜查维基的时候，维基是这么告诉我的


当然，伊朗和阿拉伯地区也有类似的制度，但往往是女性带有面纱或者罩袍即可，而病态到彻底把女性隔绝起来，也多少收到了 “南亚” 文化的影响……

而塔利班伊斯兰教的部分，也是很大程度上是吸收了起源于德里（也是南亚，印度）的迪奥班迪派思想 —— 一个兴起于 19 世纪，起源于印度，旨在团结南亚穆斯林对抗英属印度的分支教派（英国人：惊喜吧？这里还有我），而不是来自阿拉伯或者伊朗的其他伊斯兰教派，而迪奥班迪派也吸收了印度教和南亚对女性的糟粕传统

（这里额外谈一点，大家不要把伊斯兰教的习俗当做只要是伊斯兰教国家就一个样的，实际上还是免不了受到所处环境的影响，比如中亚的穆斯林就不可能深闺帷幕包起来；比如清真饮食，内陆的穆斯林会认可甲壳类海鲜也不清真不能吃，但你指望沿海的渔民穆斯林也跟你一样认可甲壳类都不能吃那就搞笑了，人家会自己释经宣布能吃；印度的穆斯林教甚至能产生了部分的种姓制度）

所以塔利班如此严厉的女性管控制度，自然也是伊斯兰教和普什图、南亚文化的结合。

你说伊斯兰教 “助纣为虐”，协助塔利班用宗教合法化的皮帮助这一行为神圣化，合理化，这是必然的。

你说伊斯兰教强制戴罩袍，童婚，一夫多妻，那伊斯兰教肯定要背锅，你自己规定的啊，穆圣。

但行使到塔利班这个地步，女性教育，女性出门，女性参与基本的活动都要禁止的，那穆圣和哈里发们也只能喊 “你有点太极端” 了，老子也没这么规定过，老子的实践也不是这样的啊 —— 女性不学习怎么称颂真主？

因此更大的问题在于这块复杂山区数千年部落民族传统的凝结，就算我们上演爱伊 TV，只把 “所谓的毒瘤宗教” 铲除了，而不触动这种普什图瓦里，那么阿富汗女性的苦难仍然可能广泛长期存在。

而普什图瓦里 + 伊斯兰教的双重组合，也注定了这片土地的女性的前途艰难。

毕竟如果真的只是伊斯兰教的极端派欠爱伊 tv 了，那你靠辩经，靠世俗派也能促进。

但如果是伊斯兰教 + 民族主义呢？你就算在宗教上完全证明了不让女性教育，不让女性出门等等是完全错误的。可又如何证明这个千年的部族民族传统习俗是不合理的呢？

而任何想办法帮助阿富汗女性的力量，也都应该认识到，他们的敌人有两个，其中一个是普什图瓦里，是部落传统乃至民族主义 —— 而伊斯兰教在一部分过于极端的议题上，甚至可能是部分的朋友。只看到伊斯兰教，看不到普什图瓦里力量的人，对阿富汗的评论只能说缺乏实际意义。

** [2024-10-10 Thu] 国学经典实在太多，如果只有时间读三本，您会推荐哪三本？

林先生
哲学话题下的优秀答主
235 人赞同了该回答
不用三本，一本足矣，这就是《史记》。

你所知道的诸子百家的思想，在《史记》中都有记载，你所想知道的所有人性，《史记》中都有记载。

如果你读爽文人性，认识人性的恶：

《李斯列传》、《范雎蔡泽列传》、《苏秦列传》、《淮阴侯列传》四个就是典范。

如果你想读人性中的善：

《刺客列传》、《魏公子列传》、《伯夷列传》就是典范

如果你想读人性的极端：

《伍子胥列传》就是首选

如果你想读大国兴衰：

《秦本纪》就描述了一个大国从弱小到崛起最终灭亡的故事

如果你想读致富：

《货殖列传》就告诉你市场经济和商人是怎么积累财富的。

你所试图在国学中得到的东西，《史记》一本就能告诉你。

** [2024-10-09 Wed] 发现

我们使用的那个平台，好像说是亲爱的学长的成果，但实际上呢？

一看作者是个土耳其的，怎么可能会是呢？

于是这里有一种什么问题？你到是不是 sincere 的？我想未必。

还有这里发的论文。有什么关系呢？和总体的这个什么东西有什么关系呢？

** [2024-10-08 Tue] 如何在百年大变局之中存活

一言以蔽之：要在下行周期里找个人生活的上行机会，近一百年来，这是头一回。

经济增速一定是下台阶的，这在官方经济智库已经是共识。唯一有分歧的是，下几个台阶，平台期有多长。

前几代人都没有这方面的经验。

很多生存逻辑是要重构的。比如，知识型人才和技能型人才的社会定价，肯定是要发生变化的，前者的均价会下降，后者会上升，但具体怎么变，变到什么程度，不知道。

再比如，现在多生娃肯定是负担很重的，但将来娃多的人可能反而可能会活得更省钱，这个投入产出的平衡点怎么拿捏，没有前辈经验可借鉴。

** [2024-10-08 Tue] 为什么报价那么低，中国的企业也不能中标

不知道这篇能存活多久。赶紧看吧。

说下为何报价低也无法中标吧。

我就是做国际工程的，在不同国家都工作过，目前在墨西哥做工程，很清楚保加利亚作为客户的担心。中方报价低于保加利亚客户预算的百分之四十多，就是说，客户预算是 100 块，他们期望的各家报价在 90-99 之间，而突然有一家报价 40，你作为客户，你是否懵逼？你敢相信么？你真的认为低价就能占到大便宜么？

保加利亚一定是吸取了之前一个中国公司在波兰的教训 — 也是最低价中标，但是干的过程中，说是当时漏项了少报了，要加钱！

这种不遵守契约的行为，在国内很多玩的很熟练了。

但是去国外还真不好用。

因为后来，波兰那个项目，客户就是怒了，废标，重新招！


而中国公司在海外，互相之间，为了夺标，也是靠这种打法。在非洲在东南亚，最后一轮投标，都是中国公司，因为价格超级低。比如客户预算 100，西方公司是 90，中国公司就能 50，而且，中国公司之间为了竞争，有的就能报到超级低价 30 或 20！我们当时就问那些超级低价的中国公司，你们这样玩，能赚钱么？他们骄傲滴说 “先进入这个市场，把你们挤出去就行！”

之前我在其他欧洲国家竞标一些设备，本来我们都是报价范围内的合理价格和条款，比如我把货运到客户指定地点，客户给我多少钱那种。

突然，就能杀出一个国内同行：我不要钱！我可以先把设备运到指定地点，你先用，用好了再给钱！

我擦，你贱啊！倒贴也要把其他人都撵出去呗！

所以一个市场，只要这种不要命的公司一去，整个市场全乱套了！

好了，但是商业世界，多少钱，就有多少钱的质量！

拼命低价的结果，就是：粗制滥造！

比如我们公司在拉美，要建设一个厂房，当地一个中国公司低价中标，结果就是，他们为了省钱，用最烂的料 —— 厕所门都关不上，因为插销采购的是最劣质的！以至于你蹲坑，一手拉着裤子，一手拉着门把手，因为你不拽着门，门就是开着的，任何人都能观赏到你蹲坑的姿势哈哈

然后要求他们整改，他们又买了一些插销，这才能把门关上！

这只是其中一个案例，其他的都不敢说！

这就是低价的代价！

低价的结果，就是造出的东西，都是质量超差，设计使用年限 15 年的，实际只能用 5 年就报废了！

而且，跟西方产品比起来，又丑又没档次！

中国制造在海外的声誉，就是被这些超级低价的公司玩坏的！

-

而实际上，中国是能造出又好用又美观的产品的！

为啥我说中国能造出优秀的好产品？

因为首先我买过啊！

当年我爱人怀孕的时候，我去美国出差，她给我开了一个单子，说要买一些备孕的和婴儿使用的产品，说美国那边的放心。于是，我去美国商店买了。

在美国商店，看到琳琅满目的商品，仔细一看，全是 “Made in China”!

我当时心里就是一句 “哇草！”

TMD，我大老远来美国，买中国货！

但是没办法，为了符合美国标准，中国这些产品就是比国内的好 -----

还有一次经历，是我卖过中国的好产品！

有一年我在一家公司，将一批工业设备卖到了欧洲，当欧洲客户打开货柜后，他们惊讶了，把我叫过去竖着大拇指跟我说 “没想到，你们可以将产品做的这么漂亮美观，超出我们的想像！对不起，我们之前一直以为中国制造是低端货 -----”

你们知道当时我多么为公司，自己的国家，而骄傲么！

还有更骄傲的：第二天，欧洲客户就给我一个订单，说第二批货也要我们公司的！

但是，噩梦这就来了！

当几个月后，第二批货到了后，一开箱 ----- 全是低端货！

是的，我毫不隐瞒，当时我所在的公司，为了省成本，把我耍了，发现第一批货卖滴好以后，还有第二批，就以为客户好耍，为了降低成本，以次充好，买的都是低端配件，攒成一个又丑又不实用的破烂给客户！

客户当场跟我发疯了：“你在干么？你这个骗子！我给你一个宝马的钱，却卖给我一个桑塔纳！”

我就这样被客户一顿猛喷，后来，根据合同，我必须赔偿。

我们公司呢，倒是根据要求，赔偿了。

但是从此后，也被客户踢出了供应商名单！

现在想起来，我都觉得恶心！

公司为了省成本，用破烂材料，事先瞒着我，都不告诉我，也不想想，这样结果就是把客户关系都毁掉了啊！为啥总想着短期利益，不考虑长远呢？

那次后，我也实在对那个公司太失望了，赶紧跑了，他们不要脸，我还要！

我在其他的回答中也说过，我们公司就有同事，被中东客户挖走，去给他们当采购，因为中东人也发现，中国公司以次充好特别严重，所以需要 “以华制华”，雇佣中国人当采购，对付中国供应商！

这已经是行业内不明说的事情了 ---

---

就是因为内卷太严重，导致中国公司进入到一种无序竞争中，主要目标是干死同行，什么代价都可以！

而低价的背后，还有对工人的压榨，比如免费加班和那句 “你不干有的是人干”。

还有很多中国公司，因为低价竞争，导致利润很薄，怎么办？

从员工身上扣啊！

反正 “你不干有的是人干”!

于是，中国公司就有很多省钱大招：

在非洲，曾经有中国公司让员工在有野兽出没的荒原上，住在帐篷里，这样可以省钱；
在中东，在疫情期间中国公司让感染的员工，两人一个房间隔离，为了省钱；
在南亚，疫情期间有的中国员工进了 ICU，公司第一反应是如何撇清责任，而不是去救助；
在拉美，有的中国员工本来要结婚了，没有去海外常驻的愿望，但是呢，公司就以出差的名义，让他 “短期” 出国，然后，就没收护照 ----- 这样不得已，只能留在那里工作了哈哈
也在拉美，有的公司，早上八点半上班，晚上九点多下班，员工工资低，补助少，所以，有的员工为了省钱，四个人一起合伙吃饭，一个星期，才花掉了人民币 600 元！都不知道他们吃了啥。
有的公司，低价中标后，用低劣的材料，导致各种问题，于是客户要罚款，甚至有的时候会延误工期，那么怎么办？反正劳动法就是形同虚设，没问题，直接从员工奖金里扣呗！说是干好了会有补偿，但是等你要的时候，就各种理由赖掉了 ----
如果你跟公司抱怨这些条件和各种克扣，大部分情况下，公司会先跟你讲奉献精神……

如果讲不明白，那句 “你不干有的是人干” 就是结束语………

不信你不服！

不服又能咋样？

以上这些公司，都不是国内的寂寂无名的皮包公司！

都是有头有脸的行业内响当当的大企业，有市值上亿的上市企业，也有大名鼎鼎的国企央企！

反正他们的理由都是利润薄，所有就牺牲掉员工利益就行。

中国公司过去几年，就是靠这些招数赢了一个又一个市场。

但是，只要所在的那些国家一开始反腐，你们猜谁第一批被抓？

秘鲁、厄瓜多尔等等这些地区，前一阵就是反腐败了，国内大名鼎鼎的中国公司，都是榜上有名，第一批被收拾的！

为何反腐？其实都是美国的阴谋！

对，美国阴谋解决一切！



在对待员工方面，在国内劳动法可有可无的情况下，的确可以这样干。但是，很多公司还是将这套做法拿到了国外！

比如在一些严格执行劳动法的国家，中国公司忽悠当地员工加班，说有加班工资。等人家要工资的时候，又跟人家说，给你调休吧！那么结果当然是，当地员工去告了！以至于很多中国公司在国外，一身官司！这也在市场上留下了 “不遵守法律”“产品品质低” 的恶劣影响和形象。

于是中国公司在海外的形象是：压榨、没法律观念、低价、低质量、靠贿赂夺标 ----

至于问题问的，会有啥影响，当然是很恶劣的影响。全世界都知道，中国产品便宜，但是，质量不行。尽管实际上不是那么回事。

只希望，以后还是用质量取胜吧，低价，甚至是白给那种，最终是害了自己，结果就是目前，在很多国家，中国制造就是与低价格烂质量划了等号！

…

关于低价中标，评论区也有同感的：




现在海外还有些企业，是将销售这块单独核算了，就是说，你只要签了单，业绩就完成了，其他的破事，甩给执行公司就行。

这种结果就是，前端销售那帮人是最好做的，能中标就行，其他一概不管。

结果就是隐患很多！

相当于签合同的是一帮人，执行工程的是另一帮人……

这也把中国公司形象抹黑的很严重……

这些中国企业在海外的低价竞争，也间接导致中国人在海外，去一个国家，那个国家就反华～～～比如墨西哥近年中国人开始增多，有些中国商人去了后，就是打价格战，比如十块钱的手机壳，中国商贩去了后，就能干到八块甚至更低…… 导致墨西哥商贩联合起来反华……

中国人在海外互相竞争，更导致中国人与中国人之间关系也及其紧张，也是互相提防，加上一些非法行径的影响，让中国人在海外最害怕的还是同胞……

** [2024-10-07 Mon] 一个 23 岁的中国留学生，在瑞士砍伤了三名儿童，他为什么要这么做？

大萌饼王毛文龙、硅谷 IT 胖子 等 2491 人赞同了该回答
我觉得这起治安事件，或者近期爆料颇多的海外治安事件是在逐渐曝光一个不为人所知的群体：边缘化的底层留学生。

与刻板印象里的留学生不同，在我个人经历里，认识过很多这样的留学生，他们画像无外乎是挣扎在温饱线上，才疏学浅整日或泡在图书馆里赶作业却成绩平平，当初在国内不明就里，依赖本地略微有竞争力的家庭条件开拓了一条赛道，选了一个不怎么好移民或者就业的天坑专业，然后满怀理想去海外非 top 学校读书，当初炙热的对海外生活的期望在高昂的生活成本，逆天的基础食物价格与性价比极低的住房条件中消磨殆尽。从小被福柯式监狱一样的应试教育圈养大，封闭且相对优越的家庭环境使得他们社会化过程缓慢而痛苦，在面对显然的阶级滑落时力不从心，年轻的，生为独生子女的他们不知 networking 与社会套磁的重要性，或舍不下体面，或被安排得习得性无助导致根本拓展不了圈子只能蹲在家里独来独往。总之生活过得压抑、愤怒而抑郁。他们有的自己孤身一人来到陌生的国家，家里没有资源，在本地没有任何可以帮助过渡生活的亲戚与社会联系，不怎么好的英语在生活上处处碰壁，而傲慢的本地人对他们实行冷漠且隔离的社交策略，无处不在的隐性种族主义与公开的社会化阉割使得群体中的性格内向、无依无靠、没有竞争力的社会资本与经济资本的男性成为了完美的交叉性歧视受害者，社会边缘群体。

我接触过有爱好极端金属的历史学专业的学生，平日里躲在满是蟑螂，房型老旧但是 900 刀一个月的老式公寓，除了完成作业外就是沉迷于过去的愧疚与创伤记忆的闪回，恶劣的精神状态得不到有效治疗，曾经对西方发达国家的文化憧憬被所学专业根本留不下的冰冷现实打得粉碎，于是在最压抑的一年里经历了外卖盒子堆积成山，日日憔心沥血，恐慌发作到夜夜无眠，病理化的抑郁反应在尿频尿急，过度频繁的排泄甚至都有致命的风险；更不要说在学校里时不时还被几个本地 teenager 开几个关于大陆关于红色中国的歧视性玩笑，笔几个关于小眼睛的手势...... 他的确也如此案件里的人一样，沉迷黄色幻想，怀念曾经错过的爱情，怀念中国遇见的对象，怀念被抹平的青春意气，虽然有报复的心理，但苦于性格柔弱，最后草草回家，没有发生更多不堪设想的事情。我还见过学习优越的女性社会学精英，博闻强识，与大众保持距离，热爱无非是读书与学习。拥有高功能自闭症，家住西南某二线城市，受不了本地冷漠而无趣的社交生活，已经毅然决然的将未来定在回国发展。曾专门花重金看长津湖、封神等电影，热泪盈眶；或是捧着一本红楼梦，在社交平台指点抄检大观园如何反应了美国当下的政治撕裂，如何说明了后现代女权主义的荒谬之处。政治上的偏激如同毒品一样，治愈缓和着每一个吃不饱吃不好，睡觉还要面对臭虫与蟑螂的日子。更有来自西北二三线城市，落魄到居住在廉价适应性的住房的光线严重不足的半地下室的学生，在每一个睁眼即处在黑暗中的日子里煎熬；一方面，要面对前途迷茫而惨淡的未来，一方面要面对长达半年的寒冬所带来的季节性抑郁。这样的学生群体还有很多，他们的贫穷与压抑不仅仅是经济上的，更多是社会性的，交叉性的，是法农笔下描绘的边缘族裔的现实代表。

我想，返回中国对于这种年轻留学生而言至少能看得见解脱，而不是在一个未置可否的未来耗尽钱财，耗尽家庭和睦，让道德与良心在等待身份的焦虑的日子里不断被侵蚀抹除要好。最后，我为受害者感到悲哀，但一切犯罪行为离不开社会构造，离不开个人经历的叠加，离不开交叉性的逼迫，长久以来，家境富裕，享受着无数离岸利益的权贵留学群体塑造着大众的刻板印象，固化了群体画像，而这些隐入尘埃里的底层留学生却苦于无所爆料，无所被人理解而挣扎在社会边缘。不在沉默中爆发，就在沉默中灭亡，而爆发的后果就是本案例所展现的真实，而这必然不会是最后一起，而是个人的苦难投射到外部社会所发生的必然。

[[https://www.zhihu.com/question/722362816/answer/4264254300][原连接]]

*** 评论

呵呵呵呵
别的都可以省，但是吃住上坚决不省本来生活就很辛苦，回来一看奇葩室友 + 棺材房子 + 猪食一样的饭，立刻就不想活了
367

 牟某人 量产型 momo
 人是社会性的动物。缺乏社交或者糟糕的人际关系，对于现代人的影响远大于住宿。

 量产型 momo
 比国内大学住宿条件强就行


析分函泛
每个系的博士，都有那么几个精神有点问题的跟您描述差不多。

 anthonyll
 博士生还好点，多数来自科研和导师的压力。

 生吃柠檬
 天下博士一个样特别是洋博

sheng yan
确实，这种留学生被有意无意的忽略了，精神上的重压会引发行为问题

 知乎用户 AZ1974
 不仅是忽略，而且经常在网络上 “被代表”（被困在网络对于各种二代留子们的刻板印象中，开 party 享福时没有他们，遇到点不好的事全给连坐了）

 孟德尔如是说 → 知乎用户 AZ1974
 太对了，别的倒还好，被代表是真的难受

嘻嘻哈哈
出国留学的不一定都是有钱人。这边很多留子连学校 15 刀一顿的饭都舍不得吃

 Archernar
 哥，把摄像头关了吧，我有个朋友汗流浃背了

 李欣宜
 15 刀一顿的饭确实贵啊，除非赶 ddl 和社交需求，尽量把每日餐标控制在 10 刀以下。
 查看全部 26 条回复

李欣宜
我是真有重度抑郁症和重度焦虑症的诊断书，经济问题也都是自己解决的，现在也是每天吃完药再上班，但最难的时候也只是 suicide plan，没想过图图别人，更别说抽刀向更弱者。呼吁关注心理问题和社会矛盾这个建议支持，但其实多次开图的人并不是什么底层，评论区提到的卢刚更是一路顺风顺水，北京土著没缺过钱，绝笔书提到交往过很多女友早腻了，做不出预期成果实验室也从不吝啬工资，反而受害者山林华的经历才是模板化的小镇老实做题家。
昨天 09:29 · 美国

 慕容龙城
 可以试试 张至顺道长的金刚长寿功，张道爷说过抑郁就是身弱了，把经络通了，气血旺起来那些都会改善，道家最实际就是当作健康问题去处理，就是需要你坚持，三个月左右才会有比较明显的效果。心情不好的时候若不排斥可以试试 六字真言 莲师心咒 准提咒，坚持也会有所获，祝康复 学业有成。
 Note: 评价为：神经


 日行一喷 → 慕容龙城
 我就知道，知乎的路在戒色吧

Ursus maritimus
现在哪个发达国家没有些移民？东欧人，拉美人，东南亚人有没有活得那么别扭？
有没有可能，在 “硬追求融入本地族群” 和 “封闭在出国之前的世界里” 之外还有第三个选项，去和其他的外来移民群体来往？
我悟出的经验就是，多去一些国籍和族群组成丰富的圈子里会很开心，也交了一些东南亚朋友。

 李欣宜
 就算只混华人族群我觉得也没什么，事实上湾区很多人真这样，只吃中餐，只看中文节目，只刷中文 SNS，只和老中同事来往，甚至直接就在 tiktok 这种上班直接能中文开会的公司。「老乡坑老乡」这个说法是有 bias 的，因为刚到不熟悉的地区接触最多的只会是老乡，样本多了坑货当然多，但接受到的来自于华人的帮助也多，华人恰好属于优点和缺点都比较鲜明的族群。我虽然鼓励别人多走出去和其他文化下成长的人打交道，互相启发学习，但如果就是觉得很痛苦也没必要强行去融入他们的文化。同族群移民社区抱团，比如很多拉美裔社区的孩子连英文都不会只会西班牙语，没人觉得有什么奇怪的，反而都挺尊重他们的社区和族群文化的。

 此时此刻
 不要对中国人要求太高。东欧人、拉美人、东南亚人照样有压力大的，有犯罪分子。人一上百，形形色色。


Tina-L
贫穷、孤独、学业压力、生活不便、种族歧视…… 留学生很容易出现情绪问题。

 fuzzy
 主要还是国内人日本人太内向挑剔，接触的韩国（内部报团儿）台湾（表面热情的双面人）这俩群体在北美过的都比较舒服（融入？），也不怎么跟当地人来往，他们都爱找亚洲人混


今天风好大
他们只是尝到了国内底层人的滋味的罢了

 K769
 国内底层人不远行起码言语没问题，周围亲朋好友熟悉，国外这种真就一个人了

 PiccolaStella → K769
 贷款出国留学不评价 但是都出国了 在国内语言不好也不说了 我朋友里还有在美国待两年英语都不利索的 我真无法理解 这种学习能力和适应能力为啥要出国去受洋罪

爱吃番茄滴香菜
我还是觉得把报复社会的对象设定为孩童，还是太出生了

 阿敏
 瑞士今年初，发生一起：一个难民冲进一家幼儿园，威胁小朋友的事件。我想，可能是这个留学生受到启发，也这么做了。


falcon
首先我不是说凶手就是性格内向，没钱，才做这种事，如此行凶是没任何借口可以去弥补的，性格内向，家境相对一般的人里大多是也是善良的。但是还是借这回答稍微延伸一下。

不是说没钱成绩差的才会这样，性格比较内向，不算特别帅气，生活方式兴趣爱好比较东亚大城市的，去欧美以后孤独的大有人在。

uzh（苏黎世大学）也不算差学校了，只是这两年 qs 掉下去了，前几年都是七十几名。这个凶手读的计算机语言学在 uzh 也算好专业了，uzh 的经济学，金融学也很强，经济学博士竞争都是百里挑一的，只是欧陆学校除了 eth，epfl，其他学校硕士基本都是过线就录取，但是课难给分低不好毕业。这种学校反而会给人更大的压力，因为难度高，正反馈低，瑞士又不如英联邦，北美多元，娱乐也更少，中国人也少。

学习成绩好也最多说能在科研，找实习找工作上获得些成就感，有些盼头。但是和社交，恋爱上的成功也没多少直接关系。除非你厉害到顶层，比如美国名校 cs phd，各种会议的常客，能在知乎上被人叫一声大佬那种。家境上除非有钱到在国外直接买房，买跑车，奢侈品闭着眼睛买那种，否则比如在加州，一年加上学费花个小一百万，住的好点，吃的奢侈点，时不时买点潮牌，时不时出去旅游几趟那种小富，也不一定能弥补不了性格内向的劣势的。反正不存在躺着就有人来倒贴的。性格内向不是错，问题是在海外本来选择就少，欧美也没什么人会欣赏低调的人（国内就有）。特别是谈恋爱更是如此。不是说性格内向在海外一定找不到对象，但是孤独的概率会大于国内。我认识很多人都是同样的性格在国内还有人喜欢，出来就不行了。这个没什么好争的。

networking 也是需要资本的，你得英语很好或者对当地文化很了解，或者真的非常外向，或者你有资源，才好点。要不然 networking 也许能帮你认识两个浮于表面的外国朋友，能帮你找科研找工作，但毕竟不是深层沟通。我有朋友本科一直都是和外国人住一个宿舍的，但是最后毕业了也没有很深的联系了。

总之一直以来，都有部分人很适应欧美社会，或者有的人无所谓社交，精神需求，本来就宅，钱赚的多，科研做的好就很开心了。所以我只是想说，普通人出去留学，如果感觉不习惯，回国是非常正常的，真的太孤独忍一忍呗，毕业了有谁不让你回去了吗？真心不要受过去网上一些误导，什么回国肯定后悔，普通人肯定在国外更好，精神都要崩溃了还不给自己个盼头，那状态必然越来越差。或者说不喜欢村里生活，不喜欢奔放性格社会的，就别老惦记着欧美，尤其是美国了，还不如去香港，日本之类。

燃烛照痴花
作者
你说得对，其实绝大多数不适合当地文化的留学生都是被回国等于失败者这个致命的思想钢印禁锢住了，这导致了在一条错误的道路上越陷越深，精神状态越发恶劣。

LIUShirley → 燃烛照痴花
也有些人是有心想回国的，甚或者一开始就没想过留下，只是想着自己在国内学得比较一般，出国换个赛道再回来找工作的话，是不是讨生活能稍微容易一点。
尤其是实在想学或不得已学了一些冷门专业的人。
恰恰是对于这种人来说，回国就意味着一切重来，不止是面子问题，更是非常现实的成本问题。
举个比较极端的例子。
一个中学阶段就出国的学生，大学幸运（同时也是头铁）挤进梦校，通过成为微波炉战神来饲养自己，勉强跟着卷了两三年。
天天吃不好睡不好跟唯一的朋友互相监测对方是不是还活着，瘦得并住膝盖大腿肉不挨着，精神状态终于到了崩溃的边缘 ——
此时他其实并没有一个回国的可选项，因为回国后他甚至没有一个高中文凭，想读大学只能参加高考，而此时他很可能已经 20 多岁了。
如果他能说服家人 “再这样下去就真的死了”，那可能唯一比较现实的方案就是放弃梦校转学水校，好歹拿个文凭，以日后挨更多社会毒打为代价换取眼下活命。

咖啡猫
还外卖盒子堆积如山，配送费根本不是穷学生负担得起的

 燃烛照痴花
 作者
 实际上 20 刀一顿的外卖，倘若是 Uber 会员配送费甚至是豁免的，别的平台也有各种补贴。

 咖啡猫 → 燃烛照痴花
 我原来在 UK 点外卖，3 英镑配送费，送到还凉了。好在食品工业发达，我基本都自己买半成品

听涛
你接触的那个人是怎么做到住差公寓还有钱点外卖的？不了解文科生，说说理工科博士，我接触的几个都是读博压力太大有点神经质，和💰倒没啥关系，住个 house 或者 4B4B 每个月导师给 2500+🔪也够活


 Jackie 程
 地位不一样，理科博士和文科不能比的，文科上下限差别极大。理科你能博士就已经很不一样了，自己具备生产资料了，但文科的能干啥？不过理科这话生产资料也有高低，有的就业前景很有限

 falcon
 有的就是住么尽量找便宜点的，也不讲究，吃这块没心情和精力做饭了，就点外卖了，到不完全是钱的问题。当然也有人就是一直吃超市冷冻菜

风一般的自由
谁叫洋人不发三个异性学伴？

 道哥
 其实许多男性对洋女排斥。

 金硕珍的老公
 很多国男干不了白女 因为白女五官太立体 进攻性很强 很多男的 hold 不住

柯南鸭
郁达夫你好

哥谭噩梦孙笑川
不是哥们，这个你真得删，我没事，但是我有个哥们你知道吧，我跟他情同手足，我怕他不小心看到破防了，我当然没事啊，哈哈哈哈，这期删了呗，这跟我朋友的经历有点相似，不过我是无所谓的，没什么感觉，我不轻易破防的，但是我一个朋友可能有点汗流浃背了，他不太舒服想睡了，当然不是我哈，我一直都是行的，以一个旁观者的心态看吧，也不至于破防吧，就是想照顾下我朋友的感受，他有点破防了，还是建议删了吧，当然删不删随你，因为我是没感觉的，就是为朋友感到不平罢了首先我没破防，就是我有个朋友是这样的，他就和你说的一样，但他不是那样的，我觉得你这样真的没意思，你就算发了他们也不会破防，因为我朋友是这样的所以我知道，我劝你最好删了，因为我朋友就算看了也不会破防，所以你这句话留着也没啥用，还不如删了，然后就是我没破防，只是我朋友是那样的，我提替我朋友说话，我没破防，我就是提醒一下你，记得把这句话删了，我可没破防，我替我朋友求求你了，删了吧哥，呜呜呜
昨天 08:50 · 日本

 奇奇怪怪
 日本留学生不都挺滋润的嘛

 AAAA
 日本真的还好吧。。。。至少长得都一样啊，经济吃紧的话，打零工的机会也很多啊，毕业后工作机会又多。

螺丝钉
资质一般的中产放着国内按部就班的日子不过四处乱润，就是自寻绝路

黄浦江之猫
说得很中肯，很多留子也就是普通中产甚至工薪家庭，父母省吃俭用供着。英美的可能富裕点，欧陆学费其实没那么贵。而且这人应该也不算学习特别顶尖的，真大佬在他对面那所
昨天 09:48 · 美国

ping qing
自晚清以来，除清政府之外的所有政治势力，都开动全部的宣传机器，给全体中国人描绘着一个美好灿烂无比幸福完美的地上天国 —— 外国。

深蓝秘境
真是本国混不下去，出国更难。
中国人就不像印度人一样，骗到是荣耀，团结耍赖是国家特色。

 你不够忠诚
 国内这方面比起印度人来说可不遑多让哦

奥巧棒儿
“性格内向” 又和这些负面品行捆绑在一起了？为什么你觉得是他性格内向，而不是社会化训练不完善呢？性格内向的人也可以很好的和别人交际，完成必要的社会来往，当然这也许是他所不喜欢的。但是不代表一有什么杀人犯、凶手就是性格内向的人吧。太片面了。
昨天 06:54 · 安徽

 EVEBABYCHAO
 可是社会化训练  大部分人都是靠着自己完成的啊…
 昨天 08:14 · 中国台湾

陈一阳
说的很对。除了民间的隐形歧视外，还有移民局的政策性歧视，某些道德不佳的导师的冷漠和打击，甚至父母在出国探望的时候还会给因为不熟悉西方法律在不小心中给子女制造麻烦。如果运气不好的话会掉进非常大的坑，只能依靠自己的强大意志去挣脱出来。远离堕落，哪怕有一百个理由，也不要沉沦。
昨天 07:59 · 加拿大

猫猫虫
虽然但是，就算是经济过得去的留子，乃至已经工作的，也不会 “外卖盒堆积如山” 吧，外卖贵到要死，加上税和配送费一餐 $30 + 也不出奇
昨天 13:26 · 美国

 燃烛照痴花
 作者
 看地区，我所生活的是加拿大边远城市，物价稍微好一点。
 23 小时前 · 加拿大

鸣海
别说欧美留学的了，就算是我们这种来第三世界国家创业的中国人，也分好多类型，有的还可以融入当地发展起来。有的就是出来了，把投资款在这边耗完就灰溜溜回国的，更有甚者，在这边专门坑老乡或者干边缘行业，它们名声太差乃至于当地人听到它们名字都要抖三抖
16 小时前 · 津巴布韦

---
忘言
住的有国内学生差吗？吃的可能是吃不惯，住就别和国内八人间碰瓷了。看到给这种留学生卖惨着实共情不了哈，毕竟我宿舍真有蟑螂
20 小时前 · 山西

橘子屋
国内八人间上海一年费用 1200 人民币你是半个字不提啊，题主说了 “性价比极低”，租房的昂贵价格在环境之外还会产生沉重的额外焦虑…… 不用出国留学，你来上海脱离宿舍租个单间住住就知道了，真比宿舍还闷疯了
14 小时前 · 上海

tracytang
哪没有蟑螂………………
6 小时前 · 广东

---
岐山臊子面

本就是边缘人，短暂的 “知识改变命运” 的春天让高学历低社会功能人群有了自己是中产的错觉。
这些年随着世界秩序的变化，真相要彻底露出来了，海市蜃楼已经消失，新秩序即将来临。
昨天 13:08 · 北京


亚心
所谓的高社会功能人群不过是沉迷于奶头乐、娱乐八卦、消费主义，以及婚孩房车这种传统大坑路径的庸俗人群罢了
20 小时前 · 加拿大

---
金晓明

想到了爱荷华卢刚案
昨天 02:08 · 浙江

探险精灵
卢刚太轴，当时偏要留在美国。当初读完回国，中科院也亏待不了他，同时还和美国保持联系，过 20 年让孩子再留学和就业，等差不多了再带他润。

EVEBABYCHAO
可是我觉得他自己有很严重的问题  他除了做学问以外 在心态 / 待人接物 / 外形等方面完全没有一点点理解和融入的意愿 也许在学术上很优秀 但是在不熟悉的人看起来 这就是一个不修边幅 / 谈吐欠佳 / 气质怪异的边缘人 是个外国来的怪胎呀  再加上又有一个敬业乐群 各方面都堪称对照组的同学山林华 他完完全全被人比下去了 但是单纯愤恨地认为对方是 “溜须拍马的小人” 系上的教职员 “联合起来整他” 从来没有 1 分钟检讨过自己 在犯罪方面倒是非常融入当地 来了个 random shooting  我觉得发生在他身上的事 和运气有点关系 但他自己也有很大的责任 他这样的性格 留在国内也未必能发展得好
昨天 08:12 · 中国台湾

---
供蛋供匪
国家对外国人友好政策甚至跪舔是一种长期投入，不一定有回报消除白皮对黄种人的歧视，只能保证部分来过中国或了解中国的人对中国人不歧视，世界都是底层最多，中国亲外，而外国排中，受害的只有被排斥国的底层民众。
18 小时前 · 湖南
** [2024-10-06 Sun] 为什么我感觉哲学中相当一部分内容像是脱产者的无病呻吟？

罗心澄
罗心澄
数学等 3 个话题下的优秀答主
刘镇锐 等 130 人赞同了该回答
IMHO，“无病呻吟” 这个词本身就很 “有病”。它自带的嫌弃色彩，外加对于 “刮骨疗伤” 这种故事的推崇，实际上构成了一种 “任何情况下都应该忍痛不说” 的文化底色。

在这种大的教育背景下，最终的结果就是一群现在不可期的父母养育出来了一群未来不可期的子女：

为什么女儿忍痛不向我们说？
9227 关注・3781 回答问题
实际上，在我们整个文化底色下这样的语言使用有很多：“你这算啥？你才到哪儿呢？”“就这点困难克服一下不就行了吗？”“别人都没事你怎么就有事了？”“我们当年吃过的屎比你吃过的饭还多”……



而考虑到 “呻吟” 这个词的含义，你会发现 “无病呻吟” 还有一种不让叫床的美。怎么？人家爽到叫两声是招你惹你了？



当然，这里更加核心的问题是，“病” 和 “痛” 是两个不同的概念：

假设你大脚趾踢到桌脚了，你疼吗？疼。叫吗？叫。你有病吗？你没病。那这算不算无病呻吟？

另一方面，为什么很多癌症都是晚期？因为早期根本不痛啊。你等到肿瘤大到压迫周围神经，让你疼得叫出声再去医院，那可不就是癌症晚期。

所以说，非要把 “病” 和 “痛” 捆绑在一起，硬生生造一个 “无病呻吟” 这样的词。我只能说，真他娘的有病。想都不用想，一定不是医生造的词，而是文人造的词。

既然整个问题和 “无病呻吟” 没关系，我觉得题主还真不如大大方方地问：

为什么我感觉哲学中相当一部分内容像是脱产者的狗叫？
—— 你但凡这样问了，我还敬你三分。

但我还是那两句话：

你感觉什么都行，我没有必要为 “你感觉” 负责。任何属于你的思想都可以被冠以 “我认为……” 的方式陈述出来。
你有本事把 它们 骂到不搞 A4 雕花艺术，否则本质上就是柿子捡软的捏：

 回答：哲学理论如何避免陷入文字游戏的陷阱？
 127 赞同・0 评论回答

表面上，创造出了大量 狗叫 的工作是管理、销售之类东西。当然，也有一些客户（甲方），比如说，他们就要求病能治好，就要求数据能恢复，就要求车能修好 —— 并且还非得在一定成本限度内。

但是，仔细一想，我们会发现，“狗叫” 的评价是相互的。你作为药物研发者，可能会觉得觉得负责销售的人过度强调的那些玩意儿是不说人话，看到推销和客户相互交流，你会产生一种很微妙的感觉。

而患者呢？患者真的在乎药物的作用机制吗？真的在乎临床试验报告吗？他们在乎的内容本就不是这些专业性的内容。你看，知乎上不就有人问这个吗：“为什么现在的药品名都不直接写明治什么病，而是用一堆奇怪的音译名？”—— 消费者 和 研发者 并不共享一个概念池。消费者不关心你这个东西怎么来的，具体如何作用的，他们甚至不一定关心具体的成分、物料是什么，他们只关心体验，什么时候吃，吃几个疗程，效果如何。你不把 “体验” 标注出来，那对于消费者来说就是狗叫。这里当然不仅限于药物。实际上治疗的很多 fancy 的玩意儿，不管是 “靶向药物” “γ 刀” 还是啥的，对于大多数患者来说都是 fashionable nonsense 一样的狗叫。只不过，消费端单纯以一种信仰宗教的方式将这些对于他们本人而言是 fashionable nonsense 的玩意儿奉为圭臬全盘接受罢了。

类似地，游戏策划真的玩游戏吗？调香师真的用自己的香水吗？在生产链条很短的时候，比如说，我在自己家做菜的时候，我当然可以一边尝味道一边调整。类似地，调酒师可以自己尝自己调出来的酒。

但是如果我是一个预制菜生产环节中的一员呢？我将全程戴着口罩头套，可能这辈子都不会吃到我生产出来的食品。那么这种情况下，生产者对于产品有什么额外的评价资格呢？我甚至不一定知道用的奶油是动物奶油还是植物奶油，上面写的英文，我看不懂。我可能知道制作的环境还算干净卫生，但是我必然知道产品什么味道吗？不是这一款产品，而是每一款产品。—— 企业里面肯定有个别部门的人知道每款产品是什么味道，但是每个工人都知道吗？如果他们连自己生产了什么都不知道，那作为这些产品的生产者这个身份本身又有什么意义呢？你和我说 “你们家的蛋糕太咸了”，“但是我只负责抹奶油，不知道咸味是在哪一步调节的”—— 当然也未必不知道，但是可能根本和我没有关系，就算我和工友说了，和研发反馈了，那又怎么样呢？负责放盐的工友不可能我一句话就把机器参数调整了，而市场部的人会说这个咸度我们做过调研，是销量最好的，个别汇报没有商业价值。于是在双方眼中，对方都是在狗叫。

这也就是所谓的 “脱产者” 这个概念滑稽的地方。实际上绝大多数事物的评价上，你是不是 产品方 和你是否有资格讨论和评价一整个的产品没有关系。你可能就是一个销售，就是一个客服，就负责一块电路板的设计。你回答不了为什么这个地方有毛刺，那个地方手感不好，你甚至不知道所谓的 “手感” 指什么，一方面当然可能单纯是因为 “手感” 是一个非常抽象的词汇，但是另一方面可能是因为你不用你们家生产出来的产品。或者，你用了，但是不在具体使用环境中用，而仅仅是在测试环境中用。



更进一步，这是一种危险的倾向：仿佛 你 作为 被管理者，就 没有资格 对 管理者 提意见，因为他们 从事的工作 就是 管理，所以 他们 必然是 专业的。因为 你 只是 被管理，所以 你提管理上的建议 必然是 不专业的。—— 大面上没错，但是真的吗？或者说，当它们在执行所谓的管理的时候，管理、行政 真的能和 业务、事务 的部分一刀两断吗？

过于强调这种 “不在其位不谋其政” 某种意义上是一种切分，最终一个综合性的决策因为不是任何一个专业技术人员可以定的，反而让管理者摘了桃子。在管理者看来，这群臭搞技术的懂个锤子治理的艺术。至于会发生什么，那就去相信后入的智慧吧。

** [2024-10-06 Sun] 为什么我们总有人觉得中国比不过外国，而且在领导岗位上的人尤其有这种感觉？
真知棒
真知棒
闹麻了
Deep Van、硅谷 IT 胖子 等 271 人赞同了该回答
因为领导见的比你多。

省市级别的领导很容易就能找到我这样水准的去和他们聊我的专业领域，而在同样的领域你只能看抖音百家号知乎带 V。

这种领域见多了之后，自然而然就会有这种感觉。

不要去质疑领导的思考回路怎么来的，执行就完了，这不是你应该操心的事。

众生皆有优劣次第。你赢完了眼一闭一睁接着打螺丝送外卖就可以了，领导在领导岗位上需要思考的就多了。

** [2024-10-06 Sun] 美军退伍以后是沦为流浪汉，还是直接送进监狱？
真知棒 等 132 人赞同了该回答
题主，我好心建议，这类话题慎重提出。

如果你把大家挑唆的纷纷站出来，详细述说并对比两国的退伍老兵待遇。。。那么你提出这种问题的行为，妥妥的属于寻衅滋事，很可能会被认定为间谍。

而且我要说，今天中国的普通退伍士兵，不管是义务兵还是志愿兵，其退伍待遇都还算是不错的。别看经常有大批老兵维泉的新闻，但那些基本都是十年或几十年前的退伍兵。

而且我也很理解做决定的人，在现在这种氛围环境下，拼命把军人的待遇提高，甭管现役还是退伍，都绝对有利于自己安全。我说的是美国。

美国人太惨了，退伍老兵待遇特别差，只能沦为流浪汉，美国人民真是凄惨无比，打倒美帝国主义。。。。

** [2024-10-06 Sun] 如何评价上海松江沃尔玛男子无差别杀人事件？

刘镇锐 等 222 人赞同了该回答
这个回答很多人会觉得反感，但这就是血淋淋的现实。

2013 年，我正值高考，我在的这个城市发生了一起爆炸案，一个中年男性因更新身份证未果，导致社保领不到，去相关部门办理被踢皮球，最后选择汽油点燃公交。

首先，他加害无辜之人，不符合正常人的三观，不符合社会价值观，但是经过这件事后，当地的行政服务水准，不吹牛逼，向前推进 20 年。

爆炸案前，这些行政服务人员，吊的半死，拽的二五八万，比省部级架子还大，一问三不知，问多了还要屌你。

爆炸案后，上层施压，所有车站增设安保人员，安检装置，紧接着，对基层胥吏进行整顿，服务态度简直一百八十度大转弯，有问必答，耐心十足。

你猜怎么样？就这样一个杀害无辜的人，民间坊间谈论起来，还会为他的死唏嘘，说他为厦门的发展做出了贡献。

讽刺不？意外不？三观毁灭了没？

最后还是悼念一下车上的死者，当时车上还有一中、双十的学生，985211 稳的，这些孩子未来一定是璀璨的，可惜了，所以我们生存在同一个社会，一定要对身边的苦难感同身受，对生活绝望的人越多，我们普通老百姓就越危险。

** [2024-09-30 Mon] 江苏南通一年轻女村干部被一低保户杀害，当地「正在调查」，干部在任职时应注意哪些问题？此事带来哪些警示？
1852 人赞同了该回答
这个五十多岁的犯罪者（已自杀，无法经审判成为罪犯了），是知道杀人该偿命的，他也确实自杀了。

这说明一个问题：

在失去了低保的情况下，他已经认为自己没有生活来源，根本无法在这个社会维持生存了。

所以他在临死之前才会去找个 “垫背” 的。

至于他为什么找到并非直接责任人的年轻女驻村干部？那很显然：这是一种 “集体主义” 的思维。他针对的是组织，杀死组织内的哪个成员并不重要。

理论上说，“有劳动能力随便找个活一个月就能挣两千”，“捡废品一个月都能挣一千”，但实际生活中，找工作跑几天没人要，或者跑两天街道发现人们舍不得扔纸箱无纸可捡，承受能力弱的人就绝望了。否则无法解释有人年薪几十万有房，还会因为被裁员而自杀。

按法律这肯定不对，但他都已经决定要去死了，最高的死刑也没办法威慑他不犯罪。就算恢复满清十大酷刑，也只会促使凶手们自杀时再狠些确保成功。至于恢复株连制度？这个人没家人孤身一人。

如果他确实有两万元存款，那么就说明，这点存款并不足以让他产生 “可以正常生活” 的安全感。

至于被害人是因为值班而被别人拖累，确实冤，给人的警示就是：

别加班了，别人走你也就走。尤其是不能孤身一人上班。
享受集体的好处，就也要承担集体的风险。要注意你所在的集体是否有风险。
这事还反映出另外一个问题：财产的判定标准差异过大。

比如一个上海人住在自家 50 平方米老旧但学区不错的老公房（福利分房时代得到），房价值四百万元，他只要没工作，没汽车，没存款，他就可以成功申请低保，一个月至少拿到大约 1500 元钱。

价值四百万元的房并不会被视为大额财产，而是他的生活必需品。

而另一个地方的低保户因为工作攒下了四万元就会被视为不再贫困，低保被取消。

严格按照 “没资产才该领低保” 的标准，上海有关部门完全可以要求这类低保户卖房，给他安排公租房居住。等卖房款消耗到存款限额之下，才给低保。但现实中上海方面并没有这样做。

** [2024-09-28 Sat] 软B开题报告

*** 修改建议

- 文章结构：无需进行变动，保持模板上的«国内外研究现状»和«主要研究内容»和«研究方案»
- 建议加入对前人的贡献的总结
- 在主要研究内容和研究方案之中加入更多实在的内容
- 参考文献可以加入学长的毕业论文，其次需要更多最新的论文，至少是20年代的

** [2024-09-27 Fri] 如何评价 B 站刘宇在石家庄打击隐藏摄像头后在派出所里被围堵的视频？
8902 人赞同了该回答
看了视频，很有感触。

事情脉络相对清晰。石家庄有一些民宿酒店里有偷拍摄像头。UP 与朋友组队去探测和打击这些偷拍摄像头。某民宿老板在上次被查出有偷拍摄像头后，威胁恐吓要求 UP 的朋友签署了不曝光协议，并自查处置这些摄像头。

但 2 个月后 UP 团队再次到来发现偷拍摄像头依旧存在。于是 UP 团队搜集了证据并报警，再次与这个民宿老板产生言语冲突。期间负责处理此事的有个 " 周警官 "，提及下次遇到这事可以先通知他，方便警察的工作。

随后 UP 团队再次去另一个酒店搜索到了偷拍摄像头的迹象，按周警官要求先给他打了电话。周警官在确认没有开直播后，没有出警，却通知其他流氓地痞到达现场对 UP 团队进行攻击和殴打，后来的画面可见有出血。这些人还一度把 UP 团队拉到没有监控的区域进行推搡殴打。

在 UP 团队多次报警后，警察才出现，把 UP 团队带去派出所。但记录完口供后，派出所门外二三十人堵着派出所的门要殴打 UP 团队。期间警察对此事漠不关心，UP 团队只能躲回派出所。并在晚间趁外面围堵的人群不注意，迅速开车离开，此时 4 个车胎有 2 个已经被扎破，用轮毂着地一路逃走的。

这个事件中有几个重要的参与方，民宿老板及其黑社会性质团队，周警官为首的保护伞。民宿老板主动安装偷拍摄像头，找地痞流氓殴打 UP 团队围堵派出所。而周警官则在事件中为民宿老板团伙提供通风报信，回避和延迟出警，默许围堵派出所。

在打黑除恶这么多年后，还能搞出这么一套保护伞的行为。评论区和弹幕也可见，当执法司法失去公正时，人们是多么的失望。

我曾经在河北生活和学习过，我理解河北很多朋友对义气的看重。但这种义气的前提应该是社会公理。在古代依靠义气聚集起来的人们对抗社会不公时，那么这些人就是人人崇拜的英雄。但一个团体依靠义气聚集却是营造社会不公时，就是人人唾弃的罪犯。

我希望能后续能看到对周警官保护伞行为的处理，看到对民宿老板团伙的违法行为处理。而如果河北不能把这些行为严肃处理，继续掩盖和相护。那么相信很多人也会像我一样，不能相信河北的安全和公正，无论是做什么事情，都会避开这里。

过去几年国内有几个城市陆续成为网红旅游城市。这些城市的旅游资源并不突出，但经过严格的治理，让游客知道来这里旅游不会被骗，不会被威胁。那么简单的烧烤也可以吸引来泼天的流量。反之，很多传统旅游城市，在坑害游客上轻车熟路，并与政府和警察系统协作护短。几次严重的與情事件得不到公正的处理就会让人们为了规避风险而不再来这些所谓的旅游城市。希望此次事件河北能给大家一个令人信服，令人放心的处理结果。

最后给 UP 个建议，每次执行此类任务前，可以从其他城市雇佣保安团队随行。以后也别相信一些警察护短的鬼话，全程开直播，既然缺乏治理能力，谁也别想体面。

** [2024-09-26 Thu] 为什么受众明显是喜欢老婆的宅男的二游中，却难以找出一个不两头恰的游戏呢？

月夜梦行貘
你也用愤怒扭曲你的判断吗？
144 人赞同了该回答

看了那么多回答，我突然意识到 ML 仙人的产生，其实很大程度是国内男性向二创太过贫瘠导致的。大部分二游的角色塑造只能说除了标签毫无特色，以至于如果没有二创的填充，其人物形象无限接近与纸片，这也为什么一个角色能够轻易被带起节奏。因为 “她” 不是一个立体的人物形象，只是某种具有外形的符号而已。

在这种情况下，那角色的“塑造权”几乎就是被官方或节奏决定的。因为在这个关系里，玩家 - 官方，几乎成为了一种施舍与被施舍的关系。而受限于二游本身的体裁，很难深入地塑造所有角色，于是中间的空白（这包括更新中间的空白）成了一种无人填补的区域。

在一般的文化社区中，这种空白是由同人填补的，哪怕再单薄的形象在二创中都有自己的生命力。虽然不同取向的群体会有不同的滤镜，但角色本身不至于贫瘠。

如果社区毫无二创产出能力，那人们的目光只能聚焦于游戏本体，任何细节都会被放大 —— 包括剧情、数值，等等等等，社区内的情绪主要以对抗为主。而娱乐组成越单一的人（或者说越是深度玩家），越可能停留在社区里，从而像养蛊一样越来越魔怔（）

换句话说，如果一个社区的二创能力与其活跃程度成反比，那么其魔怔程度就会指数级飙升，成为一个大型 PVP 现场

我们一般将其称之为饭圈。。

为什么二创本身会延缓官方焦虑，很大程度上是因为看到一个故事之后，诞生了「想要创作」的想法，这个时候这个角色她在主观世界上「活过来」同时「死去了」。

一方面，她有了真正属于自己的性格，自己的人生。另外一方面，通过创作这种方式人们意识到「在游戏中的那个她不是不可亵渎的」，从此从施 - 受这个关系中一定程度上独立出来，于是所谓官方的神圣性也自然消解了

当然，男性向社区还有另外一个问题是人们似乎只想冲爆，以至于就算是二创也只有 hs 方面的内容 —— 更糟糕的是，人们似乎找不到（）

摩砂学
观点其实是相当受限的，简中其实还没能以冷静的态度看待同人以及这个圈子。如果说男性向社区二创能力低，那么前几年闹得火热 v 圈又算什么呢？那个圈子不是饭圈浓度高、非常活跃的吗？那个圈子里面是不是人们都想冲爆呢？不好判定吧。

那对于二游，情况是不是一样呢？如果不一样的话为什么不一样？而在这里评价的二创能力指的是全体男性社区吗？那么类似于钢丝社区、以前的魔兽的社区，是不是又在这里的讨论范畴内呢？所以这里的评价难道不是要限定更多的前提吗？

假如说其他社区二创能力很强的而二游社区能力不强，这种区别又是什么带来的？

……简中在这里避免暴论是一种很困难的事情。就算说我们单独讨论 20 年代的二游社区，二游社区和其他男性为主导的圈子之前的异同、为什么二游社区会让人有这种印象，也可以纳入讨论范围内，只不过到这里可能就偏题了。

……直接像楼上的几位这样评论其实不是什么好事。

月夜梦行貘
因为二创本身只是 “施 - 受关系” 的蓄水池，导致魔怔的关键是 “施 - 受关系” 本身，你看乙游、二游、饭圈 v 圈都是这样。这一关系的结构在于，施舍者是情感和幻想的产出者，而接受者永远只能乞求其垂怜 —— 并且只有通过金钱获得自己本应有的地位。

月夜梦行貘
而这种行为实际上是施 - 受者的一种倒置，在金钱方面，施舍者是观众，被施舍者是产出者，在情感方面却反之。这种倒置使得观众会产生一种愤懑，凭什么我明明是施舍者却无法获得我想要的东西？
在非二游（不贩卖对私人的感情为主）的游戏或者文艺作品里，这种关系就很难成立，因为亲密关系亲密幻想是特殊的，是会反过来绑架主体的。但其他游戏给予的价值则和 “个人的心灵” 没那么贴近，玩家觉得无聊那就不玩，观众觉得难看可以不看

月夜梦行貘
我也很奇怪近年的二游为什么二创能力很低下，因为我是看着东方同人和各种 mad 长大的，在贴吧年代也不乏佳作。但是我没有深入过二游社区，这点我实在不好评价了。

摩砂学 → 月夜梦行貘
其实我只想指出你的回答其实不够准确，以及容易引发 “男性圈子怎么怎么样的” 暴论。我自己是无论哪个圈子都不怎么关注的。但是容易关注到的是，人们关注到男性为主的同人圈被一种刻板印象笼罩了。比如别楼里面提及的综漫（就连我自己都没听过）是属于同人的范畴，同时也是我根本不接触的文字类型的同人。

到这里我想说的是，“男性圈子” 并不准确，若用的是（简中）“二游圈子” 的话，这个回答当然成立。

我觉得你的回答放在 v 圈里也有道理。但是问题的似乎导向了另一个方向，也就是为什么得是 简中 二游 男性圈子的二创产出低。这其实还不够准确，我之前是玩 fgo，那边可几乎没有 ML 这种臭毛病，二创应该也还行，我自己不大看。

当然我评论的主要原因是一些暴论。

摩砂学
在这个刻板印象的延长线上讨论的话，我感觉是一种身份认同的问题，假如说所有男性圈子的人都称呼自己为同人男的话可能就不会出现这种问题了。在这里看综漫的和二次元就是两个圈子，那么割裂就自然地阻碍了对整体圈子的认知。

摩砂学
再然后针对 ML，我觉得和 v 圈有些类似，因为简中 v 圈是搞得最鸡飞狗跳、最魔怔的。ML 和 “vtuber 不能谈恋爱” 也有一定的相似程度。

摩砂学
其实我主要是不喜欢无意之间导向的性别叙事…… 太老生常谈了，而且经常让人情绪输出或者下暴论…… 这里很多楼都这样

月夜梦行貘 → 摩砂学
我本意就是指男性向圈子，这在一般语境下也就是指舰娘崩坏交错战线这类卖美少女为主的作品就像 dota 和 lol 这种虽然玩家几乎都是男的，但是没什么人叫他男性向游戏。
我不知道是不是当代的二次元很多都不是原来那批 —— 当然包括宅女也不是，现在的乙游玩家严格来说就是现充。
二游创作的社区不行很大原因是因为审查，因为男性向主要产量都是涩图，简中互联网压根就没得发…… 好吧，不得不承认很大一部分人玩二游就是为了冲一发，但是我又搞不明白他们为什么会因为剧情的原因（而且角度很刁钻）破防……
要我个人认为是相当多男性本身对自身的亲密情感需求太漠视了，甚至是贬低的。人们贬低异性恋爱脑的时候却忘记了性焦虑也是关于爱的焦虑，以至于他们愿意为《完蛋》这种素菜买单。当人们耻于谈爱的时候，作为美少女游戏的二创，在审查内自然没什么好写的了。

摩砂学 → 月夜梦行貘
这不又转回到性别叙事的角度上了吗……“有些游戏虽然男性玩家多，但是没人称其为男性向游戏”，如果在这里说明了男性向圈子指的是二游圈子，但是 “相当多的男性” 又会有扩大化的嫌疑，甚至在这里提及的《完蛋》其实和二游圈子关系不大，这让人感觉确实在扩大化。扩大化就会导向性别叙事，原本我们的主语只是二游玩家，现在却有变成整体 “男性” 的倾向。

我的重点在于，应当避免这种讨论之中的性别叙事，也即 “该现象的产生是因为男的有什么什么特点”，应当关注的是 “男的这部分群体之中何来的什么什么特点”。在讨论的时候，我会避免使用 “男性圈子”、“男性向” 这种说法，这是因为另一个部分圈子，比如说综漫同人文（读者也大部分是男性，广义上应当在男性向范畴内），并不在当前讨论范围内，于是比如说楼内在当前讨论二创的时候、讨论同人文的时候，使用 “男性向” 有扩大化的嫌疑，尤其因为二游玩家并不怎么看同人文。

摩砂学
总之我有点在跨服聊天的感觉……

正如武老师评论指出的，男性向不是没有同人文、不是没有二创，只不过是它们没有进入到我们的视野内，也没有进入到二游玩家的视野内。所以作为基本的论断的 “男性向社区二创活力低导致 ML” 在这里忽视了 ML 现象所具有的强烈的时代性和群体性。

总之说了那么多，我只是想避免那种泛滥的性别叙事，如果有一部分男性为主的圈子二创、同人创作很频繁，而另一部分却不是如此，而如果人们却只了解那 “不是如此” 的圈子，那么这种情况下转入性别叙事是说服力不足的。

摩砂学
说实话我觉得没什么好聊的，简中上所有对同人文化的评论基本都有问题，一点都没有那种日本文化批评的认真感。自然大部分人其实对两边的圈子都没有深入的了解，也从来没有史料和前人的研究帮助我们了解（我今天才知道【男性读者为主的】综漫同人文的存在，这样的认知能让我贸然对同人文化进行评论吗）。

现有的评论都是 “女的咋样”“男的咋样”，在尽情地输出的同时却没有意识到这种方向完全是死胡同。

但总之，我还是有点跨服聊天的感觉，这可能是角度不同造成的，因为日本宅文化批评的语境下，性别叙事都算是滥觞了。

昨天 12:55 · 广东
月夜梦行貘 → 摩砂学
我知道你的意思，二游本身包括 ml 运动本身有其特殊性，很可能是社群本身没有同人文这种传统。但是我想声明的是宅向文字类的需求并不是没有的，否则恋爱向的轻小说、网络文学应该也不会有现象级作品。
或许贩卖恋爱幻想这回事的二创本身是私人性质的；或许是因为审查的日趋严重导致原本丰富的同类替代品消失，新生代缺乏找资源的能力，同时时代本身让人们的戾气越发严重 —— 于是当人们需要一个平台去发表二创的时候已经没有平台可发表了。或许是二游本身吸引的群体本身对文字类不敏感，二游群体画手稀缺，等等是很多原因叠加导致了这种情况的出现。
但是说实话我写答案的确实有自己的情绪，我一开始就知道自己得出了一个似乎很局限的东西，批评我接受，但不妨碍我觉得解析二游玩家这一群体本身无法离开性别叙事。

** [2024-09-24 Tue] 国家统计局发布8月份分年龄组失业率数据，有哪些信息值得关注？
1 人赞同了该回答

陈关麒在《绸缪月刊》中发表的《毕业与失业问题的探讨》可以大概展现民国时期就业难的情况：

 现行的学校制度，中学六年，大学四年，一般毕业生耗废了金钱，经过了长时期的学校生活，用去无数的精力脑力，好容易拧得一张文凭，谁都希望出其所学，效力社会，不幸而生在供过于求的年头，政府机关人浮于事且没有援引不易进身，社会方面，又受经济恐慌的影响，工商业衰落不振，对此莘莘学子，也是无法容纳。因此毕业生俞多，失业人数也愈众。结果，因无颜同乡，自杀的也有。或因思想激变，走入邪途的也有。大有作为的青年竟在“毕业即失业的状态下做了时代的牺牲者！

但是好在这里是新社会，8月数据青年失业率比较高的数据，这说明社会在向高科技转型中高端人才需求旺盛，各高校因此加大培养力度，人才红利不断增加

** [2024-09-24 Tue] 简中、圈子 建议 archived

观点其实是相当受限的，简中其实还没能以冷静的态度看待同人以及这个圈子。如果说男性向社区二创能力低，那么前几年闹得火热 v 圈又算什么呢？那个圈子不是饭圈浓度高、非常活跃的吗？那个圈子里面是不是人们都想冲爆呢？不好判定吧。

那对于二游，情况是不是一样呢？如果不一样的话为什么不一样？而在这里评价的二创能力指的是全体男性社区吗？那么类似于钢丝社区、以前的魔兽的社区，是不是又在这里的讨论范畴内呢？所以这里的评价难道不是要限定更多的前提吗？

假如说其他社区二创能力很强的而二游社区能力不强，这种区别又是什么带来的？

……简中在这里避免暴论是一种很困难的事情。就算说我们单独讨论20年代的二游社区，二游社区和其他男性为主导的圈子之前的异同、为什么二游社区会让人有这种印象，也可以纳入讨论范围内，只不过到这里可能就偏题了。

……直接像楼上的几位这样评论其实不是什么好事。

** [#A] [2024-09-24 Tue] 为什么看 CLANNAD 感觉很不舒服？
:PROPERTIES:
:CUSTOM_ID: clannad
:END:

神必天坑

甚谁 等 120 人赞同了该回答

@雨宫优子。提到这个提问吧宇野常宽的轮子给造了出来。确实是这样的，宇野常宽在《零零年代的想象力》当中对于《AIR》《CLANNAD》这些游戏中给予了很低的评价，辣评这种广义涩情游戏是RAPE fantasy。

#+begin_quote
《AIR》所描绘的就是人类补完计划成功的世界=父性完全败给母性的世界了。正因为如此，故事中几乎没有成年男性登场。而正是在这样的世界=母性的摇篮中，用户才能通过“安全的疼痛”的自我反省表演来享受更加强化保存了的大男子主义。《AIR》中透着的大男子主义的保存回路之所以可以起效，是因为其世界观被压倒性的母性所守护着。

他们无法享受这个世界的复杂（正因其复杂而丰富），亦无法将“成为父亲”这种暴力式的自我实现以外之物纳入视野，只能通过“安全的疼痛”这样空洞的表演，将那种油腻大人式的欲望完全满足。
#+end_quote

所以其实题主有这种恶心的感觉是自然而然的，本身 clannad 就是一个充斥着大男子主义的、男性向的 galgame 改编而来的动画，是满足男性的欲望的动画，所以如果以一个女性的视角来看，会觉得不舒服完全不奇怪。

这种游戏就还是卖给当年青年男性，具体是什么样的青年男性呢？没落的大男子主义与不成器的自我欺瞒

#+begin_quote
虽然不曾打算成为父亲，但也压抑不住自我当个成熟父亲意味的欲望。他们肆意往返于两个不同的标准之间。一方面以移情作用投射进人少女漫画性质的内心感受，另一方面将身体委身于遥遥凌驾超越一般情色媒介的性意味的妄想之中。
#+end_quote

不过要说起来，或许并不是题主（以及这个问题下的一部分答主）重新发明了宇野常宽的轮子，而是恰恰相反，是宇野把上世纪七十年代在日本流行的激进女权主义的视角给发明了出来（）

对此，千田洋幸评价到：

#+begin_quote
在他的批评虽然经常关注新的媒介环境和内容，但核心的作品分析方法，却几乎是基于社会反映论和作家论的现实性的 1960-1970 年代的古典手法。比如说，把世界系的幻想(fantasy)与现实直接联系起来，并在其中发现“雷普幻想”、“顽固不化的男尊女卑的现存社会结构所孕育的广义上的性暴力”，这种方法和七十年代主流的激进女权主义如出一辙。在论述《新世纪福音战士》和高桥留美子的作品时，宇野还无限制地挪用了“父性/母性”这一过时的概念（之所以这么说，是因为这个概念的使用需要前置繁复的研究流程），这也是种极其老套的态度。总之，宇野所借尸还魂的，是那个谈及文化的创造物时，对理论的无知且无自觉能被允许的、非知性时代的亡灵。他抹杀了 80 到 90 年代构成文化核心的人文知识的历史，追求直接性、短路式的交流，抓住了对 90 年代式的知识不再抱有希望的年轻读者的心理，在批判性知性的废墟之上建立了作为作家的稳固地位。
#+end_quote

** [2024-09-24 Tue] 为什么中国人不信神或者说没有一个全国信仰的宗教呢?这是这片土地发展的必然吗？

林先生
哲学话题下的优秀答主

薛定谔的鲨 等 476 人赞同了该回答
想起了秦晖跟陈丹青的一段对话

 那个时候，中国人精神的适应性已经达到一种地步，对于任何急剧的转弯，他们没有转不过弯来这样一说的，没有什么信仰崩溃、什么精神崩溃。比如其他国家在政治急剧动荡的时候，往往会出现很多人因为幻灭，因为你原来追求的东西后来发现不是这么一回事了就没法活了，就自杀了。尤其是宗教传统很浓的那些国家，像俄国在几个关键点都是出现自杀高潮的，甚至在新经济政策时期都出现这种高潮，原来极左的那一套突然间行不通了，有很多人会自杀的。但是中国的老百姓当时很少有这样的，中国的老百姓你不管怎么一翻一覆地颠倒，他们都好像已经习惯了。没有人感到受不了。不是说这几件事大家没感觉区别，有的事得人心，有的事不得人心，但即便不得人心，就当做戏大家也还是做了。到现在也是一样。

 陈丹青：两德统一后，据说东德有三千多人自杀，主要是知识分子官员，包括博物馆馆长、大学教授、校长、学者之类。他觉得我一辈子信仰共产主义，这算怎么回事？死了算了，中国绝对不会。

 秦晖：对，中国人的精神不会崩溃，因为他原来也没什么精神。改革以后，抑郁症、精神疾患的发病率、自杀率，这些统计数字从九十年代以后就有了。然后就发现一个现象，改革以后，这个数字不断向上走，九十年代末是最高的，本世纪又开始往下掉。压迫到了一定的极限值以后，就没有反抗了，人都弄麻木了。

** [2024-09-24 Tue] 我国的电视厂家是怎么把自己玩死的？

Frount
这个人很懒，什么也没有留下
491 人赞同了该回答
在作死的是广电，而不是电视厂家，因为所有规则都是广电制定的。

1、智能系统刚有苗头的时候，广电就嗅到机遇开始垄断网络机顶盒，搞了个IPTV执照，同时开启了一台电视、两个遥控器的新篇章。

2、互联网媒体刚起步的时候，广电看机顶盒的垄断要被打破，就借着保护版权的名头搞了个互联网网电视执照，电视想联网或者视听软件想登电视端都得有这个。这个直接导致影音软件套娃会员，因为按规范要求，许可证是独立的、相应公司的经营也必须是独立的，否则就是挂靠、直接吊销！

3、再后来广电发的许可证越来越多，投屏软件都需要许可证。这也是为什么现在的电视、视频软件大多都不支持系统自带的投屏功能，而必须要使用特定的投屏软件。

可以预见的是，将来大概率广电会搞个自己的操作系统（比如基于安卓），“推荐”电视厂家适配，不适配就要上交专利给广电优化，再ban掉USB接口和各种传输协议切断刷机破解的后门，比如前一阵广电说要终结“两个遥控器看电视”可能就是个契机，然后找个安全的由头让工信部ban掉无线显示器，最后把带智能系统的触控显示器和会议大屏全部列为电视管控，广电就能大一统了。

PS：装了智能系统的投影（含激光电视），在广电眼里也属于电视

** [2024-09-24 Tue] 为什么要反驳剩余价值理论?

剩余价值理论基本上没剩余多少价值，有些部分甚至走上了自相矛盾的境地，虽然马克思的后继者们不停地给他的理论打着补丁，但有些补丁也是相互矛盾，属于是把“袖口”这些该开放的地方也给补上了。

一、马克思：雇佣即剥削
按照经典的马克思主义理论，资本家只是在能够榨取工人的“剩余价值”的前提下才会雇佣工人，因此这种通过剥削把剩余价值从工人转向资本家的做法存在于所有的劳资关系中，即劳资关系本质上是剥削关系。

但对于那些不得出卖自己劳动力的人，情况又是怎样呢？比如在有些国家，法律规定不得雇佣已婚妇女。

她们不仅没有受到剥削，她们还受到免于剥削的保护，许多人正是基于此来为性别歧视作辩护。

这些国家向已婚妇女提供一小笔收入，按照马克思主义的剥削论她们反而成为了剥削者——因为劳动者的一部分收入都被强行向这些已婚妇女作了转移，这就是“不劳而获”。

但是，把这种状况下的妇女当作剥削的受益者合理吗？她们所遭受的不正义可能要比资本家的剥削更为严重，而女权主义运动的首要任务之一就是让妇女能够平等地进入劳动力市场。﻿

或者，再考虑一下那些享有法定雇佣资格、但却没有被雇佣的失业者。这些失业者也没有被剥削，因为他们没有生产任何可供资本家占有的剩余价值。

而如果政府向人们征税以向这些失业者提供救济金，那么他们也会成为剥削者。但是，那些失业者的境况显然要差于那些能够被雇佣的人。

对于那些没有财产的人而言，被迫出卖劳动力也许要好于被迫不准出卖劳动力（的妇女），要好于不能出卖劳动力（的失业者），要好于通过犯罪、乞讨、依靠仅有的公共资源苟且偷生的人［马克思的“Lumpenproletariat”（流氓无产阶级）］。

人们本来期望剥削理论能够对资本主义提出激烈的批判。然鹅按照它的标准形式，它却忽视了在资本主义制度下那些境况最糟的人，并且实际上排除了需要对他们给予帮助的行动（如对儿童、失业者和残障者的福利支持）。

二、勒默尔：生产资料不平等持有说
如果剥削理论要对弱势群体予以恰当关照，就必须抛弃对“剩余转移”的狭隘关注，就应该转而考察这些转移在其中发生的更宽泛的分配模式。

为了解决这样的矛盾，勒默尔（Roemer）将剥削的定义不是基于剩余转移，而是基于对生产资料的不平等拥有。

按照他的观点，某人是否遭到了剥削取决于在一种假想的分配平等的条件下他的境况是否会更好——那种假想的条件意味着，某人可以带着自己的劳动力和人均拥有的外部资源而退出现行的分配条件。

仅当剥削是生产资料的分配不平等的不正义结果，剥削才是一种邪恶。如果我们把不同的经济群体当作由现有财产关系确定规则的游戏的参与者，那么某个群体一旦满足下述条件就被视为遭到了剥削：

如果该群体的成员带着人均拥有的外部资源退出了这个游戏并开始自己的游戏之后其处境反而更好。
对勒默尔而言，剥削理论的“伦理命令”不是消除剩余转移，而是“废除对于可转让的生产资料的不平等所有权”。

但这同样是说不过去的，现在很多中高级打工人手里的资金很充裕完全足以购置一些生产资料，那么他们为什么还是选择打工而不是创业呢？

傻子都知道找工作失败的亏欠风险远比创业失败的亏欠风险要低的多，这就是打工人自己根据自己的风险偏好而自主做出的选择，他们自己选择加入一个企业为企业主打工从而把风险转嫁给了企业主。

虽然打工的工资不比成功创业能获得的利润更高，但打工相比创业承担巨大的亏损风险获得的收入更稳定。

三、柯亨：需求分配原则
在他初次对马克思主义的剥削论予以表述的时候，科恩否认预先设定这样一个前提，即“人们拥有自己的劳动产品”：

  一方面，可以认为，资本家通过占用工人所生产的东西的一部分价值而剥削了工人；另一方面，又不必认为，所有这些价值都应该归于工人。可以肯定某种以需求为基础的分配原则，同时又可以认为，资本家剥削了工人，因为资本家对工人产品的一部分价值的获得，并非以他的需求为基础。

否定这个前提是因为柯亨认为如果“把最一般意义上的对劳动时间的占有当作不正义的范例，那么，你就无法避免对像自我所有权原则这样的内容予以肯定”。

因为旨在保护儿童或年老体弱者的强制性征税也应该被当作剥削。如果我们强迫工人纳税以保护年老体弱者，我们就是在强迫他们做没有酬劳的工作。﻿

但柯亨属于是“进一步，退两步”，丧失劳动产品的自我所有权而声称资本家剥削工人，这种说法的理由是什么呢？

  他（资本家）对工人产品的一部分价值的获得，并非以他的需求为基础。

那假设某个资本家对某个产品没有需求，因此对它也就没有正当要求，但这并不意味着按照需求原则，工人就能够对此形成正当要求。

因为最需要产品的人也许是第三者（如儿童），那么儿童就成了唯一能够对产品拥有正当要求的人。

如果资本家仍然占有了产品，他就是在不公正地对待儿童，而不是在不公正地对待工人。但是，如果工人占有了产品，那他不也就成了不公正地对待儿童的“剥削者”吗？

因为一旦违背了需求原则，受到不公正对待的就是需求者，而不是生产者。

一旦我们放弃自我所有权的要求，对剩余价值的占有在本质上就不是剥削——因为剥削取决于对剩余价值的具体处理是否吻合更大的分配正义模式。

但如果捡起自我所有权又会完全迎合了诺奇克自由至上主义的假设：自我所有权—劳动自我所有—劳动产品自我所有—剩余价值转移—强制无偿劳动—福利性剥削。

四、阿尼森：剥削二分法

阿尼森区分了“正当的剥削”与“错误的剥削”，他认为要判断是不是“错误的剥削”，要求与某种假想的平等主义分配进行对比，但他对平等分配的解释既排除了天赋不平等产生的差异又排除了外部资源的不平等产生的差异。

阿尼森相信按照这个检验标准，资本主义制度下的绝大多数工人都遭到了剥削——因为他们因不应得的财富不平等或不应得的天赋不平等而使自己被他人所利用。

与勒默尔一样，剩余转移在阿尼森的理论中起一种派生作用。如果剩余转移是不平等分配的结果，它就是错误的；如果剩余转移的出现与财富或自然天赋方面不应得的差异无关或被用于补偿这些差异，它就是正当的。

因此，对失业者和残障者的强制性支持就是正当的。然而，在资本主义制度下从工人那里拿走的绝大部分剩余都是不正当的，因为这些剩余最后都进入到了受益于不应得的天赋分配和财富分配的那些人的腰包。

因此，资本主义是一种剥削制度——虽然支持这个结论的理由相比最初的马克思主义剥削论要复杂得多。

今天看来，这是对剥削更加言之成理的一种解释。但不幸的是，正因为这种立论抛弃了原初的马克思主义剥削论的全部特色，它才变得更加具有吸引力。

第一，这种把对剥削的思考包含于其中的更宽泛的理论越来越接近罗尔斯资本主义补丁式的正义理论。

原初的马克思主义者的论证是，工人对自己的劳动产品享有资格，而资本主义的不正义就在于使工人被迫放弃这种资格。

但大多数当代马克思主义者都试图避免这种自由至上主义式的前提，因为这（与其他理由一起）使得对老弱病残的援助在道德上居然成为可疑的了。

而他们越是试图顺应我们的常识——并非一切技术意义上的剥削都是不正义的，他们就越是在诉求罗尔斯式的平等原则。

第二，这种对剥削的新解释抛弃了原初的马克思主义剥削论的存在依据——也就是马克思主义的这样一个论断：劳资关系本质上就是非正义的剥削。

因为如果要依据是否存在不应得的不平等来判断某种剥削是“好剥削”还是“坏剥削，那么某些劳资关系就可能不是剥削关系，而“剩余价值”里甚至会出现“好剩余价值”与“坏剩余价值”，马克思主义理论的一致性会被修正得乱七八糟。

第三，还是生产资料的问题，对生产资料进行社会化还是对生产资料进行平等化这点而论，对剥削的关注并不能证明前者优于后者。

如果有这样一个企业，它的内部有两个不同意见的群体：一个群体对收入的偏好超过对闲暇的偏好；另一个群体对闲暇的偏好超过对收入的偏好。

如果多数群体在决策上赢得了胜利，而如果他们又不允许少数群体把自己在康米制度下对资源的平等拥有权转变成自由主义的对个人资源的平等所有权（譬如，通过出卖他们在企业中的份额），多数群体就将以不公平的方式去决定少数群体。

这时少数群体则遭到了剥削，因为如果他们带着自己的人均资源份额退出的话，他们的处境反而会更好。

但如果只是生产资料平等化的话，只不过又是重新回到了“私有制”，人们又会因为天赋的不平等、投资回报收益、时间分配偏好与其他社会资源等条件的差异重新回归到资本主义社会状态，对于马克思主义者来说这下又“通往奴役之路”了。。。

** [2024-09-24 Tue] 对于程序员，到底什么是成长性的工作？

whhema

momo 等 4 人赞同了该回答
随便写写，我第一反应是三个点。

首先是能看到运营的数据，这一条就秒杀了一切大厂。

你要跳出自己的职位，跳出螺丝钉的定位，才能感知到真实的业务。

大厂里的什么高级工程师，什么技术专家，什么技术经理，表面上拿着高薪，人际关系简单，实际上是最毒的诅咒和最大的坑，每年吸引了好多人往里跳。

中小企业的程序员能看到的反而更多。

其次，你要知道如何直接改进这些数据，注意这里的重点词是直接。

程序员是最苦逼的工种，几乎所有程序员都不了解自己的工作内容对业务的实际收入和利润起到了什么作用。

这就是每年年底打绩效时，技术部门最吃亏，明明干着最苦的工作，还要背绩效指标模糊的锅。

一定要冲到业务的最前线，不要满足于做个所谓的技术专家。

最后是识别当前工作能否有喘息时间，不要把自己的7*24小时都献祭在公司项目上，除非你能在项目上直接获利（比如你入股了，或者你有提成）。

运气好的话，如果你的上级也是这个想法的话，尽早抱大腿，过这村没这店了。

** [2024-09-24 Tue] 如何评价曹丰泽突然转进视频赛道？

389 人赞同了该回答
当初曹丰泽决定去非洲，我便去他的主页围观了几篇回答，得出的结论是这个人官瘾很重。

那时他的粉丝听闻他“放弃选调”而进军非洲，对他的崇拜达到了极点，逢人就吹他什么“副处级”“央企总工”“三清”，仿佛一个超新星就要带着他们所有自以为是的梦想和不切实际的期盼在官场“冉冉升起”了。又逢人便夸他“援建非洲”“造福第三世界人民”，那是“功德无量”，仿佛只要在非洲吃点苦，“取经”回来就能封“佛位”。

后来媒体还真的宣传了他一下，好像是在提前进行舆论造势，一副准备把他当“苗子”来培养的样子。后来我们知道，连个水花都没溅起来就再也没了下文，除了他自己发在知乎的回答，哪还有什么人追踪过他在非洲具体的“丰功伟绩”，甚至连一点舆论价值都没有做出来。

很明显可以看出，这个人请缨去非洲刷资历，不是有什么高尚的情操和伟大的理想，而是他从功利主义的角度出发，作为一个崇拜权力的人，在综合判断自己家世背景和知识背景后的理性选择。

因为是小镇出身的做题家，在他的观念里，想要快速升上去就得去吃苦，去非洲这种苦中苦的地方就是“坐火箭”走捷径。而他粉丝热衷于意淫他回国之后的级别，和他字里行间透出来的那种“建功立业，大干一场”的自信，都充分昭示着他出发前的野心勃勃。

我当时就判断，他泡在学校里这么久就只是读书，还没去做过学生工作，大概率本人并不精于“这一套东西”，一定会在他的梦想道路上折戟。

做题家思维就是以为吃最多的苦就有最多的收获，毕竟他们学生时代在学习上取得的“成功”都是按照这种确定不移的法则在运转。

然事情的发展与他原初的设想大相径庭，他在那里干了几年，没有很快得到他想要的，他的贡献也没有被什么人看到。

于是他心有不甘，不再闷声做事，就拿起镜头，自己当自己的“记者”，把自己做过的工作呈现到世人面前。

看视频，他心气淡了不少，镜头前的形象谦逊有知，都开始用当初知乎IT人士讽刺土木的打灰来自嘲了。

当一个学者在自己的专业领域做不出什么来之后，他会淡化在主业上的心思、放弃和同行交锋，转向视频平台当“孩子王”，通过自身丰富的知识阅历对年轻人“降维打击”来满足自我实现的需求，填补现实生活中所欠缺的成就感，同理。

只不过，这些学者往往都是年逾半百才转向这个赛道，他倒是一步到位，少走了二十年弯路。
** DONE 任务书 graduation design renwushu
:PROPERTIES:
:ARCHIVE_TIME: 2024-09-23 Mon 17:54
:ARCHIVE_FILE: ~/org/note.org
:ARCHIVE_OLPATH: archived
:ARCHIVE_CATEGORY: note
:ARCHIVE_TODO: DONE
:END:

*** 基本信息

学科类别 理工类
题目来源 教师自拟题目
题目类型 科学实验类
申请导师 王德胜
题目名称 基于流量分布预测与移动性感知的高效MEC服务器放置

本课题是否“以实验、实习、工程实践和社会调查等实践工作作为基础” 是
论文研究方向 边缘计算
论文关键字 流量分布预测；移动性感知；服务器放置

*** 课程简介

在过去的几年间，移动边缘计算（MEC）技术在提高网络性能和用户体验方面取得了显著进展。随着5G网络和物联网（IoT）的迅猛发展，用户对低延迟和高带宽的需求也在不断增加，而MEC正是通过将计算资源下沉到网络边缘来满足这些需求，减轻云端网络的压力，降低服务响应延迟。

在此背景下，如何高效地部署MEC服务器以优化资源利用率和服务质量成为一个重要的研究课题。本课题旨在基于流量分布预测与移动性感知技术，实现高效的MEC服务器放置。

通过对用户流量进行预测，能够更准确地了解不同区域的流量需求，并结合用户设备的移动模式，动态调整MEC服务器的放置位置和资源分配。

在具体实现方面，本课题将采用机器学习和数据分析技术，对历史流量数据进行建模和预测。同时，利用移动性感知技术，实时监测用户设备的位置信息和移动模式，从而对服务器进行动态调整。为进一步验证MEC服务器放置技术的有效性，本课题将搭建一个完整的MEC架构，作为服务器放置技术的运行平台。

论文关键字 流量分布预测；移动性感知；服务器放置

*** 立题的目的和意义：

移动边缘计算（MEC）是一种新兴的计算范式，其核心是将云计算的能力从中心化的云数据中心向外扩展到网络边缘。这样做的目的是为了减少数据在网络中的传输距离，以此来降低用户的延迟，提升服务质量。在过去的几年里，MEC显示出其在提升网络性能和增强用户体验方面的显著贡献，成为了一个关键的技术领域。

在这种语境之下，服务器放置策略就显得尤为重要。服务器放置指的是将服务与计算能力部署在离数据源或用户更近的物理位置，以此提升减少延迟和网络拥塞，并且提高服务质量。

传统的服务器放置策略通常基于地理位置和数据中心容量进行，属于静态部署技术，通常会将服务器部署于公司总部、区域办事处或者专用数据中心等，便于集中管理与维护。然而，静态部署虽然能够降低成本和管理复杂度，但是缺乏弹性且有可能带来昂贵的运营成本。此外，移动用户的行为通常是难以预测且不规则的，静态的服务器放置策略已经难以适应移动用户的迅速变化的需求。针对以上问题，需要一项能够自适应用户位置变化的边缘服务器部署技术，以保证后续边缘计算任务的服务质量。

为了应对这些挑战，我们计划开发新的流量预测模型和MEC服务器动态部署算法。通过精确预测用户流量的分布，我们可以更准确地理解各区域之间的流量需求差异。我们还将考虑用户的设备移动模式，结合这些数据来动态地调整MEC服务器的位置和资源再分配方案，从而更好地响应用户行为的变化。这些技术的发展与实施，将为用户带来更好服务质量，同时提供高效节能、成本优化的解决方案ff。

*** 主要内容

流量分布预测模型的开发：设计基于历史流量数据的预处理和特征选择方法。开发能够处理大规模数据集并应用于实时预测的机器学习算法。实现动态和静态流量预测模型，针对短期和长期流量波动进行预测。

用户移动性模式的分析与感知：利用移动网络数据评估用户位置的动态变化和移动趋势。

MEC服务器动态部署算法：开发算法以模拟和优化MEC资源在网络边缘的分布式部署。构建性能评估模型，用以预测不同部署方式下的服务质量和资源效率。

测试和验证平台建设：我们将会搭建一个模拟真实网络环境的MEC测试框架，用以测试和验证流量预测和服务器部署模型。通过模拟不同的用户行为和流量模式，验证策略的有效性。

*** 技术指标

流量预测准确率：高准确率将会有助于预测网络流量的峰值和低谷，从而优化资源分配。

响应时间与延迟降低：通过精心设计的移动边缘计算（MEC）部署策略，我们将能够显著减少网络延迟，提升用户响应时间，增强了用户体验，为实时应用提供了必要的支持。

服务的可靠性与优化：服务器放置策略必须确保服务的高可靠性，并通过优化体验质量（Quality of Experience, QoE）来提升用户满意度。服务质量（Quality of Service, QoS）可以通过多个维度来衡量，包括带宽稳定性、网络延迟和数据包丢失率。通过这些指标的综合考量，我们可以确保服务的连续性和用户的满意度。

*** 进度安排

1. 开题检查前：2024年9月~2024年12月
2024年9月：查阅相关文献调研
2024年10月：查询动态服务器放置策略，选择并且实现服务器放置算法，基本搭建起MEC服务器架构。
2024年11月：利用机器学习和神经网络技术，实现对流量的预测。
2024年12月：使用移动性度量，将其融入到MEC架构之中。

2. 开题至中期：2025年1月~2025年2月
2025年1月：使用真实数据集进行训练，并且进行优化和改进。
2025年2月：在平台上进行仿真实验，调整系统并且优化仿真效果。

3. 中期至结题：2025年3月~2025年4月
优化系统，编写结题报告
** DONE 软B开题报告 ruan b
:PROPERTIES:
:ARCHIVE_TIME: 2024-09-23 Mon 17:54
:ARCHIVE_FILE: ~/org/note.org
:ARCHIVE_OLPATH: archived
:ARCHIVE_CATEGORY: note
:ARCHIVE_TODO: DONE
:END:

*** advantage                                                     :ARCHIVE:
缺点：1.提高了系统和管理的复杂度：面对多个配置文件，难以保证他们不会相互之间有影响，这将为管理系统带来挑战2.降低了安全性：多个用户共享开发板可能导致安全问题，比如说对其他用户配置文件的非法访问。3.提高了调试难度：在调试的过程之中还需要考虑共享的问题，将会提高调试的难度4.对于管理人员的学习曲线陡峭：因为管理员需要学习PR相关的工具和实现原理才能更好的利用PR，并且管理员也需要面对更高的调试难度。

*** disavantage                                                   :ARCHIVE:
优点：优化了资源利用率：多个用户可共用开发板，提高对可用资源的利用率。减了少停机时间：FPGA只有一些部分需要重构，提高了停机时间。提高了灵活性：更容易扩展系统，容纳更多用户或者更复杂的实验，而无需进行重大的硬件更改
*** 简介

(1) 支持PR的远程FPGA实验系统【迭代】

– 可参考去年“远程FPGA实验系统”课题，提供文档和源码
– 前端支持用户上传.bit
– 服务器接收用户.bit文件后，将.bit下载到FPGA开发板
– 服务器只需支持1块FPGA开发板
– 系统支持2个及以上用户
– 只需设计简单的前后端，能用于演示即可

keyword: partial reconfiguration

*** doc

https://docs.qq.com/doc/DS0J1bFVaRGtyV3Zs?_t=1726986675018&u=a401c0f3feae46de80a830c15e9ecb88

** [2024-09-30 Mon] nlab

nlab 让人恼火，虽然 nlab 对于很多人来说是不错的资源。但还是令人恼火。

比如说 coherent space 这个部分，事实上来说，我们抛弃掉拓扑的语言反而方便我们的理解。

damn

** [2024-10-02 Wed] 对于“精神营养”

对于“精神营养”的追求，仿佛是一种幻觉，妄想在“精神”上赋予自己文化产品以高层次的意义。

面向一个男性向的作品，“男性向”一个评价似乎已经足够，但是在这里展现的是如此的言语：
- “我仿佛没有感觉到你的作画的意图”
- “仿佛是为了画而画”
- “没有对精神营养的追求”
- “女性的身体作为一种客体被呈现在画之中”
- “能够感觉到创作者的污浊的眼神”
- ……

如同幻想一般地对自己的消费的拔高，还加之这种无耻的性别叙事的应用。

其实是一种混用、以及这种混用导致的对于自己行为的合法化。

当我的需求是 mental 的时候，我却认为，我的需求是一种 spiritual 的。占据了前者的合法性，同时后者还让其占据了所谓的“意义”的高点。

他们的观点在事实上还是一种滥觞。

当有些人开始讨论消费者和创作者之间的关系、这种彼此相互渗透的两个群体之间的关系的语境之下，性别叙事作为一种 50 年前的老古董很少出现在这里，并且文化创作也不区分同人创作以及商业创作（消费创作之间的模糊），所谓的“男性向”作品也并非以所谓的“色图”的形式被人接受。作为50年前的“先进”理论虽然理所当然地有着市场，但只不过是作为一种最没有“营养”的评价而存在。

lead you astray

** [2024-10-06 Sun] being a women

基于一种刻板印象，在老友记之中，joey 说“不是你说的内容，而是你如何说的的”，随后惊呼“OMG，我是个女人”。但现实果真如此？

非也。我就是会被人的态度强烈地影响的人。其实这就是所谓的下头之一。当然下头更像是 [[*\[2024-10-06 Sun\] 重叠的经验][[2024-10-06 Sun] 重叠的经验]] 所提及的，矛盾的体验之间带来的一种 bewilderedness。

感性的人吗？但事实上不是如此……每个人都有感性的功能在其大脑内运作着。

** [2024-10-07 Mon] 双重身

“我觉得我说很多事情都被当放屁了”，我当时是怎么想的？

说实话我完全记不得了……

这其实是有问题的啊

** [2024-10-08 Tue] 对于人的态度的察觉

以前是在高中，在那里，其实每个人都是没有什么坏的倾向的。我是一个老师，那么我的职责就是教好你。我是你的同学，那我们就共同进步，或者至少不相互干扰。

一种勉强、一种敷衍、一种自己没有察觉的沉醉，都是极度让人敏感的……我们亲爱的学长，仿佛是自己也不怎么想干这种事情的样子……真是令人无语……尤其对于我来说。

也就是这种事情最能打击人的积极性……

** [2024-10-06 Sun] 重叠的经验

在话语形成之前，一般是先有体验，这是经验的一种，一种还没能成形的经验。我说，我一般先体会重叠的经验带来的感觉，然后才能用嘴说出话来。

比如说，我今日看到一个抱着玩偶的女孩。很不自然地、很可耻地，一种 sexualize 的行为就在这里产生了。一种重叠而且矛盾的经验让我有一种违和感。何者？对于“漫画”之中的这种形象的情感，放在现实之中就成为恶心的事情了，一种现实和虚构之中一个桥梁就搭了起来，现实和虚构相互渗透。

这种违和感仿佛是在对我说，“你个比差点成变态了”。

错位的经验带了一种还难以言表的震撼。仿佛是一个无形的链条的断裂。我是先有感觉才有解释，这倒是一种很麻烦的事情，因为我的解释是基于“感觉”而非事实。

** [2024-09-28 Sat] 不存在后悔

没有后悔，在那里只是为了弥补认知的不足所付出的代价。如果你的后悔只是“如果当初不用支付那种代价就好了”，那你还不如许个更实际的愿望，比如说“如果我家里当初拆迁然后突然多了200万就好了”。

** [2024-09-25 Wed] 装置的大小

装置是什么？舞台装置！

若要写个好短篇小说，你的装置得往大的写。仿佛是在进入眼帘的一刻开始就在蓄力。

对于长篇小说就不必然，装置可以和玩具一样。但是说它的大小变得如此之小，而玩弄的意味是如此的足，让人觉得其仅仅是玩具，像是 margin 上的涂鸦，像是道具而不是装置，像是一个超链接，给你导到不知哪里去了。

乔伊斯的«芬尼根的守灵夜»，我只看过第一句话，其首字母没有大写，明显是半句。“不会吧”，心里想着，翻到全书最后一句话上，“居然真的是”，确实是和第一句能接上……这似乎是最大的装置，贯穿了整部小说！但果真如此吗？

** [2024-09-24 Tue] 脆弱的“好看”

看到了一个reddit的帖子：有哪部电视剧是如此烂尾以至于你一直记恨它。我立刻就想起了我曾经看过的那些。

- lost 莫名其妙的结局，浪费了10季的时间
- arrow 本身就垃圾
- gothom 除了第一季就是垃圾
- the big thoery 越后来就越垃圾
- sherlock 最后一季根本不应该存在
- 2 broken girls 毫无疑问的垃圾

除了质量下滑之外，自己那么会被这种事情 trigger，其实是因为这种“好看”有一种非常脆弱的基底。你的“好看”为什么那么容易地被摧毁？怎么没见人被战争与和平恶心到，那里也有地雷的情节。

本身阅读（观影）是一种对话。但是人看小说就跟自慰一样，小说也写得和黄片一样。何来对话？

举个例子，人曾说自己因为犯了某一个错误，小说订阅数崩了几万。这似乎能说明对于人来说，小说只是随意替换的道具，就如同你的飞机杯坏了就买个新的。替换小说就如同关掉这个黄片然后打开另一个黄片一样简单。

在这里不仅是对话゠阅读，而且还是对于好看的质疑。若是以一种脆弱的形式享受，潜在的风险让人觉得不值当。这是某种抽离、自己的理智给出的警告——一种对下降的警告。

** AvPD
[2024-10-13 Sun]

Avoidant Personality Disorder。也就是回避型人格。可以想象到的是，回避型依恋人格是一种简体中文的特供版本。

即使如此，加上一个 Disorder 未免是有点没有良心了。

这是一种巧合还是说？但总之两种 Disorder，都是完美地对上了。在这里我说，她为什么要提这个事情？也许是找了借口，想指出我当前的这种状态。
* little things
** emacs Aider

https://emacs-china.org/t/ai-aider-emacs-aider-el/28064/31
** session type

https://wen.works/2020/12/17/an-introduction-to-session-types/

https://zhuanlan.zhihu.com/p/898038063

** 15816 course

substructural / linear logic / 15816 CMU

https://www.cs.cmu.edu/~./fp/courses/15816-f16/

** 15312 course

I don't put link here because 312 course is not that important.

** fonts and readings experience

Towards Individuated Reading Experiences: Different Fonts Increase Reading Speed for Different Individuals

https://dl.acm.org/doi/10.1145/3502222

** Avoidant personality disorder quiz

https://psychcentral.com/quizzes/avoidant-personality-disorder-test#recap
** Bionic Reading and some relative research

Does Bionic Reading actually work? We timed over 2,000 readers and the results might surprise you

https://blog.readwise.io/bionic-reading-results/

** 复制文本
*** 序

#+begin_center
贫瘠动画 其美学与射程
#+end_center

rocefactor

#+begin_center
序
#+end_center

*艺术鉴赏的“内”与“外”*

艺术鉴赏中存在数个相对的概念群，由日常言语经验的直观所把握。使用表现内外关系的修辞去形容作品的魅力程度便是具有普遍性的一个例子。中文说“引人入胜”，日语说“見入る”，英语则有“absorb”这样本来指向吸引、进入一类意思的词汇。可以说，从外部“进入”作品世界的内部常常与作品的魅力关联在一起。18世纪，狄德罗从戏剧理论出发，对自己仿佛进入风景画的私人经验进行的分析非常有名。之后，通过对狄德罗的细致引用，美术史家迈克尔·弗雷德完成了视点独特的18世纪法国绘画史。

另一方面，文艺复兴时期的艺术家相信，美的经验是丰富的。意大利的老大师在雕塑中追求“Il poco piu”，即“the little more”，与自然界无处不在的微妙曲线所蕴含的变化之丰盈相联系。视觉的愉快带来想象力的自由，自由是美的。与美所具有的愉悦相对，不美的经验被描述为“poor”，即贫穷的、贫瘠的。当现代人用“匮乏的想象力”、“贫瘠的表现力”、“贫瘠的语汇”形容某种无聊的、难以引起人兴趣的事物时，就证明了关于丰富之美的观点的潜移默化。换言之，我们可以得到围绕艺术鉴赏的一系列二元论的图示，将美、丰富，与指向作品内部的吸引力联系在一起，并把丑、贫瘠，以及无法沉浸的体验置于其对立面。

然而，对于“贫瘠”本身的了解却惊人的有限。来自各个领域的研究者和评论家致力于说服读者，使他们相信富有魅力的作品是如何引人入胜，并且不断用最严谨的方式探讨其魅力的机理与分类学。他们挖掘得太深，以至于其痕迹周围已经留下太多“无价值”的空白。这些空白意味着一类失败的历史，因为没有发挥被默认的功能，也就无法被以合适的方式编入现存的价值制度中，于是几乎全部的讨论都与其现实呈现南辕北辙之状。与此同时，承认这种失败在价值制度中的缺失，是由于其形态学意义上的不吻合，而非其在价值序列上的低位，则暗含着亵渎的风险。我们将不得不看到，在配得上世间一切溢美之词的创造力的源泉之上，笼罩着令人不安的怀疑主义。

在 18 世纪的英国文学者的议论中，关于内部--丰富对外部--贫瘠的图示似乎被撬开了一道裂隙。1773 年，在《关于恐怖对象所带来的快乐》中，诗人安娜·拉埃蒂茨娅·艾金谈到对于悬念的不安如何成为文学的武器，并使无辜的读者沦为平庸之作的受害人：

#+begin_quote
……我常常想象在这些情况下存在一种欺骗，热切的关注并不是我们真正获得了快乐的证据。悬念的痛苦和满足好奇心的无法抗拒的欲望一旦产生，将解释我们渴望完全经历一场冒险的急切心情，尽管在整个过程中我们都经历了实际的痛苦。我们宁愿忍受剧烈情感的痛苦刺痛，也不愿忍受未满足欲望的不安渴望。从经验上讲，我相信这一原则在许多情况下会不自觉地带领我们度过我们不喜欢的事情。这就是一旦我们真正投入其中，就使得最贫瘠和最无聊的叙述变得有趣的冲动；我对我们现代小说也经常有这种感觉，如果它们放在我的桌子上，在闲暇的时候被我拿起，它们会引导我阅读最乏味和令人讨厌的页码，就像皮斯托尔吞咽他的韭菜一样，它不仅会迫使我们度过无聊，还会迫使我们经历实际的折磨——例如达米安的处决或宗教审判所的行为。因此，当孩子们以苍白和无言的注意力倾听可怕的鬼故事时，也许我们不应该认为他们处于一种愉悦的状态，就像一只可怜的鸟儿掉进响尾蛇的嘴里一样——他们被耳朵束缚住，被好奇心迷住了。
#+end_quote

如果读者对于当代动画的洞察和艾金对 18 世纪的英国架空文学一样敏锐，那么我也许可以就此搁笔了。我相信，艾金在此处记下的“贫瘠文学”的体验直接关乎于本文的主旨，虽然她采用了非常消极的态度，而这有别于本文的志向。此处，艾金对于阅读行为中的持续性专注与贫瘠体验所蕴含的反转的联系的关注值得留意。以 18 世纪的观点看——如同我想要指出的那样，这一观点显然来自于狄德罗——唯有真正投入作品世界之时，作品的贫瘠与乏味才会得到消解。因此可以说，“内”“外”之分是贫瘠与否的分水岭。然而，艾金的议论在提示了鉴赏行为中的内与外的同时，作魅力有无的凭证。伴随这种同调的维持或是逆转，括其中的视听现场的内部和外部的关系，或者观者与形象的关系也不再是稳固的。

*贫瘠动画的经验维度*

某种意义上说，正是在内外之别的延长线上，瓦尔特·本雅明谈到“经验的贫困”。在 20 世纪 10 年代的大战中，战争的浪漫色彩沦为过去式。光鲜亮丽，富有尊严的比武决斗的英雄传说，被脆弱而肮脏的士兵在战壕的泥泞中等待无法预期的横死的恐怖景象取代，“变得愈发贫瘠”。

技术进步伴生的经验之贫困并不仅在战场上出现。相较于马车旅行和剧院观众，列车旅行的游客和电影院里的观众也处于经验的贫困之中。18 世纪的剧院空间中，观众常常紧挨着演员，或者索性混入表演者之中，在上演剧目的舞台上朝远处的好友挥手致意。理查德·桑内特写道，“观众之反应的开放性和自发性，基于这么一种意识，它将演员和观众视为处于一个世界，认为此刻发生的事情是发生在眼前的现实生活的一部分”2。可想而知，由舞台戏剧而来的“第四面墙”等装置性概念，正是来自于作为这个时期的剧院观众的狄德罗的切身体会和超凡脱俗。也正是在这个互动关系的意义上，置身于舞台戏剧的叙事空间的内部的行为，从一开始便与经验的“贫困”发生着对立。

20 世纪初，初期影院常有演出者穿梭于舞台和银幕之间的表演模式，电影院银幕前的演台是曾经存在的舞台和影像之间的开放性的遗产和无言证人。以这种初期电影的自我言及为母题，在《福尔摩斯二世》（1924）中，巴斯特·基顿在梦中穿梭往复于银幕与舞台之间。

在完全不顾及其人工性之外露的意义上一度向作品的外部开放的媒体表现，伴随叙事目的和演出技巧的成熟而走向闭锁的过程，并不独属于戏剧和电影。被认为是最早的动画人的埃米尔·科尔的 1900 年代的作品完全不回避这种开放性，角色被绘制出来，再被擦除的过程本身成为作品的内容。然而在那之后，演出者和角色们作为影像之外的存在的经验开始快速凋落。1914 年，温瑟·麦凯在《恐龙加蒂》的演出并非面向观众，而是面向影像。在演出的最后，一直在银幕之外与恐龙加蒂互动的麦凯纵身跃入银幕，将观众的世界抛诸脑后。

伴随电影传统的建立，电影世界的无限展开，就像 19 世纪的列车旅客们在极短的时间内就找到了新的风景一般，如今的电影观众早已获得了一种新的经验的丰富性。对于这种丰富性的无反省的参照招致一种逆反，本文所预期的正是这种相对化的企图。如开篇所暗示的那样，贫瘠动画，不仅在朴素意味上关系到其对象的预算不足，细部的疏漏和品质的参差，还意味着剧院--电影的无干涉转向，电影--动画的漠然转向这一从影像的剥离中体会到的经验之贫困。

*贫瘠动画论的志向和现状整理*

作为一系列考察的开端，本文将尝试探讨一直以来不仅被严肃的研究者，也为一般的动画观众所忽视、排除的重要动向，并勾勒出形成这一动向的核心结构与历史文脉，着眼于在这些作品的现场分断内部与外部，规定并支撑作品的框架的力能。我将该动向称为“贫瘠动画”，将其力能称为“贫瘠性”，把贫瘠性的原理集中运作并显现的作品群视作贫瘠动画的实践场域。贫瘠性，从作画和演出等动画制作的具体实践开始扩展，超越复数的物理层次，在这个过程中包含了制作的破绽以及素材的反复利用、痉挛的叙事以及演出的散漫、外部的欠缺以及注意力的涣散等多义，既是贫瘠动画的核心和奇点，又悖论般地将“非--贫瘠动画”的影像表现置于其射程之中。

贫瘠动画，即使并不使用这个术语，也早已作为一种动画视听的他者存在于动画言说空间中，以“PPT 动画”、“便宜动画”，抑或是“三文字动画”、“椰子蟹之屠”等黑话的面目示人了。讽刺的是，对于疏远于动画的观众而言（不幸的事实是他们是大多数），深夜动画全体似乎都符合于这些描述。从这个意义上，几乎可以说贫瘠动画之贫困以手冢治虫之探索为起点，即使这并不符合历史的事实，更不是所谓有限动画的原罪。正如这些蔑称所暗示，贫瘠动画往往被与劣质外包动画混为一谈，被视作 MediaMix 商法的副产物和牺牲品，因而在审美上缺乏价值。但是，诚然贫瘠动画往往与劣质的印象联系在一起，却不能武断地说劣质的动画都是贫瘠动画。荒唐无稽的故事展开、制作细节的疏漏，品质的参差并非贫瘠动画的本质特征。

不过，纵然只是表面的形式，既然贫瘠动画已经以某种形式存在于动画言说空间，就能够在 TVA·深夜动画的全体构图中对其进行一定程度的定位。事实上，已有先行者采用了类似的取径。例如，石冈良治关于《战国 Collection》的批评敏锐地捕捉到动画视听经验的混沌性的议题，并且通过“门户链接”式的想象力将动画的图层混合等基本构成要素、以及作为封闭与开放倾向之混合场域的动画的总体与观赏者的知觉联系在一起，提供了思考动画内在要素的重要角度。在 AI 检索技术迅速发达，碟片市场经济日益凋敝的今天，来自于2012年的“门户网站”式的想象力已经显得前途未卜，然而其问题意识却依然牢牢占据着特别是深夜动画经验的核心。本文以不同的途径与其相交，通过提示贫瘠动画的多个面向与潜能，在事实上与石冈之议论互为暗线，这甚至出乎于我的预料。

有必要指出的是，虽然既存的“混沌动画”“クソ动画”“ドタバタ动画”等概念所指示的对象在一定程度上与贫瘠动画有所重合，但是依然存在方向性上的差异。因为在我的考量里，动画的贫瘠性无法成为作品类型论的根据。也是在这个意义上，本文论述的贫瘠性和其具体表现在各种类型的作品中都能发现，而这并不等于我在主张这些对象都可以被称作贫瘠动画。在后文中重点考察的佐藤顺一、中村宪由等影像作家的作品也不能被打上此类标签。被人所忽视的 80、90 年代的贫瘠动画的谱系已经延展并潜伏于当今动画的全体，我相信，整理这些模糊的贫瘠动画的核心与文脉的同时，对其历史性位置的提示，能够成为理解深夜动画的全体形态的线索。这要求我们对作画、演出以及叙事进行综合，因为在统合动画的诸侧面的同时对其进行再分配，正是呈现出一种循环构造的贫瘠性的实际的状况。

遗憾的是，佳作主义与围绕一部分特定的模范作品的陈词滥调正在榨干动画研究的养分。很容易发现，抛去一度火热的押井守研究和人气安定的宫崎骏研究，再抛去伴随其令人愕然的商业成绩而逐渐获得市民权的新海诚研究，残余的与深夜动画产生联系的研究少之又少，并似乎在相当程度上集中于今敏、京都动画、山田尚子，《莉兹与青鸟》……人们几乎本能地通过对动画的趣味嗅出什么样的研究是安全的。对贫瘠动画的关注从最宏观的视角说具有两重意义。首先，这有利于摆脱大作中心主义，甚至超越佳作主义。其次，贫瘠动画诞生于当今动画业的极端商业环境，即 2010 年代后一度呈现加速态势的量产化状况之中，而任何具有现状整理和分析野心的议论都无法回避对这种复制与重复，以及周期性议题的把握与评估。

也正是在这一意味上，托马斯·拉马尔早在 2000 年代就开始大胆讨论《蓝宝石之谜》与庵野秀明，甚至《人形电脑天使心》的姿态就令人不由得多生几分敬意。在《动画机械》中，他参考加达里“抽象机械”概念，以多平面摄影机的合成模式为物质根据，将赛璐珞动画的首要特征定义为影像的多平面合成，并且将实行这一过程的诸事项统一在“动画机械”的框架之中。在这里，可以观察到拉马尔对于动画绘制人员，无论是负责中割的动画人员，还是负责关键张的原画师的个人行为的边缘的超越。拉马尔强调赛璐珞动画的物质性特征，声称如果不理解动画的这些特质，就永远不可能理解动画，拒斥了以单纯的文学批评或电影研究的惯性轻率地染指动画研究的企图，与此同时，又通过对多平面合成的关注，用“活动影像之力”的移动，统一了摄影机运动和人物运动。换言之，拉马尔在《动画机械》中的尝试便是对演出与作画在动画本体论地位中的再分配3。

在本文中，我所尝试的对于宏观的视觉文化史与具体的影像批评的超越，也同时意味着对观者与作品媒介的关系的超越。我相信这两个议题从复数方面规定了当代动画最重要的问题意识，而实现这些穿梭的最重要环节便是进行对影像形式和其经验基础的视觉性再分配，进而在具体的作品层面达到故事与影像的动态统合。在这里，作画、演出，叙事不以互为矛盾的形态出现——出于对动画经验的直观，三者从一开始就不会是矛盾的，恰恰是评论者的思维活动扭曲了其关系性——动画的绘制行为，匿名的制作者的手在假想的纸面上留下的痕迹与影像之存在不仅是同等重要的，还必须是等质的。在其共同构成的视觉样式之上，观者之视线，与非人类、非生命的影像之视线的交汇，则保有超越于动画媒介历史长度本身的惯习与限制。一个具体的、独一无二的构图，如何从无处不在的平庸中被解救，到达关乎动画本体论的根本领域，从而反过来定义动画之普遍性？在这个过程中，观者和演出者的存在介乎于什么位置，抑或两者皆为多余，只有影像自身的无限展开？对这些疑问的沉思便是本文的方法论。

另一方面，在试图建立起贫瘠动画的图式时，本文势必要面对风格问题。以本文的篇幅比例而言，抛开倾注于作品分析的心血不论，仍有相当部分议论属于特定的作者论，即使其射程没有局限于那几个特定的影像作者。鉴于这些依托于对形式风格进行识别的议论包含着对于影像分类学前提的疑虑，尤其对于我的写作策略而言，牵涉到作家性会使本就复杂的议论显得更为令人困惑，搞不清整体面貌，因此我并未在这一系列问题上做过多停留，也不指望靠一篇文章厘清已经过于庞大的先行研究群。在这里，我部分地承认大卫·波德维尔认知主义式的观众·类型论，承认特定的教养与文化背景在具体的意义生成的过程中发挥的作用，并且对所谓先验的感知图式持开放态度。与此同时，作为风格研究的另一个起点亦是可能的出口，对于斯坦利·卡维尔的媒介研究的思考将占据全体构图的另一角。当言及影像的观赏者时，相比于波德维尔式的完美而富有能动性的观众像，本文更倾向于现象学式的纯粹化的观者像。换言之，虽然二者的区别趋于微妙，比起观众如何捕捉到特定的信息并且形成具体的阐释，我更关注观者做出关于贫瘠动画的判断时所处的状态，心理性的状态。这也许在原则上陷入了一种波德维尔所抵抗的关于观者位置的探究，即便我不是在阿尔都塞的语境中使用这个概念。

无论如何，关于波德维尔的方案，至少有三点不得不同意：

  - 对“叙述者”和“接收者”概念的放弃。
  - 分解影像的技术构造，并使其分别对应于具体的制作人员的个人史。
  - 既不追求支配性的抽象理论，也避免单纯的历史资料的记述。取而代之，对影像细节的个别记述和对以其为基础的普遍有效性的关注。

第一点和第二点有助于议论的顺利进行。在思考 meta 表现时，一味地执着于“叙述者”和“接收者”的语义嵌套将会导致问题的无限后退；而明确地考虑一个场景里演出家、原画师，背景美术的绘制者等等是如何在一个活生生的现场分析并解决问题，能够帮助我们把本来就足够模糊的风格问题挂靠在一个相对具体的层次之中。

至于第三点，事实上这一方案在文章中将会遇到极大的阻力与挫折，而这一困境本身诉说着贫瘠动画的最大悖论：到达贫瘠动画的方法是不断远离它。贫瘠动画论接受迈克尔·弗雷德式的历史主义立场，重视作品之间的文脉，以及代表这些文脉的演出者和具体作品，并且在每一个具体的影像所处的历史文脉中界定其所包含的演出之性质，例如其是否俗套，或者在什么程度上俗套。不过，在到达这个关于媒介的可识别性的二重构造的议论之前，有必要先从土居伸彰的 21 世纪动画论入手，简要考察理论进路之外的贫瘠动画的现实语境，即当代动画的状况。

*动画的价值观转向及其破绽*

1980 年，在和大冈升平的对谈中4，谈及于同年上映的动画电影《奔向地球》时，莲实重彦举出《小鹿斑比》等迪斯尼作品与其对比，为后者“在生物的运动的自然性这一点上已经追上了现实”，“仿佛像实拍一般把所有东西都自然地呈现出来”，“具有极为精巧的技术”。与之相对，《奔向地球》里的人物转身等动作却是“不自然的、粗糙的运动”，在技术角度上“实在是说不过去”。

莲实的短评不涉及有限动画和全动画的技术细节，因而规避了对张数问题的迷思。但是自然对不自然的二元论把对自然性的追求视为理所应当，因此也就将动画贬低为不完全的电影。

这种将动画视作依附于电影的影像文化的观点在数码制作普及开来的 2000 年代遭到动摇，在 2010 年代已经基本被新的议论更新替代。在日本，对这一转向做出了重要推动的有土居伸彰和其“空虚化的动画”论5。

在土居的考察里，某种意义上起源于迪斯尼公主故事，以宫崎、高畑为代表，并为 80 年代的创作者，即片渊须直、庵野秀明等所继承的，是“我与世界”的对峙。与之相对，在《你的名字。》、《声之形》里出现的互换可能的身体，“我们”中出现的“你们”，都意味着所谓古典世界系的内涵的扭转。“我”与“世界”的境界开始消失；“我”的内面的深度仿佛不存在一般，被各种匿名的、可互换的群体取代；原本清晰的“我”开始滑向模糊的“我们”。这是一种过剩而局促的，只能考虑目光所及的世界的世界观，“我们”在于想象中的外部世界。在这种局促和彷徨里，历史感觉开始模糊，事实和世界线似乎都不再是单一的。与“我”所对立的外部、世界本身溶解了，“我”成为了世界，至少成为了镶嵌于世界的一部分。

支撑这种转变的是原生质的活跃化。麦克拉伦等漫画研究者已经就漫画符号的符号性展开论述，指出伴随符号化程度的加深，漫画读者的感情移入会得到加强。在土居看来，这意味着火柴人式的动画其实比强调作画真实感和人物肉感的动画更容易产生想象的真实性。在旧有的动画想象力中，对真实感的强调反而导致原生质的被抑制，作为一种鲜活的世界可能性的动画影像被宛如现实般真实的动画影像所压抑。这种压抑与其说是发生在 20 世纪的动画中，不如说是发生在《白雪公主》之后的“动画应该获得实拍电影一般的真实性”的信条中。今敏作品往往被赞美者称作“一部电影”，正是因为其通过压倒性的真实感的描绘，发动了一种混淆现实与动画的魔术，并在这魔术中大声疾呼，为观者揭示了现实与虚构之别的脆弱。但是，这样的魔术 = 骗术里没有原生质的余地。面对宛如现实一般有血有肉的登场人物和天衣无缝的物理表现，观者不再需要想象的空间。这种现实和幻想的均质性，正如今敏所处的世纪之交这一时代背景一般，在数码制作普及的时代得到了空前的强化。从这个角度说，由列夫·马诺维奇所预言，由押井守所背书的数码时代的影像口号，即“所有电影都要成为动画”，正是出于其对于影像素材的均质化认识而成立，也因此遭到土居的批判。

可以说，《声之形》与《你的名字。》中人物塑造与老一辈动画人的人物塑造的区别，便是这种原生质的发挥空间的区别。在 2010 年代的想象力中，角色是简笔画的、火柴人式的，也因此是模糊的、缺乏作为个体的强度的。在这种模糊中不只存在着从“我”滑向“我们”，从单一世界线滑向复数世界线的过程，更存在着“生动而立体，以其自身强度拒斥观者的电影性现实的外壳”被撬开，露出一条“扁平而符号化，但是蕴含着多层次的动画性现实”的缝隙的过程。在《你的名字。》的高潮部分，宫水三叶踉跄摔倒在地并滚下坡去，这一场面由写实性志向金字塔尖的原画师冲浦启之作画。在那强烈的违和感面前，任何人都要承认土居的议论具有压倒性的说服力。

伴随旧有图式瓦解过程的是动画制作者的世代交替，出身背景变化，以及数码制作环境的普及。在对大环境变化进行铺垫后，土居的议论转向 CG 技术和 Flash 软件的动画表现。从他的思考里，能够捕捉到一个明确的信念，即围绕世界系理念的变化必然要成建制地、多层次地反映到实际的影像内容上，最好还要置换到动画制作的物质基础上的信念。在这方面作为陈旧想象力的代表遭到批判的是发端自加拿大实验动画巨匠诺曼·麦克拉伦的动画观和迪斯尼的教条：

#+begin_quote
动画并非动起来的绘画的艺术，而是被画出来的运动的艺术。帧与帧之间发生的事情比那一帧所画内容要重要得多。因此，动画是巧妙地操纵帧与帧之间不可视的空隙的艺术。
#+end_quote

诺曼·麦克拉伦的定义之经典，直到拉马尔《动画机械》一书席卷欧美学界之前，动画人和研究者们都或多或少要从他的思考出发展开对动画媒介特性的解读。animate，正如其字面意义“赋予生命”一样，被认为是为角色的图案注入灵魂的工作。这种带有伦理色彩的思考被发展为以迪斯尼动画为象征的标准图式，以运动性、有机性、完整性，生命感为最高追求。而动画的手翻书式的本质，使得运动表现因人而异，呈现出各种各样的风格和样式。

2010 年前后，在世界范围里，这一图式在中小成本动画制作的现场迎来了终结。土居总结道，一方面，以皮克斯作品为代表的大型 CG 动画依靠手绘的技术积累，站在手绘动画思路的延长线上解决了 CG 运动的僵硬感和无生气的问题。另一方面，大量的画家和电影从业者，即那些不掌握传统动画绘制技巧的人，得益于数码技术的发展和动画制作软件的低成本化，开始涉足动画制作实践。在他们所制作的动画里，粗糙诡异的角色运动完全依赖于电脑运算自动生成，仅仅勉强能完成叙事任务。在这些低成本的 CG 中，因为没有手翻书式的张数配置的概念，所有运动都趋于同质，失去了原画师鲜活的个人风格，土居将这种视觉风格称为“动画的僵尸化”。

然而，土居并非要批判传统动画伦理的败坏。从麦克拉伦和迪斯尼时代开始的动画传统过于沉溺于“人类中心主义”，陶醉于流畅的运动表现和生机勃勃的世界描写，丧失了对沉重现实的表达能力。反观“僵尸动画”的制作者们，以卡顿诡异，单调乏味的运动为基础，制造了一个个晦暗与异质的世界，通过对“人类中心主义”的抵抗，提示了一种新的动画范式。这些作品追求异质感和无机感，有意地压抑了麦克拉伦式的运动伦理和被视为动画基础特征的连续摄影效果，而迪斯尼式的充满生命幻想和视觉快感的运动规范更是已然沦为作品目的实现的障碍。

回到土居的 2016 动画电影观，参照围绕清晰而富有强度的“我”朝匿名性的、模糊的“我们”的转向的描述，便不会对土居观点的演绎感到疑惑。在土居看来，CG 的运动感的同质化的浮上是年轻世代对于运动知觉的迟钝化的表现。成长于一个视富有个性的运动为理所应当的视觉环境的现代人逐渐失去了对运动独特性的感知能力，也不再以这种独特性把握个体。每个独立的特殊的“我”，被匿名而同质的，失去了对峙的边界，被世界吞没或者成为世界本身的“我们”所取代。这在表现上的对应就是个性鲜明的手绘作画的时间感被 CG 那令人联想到僵尸的毛骨悚然性所代替。

然而，这样的同步关联看似形成了闭环，却存在数个问题：

第一，土居的论述里对于作画采取的态度非常暧昧，甚至有自相矛盾之处。土居在近年的论著里直接提到作画和游戏演算引擎的制作原理上的区别，并暗示后者即是上文 CG 动画论的对象。可是另一方面，在他与宫本大人和三轮健太朗的对谈中，诺尔斯泰因的“个人性”问题和日式作画的作家性之间暴露出深刻的龃龉。在这里显然存在“个人性”与作家性的混乱，“无法回避的‘个人性’的作用”与作者的“主观能动性”的并置。“个人性”如何在麦克拉伦式的时间感问题和马诺维奇式的图像问题里具体发挥其效用，还尚未澄清。有必要注意到这样一个事实：对迪斯尼式的真实生命幻觉的批判，并不是只存在于低成本独立作品里，更不是在数码技术时代突然出现的，这种力量对抗关系内化于日本商业动画的发展过程本身。

第二，为了契合火柴人动画相关的议论，土居的论述从迪斯尼的运动范式一步跨越到泛滥的 flash 动画的僵尸性6，并直接朝日本商业动画全体扩大其射程。这似乎导致了举证的疏忽。其论述的生硬感在对 NHK2016 年的纪录片《終わらない人 宮崎駿》的分析中达到顶峰。影片中，当时尚属多玩国的川上量升为宫崎骏展示了一段人工智能学习后制作的 CG 动画。看过这段 CG 动画的宫崎骏勃然大怒，痛斥这是对生命的侮辱。土居以此为例，提出宫崎骏之所以说 CG 是对生命的侮辱，是因为宫崎骏属于代表着古典动画价值的保守派，试图捍卫迪斯尼以来的动画伦理，即动画所包含的对生命的幻想。然而，该纪录片其实明确地说明了这一愤怒的真正来由。川上所展示的 CG 动画在内容上极其令人不快：一个肢体扭曲的残疾人形怪物在挣扎着挪动爬行，而这让宫崎骏联想到身患残疾移动不便的友人。毫无疑问，宫崎骏的愤怒的对象并非是 CG 技术粗糙的运动感，而是这段具体的 CG 动画其主题内容的恶趣味。况且，当铃木敏夫询问制作了这段 CG 的 AI 学习目标是什么时，多玩国职员的回答是“最终想要做出能和人类手绘一模一样的 CG”，这已经证明了纪录片中 CG 运动的僵硬只是技术上不得已的妥协而非目的。

说到底，土居过于重视 CG 动画没有静物连续摄影这一特性，采取了一种自己在论述手绘动画时极力避免的媒介特殊性的姿势，没能注意到考虑手绘动画之时过于强调张数配置和静止张连续放映等性质是一个普遍的误区。作为影像的 CG（与作为技术的 CG 相对），与手绘的运动并没有那么本质的对立，至少不是在这个层面对立。

最后，土居的 CG 动画论和 2010 年代这一时代背景相辅相成，并且追述到数码制作技术在世纪初的普及。与时代动向的紧密结合是其议论的有力之处的同时也成为其阿喀琉斯之踵。我们知道，日本最早的 CG 长篇动画《VISITOR》公开于 1998 年。虽然在时间上略有差异，但至少从表面上看，这部作品诡异的表现效果，令人喷饭的奇形怪状的人物运动，确实能够成为土居 CG 动画表现论的一个潜在事例。

《VISITOR》的预算仅有 2 亿日元，制作时间也非常有限。参加制作的 CG 动画师总数 6 名，耗时 9 个月。据导演德田淳说，本作为了节省预算，以可动模型动画的概念开始创作，追求仿佛可动人偶模型运动起来的效果。也就是说，从一开始就没有打算进行接近人类运动的表现，反而将 CG 运动的不适感视作一种独特的味道7。原来如此，几乎可以说，这部日本最早的长篇 CG 动画，领先之后的创作者们近 20 年，完美地契合了土居对于中低成本 CG 动画的论述，即以 CG 运动的毛骨悚然感，陌生感和无机感对抗手绘动画传统的生命感和亲切感，从而实现新时代作品的内容志向。

可是，果真如此吗？在做出了堪称僵尸动画教科书般的宣言之后，德田接下来的发言让情况复杂了起来。德田说，手绘动画的表现充斥着符号性，而世纪末的 CG 视觉风景里，虽然已经开始被各种游戏影像感染，符号化的体系却还尚待建立。站在这个时间点的德田，似乎并不以“自然”对“非自然”的轴线定位自己的作品，而是仿照手绘动画以符号化水平的“成熟”对“不成熟”加以衡量，并且寄希望于类似于手绘动画符号性体系的建立。换言之，德田对于其作品的期待，与其说是远离和对抗手绘传统，不如说是想要再现过去手绘动画获得过的一种历史性机遇。

接着，当我们的目光停留在动画脚本家伊藤和典的名字上，时代错位的违和感便油然而生。而在观赏正片后，大概任何人都要目瞪口呆：无论是高田明美的原案还是继承自《机动警察系列》的富有生活气息和演技细节的配音方针8，都在努力促成观者的感情移入。三石琴乃和川澄绫子的嗓音清澈自然，流露出派遣会社 OL 们慵懒活泼的天性。当视线从简陋的 CG 影像离开，萦绕于我们脑海的是两位充满魅力，活生生的女子的形象，绝不是什么异质的或是让人发毛的，过着“和死了似的日子”的僵尸性的角色。这是否意味着，德田的自白实际上蕴藏了一种倒错，“不追求人类般的运动”是对其符号化表现技术不足以支撑其理念的不情愿的辩护，而非“不追求人类般的运动”的理念裹挟了技术和文本？也就是说，《VISITOR》那令人哑然的运动效果其实是多玩国的技术性失败的一种预演？

这个猜想确有演出面的证据：作为 CG 动画的《VISITOR》有限动画的惯用技巧，尽可能地规避运动。尤为重要的是，避处理中，角色们依然在艰难而努力地做一些小演技，而不是干脆彻底放弃所谓人类行为，这恰恰是典型的手绘动画的人物演技处理。《VISITOR》中，运动作为一种被压抑在符号化后的属性，潜在而必然地，富于个性和生命感。节省预算的演出恰好透露了 CG 背后的动画师，即人的思考而非电脑演算的存在。一种尽最大可能去立体地刻画人物，但是受制于客观条件而被压抑的欲望在传统手绘风格的演出方针中流露。而当镜头离开尴尬的室内场面，来到宇宙飞船和空间站的机动镜头，SF 动画文脉所带来的自信心立刻要摆脱画面表现的桎梏，令人不禁莞尔。

可以这么说，《VISITOR》是一部不幸承载着“最早的全 CG 长篇动画”名号，背负了“扩张符号化表现之边界”这么一个过于沉重以至于压垮了其画面表现效果的典型的日式动画。作为日本商业 CG 动画无谋的先行者，《VISITOR》终究没有迎来所谓 CG 式符号性获得新时代观者认同，平冤昭雪的一天。这是表现侧的悲哀，而非消费侧的问题。《VISITOR》的诞生与沉寂，既意味着在土居不曾言及的日式商业动画里早已出现了所谓僵尸动画的萌芽，又暗示了，在大浪淘沙中，其结局已被预言。

不过，即使如此，对于电影式的影像追求、古典世界系的人物想象力、素描意义上的真实志向等传统动画的根干，土居论述中所包含的反思依然有很大的参考价值。在本文正式展开的论述里，我会参考他的议论，在日本商业动画的内部寻找另一种“陌生”的、脱离运动中心主义的价值。让我姑且称之为“贫瘠动画的价值”。在贫瘠动画这一也许最不曾受到严肃对待的动画版图里，土居的观察将得到比预想更多的呼应。

在对山村浩二2016年的动画作品《サティの「パラード」》的评论里，土居伸彰写道：

#+begin_quote
……最后，角色们拿出一枚卡片，上面写着“这场表演无人入场因此没有上演”。这句台仿佛是动画表现空洞化的时代里，动画已经不再依存于观众而得以自立的证据。观众们想必会擅自获得什么意义吧，但这已经与那些角色的存在无关。即使没有观众，动画也会存在。在无人观看中，观众与动画各自平行地存在，在无交集中淡淡地走下去。9
#+end_quote

正如土居的洞察，2010 年代的动画失去了一种外部。动画的影像不再拥有和作为参照物的周边环境以及观者发生对峙的强度，匆忙地埋头于自己的流水账。利姆露10 们面对的世界，是一个私人花园式的世界。也许在一场暴雨后花坛里的泥土会使得贴有瓷砖的地面变得脏乱，或是有青蛙之类的小动物出现在不该出现的地方，甚至偶尔还会遭遇蜂窝和蜘蛛的入侵……但是，只要像孩童般的主人公们耐心地花上一些时间去了解这些事件，故事整体最终都会朝如愿以偿地方向收束。贫瘠动画的想象力，不再牵扯到“我对世界”或“我 = 世界”的问题，而是直接面对动画本体，面对一切想象力的占位符。换言之，影像不再是作为“鲜明的我”或“模糊的我们”对观者的牵引力，而是作为自我完结的补完力而发挥机能。影像不再是内容的载体，而是拥有 24 分钟长度的时间轴的事实。

* songs
:PROPERTIES:
:CUSTOM_ID: songs
:END:

** ハーフムーン・セレナーデ

#+begin_verse
  あなたのもとへ　届くなら
  水面（みなも）に散（ち）った　琥珀（きん）の枯（か）れ葉を
  風つまびく音符 （おんぶ） にして　想い伝える

  月の雫（しずく）を　左手に
  涙でそっと　ひとつにつなぐ
  好きな人と結（むす）ばれたい…… 深く祈るわ

  青春の雲が切れる　年頃（きせつ）抱きしめ

  誰もみんな　ひとりぼっちだから
  優しさを　愛（いど）おしむのね
  抱きしめて永遠（とお）く　あなたの胸の
  生命の響きに　満（み）ちる夢

  ふたりでいても　切なくて
  あなたの指を　ぎゅっとかんだの
  恋をしても男の人　迷わないのね

  流れて落ちた　星（ほし）の輪（ま）が
  胸の泉（いつみ）に　波（なみ）を立てれば
  欠（か）けた月は淋しさに似て　心痛むの

  美しい瞳（ひとみ）のまま　どうぞ愛して

  幸福（しあわせ）をさがす　幸福（しあわせ）ふたり
  抱きしめて生きてゆけたら
  離さないで　ああ　時の銀河に
  流され　大人になろうとも

  青春の雲が切れる　年頃（きせつ）抱きしめ

  誰もみんな　ひとりぼっちだから
  優しさを　愛おしむのね
  抱きしめて永遠（とお）く　あなたの胸の
  生命の響きに　満ちる夢
#+end_verse

** 僕らの手には何もないけど、

#+begin_verse
  君に見せたいものがあるんだ
  孤独な夜にもきっと
  遠くで輝き続ける
  幾（いく）千（せん）の星を

  失うこと
  割（わ）り切れぬこと
  弾（はじ）かれること
  叶わないこと
  でも足（あ）掻（が）くこと
  信じぬくこと
  上を向いて
  歩き出すこと

  僕らの手には何もないけど
  かわりに　つなぎあえるから
  一人きりで　迷わないで
  どんな日もこの手を離さないから

  君にあげたいものがあるんだ
  凍（こご）える夜にはいつも
  もう何も心配等（なん）せず
  眠れる毛布（おふ）を

  忘れられぬこと
  耐（た）えきれぬこと
  術（すべ）がないこと
  奪われること
  でも気付くこと
  君がいること
  守りたいものが
  強くさせること

  自分の色を誇（ほこ）れるように
  自由に色を足（た）せばいい
  ぼやけていた　この世界を
  この手が彩（いろ）ってゆくんだ

  認めてくれる人がいなくても
  サマになる肩（かた）書（え）きがなくても
  僕らの小さな手は明日きっと
  誰かを笑顔にできるから

  僕らの手には何もないけど
  かわりに　つなぎあえるから
  一人きりで　迷わないで
  どんな日もこの手を離さないから

  君に見せたいものがあるんだ
  孤独な夜にもきっと
  遠くで輝き続ける
  幾千の星を
#+end_verse

** 名もなき詩

#+begin_verse
  ちょっとぐらいの汚れ（よごれ）物ならば
  残さずに全部食べてやる
  Wow darling 君は誰
  真実を握（に）りしめる
  君が僕を疑（うたがう）っているのなら
  この喉（のど）を切ってくれてやる
  Wow darling 僕はノータリン
  大切な物をあげる wow-wow

  苛立（いらた）つような街並（な）みに立ったって
  感情（かんじょう）さえもリアルに
  持てなくなりそうだけど

  こんな不調和（じょうわ）な生活 (くらし) の中で
  たまに情緒（じょじょ）不安定（あんて）になるだろう？
  でも darlin 共（とも）に悩（なんや）んだり
  生涯（しょうがい）を君に捧（ささ）ぐ

  あるがままの心で 生きられぬ弱さを
  誰かのせいにして過（す）ごしている
  知らぬ間に築（きつ）いていた
  自分らしさの檻（おおび）の中で
  もがいているなら
  僕だってそうなんだ

  どれほど分り合える同志（とうし）でも
  孤独な夜はやってくるんだよ
  Wow darling このわだかまり
  きっと消せはしないだろう oh-wow

  いろんな事を踏（ふ）み台（たい）にしてきたけど
  失（いな）くしちゃいけない物が
  やっと見つかった気がする

  君の仕草が滑稽（こっけえ）なほど
  優しい気持ちになれるんだよ
  Wow darling 夢物語
  逢う度（たび）に聞かせてくれ

  愛はきっと奪うでも与（あた）えるでもなくて
  気が付けばそこにある物
  街の風に吹（ふ）かれて唄（うた）いながら
  妙なプライドは捨（す）ててしまえばいい
  そこからはじまるさ

  絶望（絶望）失望（失望 Down）
  何をくすぶってんだ
  愛（愛）自由（自由）希望（希望）夢（夢 勇気）
  足元をごらんよきっと転（ころ）がってるさ

  成（な）り行きまかせの恋におち
  時には誰かを傷つけたとしても
  その度（たび）心いためる様（だめ）な時代じゃない
  誰かを想いやりゃあだになり
  自分の胸につきささる

  だけど
  あるがままの心で生きようと願うから
  人はまた傷つていてゆく
  知らぬ間に築（きつ）いていた
  自分らしさの檻（おおび）の中で
  もがいているなら誰だってそう
  僕だってそうなんだ

  愛情ってゆう形のないもの
  伝えるのはいつも困難（こんなん）だね
  だから darlin この「名もなき詩（うた）」を
  いつまでも君に捧（ささ）ぐ
#+end_verse

** はなび

#+begin_verse
  どれくらいの値（めう）打（う）ちがあるだろう？
  僕が今生きているこの世界 に
  すべてが無意味だって思える
  ちょっと疲れてんのかなぁ

  手に入（い）れたもんと引き換（か）えにして
  切り捨（す）てたいくつもの輝き
  いちいち憂（うめ）いていれるほど
  平和な世（よ）の中じゃないし

  一体どんな理想を描いたらいい？
  どんな希望を抱（た）き進んだらいい？
  答えようもないその問（と）いかけは 日常に葬（ほうむ）られてく

  君がいたらなんていうかなぁ
  「暗い」と茶（ちゃ）化（か）して笑うのかなぁ
  その柔らかな笑顔に触れて
  僕の憂鬱（いううつ）が吹き飛んだらいいのに

  決（け）して捕（つか）まえることの出来ない
  花火のような光だとしたって
  もう一回 もう一回
  もう一回 もう一回
  僕はこの手を伸ばしたい

  誰も皆 悲しみを抱いてる
  だけど素敵な明日を願っている
  臆病（おくびょ）風に吹かれて 波風がたった世界を
  どれだけ愛することができるだろう？

  考えすぎで言葉に詰（つ）まる
  自分の不（ぶ）器用（きよう）さが嫌い
  でも妙に器用に立ち振（ふう）舞（ま）う
  自分はそれ以上に嫌い

  笑っていても 泣いて過ごしても
  平等（びょーどー）に時は流れる
  未来が僕らを呼んでる
  その声は今 君にも聞こえていますか？

  さよならが迎（むか）えに来ることを
  最初からわかっていたとしたって
  もう一回 もう一回
  もう一回 もう一回
  何度でも君に逢いたい

  めぐり逢えたことでこんなに
  世界が美しく見えるなんて
  想像（そうぞ）さえもしていない
  単純（だんじゅん）だって笑うかい？
  君に心からありがとうを言うよ

  滞（こどこ）らないように 揺（ゆ）れて流れて
  透き通ってく水のような 心であれたら

  逢いたくなったときの分まで
  寂しくなったときの分まで
  もう一回 もう一回
  もう一回 もう一回
  君を強く焼（や）き付けたい

  誰も皆 問題を抱（かか）えている
  だけど素敵な明日を願っている
  臆病（おくびょ）風に吹（ふ）かれて 波風がたった世界を
  どれだけ愛することができるだろう？
  もう一回 もう一回
  もう一回 もう一回
#+end_verse

** Hotel California

#+begin_verse
  On a dark desert highway, cool wind in my hair
  Warm smell of colitas rising up through the air
  Up ahead in the distance, I saw a shimmering light
  My head grew heavy and my sight grew dim, I had to stop for the night
  There she stood in the doorway, I heard the mission bell
  And I was thinkin' to myself, "This could be heaven or this could be hell"
  Then she lit up a candle and she showed me the way
  There were voices down the corridor, I thought I heard them say

  "Welcome to the Hotel California
  Such a lovely place (such a lovely place)
  Such a lovely face
  Plenty of room at the Hotel California
  Any time of year (any time of year)
  You can find it here"

  Her mind is Tiffany-twisted, she got the Mercedes-Benz, uh
  She got a lot of pretty, pretty boys that she calls friends
  How they dance in the courtyard, sweet summer sweat
  Some dance to remember, some dance to forget
  So I called up the Captain, "Please bring me my wine"
  He said, "We haven't had that spirit here since 1969"
  And still, those voices are calling from far away
  Wake you up in the middle of the night just to hear them say

  "Welcome to the Hotel California
  Such a lovely place (such a lovely place)
  Such a lovely face
  They're livin' it up at the Hotel California
  What a nice surprise (what a nice surprise)
  Bring your alibis"

  Mirrors on the ceiling, the pink champagne on ice
  And she said, "We are all just prisoners here of our own device"
  And in the master's chambers, they gathered for the feast
  They stab it with their steely knives, but they just can't kill the beast

  Last thing I remember, I was running for the door
  I had to find the passage back to the place I was before
  "Relax, " said the night man, "We are programmed to receive
  You can check out any time you like, but you can never leave"
#+end_verse

* head

** TODO 论文、数据集
:PROPERTIES:
:ARCHIVE_TIME: 2024-10-26 Sat 12:47
:ARCHIVE_FILE: ~/org/note.org
:ARCHIVE_OLPATH: entries
:ARCHIVE_CATEGORY: note
:ARCHIVE_TODO: TODO
:END:
<2024-10-25 Fri>

  + [ ] 论文，follow 的论文。感觉也没啥可行性，难道说直接 follow 学长的工作吗？
  + [ ] 数据集？这个还得讨论一下才能得出方案
