# -*- olivetti-body-width: 60; -*-
#+startup: overview

Archived entries from file /home/one/org/note.org


* head

** test
:PROPERTIES:
:ARCHIVE_TIME: 2024-09-24 Tue 16:19
:ARCHIVE_FILE: ~/org/note.org
:ARCHIVE_CATEGORY: note
:END:
** DONE 软B开题报告 ruan b
:PROPERTIES:
:ARCHIVE_TIME: 2024-09-23 Mon 17:54
:ARCHIVE_FILE: ~/org/note.org
:ARCHIVE_OLPATH: archived
:ARCHIVE_CATEGORY: note
:ARCHIVE_TODO: DONE
:END:

*** advantage                                                     :ARCHIVE:
缺点：1.提高了系统和管理的复杂度：面对多个配置文件，难以保证他们不会相互之间有影响，这将为管理系统带来挑战2.降低了安全性：多个用户共享开发板可能导致安全问题，比如说对其他用户配置文件的非法访问。3.提高了调试难度：在调试的过程之中还需要考虑共享的问题，将会提高调试的难度4.对于管理人员的学习曲线陡峭：因为管理员需要学习PR相关的工具和实现原理才能更好的利用PR，并且管理员也需要面对更高的调试难度。

*** disavantage                                                   :ARCHIVE:
优点：优化了资源利用率：多个用户可共用开发板，提高对可用资源的利用率。减了少停机时间：FPGA只有一些部分需要重构，提高了停机时间。提高了灵活性：更容易扩展系统，容纳更多用户或者更复杂的实验，而无需进行重大的硬件更改
*** 简介

(1) 支持PR的远程FPGA实验系统【迭代】

– 可参考去年“远程FPGA实验系统”课题，提供文档和源码
– 前端支持用户上传.bit
– 服务器接收用户.bit文件后，将.bit下载到FPGA开发板
– 服务器只需支持1块FPGA开发板
– 系统支持2个及以上用户
– 只需设计简单的前后端，能用于演示即可

keyword: partial reconfiguration

*** doc

https://docs.qq.com/doc/DS0J1bFVaRGtyV3Zs?_t=1726986675018&u=a401c0f3feae46de80a830c15e9ecb88

** DONE 任务书 graduation design renwushu
:PROPERTIES:
:ARCHIVE_TIME: 2024-09-23 Mon 17:54
:ARCHIVE_FILE: ~/org/note.org
:ARCHIVE_OLPATH: archived
:ARCHIVE_CATEGORY: note
:ARCHIVE_TODO: DONE
:END:

*** 基本信息

学科类别 理工类
题目来源 教师自拟题目
题目类型 科学实验类
申请导师 王德胜
题目名称 基于流量分布预测与移动性感知的高效MEC服务器放置

本课题是否“以实验、实习、工程实践和社会调查等实践工作作为基础” 是
论文研究方向 边缘计算
论文关键字 流量分布预测；移动性感知；服务器放置

*** 课程简介

在过去的几年间，移动边缘计算（MEC）技术在提高网络性能和用户体验方面取得了显著进展。随着5G网络和物联网（IoT）的迅猛发展，用户对低延迟和高带宽的需求也在不断增加，而MEC正是通过将计算资源下沉到网络边缘来满足这些需求，减轻云端网络的压力，降低服务响应延迟。

在此背景下，如何高效地部署MEC服务器以优化资源利用率和服务质量成为一个重要的研究课题。本课题旨在基于流量分布预测与移动性感知技术，实现高效的MEC服务器放置。

通过对用户流量进行预测，能够更准确地了解不同区域的流量需求，并结合用户设备的移动模式，动态调整MEC服务器的放置位置和资源分配。

在具体实现方面，本课题将采用机器学习和数据分析技术，对历史流量数据进行建模和预测。同时，利用移动性感知技术，实时监测用户设备的位置信息和移动模式，从而对服务器进行动态调整。为进一步验证MEC服务器放置技术的有效性，本课题将搭建一个完整的MEC架构，作为服务器放置技术的运行平台。

论文关键字 流量分布预测；移动性感知；服务器放置

*** 立题的目的和意义：

移动边缘计算（MEC）是一种新兴的计算范式，其核心是将云计算的能力从中心化的云数据中心向外扩展到网络边缘。这样做的目的是为了减少数据在网络中的传输距离，以此来降低用户的延迟，提升服务质量。在过去的几年里，MEC显示出其在提升网络性能和增强用户体验方面的显著贡献，成为了一个关键的技术领域。

在这种语境之下，服务器放置策略就显得尤为重要。服务器放置指的是将服务与计算能力部署在离数据源或用户更近的物理位置，以此提升减少延迟和网络拥塞，并且提高服务质量。

传统的服务器放置策略通常基于地理位置和数据中心容量进行，属于静态部署技术，通常会将服务器部署于公司总部、区域办事处或者专用数据中心等，便于集中管理与维护。然而，静态部署虽然能够降低成本和管理复杂度，但是缺乏弹性且有可能带来昂贵的运营成本。此外，移动用户的行为通常是难以预测且不规则的，静态的服务器放置策略已经难以适应移动用户的迅速变化的需求。针对以上问题，需要一项能够自适应用户位置变化的边缘服务器部署技术，以保证后续边缘计算任务的服务质量。

为了应对这些挑战，我们计划开发新的流量预测模型和MEC服务器动态部署算法。通过精确预测用户流量的分布，我们可以更准确地理解各区域之间的流量需求差异。我们还将考虑用户的设备移动模式，结合这些数据来动态地调整MEC服务器的位置和资源再分配方案，从而更好地响应用户行为的变化。这些技术的发展与实施，将为用户带来更好服务质量，同时提供高效节能、成本优化的解决方案ff。

*** 主要内容

流量分布预测模型的开发：设计基于历史流量数据的预处理和特征选择方法。开发能够处理大规模数据集并应用于实时预测的机器学习算法。实现动态和静态流量预测模型，针对短期和长期流量波动进行预测。

用户移动性模式的分析与感知：利用移动网络数据评估用户位置的动态变化和移动趋势。

MEC服务器动态部署算法：开发算法以模拟和优化MEC资源在网络边缘的分布式部署。构建性能评估模型，用以预测不同部署方式下的服务质量和资源效率。

测试和验证平台建设：我们将会搭建一个模拟真实网络环境的MEC测试框架，用以测试和验证流量预测和服务器部署模型。通过模拟不同的用户行为和流量模式，验证策略的有效性。

*** 技术指标

流量预测准确率：高准确率将会有助于预测网络流量的峰值和低谷，从而优化资源分配。

响应时间与延迟降低：通过精心设计的移动边缘计算（MEC）部署策略，我们将能够显著减少网络延迟，提升用户响应时间，增强了用户体验，为实时应用提供了必要的支持。

服务的可靠性与优化：服务器放置策略必须确保服务的高可靠性，并通过优化体验质量（Quality of Experience, QoE）来提升用户满意度。服务质量（Quality of Service, QoS）可以通过多个维度来衡量，包括带宽稳定性、网络延迟和数据包丢失率。通过这些指标的综合考量，我们可以确保服务的连续性和用户的满意度。

*** 进度安排

1. 开题检查前：2024年9月~2024年12月
2024年9月：查阅相关文献调研
2024年10月：查询动态服务器放置策略，选择并且实现服务器放置算法，基本搭建起MEC服务器架构。
2024年11月：利用机器学习和神经网络技术，实现对流量的预测。
2024年12月：使用移动性度量，将其融入到MEC架构之中。

2. 开题至中期：2025年1月~2025年2月
2025年1月：使用真实数据集进行训练，并且进行优化和改进。
2025年2月：在平台上进行仿真实验，调整系统并且优化仿真效果。

3. 中期至结题：2025年3月~2025年4月
优化系统，编写结题报告

** DONE try to fix vscode <2024-09-23 Mon>
:PROPERTIES:
:ARCHIVE_TIME: 2024-09-23 Mon 17:54
:ARCHIVE_FILE: ~/org/note.org
:ARCHIVE_OLPATH: archived
:ARCHIVE_CATEGORY: note
:ARCHIVE_TODO: DONE
:END:
[2024-09-23 Mon 13:55]

** DONE ask for gitee
:PROPERTIES:
:ARCHIVE_TIME: 2024-09-24 Tue 18:49
:ARCHIVE_FILE: ~/org/note.org
:ARCHIVE_OLPATH: entries
:ARCHIVE_CATEGORY: note
:ARCHIVE_TODO: DONE
:END:
<2024-09-24 Tue>

** CANCELED gitee code
:PROPERTIES:
:ARCHIVE_TIME: 2024-09-24 Tue 18:49
:ARCHIVE_FILE: ~/org/note.org
:ARCHIVE_OLPATH: entries
:ARCHIVE_CATEGORY: note
:ARCHIVE_TODO: CANCELED
:END:
<2024-09-24 Tue>

Some how I can get it.

** DONE wait for gitee
:PROPERTIES:
:ARCHIVE_TIME: 2024-09-24 Tue 19:55
:ARCHIVE_FILE: ~/org/note.org
:ARCHIVE_OLPATH: entries
:ARCHIVE_CATEGORY: note
:ARCHIVE_TODO: DONE
:END:
<2024-09-24 Tue>

** DONE file the document
:PROPERTIES:
:ARCHIVE_TIME: 2024-09-25 Wed 00:48
:ARCHIVE_FILE: ~/org/note.org
:ARCHIVE_OLPATH: entries
:ARCHIVE_CATEGORY: note
:ARCHIVE_TODO: DONE
:END:
<2024-09-24 Tue>

** DONE csl for chinese paper citation
:PROPERTIES:
:ARCHIVE_TIME: 2024-09-25 Wed 00:48
:ARCHIVE_FILE: ~/org/note.org
:ARCHIVE_OLPATH: entries
:ARCHIVE_CATEGORY: note
:ARCHIVE_TODO: DONE
:END:
<2024-09-24 Tue>

** DONE define convolution
:PROPERTIES:
:ARCHIVE_TIME: 2024-09-25 Wed 01:04
:ARCHIVE_FILE: ~/org/note.org
:ARCHIVE_OLPATH: entries
:ARCHIVE_CATEGORY: note
:ARCHIVE_TODO: DONE
:END:
<2024-09-24 Tue>

* other

** [2024-09-26 Thu] 为什么受众明显是喜欢老婆的宅男的二游中，却难以找出一个不两头恰的游戏呢？

月夜梦行貘
你也用愤怒扭曲你的判断吗？
144 人赞同了该回答

看了那么多回答，我突然意识到 ML 仙人的产生，其实很大程度是国内男性向二创太过贫瘠导致的。大部分二游的角色塑造只能说除了标签毫无特色，以至于如果没有二创的填充，其人物形象无限接近与纸片，这也为什么一个角色能够轻易被带起节奏。因为 “她” 不是一个立体的人物形象，只是某种具有外形的符号而已。

在这种情况下，那角色的“塑造权”几乎就是被官方或节奏决定的。因为在这个关系里，玩家 - 官方，几乎成为了一种施舍与被施舍的关系。而受限于二游本身的体裁，很难深入地塑造所有角色，于是中间的空白（这包括更新中间的空白）成了一种无人填补的区域。

在一般的文化社区中，这种空白是由同人填补的，哪怕再单薄的形象在二创中都有自己的生命力。虽然不同取向的群体会有不同的滤镜，但角色本身不至于贫瘠。

如果社区毫无二创产出能力，那人们的目光只能聚焦于游戏本体，任何细节都会被放大 —— 包括剧情、数值，等等等等，社区内的情绪主要以对抗为主。而娱乐组成越单一的人（或者说越是深度玩家），越可能停留在社区里，从而像养蛊一样越来越魔怔（）

换句话说，如果一个社区的二创能力与其活跃程度成反比，那么其魔怔程度就会指数级飙升，成为一个大型 PVP 现场

我们一般将其称之为饭圈。。

为什么二创本身会延缓官方焦虑，很大程度上是因为看到一个故事之后，诞生了「想要创作」的想法，这个时候这个角色她在主观世界上「活过来」同时「死去了」。

一方面，她有了真正属于自己的性格，自己的人生。另外一方面，通过创作这种方式人们意识到「在游戏中的那个她不是不可亵渎的」，从此从施 - 受这个关系中一定程度上独立出来，于是所谓官方的神圣性也自然消解了

当然，男性向社区还有另外一个问题是人们似乎只想冲爆，以至于就算是二创也只有 hs 方面的内容 —— 更糟糕的是，人们似乎找不到（）

摩砂学
观点其实是相当受限的，简中其实还没能以冷静的态度看待同人以及这个圈子。如果说男性向社区二创能力低，那么前几年闹得火热 v 圈又算什么呢？那个圈子不是饭圈浓度高、非常活跃的吗？那个圈子里面是不是人们都想冲爆呢？不好判定吧。

那对于二游，情况是不是一样呢？如果不一样的话为什么不一样？而在这里评价的二创能力指的是全体男性社区吗？那么类似于钢丝社区、以前的魔兽的社区，是不是又在这里的讨论范畴内呢？所以这里的评价难道不是要限定更多的前提吗？

假如说其他社区二创能力很强的而二游社区能力不强，这种区别又是什么带来的？

……简中在这里避免暴论是一种很困难的事情。就算说我们单独讨论 20 年代的二游社区，二游社区和其他男性为主导的圈子之前的异同、为什么二游社区会让人有这种印象，也可以纳入讨论范围内，只不过到这里可能就偏题了。

……直接像楼上的几位这样评论其实不是什么好事。

月夜梦行貘
因为二创本身只是 “施 - 受关系” 的蓄水池，导致魔怔的关键是 “施 - 受关系” 本身，你看乙游、二游、饭圈 v 圈都是这样。这一关系的结构在于，施舍者是情感和幻想的产出者，而接受者永远只能乞求其垂怜 —— 并且只有通过金钱获得自己本应有的地位。

月夜梦行貘
而这种行为实际上是施 - 受者的一种倒置，在金钱方面，施舍者是观众，被施舍者是产出者，在情感方面却反之。这种倒置使得观众会产生一种愤懑，凭什么我明明是施舍者却无法获得我想要的东西？
在非二游（不贩卖对私人的感情为主）的游戏或者文艺作品里，这种关系就很难成立，因为亲密关系亲密幻想是特殊的，是会反过来绑架主体的。但其他游戏给予的价值则和 “个人的心灵” 没那么贴近，玩家觉得无聊那就不玩，观众觉得难看可以不看

月夜梦行貘
我也很奇怪近年的二游为什么二创能力很低下，因为我是看着东方同人和各种 mad 长大的，在贴吧年代也不乏佳作。但是我没有深入过二游社区，这点我实在不好评价了。

摩砂学 → 月夜梦行貘
其实我只想指出你的回答其实不够准确，以及容易引发 “男性圈子怎么怎么样的” 暴论。我自己是无论哪个圈子都不怎么关注的。但是容易关注到的是，人们关注到男性为主的同人圈被一种刻板印象笼罩了。比如别楼里面提及的综漫（就连我自己都没听过）是属于同人的范畴，同时也是我根本不接触的文字类型的同人。

到这里我想说的是，“男性圈子” 并不准确，若用的是（简中）“二游圈子” 的话，这个回答当然成立。

我觉得你的回答放在 v 圈里也有道理。但是问题的似乎导向了另一个方向，也就是为什么得是 简中 二游 男性圈子的二创产出低。这其实还不够准确，我之前是玩 fgo，那边可几乎没有 ML 这种臭毛病，二创应该也还行，我自己不大看。

当然我评论的主要原因是一些暴论。

摩砂学
在这个刻板印象的延长线上讨论的话，我感觉是一种身份认同的问题，假如说所有男性圈子的人都称呼自己为同人男的话可能就不会出现这种问题了。在这里看综漫的和二次元就是两个圈子，那么割裂就自然地阻碍了对整体圈子的认知。

摩砂学
再然后针对 ML，我觉得和 v 圈有些类似，因为简中 v 圈是搞得最鸡飞狗跳、最魔怔的。ML 和 “vtuber 不能谈恋爱” 也有一定的相似程度。

摩砂学
其实我主要是不喜欢无意之间导向的性别叙事…… 太老生常谈了，而且经常让人情绪输出或者下暴论…… 这里很多楼都这样

月夜梦行貘 → 摩砂学
我本意就是指男性向圈子，这在一般语境下也就是指舰娘崩坏交错战线这类卖美少女为主的作品就像 dota 和 lol 这种虽然玩家几乎都是男的，但是没什么人叫他男性向游戏。
我不知道是不是当代的二次元很多都不是原来那批 —— 当然包括宅女也不是，现在的乙游玩家严格来说就是现充。
二游创作的社区不行很大原因是因为审查，因为男性向主要产量都是涩图，简中互联网压根就没得发…… 好吧，不得不承认很大一部分人玩二游就是为了冲一发，但是我又搞不明白他们为什么会因为剧情的原因（而且角度很刁钻）破防……
要我个人认为是相当多男性本身对自身的亲密情感需求太漠视了，甚至是贬低的。人们贬低异性恋爱脑的时候却忘记了性焦虑也是关于爱的焦虑，以至于他们愿意为《完蛋》这种素菜买单。当人们耻于谈爱的时候，作为美少女游戏的二创，在审查内自然没什么好写的了。

摩砂学 → 月夜梦行貘
这不又转回到性别叙事的角度上了吗……“有些游戏虽然男性玩家多，但是没人称其为男性向游戏”，如果在这里说明了男性向圈子指的是二游圈子，但是 “相当多的男性” 又会有扩大化的嫌疑，甚至在这里提及的《完蛋》其实和二游圈子关系不大，这让人感觉确实在扩大化。扩大化就会导向性别叙事，原本我们的主语只是二游玩家，现在却有变成整体 “男性” 的倾向。

我的重点在于，应当避免这种讨论之中的性别叙事，也即 “该现象的产生是因为男的有什么什么特点”，应当关注的是 “男的这部分群体之中何来的什么什么特点”。在讨论的时候，我会避免使用 “男性圈子”、“男性向” 这种说法，这是因为另一个部分圈子，比如说综漫同人文（读者也大部分是男性，广义上应当在男性向范畴内），并不在当前讨论范围内，于是比如说楼内在当前讨论二创的时候、讨论同人文的时候，使用 “男性向” 有扩大化的嫌疑，尤其因为二游玩家并不怎么看同人文。

摩砂学
总之我有点在跨服聊天的感觉……

正如武老师评论指出的，男性向不是没有同人文、不是没有二创，只不过是它们没有进入到我们的视野内，也没有进入到二游玩家的视野内。所以作为基本的论断的 “男性向社区二创活力低导致 ML” 在这里忽视了 ML 现象所具有的强烈的时代性和群体性。

总之说了那么多，我只是想避免那种泛滥的性别叙事，如果有一部分男性为主的圈子二创、同人创作很频繁，而另一部分却不是如此，而如果人们却只了解那 “不是如此” 的圈子，那么这种情况下转入性别叙事是说服力不足的。

摩砂学
说实话我觉得没什么好聊的，简中上所有对同人文化的评论基本都有问题，一点都没有那种日本文化批评的认真感。自然大部分人其实对两边的圈子都没有深入的了解，也从来没有史料和前人的研究帮助我们了解（我今天才知道【男性读者为主的】综漫同人文的存在，这样的认知能让我贸然对同人文化进行评论吗）。

现有的评论都是 “女的咋样”“男的咋样”，在尽情地输出的同时却没有意识到这种方向完全是死胡同。

但总之，我还是有点跨服聊天的感觉，这可能是角度不同造成的，因为日本宅文化批评的语境下，性别叙事都算是滥觞了。

昨天 12:55 · 广东
月夜梦行貘 → 摩砂学
我知道你的意思，二游本身包括 ml 运动本身有其特殊性，很可能是社群本身没有同人文这种传统。但是我想声明的是宅向文字类的需求并不是没有的，否则恋爱向的轻小说、网络文学应该也不会有现象级作品。
或许贩卖恋爱幻想这回事的二创本身是私人性质的；或许是因为审查的日趋严重导致原本丰富的同类替代品消失，新生代缺乏找资源的能力，同时时代本身让人们的戾气越发严重 —— 于是当人们需要一个平台去发表二创的时候已经没有平台可发表了。或许是二游本身吸引的群体本身对文字类不敏感，二游群体画手稀缺，等等是很多原因叠加导致了这种情况的出现。
但是说实话我写答案的确实有自己的情绪，我一开始就知道自己得出了一个似乎很局限的东西，批评我接受，但不妨碍我觉得解析二游玩家这一群体本身无法离开性别叙事。

** [2024-09-24 Tue] 国家统计局发布8月份分年龄组失业率数据，有哪些信息值得关注？
1 人赞同了该回答

陈关麒在《绸缪月刊》中发表的《毕业与失业问题的探讨》可以大概展现民国时期就业难的情况：

 现行的学校制度，中学六年，大学四年，一般毕业生耗废了金钱，经过了长时期的学校生活，用去无数的精力脑力，好容易拧得一张文凭，谁都希望出其所学，效力社会，不幸而生在供过于求的年头，政府机关人浮于事且没有援引不易进身，社会方面，又受经济恐慌的影响，工商业衰落不振，对此莘莘学子，也是无法容纳。因此毕业生俞多，失业人数也愈众。结果，因无颜同乡，自杀的也有。或因思想激变，走入邪途的也有。大有作为的青年竟在“毕业即失业的状态下做了时代的牺牲者！

但是好在这里是新社会，8 月数据青年失业率比较高的数据，这说明社会在向高科技转型中高端人才需求旺盛，各高校因此加大培养力度，人才红利不断增加

** [2024-09-24 Tue] 简中、圈子 建议 archived

观点其实是相当受限的，简中其实还没能以冷静的态度看待同人以及这个圈子。如果说男性向社区二创能力低，那么前几年闹得火热 v 圈又算什么呢？那个圈子不是饭圈浓度高、非常活跃的吗？那个圈子里面是不是人们都想冲爆呢？不好判定吧。

那对于二游，情况是不是一样呢？如果不一样的话为什么不一样？而在这里评价的二创能力指的是全体男性社区吗？那么类似于钢丝社区、以前的魔兽的社区，是不是又在这里的讨论范畴内呢？所以这里的评价难道不是要限定更多的前提吗？

假如说其他社区二创能力很强的而二游社区能力不强，这种区别又是什么带来的？

……简中在这里避免暴论是一种很困难的事情。就算说我们单独讨论20年代的二游社区，二游社区和其他男性为主导的圈子之前的异同、为什么二游社区会让人有这种印象，也可以纳入讨论范围内，只不过到这里可能就偏题了。

……直接像楼上的几位这样评论其实不是什么好事。

** [2024-09-24 Tue] 为什么看 CLANNAD 感觉很不舒服？

神必天坑
甚谁 等 120 人赞同了该回答
@雨宫优子。提到这个提问吧宇野常宽的轮子给造了出来。确实是这样的，宇野常宽在《零零年代的想象力》当中对于《AIR》《CLANNAD》这些游戏中给予了很低的评价，辣评这种广义涩情游戏是RAPE fantasy。

 《AIR》所描绘的就是人类补完计划成功的世界=父性完全败给母性的世界了。正因为如此，故事中几乎没有成年男性登场。而正是在这样的世界=母性的摇篮中，用户才能通过“安全的疼痛”的自我反省表演来享受更加强化保存了的大男子主义。《AIR》中透着的大男子主义的保存回路之所以可以起效，是因为其世界观被压倒性的母性所守护着。

 他们无法享受这个世界的复杂（正因其复杂而丰富），亦无法将“成为父亲”这种暴力式的自我实现以外之物纳入视野，只能通过“安全的疼痛”这样空洞的表演，将那种油腻大人式的欲望完全满足。

所以其实题主有这种恶心的感觉是自然而然的，本身 clannad 就是一个充斥着大男子主义的、男性向的 galgame 改编而来的动画，是满足男性的欲望的动画，所以如果以一个女性的视角来看，会觉得不舒服完全不奇怪。

这种游戏就还是卖给当年青年男性，具体是什么样的青年男性呢？没落的大男子主义与不成器的自我欺瞒

 虽然不曾打算成为父亲，但也压抑不住自我当个成熟父亲意味的欲望。他们肆意往返于两个不同的标准之间。一方面以移情作用投射进人少女漫画性质的内心感受，另一方面将身体委身于遥遥凌驾超越一般情色媒介的性意味的妄想之中。

不过要说起来，或许并不是题主（以及这个问题下的一部分答主）重新发明了宇野常宽的轮子，而是恰恰相反，是宇野把上世纪七十年代在日本流行的激进女权主义的视角给发明了出来（）

对此，千田洋幸评价到：

 在他的批评虽然经常关注新的媒介环境和内容，但核心的作品分析方法，却几乎是基于社会反映论和作家论的现实性的 1960-1970 年代的古典手法。比如说，把世界系的幻想(fantasy)与现实直接联系起来，并在其中发现“雷普幻想”、“顽固不化的男尊女卑的现存社会结构所孕育的广义上的性暴力”，这种方法和七十年代主流的激进女权主义如出一辙。在论述《新世纪福音战士》和高桥留美子的作品时，宇野还无限制地挪用了“父性/母性”这一过时的概念（之所以这么说，是因为这个概念的使用需要前置繁复的研究流程），这也是种极其老套的态度。总之，宇野所借尸还魂的，是那个谈及文化的创造物时，对理论的无知且无自觉能被允许的、非知性时代的亡灵。他抹杀了 80 到 90 年代构成文化核心的人文知识的历史，追求直接性、短路式的交流，抓住了对 90 年代式的知识不再抱有希望的年轻读者的心理，在批判性知性的废墟之上建立了作为作家的稳固地位。

** [2024-09-24 Tue] 为什么中国人不信神或者说没有一个全国信仰的宗教呢?这是这片土地发展的必然吗？

林先生
哲学话题下的优秀答主

薛定谔的鲨 等 476 人赞同了该回答
想起了秦晖跟陈丹青的一段对话

 那个时候，中国人精神的适应性已经达到一种地步，对于任何急剧的转弯，他们没有转不过弯来这样一说的，没有什么信仰崩溃、什么精神崩溃。比如其他国家在政治急剧动荡的时候，往往会出现很多人因为幻灭，因为你原来追求的东西后来发现不是这么一回事了就没法活了，就自杀了。尤其是宗教传统很浓的那些国家，像俄国在几个关键点都是出现自杀高潮的，甚至在新经济政策时期都出现这种高潮，原来极左的那一套突然间行不通了，有很多人会自杀的。但是中国的老百姓当时很少有这样的，中国的老百姓你不管怎么一翻一覆地颠倒，他们都好像已经习惯了。没有人感到受不了。不是说这几件事大家没感觉区别，有的事得人心，有的事不得人心，但即便不得人心，就当做戏大家也还是做了。到现在也是一样。

 陈丹青：两德统一后，据说东德有三千多人自杀，主要是知识分子官员，包括博物馆馆长、大学教授、校长、学者之类。他觉得我一辈子信仰共产主义，这算怎么回事？死了算了，中国绝对不会。

 秦晖：对，中国人的精神不会崩溃，因为他原来也没什么精神。改革以后，抑郁症、精神疾患的发病率、自杀率，这些统计数字从九十年代以后就有了。然后就发现一个现象，改革以后，这个数字不断向上走，九十年代末是最高的，本世纪又开始往下掉。压迫到了一定的极限值以后，就没有反抗了，人都弄麻木了。

** [2024-09-24 Tue] 我国的电视厂家是怎么把自己玩死的？

Frount
这个人很懒，什么也没有留下
491 人赞同了该回答
在作死的是广电，而不是电视厂家，因为所有规则都是广电制定的。

1、智能系统刚有苗头的时候，广电就嗅到机遇开始垄断网络机顶盒，搞了个IPTV执照，同时开启了一台电视、两个遥控器的新篇章。

2、互联网媒体刚起步的时候，广电看机顶盒的垄断要被打破，就借着保护版权的名头搞了个互联网网电视执照，电视想联网或者视听软件想登电视端都得有这个。这个直接导致影音软件套娃会员，因为按规范要求，许可证是独立的、相应公司的经营也必须是独立的，否则就是挂靠、直接吊销！

3、再后来广电发的许可证越来越多，投屏软件都需要许可证。这也是为什么现在的电视、视频软件大多都不支持系统自带的投屏功能，而必须要使用特定的投屏软件。

可以预见的是，将来大概率广电会搞个自己的操作系统（比如基于安卓），“推荐”电视厂家适配，不适配就要上交专利给广电优化，再ban掉USB接口和各种传输协议切断刷机破解的后门，比如前一阵广电说要终结“两个遥控器看电视”可能就是个契机，然后找个安全的由头让工信部ban掉无线显示器，最后把带智能系统的触控显示器和会议大屏全部列为电视管控，广电就能大一统了。

PS：装了智能系统的投影（含激光电视），在广电眼里也属于电视

** [2024-09-24 Tue] 为什么要反驳剩余价值理论?

剩余价值理论基本上没剩余多少价值，有些部分甚至走上了自相矛盾的境地，虽然马克思的后继者们不停地给他的理论打着补丁，但有些补丁也是相互矛盾，属于是把“袖口”这些该开放的地方也给补上了。

一、马克思：雇佣即剥削
按照经典的马克思主义理论，资本家只是在能够榨取工人的“剩余价值”的前提下才会雇佣工人，因此这种通过剥削把剩余价值从工人转向资本家的做法存在于所有的劳资关系中，即劳资关系本质上是剥削关系。

但对于那些不得出卖自己劳动力的人，情况又是怎样呢？比如在有些国家，法律规定不得雇佣已婚妇女。

她们不仅没有受到剥削，她们还受到免于剥削的保护，许多人正是基于此来为性别歧视作辩护。

这些国家向已婚妇女提供一小笔收入，按照马克思主义的剥削论她们反而成为了剥削者——因为劳动者的一部分收入都被强行向这些已婚妇女作了转移，这就是“不劳而获”。

但是，把这种状况下的妇女当作剥削的受益者合理吗？她们所遭受的不正义可能要比资本家的剥削更为严重，而女权主义运动的首要任务之一就是让妇女能够平等地进入劳动力市场。﻿

或者，再考虑一下那些享有法定雇佣资格、但却没有被雇佣的失业者。这些失业者也没有被剥削，因为他们没有生产任何可供资本家占有的剩余价值。

而如果政府向人们征税以向这些失业者提供救济金，那么他们也会成为剥削者。但是，那些失业者的境况显然要差于那些能够被雇佣的人。

对于那些没有财产的人而言，被迫出卖劳动力也许要好于被迫不准出卖劳动力（的妇女），要好于不能出卖劳动力（的失业者），要好于通过犯罪、乞讨、依靠仅有的公共资源苟且偷生的人［马克思的“Lumpenproletariat”（流氓无产阶级）］。

人们本来期望剥削理论能够对资本主义提出激烈的批判。然鹅按照它的标准形式，它却忽视了在资本主义制度下那些境况最糟的人，并且实际上排除了需要对他们给予帮助的行动（如对儿童、失业者和残障者的福利支持）。

二、勒默尔：生产资料不平等持有说
如果剥削理论要对弱势群体予以恰当关照，就必须抛弃对“剩余转移”的狭隘关注，就应该转而考察这些转移在其中发生的更宽泛的分配模式。

为了解决这样的矛盾，勒默尔（Roemer）将剥削的定义不是基于剩余转移，而是基于对生产资料的不平等拥有。

按照他的观点，某人是否遭到了剥削取决于在一种假想的分配平等的条件下他的境况是否会更好——那种假想的条件意味着，某人可以带着自己的劳动力和人均拥有的外部资源而退出现行的分配条件。

仅当剥削是生产资料的分配不平等的不正义结果，剥削才是一种邪恶。如果我们把不同的经济群体当作由现有财产关系确定规则的游戏的参与者，那么某个群体一旦满足下述条件就被视为遭到了剥削：

如果该群体的成员带着人均拥有的外部资源退出了这个游戏并开始自己的游戏之后其处境反而更好。
对勒默尔而言，剥削理论的“伦理命令”不是消除剩余转移，而是“废除对于可转让的生产资料的不平等所有权”。

但这同样是说不过去的，现在很多中高级打工人手里的资金很充裕完全足以购置一些生产资料，那么他们为什么还是选择打工而不是创业呢？

傻子都知道找工作失败的亏欠风险远比创业失败的亏欠风险要低的多，这就是打工人自己根据自己的风险偏好而自主做出的选择，他们自己选择加入一个企业为企业主打工从而把风险转嫁给了企业主。

虽然打工的工资不比成功创业能获得的利润更高，但打工相比创业承担巨大的亏损风险获得的收入更稳定。

三、柯亨：需求分配原则
在他初次对马克思主义的剥削论予以表述的时候，科恩否认预先设定这样一个前提，即“人们拥有自己的劳动产品”：

  一方面，可以认为，资本家通过占用工人所生产的东西的一部分价值而剥削了工人；另一方面，又不必认为，所有这些价值都应该归于工人。可以肯定某种以需求为基础的分配原则，同时又可以认为，资本家剥削了工人，因为资本家对工人产品的一部分价值的获得，并非以他的需求为基础。

否定这个前提是因为柯亨认为如果“把最一般意义上的对劳动时间的占有当作不正义的范例，那么，你就无法避免对像自我所有权原则这样的内容予以肯定”。

因为旨在保护儿童或年老体弱者的强制性征税也应该被当作剥削。如果我们强迫工人纳税以保护年老体弱者，我们就是在强迫他们做没有酬劳的工作。﻿

但柯亨属于是“进一步，退两步”，丧失劳动产品的自我所有权而声称资本家剥削工人，这种说法的理由是什么呢？

  他（资本家）对工人产品的一部分价值的获得，并非以他的需求为基础。

那假设某个资本家对某个产品没有需求，因此对它也就没有正当要求，但这并不意味着按照需求原则，工人就能够对此形成正当要求。

因为最需要产品的人也许是第三者（如儿童），那么儿童就成了唯一能够对产品拥有正当要求的人。

如果资本家仍然占有了产品，他就是在不公正地对待儿童，而不是在不公正地对待工人。但是，如果工人占有了产品，那他不也就成了不公正地对待儿童的“剥削者”吗？

因为一旦违背了需求原则，受到不公正对待的就是需求者，而不是生产者。

一旦我们放弃自我所有权的要求，对剩余价值的占有在本质上就不是剥削——因为剥削取决于对剩余价值的具体处理是否吻合更大的分配正义模式。

但如果捡起自我所有权又会完全迎合了诺奇克自由至上主义的假设：自我所有权—劳动自我所有—劳动产品自我所有—剩余价值转移—强制无偿劳动—福利性剥削。

四、阿尼森：剥削二分法

阿尼森区分了“正当的剥削”与“错误的剥削”，他认为要判断是不是“错误的剥削”，要求与某种假想的平等主义分配进行对比，但他对平等分配的解释既排除了天赋不平等产生的差异又排除了外部资源的不平等产生的差异。

阿尼森相信按照这个检验标准，资本主义制度下的绝大多数工人都遭到了剥削——因为他们因不应得的财富不平等或不应得的天赋不平等而使自己被他人所利用。

与勒默尔一样，剩余转移在阿尼森的理论中起一种派生作用。如果剩余转移是不平等分配的结果，它就是错误的；如果剩余转移的出现与财富或自然天赋方面不应得的差异无关或被用于补偿这些差异，它就是正当的。

因此，对失业者和残障者的强制性支持就是正当的。然而，在资本主义制度下从工人那里拿走的绝大部分剩余都是不正当的，因为这些剩余最后都进入到了受益于不应得的天赋分配和财富分配的那些人的腰包。

因此，资本主义是一种剥削制度——虽然支持这个结论的理由相比最初的马克思主义剥削论要复杂得多。

今天看来，这是对剥削更加言之成理的一种解释。但不幸的是，正因为这种立论抛弃了原初的马克思主义剥削论的全部特色，它才变得更加具有吸引力。

第一，这种把对剥削的思考包含于其中的更宽泛的理论越来越接近罗尔斯资本主义补丁式的正义理论。

原初的马克思主义者的论证是，工人对自己的劳动产品享有资格，而资本主义的不正义就在于使工人被迫放弃这种资格。

但大多数当代马克思主义者都试图避免这种自由至上主义式的前提，因为这（与其他理由一起）使得对老弱病残的援助在道德上居然成为可疑的了。

而他们越是试图顺应我们的常识——并非一切技术意义上的剥削都是不正义的，他们就越是在诉求罗尔斯式的平等原则。

第二，这种对剥削的新解释抛弃了原初的马克思主义剥削论的存在依据——也就是马克思主义的这样一个论断：劳资关系本质上就是非正义的剥削。

因为如果要依据是否存在不应得的不平等来判断某种剥削是“好剥削”还是“坏剥削，那么某些劳资关系就可能不是剥削关系，而“剩余价值”里甚至会出现“好剩余价值”与“坏剩余价值”，马克思主义理论的一致性会被修正得乱七八糟。

第三，还是生产资料的问题，对生产资料进行社会化还是对生产资料进行平等化这点而论，对剥削的关注并不能证明前者优于后者。

如果有这样一个企业，它的内部有两个不同意见的群体：一个群体对收入的偏好超过对闲暇的偏好；另一个群体对闲暇的偏好超过对收入的偏好。

如果多数群体在决策上赢得了胜利，而如果他们又不允许少数群体把自己在康米制度下对资源的平等拥有权转变成自由主义的对个人资源的平等所有权（譬如，通过出卖他们在企业中的份额），多数群体就将以不公平的方式去决定少数群体。

这时少数群体则遭到了剥削，因为如果他们带着自己的人均资源份额退出的话，他们的处境反而会更好。

但如果只是生产资料平等化的话，只不过又是重新回到了“私有制”，人们又会因为天赋的不平等、投资回报收益、时间分配偏好与其他社会资源等条件的差异重新回归到资本主义社会状态，对于马克思主义者来说这下又“通往奴役之路”了。。。

** [2024-09-24 Tue] 对于程序员，到底什么是成长性的工作？

whhema

momo 等 4 人赞同了该回答
随便写写，我第一反应是三个点。

首先是能看到运营的数据，这一条就秒杀了一切大厂。

你要跳出自己的职位，跳出螺丝钉的定位，才能感知到真实的业务。

大厂里的什么高级工程师，什么技术专家，什么技术经理，表面上拿着高薪，人际关系简单，实际上是最毒的诅咒和最大的坑，每年吸引了好多人往里跳。

中小企业的程序员能看到的反而更多。

其次，你要知道如何直接改进这些数据，注意这里的重点词是直接。

程序员是最苦逼的工种，几乎所有程序员都不了解自己的工作内容对业务的实际收入和利润起到了什么作用。

这就是每年年底打绩效时，技术部门最吃亏，明明干着最苦的工作，还要背绩效指标模糊的锅。

一定要冲到业务的最前线，不要满足于做个所谓的技术专家。

最后是识别当前工作能否有喘息时间，不要把自己的7*24小时都献祭在公司项目上，除非你能在项目上直接获利（比如你入股了，或者你有提成）。

运气好的话，如果你的上级也是这个想法的话，尽早抱大腿，过这村没这店了。

** [2024-09-24 Tue] 如何评价曹丰泽突然转进视频赛道？

389 人赞同了该回答
当初曹丰泽决定去非洲，我便去他的主页围观了几篇回答，得出的结论是这个人官瘾很重。

那时他的粉丝听闻他“放弃选调”而进军非洲，对他的崇拜达到了极点，逢人就吹他什么“副处级”“央企总工”“三清”，仿佛一个超新星就要带着他们所有自以为是的梦想和不切实际的期盼在官场“冉冉升起”了。又逢人便夸他“援建非洲”“造福第三世界人民”，那是“功德无量”，仿佛只要在非洲吃点苦，“取经”回来就能封“佛位”。

后来媒体还真的宣传了他一下，好像是在提前进行舆论造势，一副准备把他当“苗子”来培养的样子。后来我们知道，连个水花都没溅起来就再也没了下文，除了他自己发在知乎的回答，哪还有什么人追踪过他在非洲具体的“丰功伟绩”，甚至连一点舆论价值都没有做出来。

很明显可以看出，这个人请缨去非洲刷资历，不是有什么高尚的情操和伟大的理想，而是他从功利主义的角度出发，作为一个崇拜权力的人，在综合判断自己家世背景和知识背景后的理性选择。

因为是小镇出身的做题家，在他的观念里，想要快速升上去就得去吃苦，去非洲这种苦中苦的地方就是“坐火箭”走捷径。而他粉丝热衷于意淫他回国之后的级别，和他字里行间透出来的那种“建功立业，大干一场”的自信，都充分昭示着他出发前的野心勃勃。

我当时就判断，他泡在学校里这么久就只是读书，还没去做过学生工作，大概率本人并不精于“这一套东西”，一定会在他的梦想道路上折戟。

做题家思维就是以为吃最多的苦就有最多的收获，毕竟他们学生时代在学习上取得的“成功”都是按照这种确定不移的法则在运转。

然事情的发展与他原初的设想大相径庭，他在那里干了几年，没有很快得到他想要的，他的贡献也没有被什么人看到。

于是他心有不甘，不再闷声做事，就拿起镜头，自己当自己的“记者”，把自己做过的工作呈现到世人面前。

看视频，他心气淡了不少，镜头前的形象谦逊有知，都开始用当初知乎IT人士讽刺土木的打灰来自嘲了。

当一个学者在自己的专业领域做不出什么来之后，他会淡化在主业上的心思、放弃和同行交锋，转向视频平台当“孩子王”，通过自身丰富的知识阅历对年轻人“降维打击”来满足自我实现的需求，填补现实生活中所欠缺的成就感，同理。

只不过，这些学者往往都是年逾半百才转向这个赛道，他倒是一步到位，少走了二十年弯路。
