#+title:Diary
#+author:mhx
#+options: H:4 num:nil
#+infojs_opt: view:info toc:4 buttons:t
#+html_head: <link rel="stylesheet" type="text/css" href="style.css"/>
#+html_link_home: index.html

* 2024

** 2024-9 September

*** 2024-09-24 Tuesday

**** 脆弱的“好看”
:PROPERTIES:
:CUSTOM_ID: diary-cuiruodehaokan
:END:

看到了一个 reddit 的帖子：有哪部电视剧是如此烂尾以至于你一直记恨它。我立刻就想起了我曾经看过的那些。

  + lost 莫名其妙的结局，浪费了10季的时间
  + the arrow 本身就垃圾
  + gotham 除了第一季就是垃圾
  + the big-bang theory 越后来就越垃圾
  + sherlock 最后一季根本不应该存在
  + 2 broken girls 毫无疑问的垃圾

除了质量下滑之外，自己那么会被这种事情 trigger，其实是因为这种“好看”有一种非常脆弱的基底。你的“好看”为什么那么容易地被摧毁？怎么没见人被战争与和平恶心到，那里也有地雷的情节。

本身阅读（观影）是一种对话。但是人看小说就跟自慰一样，小说也写得和黄片一样。何来对话？

举个例子，一女作者去写男频（ps. 这个词真是……）曾说自己因为犯了某一个错误，小说订阅数崩了几万。这似乎能说明对于人来说，小说只是随意替换的道具，就如同你的飞机杯坏了就买个新的。替换小说就如同关掉这个黄片然后打开另一个黄片一样简单。

在这里不仅是对话゠阅读，而且还是对于好看的质疑。若是以一种脆弱的形式享受，潜在的风险却让人觉得不值当。这是某种抽离、自己的理智给出的警告——一种对下降的警告。

** 2024-10 October

*** 2024-10-2 Wednesday

**** 对于“精神营养”
:PROPERTIES:
:CUSTOM_ID: diary-duiyujingshenyingyang
:END:

对于“精神营养”的追求，仿佛是一种幻觉，妄想在“精神”上赋予自己文化产品以高层次的意义。

面向一个男性向的作品，“男性向”一个评价似乎已经足够，但是在这里展现的是如此的言语：

  - “我仿佛没有感觉到你的作画的意图”
  - “仿佛是为了画而画”
  - “没有对精神营养的追求”
  - “女性的身体作为一种客体被呈现在画之中”
  - “能够感觉到创作者的污浊的眼神”
  - ……

如同幻想一般地对自己的消费的拔高，还加之这种无耻的性别叙事的应用。

其实是一种混用、以及这种混用导致的对于自己行为的合法化。

当我的需求是 mental 的时候，我却认为，我的需求是一种 spiritual 的。占据了前者的合法性，同时后者还让其占据了所谓的“意义”的高点。

他们的观点在事实上还是一种滥觞。

当有些人开始讨论消费者和创作者之间的关系、这种彼此相互渗透的两个群体之间的关系的语境之下，性别叙事作为一种 50 年前的老古董很少出现在这里，并且文化创作也不区分同人创作以及商业创作（消费创作之间的模糊），所谓的“男性向”作品也并非以所谓的“色图”的形式被人接受。作为 50 年前的“先进”理论虽然理所当然地有着市场，但只不过是作为一种最没有“营养”的评价而存在。

lead you astray

[2024-10-02 Wed]

*** 2024-10-6 Sunday

**** being a women

基于一种刻板印象，在老友记之中，joey 说“不是你说的内容，而是你如何说的的”，随后惊呼“OMG，我是个女人”。但现实果真如此？

非也。我就是会被人的态度强烈地影响的人。其实这就是所谓的下头之一。当然下头更像是之前提及的，矛盾的体验带来的一种 bewilderedness。

感性的人吗？但事实上不是如此……每个人都有感性的功能在其大脑内运作着。

*** 2024-10-7 Monday

**** 双重身

“我觉得我说很多事情都被当放屁了”，我当时是怎么想的？

说实话我完全记不得了……

这其实是有问题的啊

*** 2024-10-8 Tuesday
**** 对于人的态度的察觉

以前是在高中，在那里，其实每个人都是没有什么坏的倾向的。我是一个老师，那么我的职责就是教好你。我是你的同学，那我们就共同进步，或者至少不相互干扰。

一种勉强、一种敷衍、一种自己没有察觉的沉醉，都是极度让人敏感的……我们亲爱的学长，仿佛是自己也不怎么想干这种事情的样子……真是令人无语……尤其对于我来说。

也就是这种事情最能打击人的积极性……
**** 书评 of east of eden
:PROPERTIES:
:CUSTOM_ID: review-on-east-of-eden
:END:

John Steinbeck 的 east of eden。首先是让人惋惜，其次是让人骂出，“其实获普利策奖的作家也只不过是一个二流作家”。

一开始最引人瞩目的就是简洁轻快的语言。以及之中完全在把握之中的叙事。

但是这种把握却让人觉得二流。因为……

对于角色的描写，仿佛是为了剧情而服务的。在这里原本两者一体的，却变为两个分离的个体了。主人公母亲的性格仿佛就是用来打破的---她不被允许发表自己的意见---在某一章节的最后，仿佛是理所当然的，她破天荒说出了自己的心里话。仿佛她的存在就是为了这一刻，作为一个死板的家庭里面的、无法表示自己观点的母亲，以这个身份在章节的末尾营造一种戏剧性。

又一章的末尾，主人公和自己的哥讲点心里话。但这却让人疑惑，“他果真是如此讲话的吗？”。主人公难得有一段长一些的对话，但却感觉和他的性格对不上？但其实是“他的性格”本身居然没有定形下来。

小说里面最难写的就是对话。至此我已经放弃这本书了，因为对话让人发觉作者水平不咋的。不会写对话建议像百年孤独一样别写。

[2024-10-08 Tue]

*** 2024-10-13 Sunday

**** AvPD

Avoidant personality disorder。也就是回避型人格。可以想象到的是，回避型依恋人格是一种简体中文的特供版本。

即使如此，加上一个 Disorder 未免是有点没有良心了。

这是一种巧合还是说？但总之两种 Disorder，都是完美地对上了。在这里我说，她为什么要提这个事情？也许是找了借口，想指出我当前的这种状态。

**** 累

体测累人，也只有这种时候才会想着“Damn，我早该做点运动”。

但今天让人想起那一年之前的事情啊，也就是酗酒而后体测之事。

像是怀念又不像是怀念。为何人都是要变化的呢？难道时间带来的变化都是让人伤感的吗？

*** 2024-10-14 Monday

这里是测试

*** 2024-10-15 Tuesday

**** 耻辱！

在写所谓的开题报告

耻辱！

当然只是因为不想写所以才那么别扭的

但是耻辱！

对于人的依赖，竟然到了这种程度

说是“依赖型人格障碍”……以前竟然不知道这类事物

即使是障碍也过于耻辱了！

**** 现在的肩膀还是痛的

这是何等的强力！

（这仅仅是因为体测而已）

*** 2024-10-16 Wednesday

**** AvPD 以及雪国
:PROPERTIES:
:CUSTOM_ID: xueguo
:END:

在雪国里的那种描写

徒劳作为关键词反复出现。

一种矛盾的话语，一种重复的说辞。到底是哪边呢？到底是在乎还是不在乎？

我想问清楚。但有什么在阻碍着……到底是作为人的能力下降了

*** 2024-10-18 Friday

**** Nicorenka

尼古拉和尼古连卡。说到底人是难以意识到后者怎么就是爱称了。

但假设用另一种思路来看，也就是考虑重音。

前者的话，应该是 ~ˈnɪkɚlaɪ~ ，但是对于后者来说 ~ˈnɪkɚˈrenka~ 了。

其实是差别很大的，后者确实更像爱称。尤其你尝试用日本人的读法的话。

可是我说这话谁又懂呢？

*** 2024-10-19 Saturday

**** 星期六，啥也不想干

但是今天还是搞了一些 org 的玩意。

到底是无聊的。

说起来挺想打电话的。但是……

在犹豫什么呢？

**** meta

今天还看见有人说为何要搞什么 meta-programming。真是愚蠢。不搞 meta 一点哪里来的 pattern matching 呢？

**** dere 是买不来的！

这只是一句很无聊的台词。

为什么突然想到呢？

可能从来不是迟钝，而是更吃 dere 这一套。

稍微想一下，如果说的是 せんぱい，且不是英语的那种重音，效果又会如何呢？

难道说人的真情都是会在这种小事之中被忽视而消散吗？

*** 2024-10-20 Sunday

**** 味道

人身上的味道……

一股药味，这倒是正当的理由，人总不能不治病

但还是很影响人……

**** 周日的图书馆

周日人多了，难不成来这里消遣的？

何必来这里做消遣，

把我的位置都占了。

**** 焦躁

一种焦躁，仿佛是那种说法，在什么上空的幽灵。说到底是什么……

……

到底是……

*** 2024-10-21 Monday
:PROPERTIES:
:CUSTOM_ID: 20241021Monday
:END:

**** 君可知有些人只看 lesbian porn
:PROPERTIES:
:CUSTOM_ID: lesbianporn
:END:

我称这种现象为“和现实的短路”，和现实的短路连接，经验的重叠。

当人说出“I am not an actor”的时候，似乎能够预见其为什么只会看 lesbian porn：porn 里面演员们的演技，短路到现实之中，而现实是“I am not an actor”，于是一种重叠的、矛盾的经验让人产生了厌恶。而为什么 lesbian porn 会被人中意？为的就是消解“矛盾的”这一特征：lesbian 在取悦女人这方面自然地超过几乎所有男性。

从另一个角度，可以消解掉“短路”这一现象：如果我消费的产品不会让人联想到现实即可。仅仅从这个角度来说，似乎是可以解释的了。

**** Textual Poacher

中文翻译出版的时候有对原作者的采访，采访之中有提及耽美……

等会儿，说到底这个词究竟是如何诞生的？00 年代的时候就有这个词吗……

你们这些人真实罪孽不浅啊……

既然有男性和男性在性交，为什么不直接叫 BL！

ps. from [2024-10-29 Tue 15:52] 想起来了，是因为审查。所以罪在审查。

**** 折腾

搞了一下午的问题，解决起来确实如此的简单。

只要将 ~init-org~ 放在最后就行了。

真是胡闹……

但这也说明了作日志是很重要的，因为我想起来说，就是从用了新的 org 开始，emacs 变得贼卡。

见鬼了
*** 2024-10-22 Tuesday
**** debug for org

Today I figure out why the inline math formulae looked very small in the exported html.

This is because that the width of the svg is not right. And then the css resize the width. Thus the formulae looked very small.

The problem can be solved after specifying the ~:page-width~ in
~org-html-latex-image-options~.

**** today I make a post in ~mildlypenis~ subreddit

And then maybe the "mildlypenis" is not mildly at all. It is just penis symbol but with a LaTeX symbol package.

I deleted the post (after I saw a fucking downvote).

ps. reddit is so powerful because I can literally see the ratio. Damn.

**** 重复

[[*AvPD 以及雪国]]

一种常常说出口的话语就在这里。令人怀念的感觉……

就好像雪国里面那样，驹子的一本本厚厚的日记……

岛村看到了，“徒劳”二字浮现出来。倒不是日记真的徒劳，而是……

是不是偶尔会想到雪国是不是就是这个原因呢？

这种反复到底意味着什么？这虚幻的，倒不是那种让人心生怜爱的事物，反而是搅动了什么，让人感到了什么

一种 detachment，又或者说 bewilderedness？为什么说是“令人怀念”，就如同许久以前的那样。原来也有这一层的原因……

人到底还是太贪心了

[2024-10-22 Tue 20:18]

**** 累了不想搞

其实是很简单的事情，具体来说就是写 PPT 这种程度的事情。直接复制上去就可以了。但是……想到要将这种其实没什么价值的事物念出来……真是丢人！

[2024-10-22 Tue 20:22]

**** 腰部

一个人的手，应该放在哪里呢？

在腰部上的这个部分，也就是硬的和石头一样的这个部分，手放在这个地方上非常适合

非常适合……

*** 2024-10-23 Wednesday

**** 有关 R18 音声的思考

说到底就是两个字：官能。如果要用别的字眼的话，那就是感官。

对于音声来说，要达成的就是一种共感：如何要用听觉传达出别的感官上的刺激？

人都是精神的生物。要做到这点，只能说靠大脑欺骗自己。让精神接受那听觉的官能之中的暗示，作为其他官能的媒介。

人的感受力就是关于接受这种暗示的能力。

这样的话似乎能够解释这种现象：音声之中出现的体液的声音、“stimulator”的震动声，几乎是最让人 turn on 的声音。

这里说得太直接了，过于羞耻，于是言尽于此。

**** 咖啡吓人

有点 Panic Attack，现在感觉更像是咖啡导致的。

*** 2024-10-24 Thursday

**** 很严重的发现！

草婴的《安娜》的译本的前言，居然有借鉴的痕迹！

真是可耻啊。

**** 答辩了

作为第一个上去的，感觉担忧的事物其实在人眼中是那么无关紧要的事情。伤心

**** 又想看 Ulysses 了

但是我和 War and Peace 对比了一下，结果还是后者好看得多。

所以看个毛线的 Ulysses。

*** 2024-10-25 Friday

**** 又整了一些 Emacs

得不偿失！但事实果真如此？

究竟到底，只是消遣时间……

[2024-10-25 Fri 12:54]

**** today I learn how to modify the frame parameter

#+begin_src emacs-lisp
  (modify-all-frames-parameters
   '((right-divider-width . 20)
     (internal-border-width . 10)))
#+end_src

And also I install ~org-modern~, and other things. I have learn a lot. And also
I know that ~window-divider~ is the name of the face line/border between
windows. Customizing that face helps a lot.

#+begin_src emacs-lisp
  (dolist (face '(window-divider
                  window-divider-first-pixel
                  window-divider-last-pixel))
    (face-spec-reset-face face)
    (set-face-foreground face (face-attribute 'default :background)))
#+end_src

**** Alternative

看到了吉成钢的作画

COOL~~~~~~~~~~~~~~

着实好看

但感觉 Muv Luv 像是变成超级系机器人动画了，就像是 Gurren Lagann 里面的剧情一样了，“接下来是准备让谁牺牲呢？”，竟然能让人怀着这种心情……

感觉能把这种有点右翼的情结写得和机器人动画一样，有点别扭地好笑

欸！

[2024-10-25 Fri 19:52]

**** Bangledash

人也是被逼的，家庭产业吗？

可能是我见识少了还是如何，但确实少见

人都是有苦衷的啊

只不过我可没有闲工夫来帮你

[2024-10-25 Fri 22:29]

*** 2024-10-26 Saturday
**** 人还是得和人讲话

受不了……确实受不了

**** boki

王朔的《动物凶猛》，倒不是作品本身有什么可说的

而是一个对于勃起的描写

就是小伙伴们脱光了衣服去泳池玩，有男有女的，还不是精虫上脑的年龄，甚至恰恰相反

直言，“在那里，却看见了骇人的勃起”

主人公就怒斥这个勃起的家伙，叫他滚，然后他就滚了

骇人吗……确实骇人，丑陋！

PS. 找了一下原文

#+begin_quote
“直了直了！”大家忽然一起指了半大的孩子。

在倥偬悠高的手电光中，我看到一个骇人的勃起。

犹如肚子被撞了一肘，我感到一阵恶心。就像人脑袋上突然长出一枝梅花鹿的角杈令我无法忍受，简直是活见鬼！
#+end_quote

[2024-10-26 Sat]

*** 2024-10-27 Sunday

**** VILE PH

这个组织可以使用 vile 来形容！

简直是 society of control 之下的典范

在这里，用户没有被当作人来看待，而是数据，是 database 里的一条 entity

作为感性的 fetish 被 algorithms 揣测

**** 每个人的 Vices

每个人都有的 Vices

都是等待偿还的债

**** Denote 好像找到一点感觉了

#+begin_quote
"好像找到一点感觉了"
#+end_quote

怎么感觉有些色情

总之 denote 将 query 的职责完全推卸了，file tag 全部体现在文件名上面，于是 query 就交给用户了

有点卑鄙

**** 为了鸡汤掉书袋
:PROPERTIES:
:CUSTOM_ID: diary-weilejitangdiaoshudai
:END:

看到越来越多的人在扯什么鸡巴王阳明

其实连掉书袋都算不上，就如同国外就已经有的，拿着斯多葛主义的名声，写一些垃圾至极的鸡汤

在简中也渐渐流行了起来吗……

其实不如读一读圣经来的好，虽然所有人都瞧不起圣经，但谁又瞧得起你那些东西呢？

想起了谷崎润一郎的《少将滋干之母》，又想起了京阿尼火灾纪录片里的一位。
看到了自己女儿烧焦的死尸，受到了冲击，转向圣经以寻慰藉……

到底是人生的启示，还是面对灾难的应激反应？

那么对于今天这些人，到底是哪里来的蛊惑的力量，又满足了什么需求呢？

[2024-10-27 Sun 18:41]

*** 2024-10-28 Monday
:PROPERTIES:
:CUSTOM_ID: 20241028Monday
:END:

**** 嘎人！

到底是世道的问题……

嘎人！早该嘎嘎了

#+begin_quote
警情通报

2024年10月28日15时20分许，海淀区万泉庄路和万柳中路交叉口附近，发生一起持刀伤人案件，导致5名路人受伤，其中3名未成年人。犯罪嫌疑人唐某某（男，50岁）被当场控制，伤者及时送医治疗，无生命危险。目前，案件正在进一步调查中。
#+end_quote

人常说，“自杀者懦弱，有勇气自杀，却没勇气拖几个人下水，哪怕是拉个垫背的”，现在好了！自杀者不懦弱了，甚至有勇气到不自杀了，就专杀别人来泄愤！

#+begin_quote
说说遇到突发情况该怎么办。

先声明京城被隐藏了。针对噶人总结一下经验教训，咱们有些网 u 玩甲，但是不可能指望所有人都穿防刺服，那玩意也不便宜，所以买甲胄直接图一乐。

我建议有娃的家长，尽量自己接送，或者至少有个成年人接送。其二，遇到突发情况，比如刀战，要求各个见义勇为不现实，但是冷静下来先保全自己再视情况应该没啥问题。其三，现场摇人，我看了几次伤亡小的都是好几个路人一拥而上，平心而论上年纪的老登没刀后战力很一般。切记，别撒丫子乱跑（踩踏），别单独当勇士要抱团。
#+end_quote

[2024-10-28 Mon 19:04]

**** 犀利
:PROPERTIES:
:ID:       fd57760d-334c-4e4a-88a0-828c770e66e7
:CUSTOM_ID: diary-xili
:END:

君可知《文学回忆录》，可谓是垃圾！当然啦，受不受欢迎、受不受喜爱，和这个东西是不是垃圾之间没有任何关系

人喜欢的就是一种犀利，这种犀利感用在批评里面倒还好——人就是想看锐评！

今天……我们手头上的这部书吕思勉《中国通史》，用这些滑稽的暴论博人眼球，若是放在什么评论、散文之中就算了，竟然敢放在“通史”之中，着实无耻！

在声称“立太子，君行周公之事”为“捏造”之后，接下来的论述之中，竟然没有任何的一丝文献支持，全然和伪史论者一个论述模式！做学问这种态度！

事实其实也是明确了的，人就是喜欢看犀利的，谁在乎你的治学态度呢？谁在乎你是不是严谨的呢？反正我读一读历史，也是消遣罢了

无耻！

[2024-10-28 Mon 20:15]

**** 微信读书

下流的软件，滚一边去！

[2024-10-28 Mon 23:58]

*** 2024-10-29 Tuesday
:PROPERTIES:
:CUSTOM_ID: 20241029Monday
:END:

**** 不写不快

事实 1：怀孕作为一种身体的形变、作为幻想会让人兴奋

事实 2：女性怀孕会让人联想到现实之中的妊娠，但后者基本等同于痛苦，于是联想的链条上面就自然有痛苦这一节

事实 3：作为一种幻想，男性怀孕同样让人兴奋（again, 作为一种幻想），但是难以让人联想到现实，因为男的无法怀孕

事实 4：事实 2 和事实 3 合情合理，却让人恶心：我们当一视同仁

事实 5：于是我打算消除自己的偏见，拥抱女性妊娠作为一种性癖

[2024-10-29 Tue 13:37]

**** 春雪

大失所望！

完全没有想象之中的那样畸形！

你以为我是来看什么高级玩意的？就等着看你写自杀殉情乱伦来着

现在好了，女人和男人做完爱，知道悔改了！剃发出家了，男人也死了，那我去哪里寻刺激？！

现在我还能在哪看到性描写？！

[2024-10-29 Tue 15:27]

**** 还不是因为你

我很久之前推荐，就比如说我推荐了 A 和 B 和 C

然后前两个被忽视了，这实际上是很正常的事情。随后人看了 C

但是这人突然跑过来说，你看你给我推荐了些什么，这么重的（或者说这么锋利的）

我反而比较无语：欸，A 和 B 不是这样的呀，你没去看那些，只看了这些，却说我推荐的有问题，可我不是在多尝试吗……

[2024-10-29 Tue 17:32]

*** 2024-10-30 Wednesday
:PROPERTIES:
:CUSTOM_ID: 20241030Wednesday
:END:

**** 结束啦

没有，其实没有结束，只是一件事情要开始了，而其他事情还没有动静

[2024-10-30 Wed 17:17]

**** 人在什么样的时候，会露出什么样的表情？

难道最让人陶醉的不就是观察高潮的时候她们的表情吗？

[2024-10-30 Wed 20:50]

**** 无题

聊天，剩下的印象却是如此的浅

“走肾”，我只记得对这个词语的厌恶

当时是如何谈论到这种事情的呢？

并且更重要的是，只有这种无关紧要的事情存留了下来吗？

时常陷入的追忆之中的，那弥足珍贵的，难道就成了再也无法遇见的事物吗？

[2024-10-30 Wed 23:54]

*** 2024-10-31 Thursday
:PROPERTIES:
:CUSTOM_ID: 20241031Thursday
:END:

**** 看完了奔马

话不多说，赶紧看晓寺

[2024-10-31 Thu 00:30]

**** 看完了晓寺
:PROPERTIES:
:CUSTOM_ID: diary-kanwanlexiaosi
:END:

经过爆裂的奔马，这回的晓寺又该选用什么形容词呢？

Exotic!

-----

并不是那偷窥的行为本身，而是对于那种埋藏着的 delicacy 的玷污……

让人羞愧

我是想看到一些畸形的，但还是没想到有这般激进的，甚至到了让人羞愧的地步

[2024-10-31 Thu 09:38]

**** 一种思辨的张力（误）

如果说一位男性健身，其有着诱人的胸脯，这个时候对于胸脯的赞美倒是有着学问在里面

曾经看到有位女性，问出“如何想男妈妈询问，能否让我摸一下他的胸肌”

恕我直言，若是私底下问倒还好，放在公共论坛上，那就是令人作呕了

我在这里的评判标准：性别互换之后，若是感到恶心，则原本的事情也是恶心的

当然这个评判标准其实过于专断了，因为确实有很多事情无法这样判定，比如说：妊娠作为性癖，放在女性身上就会自然地让人联想到痛苦，因为现实中女性确实能够怀孕；但是放在男性身上，就变为单纯的幻想了，因为幻想之中的怀孕的男性，是不存在于现实之中的。

对于幻想就能够消费得心安理得，这是很自然的事情

尽管这是自然的事情，但依然是虚伪的

随后，另一件事情发生了，假设只是部分的性别互换呢？比如说是一位男的询问另一个男的，“我能摸摸你的胸肌吗”，事情却变得没有异常了。何者？This is how straight people talk

但是，事情又突入了另一个视角，如果说上面这种事情是出自一位女性的脑海之中呢？若是有着不纯的念想，整件事情又变得恶心了起来。是的，我上面这句话，其实也是“出自一个男性的视角”，也就是说我的妄想之中的女性的妄想令人生恶！事情好像没完没了了

其实，面对这种似乎没完没了的推理的链条，似乎人的写作都是被身份给限制住了，由此考量，似乎一个专断的评判标准变得方便了起来。所以说，是的，在公共论坛问出“我该如何询问男妈妈，能否让我摸一下他的胸肌”其实就和“我该如何询问女菩萨……”是同等的恶心和油腻。所以说，是的，对于妊娠作为一种性癖，也只能是：女性应当心安理得地享用男性的妊娠作为性癖，男性也应当心安理得地享用女性的妊娠作为性癖，双方之间的指责和厌恶都是无理的；或者相反

如果女性能够合法地妄想两个男性之间的互动，那男性也应该被允许妄想两个女性之间的互动

或许还是免了，不必如此。不如给所有人打上标签：那令人厌恶的女性，就直接指责为是公开发情的下流的下体还在 dripping 的雌性吧；那令人厌恶的男性，就直接指责为脑子长在阳具里的咸湿猥琐缺爱阳痿又性饥渴的男子吧！

本就应该如此！

[2024-10-31 Thu 12:33]

**** 什么时候开了 TUN Mode

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

烦躁！狂！

就是你！就是你搞的！

[2024-10-31 Thu 22:50]

**** The history and allure of interactive visual novels
:PROPERTIES:
:CUSTOM_ID: diary-thehistoryofvisualnovels
:END:

Underwhelming!

美国人眼中的 eroge，可以预见的是，其理解也不过如此地肤浅

Visual Novels 作为一种媒介，他好像主要讨论了在媒介这边的事情，以及媒介本身的事情，可是，在媒介那边呢？

以及，他举的例子……这么多的空有名声的作品……很是无语

比如说第 6 章之中的，对于 utsuge 的游戏的举例：沙耶之歌、DDLC、君与彼女与彼女之恋、壳之少女、恋狱~月狂病。好吧，除了 Innocent Grey 的恋狱这部没有玩过，其他的我都玩过……并不是很能 get 到作者在讲什么，尽管例子我基本都玩过

让人觉得是梗小鬼：哼，若是你从 DDLC 入门的，可以说你这本书都不该写

基本上没什么意思，英文还看得我头大，恼怒！言尽于此！

[2024-10-31 Thu 23:59]

** 2024-11 November
*** 2024-11-01 Friday
**** 今日无事发生
*** 2024-11-02 Saturday

**** 建议删除
[2024-11-02 Sat 12:05]

**** 建议删除

[2024-11-02 Sat 22:56]

*** 2024-11-03 Sunday

**** 建议删除
[2024-11-03 Sun 11:51]

**** 钱锺书
:PROPERTIES:
:CUSTOM_ID: diary-qianzhongshu
:END:

以前看钱锺书的散文，看到钱是如何评价自己的文章、作品

说到《围城》，钱说《围城》写时年少不成熟，许多缺点想改却没机会改了（改稿遗失了）

说到《宋诗选注》，又是遗憾，说有不少名篇没选上去

有人说他谦虚，“钱锺书先生的《围城》那么好，还说它满是缺点，这难道不是谦虚吗？”

没，因为《围城》确实写得不好。同一时期的散文集《写在人生边上》其实也不好：一个 20 多岁的青年能有什么深刻的人生感悟？

既然作者本人都说不好了，还每次都在各种翻译版、再版前言里面提及，那我顺着他的意思，也觉得不好——确实不好！

很久以前看到刘皓明批评钱，结果被“你太不尊重”“你又算个什么”之类的批评围攻……说到底是见不得自己的 idol 被批评罢了

[2024-11-03 Sun 15:07]

*** 2024-11-04 Monday

**** 建议删除

[2024-11-04 Mon 19:03]

*** 2024-11-05 Tuesday

**** 建议删除

[2024-11-05 Tue 01:07]

*** 2024-11-06 Wednesday

**** 建议删除

[2024-11-06 Wed 13:46]

**** 占位
[2024-11-06 Wed 23:56]

*** 2024-11-07 Thursday

**** 建议删除

原来还是很难承受住这种纯度非常高的 boy meets girl 的故事

。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。

[2024-11-07 Thu 15:58]

**** 所以 FGO 什么时候死啊

！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

赶紧把月姬 R 做完好不好

[2024-11-07 Thu 22:35]

*** 2024-11-08 Friday

**** 手游真乃毒瘤也

月姬R 的销量，能顶得上多少个卡池呢？

真是下流！

[2024-11-08 Fri 00:24]
