#+title:To the Reader Setting Out
To read a poem is to depart from the familiar, to leave all expectations behind.
BY Edward Hirsch
Originally Published: 一月 23, 2006

The reader of poetry is a kind of pilgrim setting out, setting forth. The reader is what Wallace Stevens calls “the scholar of one candle.” Reading poetry is an adventure in renewal, a creative act, a perpetual beginning, a rebirth of wonder. “Beginning is not only a kind of action,” Edward Said writes in /Beginnings/, “it is also a frame of mind, a kind of work, an attitude, a consciousness.” I love the frame of mind, the playful work and working playfulness, the form of consciousness—the dreamy attentiveness—that come with the reading of poetry.

Reading is a point of departure, an inaugural, an initiation. Open the Deathbed Edition of Leaves of Grass (1891-1892) and you immediately encounter a series of “Inscriptions,” twenty-six poems that Walt Whitman wrote over a period of three decades to inscribe a beginning, to introduce and inaugurate his major work, the one book he had been writing all his life. Beginning my own book on the risks and thralls, the particular enchantments, of reading poetry, I keep thinking of Whitman’s six-line poem “Beginning My Studies.”

#+begin_verse
Beginning my studies the first step pleas’d me so much,
The mere fact consciousness, these forms, the power of motion,
The least insect or animal, the senses, eyesight, love,
The first step I say awed me and pleas’d me so much,
I have hardly gone and hardly wish’d to go any farther,
But stop and loiter all the time to sing it in ecstatic songs.
#+end_verse

I relish the way that Whitman lingers in this one-sentence poem over the very first step of studying, the mere fact—the miracle—of consciousness itself, the joy of encountering “these forms,” the empowering sense of expectation and renewal, the whole world blooming at hand, the awakened mental state that takes us through our senses from the least insect to the highest power of love. We can scarcely turn the page, so much do we linger with pleasure over the ecstatic beginning. We are instructed by Whitman in the joy of starting out that the deepest spirit of poetry is awe.

Poetry is a way of inscribing that feeling of awe. I don’t think we should underestimate the capacity for tenderness that poetry opens within us. Another one of the “Inscriptions” is a two-line poem that Whitman wrote in 1860. Called simply “To You,” it consists in its entirety of two rhetorical questions:

#+begin_verse
Stranger, if you passing meet me and desire to speak to me, why should you
     not speak to me?
And why should I not speak to you?
#+end_verse

It seems entirely self-evident to Whitman that two strangers who pass each other on the road ought to be able to loiter and speak, to connect. Strangers who communicate might well become friends. Whitman refuses to be bound, to be circumscribed, by any hierarchical or class distinctions. One notices how naturally he addresses the poem not to the people around him, whom he already knows, but to the “stranger,” to the future reader, to you and me, to each of us who would pause with him in the open air. Let there be an easy flow—an affectionate commerce—between us.

Here is one last “Inscription,” the very next poem in Leaves of Grass. It’s called “Thou Reader” and was written twenty-one years after “To You.”

#+begin_verse
Thou reader throbbest life and pride and love the same as I,
Therefore for thee the following chants.
#+end_verse

I am completely taken by the way that Whitman always addresses the reader as an equal, as one who has the same strange throb of life he has, the same pulsing emotions. There’s a desperate American friendliness to the way he repeatedly dedicates his poems to strangers, to readers and poets to come, to outsiders everywhere. Whoever you are, he would embrace you. I love the deep affection and even need with which Whitman dedicates and sends forth his poems to the individual reader. He leaves each of us a gift. To you, he says, the following chants.
